### ISSUE TITLE
[UI Wallet] incorrect rounding on send screen after some amount

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#1000]
When we try to set the amount >= 134999999.99999999 and click on fee or comment field, wallet incorrect rounding the amount

**Comment by VladislavKulyba** [comment]
incorrect rouding leads to exceeding of maximum emission (253999999.99999999 BEAM)
![image](https://user-images.githubusercontent.com/51320829/67003036-cf715980-f0e5-11e9-9e51-b68b29305320.png)

**Comment by chapati** [comment]
Fixed at https://github.com/BeamMW/beam/commit/dc4c3a002d2e0d7d7cc216c776212304e0ae962b

**Comment by Roberrtt** [comment]
Checked
