### ISSUE TITLE
"Logout" from wallet

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam#1001]

**Comment by dariatarakanova** [comment]
1) Add "Clear wallet" item in the settings - https://zpl.io/V0prm8m
2) Add confirmation alert screen - https://zpl.io/aXmW788

**Comment by dariatarakanova** [comment]
Please do the following:
1) Add menu item "Remove current wallet" in the settings - https://zpl.io/V0prm8m
2) Add confirmation alert - https://zpl.io/aXmW788
3) Add password confirmation after alert - https://zpl.io/2GR11XY

**Comment by chapati** [comment]
Moved to #1478
