### ISSUE TITLE
Pixelated BEAM logo

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#1006]
On 100% scale you get 
![Selection_054](https://user-images.githubusercontent.com/846272/66919813-b788cf80-f02a-11e9-8a5c-6e87f016ce7a.png)

Note: this issue is a result of fixing blurry logo on high dpi scales

**Comment by Roberrtt** [comment]
Make images the logo and "BEAM" a clearer 
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5c88ecca5a12d91940275c8c
![Screenshot_18](https://user-images.githubusercontent.com/50007056/70122343-84090f80-1681-11ea-8880-de05edeec95c.png)

**Comment by Roberrtt** [comment]
checked
