### ISSUE TITLE
Export / import transaction history, tags and addresses

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam#1009]

**Comment by dariatarakanova** [comment]
------ Export
- Add "Export wallet data" and "Import wallet data" on Settings screen https://zpl.io/V0prm8m
- If user choses export, open this screen https://zpl.io/am77ZLQ (by default all items in the list should be selected). Next open default export screen.

------ Import
- If user chooses Import open Files screen https://zpl.io/VQddXEx

Import alerts are here https://zpl.io/agOO4mR and https://zpl.io/2yGGvoG

**Comment by chapati** [comment]
Moved to #1481
