### ISSUE TITLE
Node connectivity in UI wallet

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#101]
The following statuses should be supported:
* green (online): wallet is connected to node, node has no known errors (example: no node configuration errors, no version incompatibility etc)
* red + error message: either wallet is not connected to the node or node has known errors (example:  node is not connected to peers etc)

**Comment by kaminskyelina** [comment]
Additionally to the color, need add suggestions for user 
For example "Check internet connection", "Change Note in Settings" or something else that will help to user to solve the problem by himself.  @sasha-abramovich  what do you think?

**Comment by gingervik** [comment]
@kaminskyelina @sasha-abramovich do you think that error message is not enought?

**Comment by sasha-abramovich** [comment]
@gingervik @kaminskyelina you both are right! the error messages should be actionable for the user. When the team will be able to list all the error messages we could phrase them appropriately :) Sometimes explicit instructions will come handy, sometimes just the error itself will be enough.

**Comment by Denis-Asipenko** [comment]
checked
