### ISSUE TITLE
Export transactions history (csv)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam#1010]

**Comment by dariatarakanova** [comment]
Steps:
1)Export in CSV format, according to the order that in the wallet
2) Save file

Please add export icon between search and payment proof icons. 
Design: https://zpl.io/2vPvPNj

No need to add export icon if we have no transactions.

**Comment by Denis-Asipenko** [comment]
Please change the statuses names when exporting the transaction history according to the design.
Also, when entering a comment on Cyrillic comment doesn't correctly display when exporting the transaction history.
![image](https://user-images.githubusercontent.com/45556620/69962773-c9153080-151f-11ea-86ff-64be8b6bc658.png)
Transaction statuses according to the design.
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5d0caf09627ac8566a69540a
![image](https://user-images.githubusercontent.com/45556620/69962942-2610e680-1520-11ea-9aa6-aeafb246e463.png)

**Comment by echoby** [comment]
Problem with Cyrillic actual only for Windows

**Comment by Denis-Asipenko** [comment]
checked
