### ISSUE TITLE
[UI SWAP] Restriction for Exchange rate

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#1013]
Please, restrict the Exchange rate to avoid incorrect rounding.
![image](https://user-images.githubusercontent.com/44496108/67011024-790d1680-f0f7-11e9-973a-83d41250847a.png)
We decided to restrict Exchange rate it should be more than `0.00000001`

If user input exchange rate >`0.00000001` as an example `0.000000011`
We should:
- mark the rate as red
- show the red error message under rate
- disable the buttons: `copy transaction token` & `publish transaction token` 
![image](https://user-images.githubusercontent.com/44496108/67011051-84604200-f0f7-11e9-802f-3e69e6e30fec.png)

**Comment by iamien1993** [comment]
Exchange rate works incorrectly
![image](https://user-images.githubusercontent.com/44057235/67087607-eed2ba00-f1ab-11e9-8a98-1d3d5b910cd2.png)

**Comment by VladislavKulyba** [comment]
1. Fill in Send amount field with 154 and Receive amount with 0.00000001. Click on comment, rate didn't count:
![image](https://user-images.githubusercontent.com/51320829/67280554-142a3580-f4d6-11e9-9f6c-63652879b599.png)
2. Fill in Send amount field with 154 and Exchange rate with 0.0000000001. Offer could be published.
![image](https://user-images.githubusercontent.com/51320829/67280632-3d4ac600-f4d6-11e9-85fd-01b9662fcc42.png)
3. Fill in Send amount field with 154 and Exchange rate with 0.00000000000001. The red error message under rate doesn't show.
![image](https://user-images.githubusercontent.com/51320829/67280845-b77b4a80-f4d6-11e9-8ec7-f295ec3a2b0a.png)
4. Fill in Send amount field with 154 and Receive amount with 154. Сomma after exchange rate value
![image](https://user-images.githubusercontent.com/51320829/67281092-5dc75000-f4d7-11e9-8042-41e84821a69c.png)

**Comment by chapati** [comment]
Everything should be perfect now.

**Comment by Roberrtt** [comment]
4.Fill in Send amount field with 154 and Receive amount with 154. Сomma after exchange rate value
![67281092-5dc75000-f4d7-11e9-8042-41e84821a69c](https://user-images.githubusercontent.com/50007056/67549613-58534b00-f70d-11e9-8612-2959fc4bacd1.png)

**Comment by Roberrtt** [comment]
Comma displayed if localization (Russian)
If in (England USA) localization, comma is not displayed

**Comment by Roberrtt** [comment]
Checked
