### ISSUE TITLE
[UI SWAP] Make balances copiable on Atomic Swap screen

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#1014]
When user right-clicks on the balance card to copy balance, the balance should be copiable
![image](https://user-images.githubusercontent.com/44496108/67013976-b2945080-f0fc-11e9-829b-ec8c40e30a93.png)

**Comment by gingervik** [comment]
please, remove local digital grouping symbol during copy

**Comment by Roberrtt** [comment]
Checked

**Comment by Roberrtt** [comment]
Reproduced

**Comment by Roberrtt** [comment]
Checked
