### ISSUE TITLE
[UI Swap] There is no vertical scroll on atomic swap screen

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1015]
1 -Wallet>atomic swap>create offer
2 -Wallet>receive>swap

Precondition
Screen resolution 1366 x768

Steps:
- go to 1 Or 2
- make scroll up and down.

Expected: There is a scroll to view the bottom buttons.
Actual: There is no scroll and it is impossible to see the bottom buttons.
![Screenshot_100](https://user-images.githubusercontent.com/50007056/67014209-1ae33200-f0fd-11e9-99dd-b0d28ec18d71.png)

**Comment by Roberrtt** [comment]
Scroll only works in full screen mode.
Also in the wallet settings.
In settings, swap scroll is, but does not go down to fill QTUM
![Screenshot_163](https://user-images.githubusercontent.com/50007056/67460155-f8906d80-f642-11e9-9f86-34805072aa25.png)
![Screenshot_164](https://user-images.githubusercontent.com/50007056/67460157-f9290400-f642-11e9-9238-43224dcc95f2.png)
![5](https://user-images.githubusercontent.com/50007056/67460644-3641c600-f644-11e9-8756-403ed7b24a25.gif)

**Comment by Roberrtt** [comment]
Not fixed
Build 4.0.6481

**Comment by VladislavKulyba** [comment]
checked
