### ISSUE TITLE
Avoid using double for amounts in swap module

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#1017]
This is not a good practice to use double for amounts since you can lost precision.
Please, check swap module for this issue.
If you convert amounts to string, do not use conversion to double too.

**Comment by chapati** [comment]
There are TODO:double for this after https://github.com/BeamMW/beam/commit/dc4c3a002d2e0d7d7cc216c776212304e0ae962b

Also please talk to me before changing UI. I would explain what has been done.

**Comment by VladislavKulyba** [comment]
checked
