### ISSUE TITLE
Decrease Transaction time on Exchanges

### ISSUE THREAD

**Issue by AndroidDev77** [BeamMW/beam#1019]
The time it takes to send Beam to an exchange like Binance is far too high. It takes upwards of a few hours, meanwhile Wallet to Wallet transactions only take 5 seconds. This is one of the great qualities this coin has over other coins. 

Design a solution for exchanges to better handle Beam transactions. This hour long delay can put customers off of using the coin as you can't even track the transaction after it is sent. Beam mining sites currently have the ability to send payments within seconds and Exchanges should implement the same.

Alternatively you can request exchanges explain that transaction times to exchanges are far greater than wallet to wallet transactions.

**Comment by gingervik** [comment]
Hello @AndroidDev77 
Exchanges set their own number of confirmations that is why it takes different time for different exchanges.
It does not depends on Beam
