### ISSUE TITLE
[UI SWAP] Token code doesn't change if user tries to change currency

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#1023]
Steps:
- open wallet
- go to Atomic Swap
- click on create offer
- change the sending currency to BEAM
- set the amounts for both sender & receiver
- change the receiving currency to BTC
Actual: offer token didn't change 
![token](https://user-images.githubusercontent.com/44496108/67207261-d9fc5d80-f41b-11e9-8335-4561e0b85501.gif)
Expected: offer token should be changed

**Comment by Roberrtt** [comment]
Checked:
