### ISSUE TITLE
[MOBILE] Wallet crash at the login. 

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1027]
This is a bug inside the library.
Error: **Fatal Exception: std::runtime_error
sqlite error code=1, cannot rollback - no transaction is active**
Crash log:
[com_mw_beam_beamwalletiosmainnet.txt](https://github.com/BeamMW/beam/files/3754356/com_mw_beam_beamwalletiosmainnet.txt)
Device : iPhone SE
Video of the crash of the wallet:
[video_2019-10-22_10-46-02.zip](https://github.com/BeamMW/beam/files/3754270/video_2019-10-22_10-46-02.zip)

**Comment by anatolse** [comment]
it was fixed in commit 7b35934120f24145c397d7f98c283b4753368dfc

**Comment by Denis-Asipenko** [comment]
checked
