### ISSUE TITLE
[UI SWAP] Need to increase amount size to 14 symbols

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1030]
build: 4.0.6441
![Screenshot_147](https://user-images.githubusercontent.com/50007056/67377118-dd175b00-f58d-11e9-9a5f-3a790a6bba96.png)
![Screenshot_148](https://user-images.githubusercontent.com/50007056/67377119-ddaff180-f58d-11e9-85cb-ca18620d26c8.png)

**Comment by gingervik** [comment]
Relates to #942

**Comment by Roberrtt** [comment]
When you open the transaction information, the transaction amounts move down
![6](https://user-images.githubusercontent.com/50007056/67520862-58722d00-f6b2-11e9-9b70-8d58e128849d.gif)

**Comment by Roberrtt** [comment]
Checked
