### ISSUE TITLE
[UI SWAP] Inaccurate rounding of rate to beam (0.2>1.9999999)

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1035]
Precondition
10 must be entered in the "send amount " field

If you put 1.9999998565 in rate, the amount in the beam(receive) is rounded not correctly
Also, if you insert the number 13.99999999 in  beam(receive),  rate is rounded not correctly

Receive and rate must match the entered data

![Screenshot_175](https://user-images.githubusercontent.com/50007056/67488174-07454780-f678-11e9-9010-f4b08d88e216.png)
![Screenshot_177](https://user-images.githubusercontent.com/50007056/67488177-07454780-f678-11e9-930f-a63ab4ae27f8.png)
![Screenshot_178](https://user-images.githubusercontent.com/50007056/67488178-07ddde00-f678-11e9-9758-71330d10f44f.png)

**Comment by VladislavKulyba** [comment]
Incorrect rate rounding to maximum emisssion

[2019-11-04_9-58-58.zip](https://github.com/BeamMW/beam/files/3803505/2019-11-04_9-58-58.zip)

**Comment by VladislavKulyba** [comment]
checked
