### ISSUE TITLE
[UI SWAP] Add new status for swap progress and forbid using cancel when it's not possible

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#1037]
@alexandrashelenkova @sasha-abramovich 
1. We need to add new status (or statuses) for swap progress to make progress clearly understanding for the user.
As an example when users start the swap, but one of side close the wallet(another side will wait for the response)

2. @Aleksandr-Starun we need to forbid using cancel when it's not possible according to the swap progress

**Comment by sasha-abramovich** [comment]
Need to discuss with @BigRomanov. I'd suggest to have the same status icon but write something like "initializing transaction", "waiting for peer" etc. Thoughts?

**Comment by alexandrashelenkova** [comment]
Agreed

**Comment by Aleksandr-Starun** [comment]
1) Status "waiting for peer" has already added.
2) "cancel" disabled when it's not possible according to the swap progress
