### ISSUE TITLE
[UI SWAP]If you stretch the application, transaction details are not displayed

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1038]
Also, it is reproduced if you move between " Active offers" and " Transaction "
Expectated.Transaction details are displayed.
![1](https://user-images.githubusercontent.com/50007056/67678414-95327280-f997-11e9-8a99-79d9d704647b.gif)
![2](https://user-images.githubusercontent.com/50007056/67678415-95327280-f997-11e9-8b8d-e9daaa3ad8b8.gif)

**Comment by echoby** [comment]
@chapati 
review, pls

**Comment by chapati** [comment]
It looks OK.

**Comment by gingervik** [comment]
checked
