### ISSUE TITLE
[cli swap] Move all swap commands to one specific group

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#1045]
![image](https://user-images.githubusercontent.com/44496108/67755941-24985e00-fa4a-11e9-9062-799f65b388f2.png)
Make the group for command and move there the commands:
- swap_init
- swap_accept
- set_swap_settings
- show_swap_settings

**Comment by Denis-Asipenko** [comment]
Please move the commands to the left column. We need all the teams to be on the same side.
![image](https://user-images.githubusercontent.com/45556620/70312089-f4e82d00-1823-11ea-820e-3b064ceac0d1.png)

**Comment by Denis-Asipenko** [comment]
checked
