### ISSUE TITLE
Update Beam Desktop Wallet icon

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam#1048]
Please updates app icons on Mainnet, Testnet and Masternet

https://drive.google.com/drive/folders/1d2-r4EZpdTeOYHWKGLxfycR0-pvxlKYO?usp=sharing

**Comment by VladislavKulyba** [comment]
wrong displaying of icon on task bar
![image](https://user-images.githubusercontent.com/51320829/72803353-f39d8300-3c5e-11ea-8324-6d68e33df076.png)

**Comment by VladislavKulyba** [comment]
checked on Masternet.
Waiting for Testnet and Mainnet

**Comment by VladislavKulyba** [comment]
checked on testnet
checked on mainnet
