### ISSUE TITLE
Wallet won't open in Ubuntu 16.04

### ISSUE THREAD

**Issue by semafor0** [BeamMW/beam#105]
I successfully installed the .deb wallet client, and I see the icon now in my applications. When I run it, the icon appears on the app sidebar, glows a few times, and then closes. I don't see any UI or dialog box.

**Comment by Sergei-Beam** [comment]
Hi @semafor0 

Thanks for your efforts to make Beam better.
It's known issue which was fixed, but it looks like on your PC it reproduced again.
Can you please install the Kdump and send me the generated file? 
Please use for install the next command on terminal: 
```$ sudo apt-get install linux-crashdump kdump-tools``` 
On all dialog windows push yes, then again run the wallet.
Go to ``` /var/crash/```  find  the crash file it should be called something like **usr_bin_BeamWalet.1000.crash**
Thank you.

Regards,
BEAM team

**Comment by semafor0** [comment]
I installed kdump and ran it again, but no report is generating.

**Comment by gingervik** [comment]
Hi @semafor0 
please check out supported platforms https://documentation.beam.mw/en/agile-atom-4194/rtd_pages/user_supported_platforms.html
At the moment Beam only works on processors that support AVX instruction set.
