### ISSUE TITLE
[UI Swap] Wrong displaying of the status 'connect other currency wallet to start trading' when resizing is happened.

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam#1054]
Pre-conditions:
1. Wallet is opened.
2. The nodes for swap in settings are disconnect.

Steps to reproduce:
1. Open Atomic Swap Tab. Status is showing as 
![image](https://user-images.githubusercontent.com/51320829/67941122-09625580-fbe6-11e9-8c3d-773612fdadfe.png)
2. Go to Settings -> Swap and connect to 2 of 3 nodes.
3. Open Atomic Swap Tab.

Expected: Status is showing on two lines, you could read full sentense
Actual: 
![image](https://user-images.githubusercontent.com/51320829/67941397-91e0f600-fbe6-11e9-989a-4142e579fd3d.png)

**Comment by gingervik** [comment]
checked on d.d._4.0.6580
