### ISSUE TITLE
Error when try to run BeamWallet on Linux

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#106]
error while loading shared libraries libcudart.so.10

**Comment by vrvaderom** [comment]
This happens on my new Dell Latitude E7450 as well.
Also happens on GPU Amazon instance with NVIDIA Tesla GPU and MATE desktop.

**Comment by nesbox** [comment]
seems on current master branch (testnet3 in near future) we don't have dependency with `libcudart.so`, while testnet2 has.
just carefully check it on `testnet3`.

**Comment by gingervik** [comment]
checked on testnet 3. can be closed
