### ISSUE TITLE
Minor Spelling Error

### ISSUE THREAD

**Issue by Alesio7** [BeamMW/beam#1064]
"i agree" instead of "I agree" is not formal. Version 3.1.5765 on macOS Mojave
![68089760-52124c80-fe3a-11e9-815e-305795dc9c0a](https://user-images.githubusercontent.com/41215180/68226500-2d47e180-ffc0-11e9-9496-ac41449b4a75.png)

**Comment by gingervik** [comment]
fixed on mainnet_rc
