### ISSUE TITLE
Update Testnet and Masternet gradient colors

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam#1068]
Please change gradient on Testnet and Masternet.

Testnet colors: https://zpl.io/an7j97n https://zpl.io/VDoXnLJ
Masternet colors: https://zpl.io/beOloRq https://zpl.io/br0dWwX

**Comment by VladislavKulyba** [comment]
Checked for masternet. Waiting for new version of testnet

**Comment by VladislavKulyba** [comment]
checked on testnet
