### ISSUE TITLE
Wallet stucks when updating to new version.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1069]
Steps to reproduce behavior:
1. Upgrade your existing wallet to a new version.
2. After the update, run the wallet.
Expected: The wallet is started and a folder with the version number for the database is created.
Actual: Wallet stucks and running in the background. After retry the startup is created Beam Wallet4.dmp.
[Beam Wallet4.zip](https://github.com/BeamMW/beam/files/3814350/Beam.Wallet4.zip)

**Comment by gingervik** [comment]
checked on mainnet_rc
