### ISSUE TITLE
BeamWallet will not open in Ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by joshbpa** [BeamMW/beam#107]
The application appears to install but will not open. I have attached a log file from /var/crash.
[usr_bin_BeamWallet.1000.crash.txt](https://github.com/BeamMW/beam/files/2615892/usr_bin_BeamWallet.1000.crash.txt)

**Comment by gingervik** [comment]
Hi @joshbpa 
Seems like your processor doesn't support AVX instructions.
It will be fixed in next release (coming soon)

**Comment by gingervik** [comment]
https://documentation.beam.mw/en/agile-atom-4194/rtd_pages/user_supported_platforms.html
