### ISSUE TITLE
[UI Wallet]Sorting status is incorrectly sorted by DESK and ASK

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1070]
Status 'sent to own address' higher than "received"
![Screenshot_285](https://user-images.githubusercontent.com/50007056/68303668-631ac200-00b5-11ea-99cb-5b6a55c34bcd.png)

**Comment by sasha-abramovich** [comment]
let's make it alphabetical order

**Comment by gingervik** [comment]
checked
