### ISSUE TITLE
Add functionality to auto-deletion and rebuilding the UTXO-image if it is damaged somehow

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#1075]
If user closed the wallet and damaged UTXO-image.
Next time when he will start the wallet if we detect that UTXO-image is almost correct but damaged we should auto-delete and rebuilding it.

**Comment by rojomisin** [comment]
possibly relevant, I had a bug where the rebuilding `node-utxo-image.bin` file for a v4 beam-node, was stuck without messaging/logging. had to kill -9 process.  

1. start a 4.x sync and stop
2. copy in a new 5.x beam-node binary and start sync w/ mining config, keys etc
3. run beam node and it is stuck at 
"Rescanning owned Txos..." w/ no output, can't kill process

**Comment by valdok** [comment]
During initialization the node re-evaluates its state and compares to what it should be. If this fails - it deletes the existing node-utxo-image.bin, rebuilds it, and tries again.

We don't have other "light" means to test the validity of this file.
