### ISSUE TITLE
Create Offer screen fixes

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#1077]
- Don't display "my address"
- Everything should be called "Swap token" (no transaction token, no addresses, no contacts)
- "Publish Transaction Token" rename to "Publish Offer"

**Comment by chapati** [comment]
This error message left intact wit the 'address' in it. This is approved by Abramovich
![Selection_093](https://user-images.githubusercontent.com/12074933/68585770-be81f100-04b5-11ea-9acf-6b13dcb84426.png)

**Comment by gingervik** [comment]
checked on dd_4.0.6612
