### ISSUE TITLE
Accept Offer screen: textual fixes

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#1082]
- The title of the screen should be “Accept Swap Offer” 
- Notification on “Own Offer” text – Change to: “You cannot accept your own offer”, the dialog box should say "The swap token was generated by you, and therefore cannot be accepted." and display the "I understand" on the only button.

**Comment by Roberrtt** [comment]
Checked

**Comment by Roberrtt** [comment]
Buttons "Accept Offer ,Create Offer ,Send ,Receive" written with a capital letter. 
Make it to be written with a lowercase letter
![Screenshot_108](https://user-images.githubusercontent.com/50007056/68833503-aa600e80-06c4-11ea-96b6-b18920974ca4.png)

**Comment by chapati** [comment]
Now only buttons with text starting with "I " should be uppercase

**Comment by Sergei-Beam** [comment]
Checked
