### ISSUE TITLE
Create Offer screen: fix error message

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#1085]
- “QTUM is not connected” error message appears on the right-hand side when a user chooses QTUM. But, when he chooses QTUM on the left side, the message does not appear (while it should)
- Remove the dot at the end of “%S not connected” error message.

**Comment by chapati** [comment]
Also added fee check in 'Accept Offer' window

**Comment by chapati** [comment]
Please review, a lot of changes

**Comment by roman-strilets** [comment]
everything is ok

**Comment by Roberrtt** [comment]
Checked
