### ISSUE TITLE
[GUI Wallet] - Swap Settings - Password isn't required after edition seed phrase

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam#1086]
Pre-conditions:
1. Switch to electrum
2. Node address is filled in.
Steps to reproduce:
1. Click on generate new seed phrase. Popup 'Generate new seed phrase' is opened
2. Enter the password. Popup 'New seed phrase' is opened
3. Click generate another seed phrase and than close this popup.
4. Click on edit your seed phrase and enter the password. Popup 'Enter your seed phrase' is opened
5. Enter valid data instead of one word. Click on apply
6. Click on edit your seed phrase again

Expected: Popup 'Edit seed phrase' is opened and required the password
Actual: Password isn't required.

[2019-11-04_16-31-28.zip](https://github.com/BeamMW/beam/files/3830568/2019-11-04_16-31-28.zip)

**Comment by echoby** [comment]
Can't reproduce. Build 4.1.6961

**Comment by VladislavKulyba** [comment]
This issue not reproduces anymore
