### ISSUE TITLE
Create offer screen: Exchange rate functionality should be more easily discovered

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#1087]
- Exchange Rate control should be better discoverable (somehow other input fields are very clear, while this one can easily pass unnoticed)

**Comment by alexandrashelenkova** [comment]
Design is here https://zpl.io/VxQWz0E
- Move Exchange rate field to transaction fee line
- Make input field longer
- Automatically put offered exchange rate (but keep the it editable)

Was
![image (2)](https://user-images.githubusercontent.com/7249484/68770759-b8307800-0661-11ea-834b-658ce6119720.png)

New
![receive-swap - currency swap](https://user-images.githubusercontent.com/7249484/68770777-be265900-0661-11ea-9261-caca966f3363.jpg)

**Comment by Sergei-Beam** [comment]
checked
