### ISSUE TITLE
When you click "copy transaction address" address don't save and don't close screen.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1090]
When we click on "copy transaction address" the address should be saved in the "**Addresses**" screen(tab "**MY ACTIVE ADDRESS**") and the "**Receive**" screen should be closed.
Also, address should be saved when user navigates to another screen from the "**Receive**" screen.
![image](https://user-images.githubusercontent.com/45556620/68574069-24e91e00-047a-11ea-8d06-12680b4823b8.png)

**Comment by Roberrtt** [comment]
Checked
