### ISSUE TITLE
Swap confirmation panel: textual fixes

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#1093]
- The text in the window relates to a regular transaction, not to the swap. The text should be ”Keep your wallet online. The swap normally takes about 1 hour to complete." 
- The title should be “Confirm atomic swap”

**Comment by chapati** [comment]
(%number_of_confirmations %currency_name confirmations) - this is removed (approved by Romanov)

**Comment by gingervik** [comment]
checked
