### ISSUE TITLE
Atomic Swap: transaction fees should be clarified

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#1094]
In Swap Send/Receive/Confirm/Transaction details:
- Transaction Fee -> BEAM Transaction Fee
- Transaction fee rate - > BTC(LTC/QTUM) Transaction Fee Rate

**Comment by gingervik** [comment]
![image](https://user-images.githubusercontent.com/28015224/68647227-6b985000-052e-11ea-89f5-7861c8624a78.png)

**Comment by chapati** [comment]
For beam network it is always flat fee (no rate). Rate is used for BTC/LTC/QTUM fees. So it is correct.

**Comment by gingervik** [comment]
checked
