### ISSUE TITLE
Hide Balances and Transaction Amounts

### ISSUE THREAD

**Issue by Alesio7** [BeamMW/beam#1097]
There's no option for this feature on desktop:
![Screen Shot 2019-11-11 at 6 51 18 PM](https://user-images.githubusercontent.com/41215180/68630126-5088fa00-04b4-11ea-8f9e-56f812484d3d.png)

Here's mobile:
![IMAGE 2019-11-11 18:54:25](https://user-images.githubusercontent.com/41215180/68630267-bffee980-04b4-11ea-9ecb-1a6f63d52b5f.jpg)

**Comment by gingervik** [comment]
hello @Alesio7 functionalities on desktop and mobile platforms are different. For mobile hide mode was implemented because people use phones in public places.
We are not going to implement it in Desktop version in next releases

**Comment by Alesio7** [comment]
I think it would be a useful feature to have for showing a relative or friend how to interact within the Beam wallet so they can use it themselves. For now, I will close the issue.
