### ISSUE TITLE
Changing logic of swap cancellation

### ISSUE THREAD

**Issue by Aleksandr-Starun** [BeamMW/beam#1101]
Main changes: 
1. Refund time was reduced to  6 and 12 hours
2. Fast cancellation: if first side locked coins, and second side cancelled tx then first side would make fast refund
3. Fast refund: if Beam side made refund, then BTC side also can make fast refund

Other changes:
1. Transaction can expire
  - offer expiration time is over
  - second side accepted offer but first side was not online for 2 hours
2. BTC side will not try to do Beam Redeem if there are less then 60 blocks to Beam Refund 
3. fee и feeRate selected by user are used in all transactions (for example, for Beam side fee will be used for Beam lock and Beam Refund transactions)
4. If creating of Beam transactions takes long time and there are less then N blocks then swap will be failled with error that there is not enouth time for BTC(LTC/QTUM) Lock
  N for:
  BTC - 70
  LTC - 20
  QTUM - 30

**Comment by Sergei-Beam** [comment]
checked
