### ISSUE TITLE
Swap - Add ability to connect to random Electrum node

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#1102]
it would be good if user have ability to connect to random electrum node. Please, add in settings section

**Comment by Sergei-Beam** [comment]
@alexandrashelenkova Just as an example and an idea to this task
In original Electrum wallet same settings look like that:
1. Autoconnection to a random node
![image](https://user-images.githubusercontent.com/44496108/70240494-5fdf2880-177e-11ea-
8930-714e1601b24e.png)
2. Manual mode, where user can type any of server or chose anyone from the list and set it as a server without manual typing
![image](https://user-images.githubusercontent.com/44496108/70240521-6cfc1780-177e-11ea-8777-459e6f0a62c7.png)

**Comment by beam-mw** [comment]
Let's just connect to a random node from the list without presenting the full list. That way it will work exactly like connecting to a random beam node. Just the actually connected node (ip or url) will be shown.

If the current node disconnects, the user will be automatically switched to another node, and the field will be updated.

**Comment by alexandrashelenkova** [comment]
Updated design here https://zpl.io/bAnwzwn
@sasha-abramovich please approve.

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova left my comments

**Comment by alexandrashelenkova** [comment]
Fixed. 
Please note that Random node should be selected by default.

**Comment by roman-strilets** [comment]
mainnet electrum nodes.
btc:
104.248.139.211:50002
148.251.22.104:50002
157.245.172.236:50002
167.172.42.31:50002
178.62.80.20:50002
2AZZARITA.hopto.org:50006
52.1.56.181:50002
Bitkoins.nl:50512
bitcoin.grey.pw:50004
bitcoin.lukechilds.co:50002
bitcoin.lukechilds.co:50002
blkhub.net:50002
btc.electroncash.dk:60002
btc.litepay.ch:50002
btc.usebsv.com:50006
e5a8f0d103c23.not.fyi:50002
electrum.hodl-shop.io:50002
electrum.jochen-hoenicke.de:50005
electrum.networkingfanatic.com:50002
electrum.vom-stausee.de:50002
electrum1.privateservers.network:50002
electrum2.privateservers.network:50002
electrumx.electricnewyear.net:50002
electrumx.schulzemic.net:50002
exs.ignorelist.com:50002
fortress.qtornado.com:443
hamsterlove.ddns.net:50002
ns3079943.ip-217-182-196.eu:50002
ns3079944.ip-217-182-196.eu:50002
thanos.xskyx.net:50002
vps4.hsmiths.com:50002
xtrum.com:50002
satoshi.fan:50002

ltc:
backup.electrum-ltc.org:443
btc.cihar.com:60002
electrum-ltc.bysh.me:50002
electrum.ltc.xurious.com:50002
ltc.litepay.ch.org:50022

qtum:
s1.qtum.info:50002
s2.qtum.info:50002
s3.qtum.info:50002
s4.qtum.info:50002
s5.qtum.info:50002
s7.qtum.info:50002
s8.qtum.info:50002
s9.qtum.info:50002

**Comment by roman-strilets** [comment]
testnet electrum nodes.
btc:
testnet.qtornado.com:51002
bitcoin.cluelessperson.com:51002
testnet.hsmiths.com:53012
testnet1.bauerj.eu:50002
tn.not.fyi:55002

ltc:
electrum.ltc.xurious.com:51002
electrum-ltc.bysh.me:51002

qtum:
s1.qtum.info:51002
s2.qtum.info:51002
s3.qtum.info:51002

**Comment by Sergei-Beam** [comment]
checked, but would need to recheck on mainnet too
