### ISSUE TITLE
Extend swap details with explanations what is happening and with time estimations

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#1104]
Atomic swaps:
* Waiting for peer: if no peer will respond in %XX %timeunits, the swap will be canceled automatically
* In progress [normal]: the swap is expected to complete in %XX %timeunits at most
* In progress [refunding]: the refund of your %coins will start in %XX %timeunits (actual refund duration depends on the transaction fee specified for the %coins blockchain)

all the times are displayed maximum in 5mins quants

**Comment by Sergei-Beam** [comment]
@anatolse Please change the text for case 
- Waiting for peer

**Comment by azaidelson** [comment]
Waiting for peer: if nobody accepts the offer in %XX %timeunits, the offer will be automatically canceled 
In progress [normal]: the swap is expected to complete in %XX %timeunits at most
In progress [refunding]: the refund of your %coins will start in %XX %timeunits. Refund duration depends on the transaction fee you specified for %coins

**Comment by sasha-abramovich** [comment]
Also
* indicate the "canceling" status with "Refunding" in extending transaction details.
* "pending" should be called "waiting for peer"

**Comment by Aleksandr-Starun** [comment]
"canceling" will be done in separate task #1115

**Comment by Denis-Asipenko** [comment]
@Aleksandr-Starun Messages must begin with a capital letter.
![image](https://user-images.githubusercontent.com/45556620/69343997-ae210180-0c7f-11ea-9b98-70f5bc2a1e12.png)

**Comment by Denis-Asipenko** [comment]
checked
