### ISSUE TITLE
Extend tx details with explanations what is happening and with time estimations 

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#1105]
Normal transactions:
* Waiting for sender/receiver: If the [sender|receiver] won't get online in %XX %timeunits, the transaction will be cancelled automatically
* In progress (normal): The transaction is expected to complete in %XX %timeunits

**Comment by sasha-abramovich** [comment]
* In progress (normal): The transaction is usually expected to complete in a few minutes.
* In progress (long): It is taking longer than usual. In case the transaction could not be completed it will be canceled automatically in %XX %timeunits.

**Comment by Sergei-Beam** [comment]
@anatolse please make the next changes:
1. Change text according to the comment https://github.com/BeamMW/beam/issues/1105#issuecomment-561528147 for both sender and receiver
2.Waiting for sender/receiver - change a typo in the word _cancelled_ to **canceled** 
3. Move payment proof buttons to the top.
![image](https://user-images.githubusercontent.com/44496108/70125464-dbaa7980-1687-11ea-84ef-3902753e2cbc.png)

**Comment by anatolse** [comment]
p.3 I just hid this buttons for "in progress" status

**Comment by Sergei-Beam** [comment]
The timer is increasing instead of decreasing from 2h till expired
![image](https://user-images.githubusercontent.com/44496108/70513583-ff1b6b80-1b42-11ea-8cf3-6ed992b286a8.png)
![image](https://user-images.githubusercontent.com/44496108/70513591-0478b600-1b43-11ea-9e55-f1eb1d3ec542.png)

**Comment by Sergei-Beam** [comment]
checked
