### ISSUE TITLE
Warn BTC sender about charging the transaction fee

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#1112]
ignore this

**Comment by sasha-abramovich** [comment]
![image](https://user-images.githubusercontent.com/44961099/69236091-65a50d80-0bc5-11ea-8b87-2a4e269231f0.png)
Write the same message above the buttons.

**Comment by azaidelson** [comment]
Text: "Once the offer is accepted by the other side, the BTC transaction fee will be charged even if the offer is cancelled"

**Comment by Roberrtt** [comment]
checked
