### ISSUE TITLE
Warn user if he has active transactions which require wallet to be online

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#1116]
Beam transactions have negotiation states, when wallet communicates with another wallet (they have to sign simple tx or lock tx). If wallet will go offline being in these states, then transactions may become expired. We should warn users about this when he closes wallet app.

**Comment by Roberrtt** [comment]
If you accept the transaction and try to close the application,  up a pop-up with a warning, when we cancel the warning and go to the wallet tab, up a popup.
![12](https://user-images.githubusercontent.com/50007056/69403113-d0ac2c80-0d0a-11ea-8665-0b4454b1ff62.gif)

**Comment by Roberrtt** [comment]
When offer in "waiting for peer", we don't show popup a warning

**Comment by Roberrtt** [comment]
Checked
