### ISSUE TITLE
Create Offer: expiration time should also have shorter time intervals

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#1122]

**Comment by alexandrashelenkova** [comment]
15, 30 min, 1-2-4-6-12 hours

**Comment by dariatarakanova** [comment]
Please make "Offer expiration time" **30 minutes** by default.
Another choosable variations are: 15 minutes, 1 hour, 2 hours, 6 hours.

https://zpl.io/VqlKPrm

**Comment by VladislavKulyba** [comment]
checked
