### ISSUE TITLE
Accept offer (from SBBS board): the token should not be presented

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#1124]

**Comment by beam-mw** [comment]
We just need to move the token to the bottom of the screen (as it is in the Create offer dialog today, small, grey and at the bottom) and also make it folded (with some triangle or something).

**Comment by alexandrashelenkova** [comment]
https://zpl.io/aR09QLn
https://zpl.io/bLnnNYD

**Comment by Roberrtt** [comment]
1.Make a hiding token for the screen "Create a Swap offer" and align the token text as on the screen "accept swap offer"
![Screenshot_322](https://user-images.githubusercontent.com/50007056/70701113-dd55ec00-1cdc-11ea-8ea9-a83105d39979.png)
2. Do the same design with a hidden token for the screen 'Accept swap offer' when we paste the copied token in the field 'Swap token'
https://zpl.io/aR09QLn
![Screenshot_323](https://user-images.githubusercontent.com/50007056/70701933-47bb5c00-1cde-11ea-9b3d-d434a97414c3.png)

**Comment by Roberrtt** [comment]
checked

**Comment by echoby** [comment]
Please, retest after a2f8b53 commit
