### ISSUE TITLE
Atomic swap: need to see "MY OFFERS" for all the pairs

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#1126]

**Comment by alexandrashelenkova** [comment]
Added "All coins" option in coins drop down. With selected "Only my offers" checkmarks, list will show all my offers for all the pairs.

**Comment by alexandrashelenkova** [comment]
Updated filters a  bit more (added Send/receive drop down, All/mine filter and multi choice for currencies). @gingervik do we still have time to implement it in current sprint please? Or should be moved to 4.2?
https://zpl.io/VKy7WAP
<img width="772" alt="Screenshot 2019-12-09 at 22 22 28" src="https://user-images.githubusercontent.com/7249484/70465632-65b47100-1ad2-11ea-9eb1-52657f46d7f2.png">

**Comment by gingervik** [comment]
@alexandrashelenkova 
discussed with @beam-mw 
moved to wallet improvements
