### ISSUE TITLE
Warn appears if there're no active transactions

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#1133]
Related to #1116
1. run wallet A
2. create an offer on Atomic Swap page (eg. BTC-> BEAM)
3. run and accept the offer on wallet B
4. Wait while BTC will be locked on wallet A
5. immediately cancel the offer on wallet B
6. wait while wallet A will have been done refund
7. try to close the wallet
Expected: Warn doesn't appear
Actual: Warn appears if there are no active transactions
![image](https://user-images.githubusercontent.com/44496108/69939551-2d6ccb80-14f1-11ea-86ff-d834fdf80517.png)

**Comment by VladislavKulyba** [comment]
checked
