### ISSUE TITLE
Add validator to set qtum feerate

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#1134]
User shouldn't be able to set the swap_feerate less than 500000 for QTUM 
![image](https://user-images.githubusercontent.com/44496108/69963749-ef3bd000-1521-11ea-8483-1acc15c384db.png)

**Comment by roman-strilets** [comment]
qtum min feerate: 400 000
ltc min feerate: 1000
btc min feerate: 1000

**Comment by Denis-Asipenko** [comment]
need change default fee for LTC
![image](https://user-images.githubusercontent.com/45556620/85523388-96439e80-b60f-11ea-8316-4dc495eaa095.png)

**Comment by Denis-Asipenko** [comment]
we also need to set these values for the API. In addition, we need to display a warning message if the user specified a fee below the minimum.https://github.com/BeamMW/beam/issues/1134#issuecomment-648102147
![image](https://user-images.githubusercontent.com/45556620/85703568-281eda80-b6e8-11ea-8ece-c7b87fcb8980.png)

**Comment by Denis-Asipenko** [comment]
checked
