### ISSUE TITLE
[GUI Wallet] Reduce the space between buttons "Show my wallet" and "Restore wallet or create a new one"

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam#1135]
The button "Restore wallet or create a new one" is closer to version wallet, when it should be closer to "Show my wallet"  
![image](https://user-images.githubusercontent.com/51320829/69954771-22279900-150d-11ea-90cc-862e853e0b2c.png)
This is particularly visible on fullscreen mode 
![image](https://user-images.githubusercontent.com/51320829/69954999-c01b6380-150d-11ea-9a85-855596a039f3.png)

**Comment by Roberrtt** [comment]
Wallet is created and the initial login screen of the wallet
When the screen resolution is 1368x768, the button "Restore wallet or create a new one" is not visible.
![Screenshot_318](https://user-images.githubusercontent.com/50007056/70602757-2f780e00-1c06-11ea-813e-3e6cde27118d.png)

**Comment by gingervik** [comment]
it's ok on 1920x1080
all resolution issues will be fixed in #15
