### ISSUE TITLE
UI Wallet crashing in Ubuntu 18.04.1

### ISSUE THREAD

**Issue by joshbpa** [BeamMW/beam#114]
I installed a new processor that supports AVX instruction set the UI wallet ui now loads properly. 

However, the wallet crashes when I attempt to login. I have attached the .crash files. I am using Beam Wallet desktop app version 1.0.3055

[_usr_bin_BeamWallet.1000.crash.txt](https://github.com/BeamMW/beam/files/2630785/_usr_bin_BeamWallet.1000.crash.txt)

**Comment by gingervik** [comment]
it should be fixed on Testnet 3 which is released in next several days
