### ISSUE TITLE
Reply with meaningful error message if the user try to import Electrum segwit seed 

### ISSUE THREAD

**Issue by vcorem** [BeamMW/beam#1140]
Currently, If the user tries to import Electrum segwit seed into the Atomic Swaps BTC settings, the Apply button is grayed out but there is no error message.

**Comment by gingervik** [comment]
We need to show error when we do not support this seed or there are mistakes in it
@sasha-abramovich please, provide text

**Comment by sasha-abramovich** [comment]
Suggested error message text: 
Segwit seed phrase is not supported yet.

**Comment by sasha-abramovich** [comment]
When the seed phrase is illegal/invalid, the error message should be:
Invalid seed phrase. Please check again and resubmit.

**Comment by Roberrtt** [comment]
checked
