### ISSUE TITLE
Support electrumx servers without full data

### ISSUE THREAD

**Issue by Aleksandr-Starun** [BeamMW/beam#1141]
We should add support servers without full TX's data to ignore errors like:
E 2019-12-05.10:04:30.473 [9095df5d7dee45179cd7cf87a1241ff8][5] Bridge internal error: type = 3; message = daemon error: DaemonError({'code': -5, 'message': 'No such mempool or blockchain transaction. Use gettransaction for wallet transactions.'})
D 2019-12-05.10:04:30.473 Async update started!

**Comment by gingervik** [comment]
Checked by @Sergei-Beam
