### ISSUE TITLE
Settings - Add reasons for node connection indicator

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#1146]
Please, add reasons for node connection indicator as it made for wallet connection indicator

![image](https://user-images.githubusercontent.com/28015224/70300097-ac227b00-1807-11ea-82bc-135b02eb19ec.png)

**Comment by alexandrashelenkova** [comment]
Added alert info here https://zpl.io/bAnwzwn
@sasha-abramovich please approve

**Comment by sasha-abramovich** [comment]
Approved.

**Comment by gingervik** [comment]
next reasons were added
- Cannot connect to node
- Invalid credentials
- Invalid genesis block (for Electrum only now)
