### ISSUE TITLE
Add info about fee when user create/accept offer

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#1148]
User should see amount of fee which will be taken from swap amount

Example: 
I did the following trade, and instead of 0.000724 BTC, I got 0.0004 BTC

@alexandrashelenkova please, add design for create offer screen, accept offer screen

**Comment by alexandrashelenkova** [comment]
Updated screens here 
https://zpl.io/aBpdY9m
https://zpl.io/aR09QLn
@sasha-abramovich please approve

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova except "sat" with small letters (or big letters everywhere) I have no comments. Just one question: are there any changes expected in the send confirmation window?

**Comment by alexandrashelenkova** [comment]
Changed letter to small ones. On send confirmation I think would be enough just to add one more line with Transaction fee.

**Comment by VladislavKulyba** [comment]
Please, add BTC Transaction fee (est) to transaction details
![image](https://user-images.githubusercontent.com/51320829/70899421-9d0dab00-2007-11ea-8506-7aeb35d9f43f.png)

**Comment by VladislavKulyba** [comment]
checked
