### ISSUE TITLE
beam-node core dumps with illegal instruction

### ISSUE THREAD

**Issue by joshbpa** [BeamMW/beam#115]
When I download and run the beam-node binary on Ubuntu 18.04.1 it core dumps with an illegal instruction.

I have installed a CPU that supports the AVX instruction set, so that is not the issue. I have attached the log file. I am using beam-node-1.0.3055

[node_18_11_29_15_16_50.log](https://github.com/BeamMW/beam/files/2630839/node_18_11_29_15_16_50.log)

**Comment by gingervik** [comment]
acc to logs I see that you stopped node after it tried to connect to peer
you should whait for a while
also you can add several peers like peer = 139.59.174.80:8100,167.99.221.104:8100,159.65.201.244:8100
@joshbpa

**Comment by gingervik** [comment]
no user's responce since testnet
