### ISSUE TITLE
[UI SWAP] Add exchange rate for both currencies

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam#1151]

**Comment by beam-mw** [comment]
We should always show one rate to BTC (LTC, QTUM). This should look exactly like in exchange.

**Comment by gingervik** [comment]
also for create offer screen we should show only BEAM to btc/ltc/qtum 
![image](https://user-images.githubusercontent.com/28015224/70426291-d2ece580-1a83-11ea-8186-843eec568bc6.png)

**Comment by gingervik** [comment]
checked for create/accept/offers
