### ISSUE TITLE
Immediately cancel offer on both sides which was applied but on Beam side, there are not enough available coins

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam#1152]
If the party that made the offer doesn't have Beams at the time when someone accepted the offer (replied), the transaction should be failed on both sides as quickly as possible

**Comment by gingervik** [comment]
Need to be discussed

**Comment by Sergei-Beam** [comment]
@anatolse description was updated, please take a look  it

**Comment by Sergei-Beam** [comment]
checked
