### ISSUE TITLE
Own offer changes the status from"Cancel offer" to "Accept offer"

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1153]
Description:
When we create an offer and remove the created address from this offer, our offer changes its status to " Accept offer"

Precondition:
Node LTC are configured, wallet open and the tab "Atomic swap" is open

Steps:
- click create offer
- create offer LTC -BEAM and publish offer
- the offer in active transactions has the status "cancel offer'
- open tab Address - delete new address
- open tab Atomic swap
- pay attention to the status of our offer 

Expected; own offer has the status "Cancel offer"
Actual: own offer has the status "Accept offer"
[2019-12-06 10-42-56-175.zip](https://github.com/BeamMW/beam/files/3931069/2019-12-06.10-42-56-175.zip)

**Comment by sasha-abramovich** [comment]
The smart user should see the following message:
"There is (x) active [transaction(s)|offer(s)] that use this address, therefore the address cannot be [deleted|edited]." and [ok button]. Of course, for editing the message should appear only when changing the address duration.

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova for the next sprint, we would like to have more informative message that helps to recognize the transaction related to the address. Such as: to show a transaction comment, an amount or something similar. Please attend for 4.2.

**Comment by gingervik** [comment]
1. If there are several active transactions message should be "There are (x) active [transactions|offers]"
2. If user has active offer message should be about offer. If regular transaction - transaction, if user gas swat transaction from accepted offer - transaction

**Comment by gingervik** [comment]
checked
