### ISSUE TITLE
Add ability to see block confirmation on Beam side

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam#1155]
![image](https://user-images.githubusercontent.com/51320829/70308766-08dc6080-181d-11ea-9a3a-78744f97ba63.png)

**Comment by Zeke133** [comment]
![image](https://user-images.githubusercontent.com/32778545/70849254-e2f23400-1e8c-11ea-8dc2-d6c87299eba4.png)
Warning message with content added:
"If peer will not finish negotiation in %1, the offer will be automatically canceled"

**Comment by sasha-abramovich** [comment]
> If the other side will not sign the transaction in %1 <time units>, the offer will be canceled automatically.

**Comment by VladislavKulyba** [comment]
checked
