### ISSUE TITLE
Settings screen - Connection settings modifying

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#1161]
1. Add separate field "Port" for general setting and swap(Electrum also)
2. Rename ip:port to "Remote node address" ![image](https://user-images.githubusercontent.com/28015224/70422070-20655480-1a7c-11ea-9589-e0f3167c145f.png)

**Comment by VladislavKulyba** [comment]
checked

**Comment by VladislavKulyba** [comment]
It's done only for general Settings. Please, add separate field "Port" for Swap Settings and Electrum.

**Comment by VladislavKulyba** [comment]
checked
