### ISSUE TITLE
Add ability to set swap fee < min

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#1162]
User should have an ability to set fee < min default (UI and cli for all currencys)
![image](https://user-images.githubusercontent.com/28015224/70423383-6de2c100-1a7e-11ea-83bf-876fd44ac485.png)

**Comment by sasha-abramovich** [comment]
Write under the commission field (in dark grey color):
Remember to validate the minimal expected commission with the [qtum|btc|ltc] blockchain.

**Comment by gingervik** [comment]
checked fo UI
@Roberrtt please check for cli

**Comment by Roberrtt** [comment]
checked

**Comment by Roberrtt** [comment]
Add a warning (Remember to validate the expected fee rate...) for:
- when we create  offer - send BTC  receive BEAM
- when we accept  offer - send BTC  receive BEAM

**Comment by Roberrtt** [comment]
checked
