### ISSUE TITLE
Swap offer doesn't appear sometimes on the board

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#1164]
When the user creates a swap offer it doesn't appear sometimes on the board.
Look the video below
https://drive.google.com/file/d/1Q0AxqNxn4psgRUmTUbbxOWvta4v70ShA/view

Note: I tried to reproduce it but on my side, it appears each time I try

**Comment by Zeke133** [comment]
I've tied to reproduce it on masternet, but unsuccessfully. On mainnet cloud node bug reproducible both with own and foreign wallets.

**Comment by Zeke133** [comment]
Did not reproduced on any other mainnet node than originating bug. Possible a problem in a cloud setup.

**Comment by gingervik** [comment]
@RaFuN you should re-setup your cloud node

**Comment by azaidelson** [comment]
Reproduces in 4.1.6978/

**Comment by azaidelson** [comment]
[beam v4.1.6978 windows report.zip](https://github.com/BeamMW/beam/files/3983885/beam.v4.1.6978.windows.report.zip)

[beam-node.cfg.txt](https://github.com/BeamMW/beam/files/3984719/beam-node.cfg.txt)

**Comment by azaidelson** [comment]
Upgrading the node to 4.1.6978 solves the problem
