### ISSUE TITLE
The CLI wallet crashes if node BTC Active connection=none

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1165]
If node BTC doesn't a connection(Active connection= none), then we should prohibit the creation of an offer 

Precondition:
There are 2 Wallets - A = CLI wallet    B= UI wallet
The wallets created, node BTC  is configured  but (wallet A) Active connection= none
![Screenshot_312](https://user-images.githubusercontent.com/50007056/70507013-903b1400-1b3c-11ea-91a0-fb12f828d0af.png)

Steps
- in wallet (A) create offer
- in wallet (B) accept this offer
- in wallet(A)  start to listen -n 127.0.0.1:10005

Expected: It was impossible to create an offer
Actual: Wallet doesn't listen and creates dump files

**Comment by roman-strilets** [comment]
please recheck it

**Comment by Roberrtt** [comment]
checked
