### ISSUE TITLE
Add ability to edit electrum server if it was disconnected during active transaction

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam#1166]
If Electrum server was disconnected, there is no ability to change Node address server and connect to other. Please add button "Edit Node address" for changing peer while there is active transaction.
![image](https://user-images.githubusercontent.com/51320829/70515118-d8126900-1b45-11ea-9ddd-e23665c077fe.png)

**Comment by Roberrtt** [comment]
checked
