### ISSUE TITLE
Change the transaction fee in details from BEAM to GROTH

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1168]
We need to specify the Transaction fee in GROTH instead of BEAM in details for swap and between the beam.
Instead 0.000001 BEAM - need specify 100 GROTH
![Screenshot_317](https://user-images.githubusercontent.com/50007056/70521709-bec2ea00-1b50-11ea-8744-1162cbde9cb4.png)

**Comment by gingervik** [comment]
checked for regular and swap transactions
