### ISSUE TITLE
Transactions table - Coin icons remain in place when sorted

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1169]
When sorting any of the columns(from,to,sent), the coin icons remain in place.
Also when there are many different transactions, the icons of the coins are swapped.
[Video.zip](https://github.com/BeamMW/beam/files/3948880/Video.zip)

Steps:
-create 2 offer BEAM> LTC  and 2 offer LTC < BEAM
-click column "To'
-look at the coin icons

Expected: coin icons are sorted together with the transaction
Actual: Coin icons remain in place

**Comment by gingervik** [comment]
checked
