### ISSUE TITLE
Cosmetic changes for the better clarity

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#117]
Please rename the following text labels

- Settings screen: _Mining threads_ to _Mining threads (CPU)_
- Settings screen: _Wallet location path_ to _Wallet folder location_
- UTXO screen: _Height_ to _Blockchain Height_, _Hash_ to _Last block hash_

Also:
- Please align the QR code and add _Scan to send_ caption.

**Comment by Denis-Asipenko** [comment]
checked

**Comment by gingervik** [comment]
Bug is reproduced again
![image](https://user-images.githubusercontent.com/28015224/49719751-1d6c3400-fc6f-11e8-862c-a41a27bc3b1f.png)

**Comment by Denis-Asipenko** [comment]
checked
![screenshot_7](https://user-images.githubusercontent.com/45556620/49731886-6dee8c00-fc85-11e8-97e2-5cd16241d933.png)
