### ISSUE TITLE
Swap transaction in waiting state has the wrong status in CLI

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#1170]
Steps:
- run CLI wallet
- setup swap settings
- initialize the swap token
- open the swap_tx_history
Expected: swap transaction has status `waiting for peer`
Actual: swap transaction has status `completed`
![image](https://user-images.githubusercontent.com/44496108/70605835-4883bd80-1c0c-11ea-914a-eb0ea64a6d07.png)

**Comment by gingervik** [comment]
checked on master 4.1.6836
![image](https://user-images.githubusercontent.com/28015224/70859876-1aafb900-1f2b-11ea-9e9a-a2c011a0af1a.png)
