### ISSUE TITLE
Wrong TX status in error message when I try to cancel usual tx in in_progress status

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#1171]
Steps:
- run CLI wallet
- send usual tx to another wallet
- try to cancel the tx in in_progress status
Expected: transaction doesn't cancel, the error message shows reason status `in progress`
Actual: transaction doesn't cancel, the error message shows reason status **`sending RefundTX`**
![image](https://user-images.githubusercontent.com/44496108/70605973-8ed91c80-1c0c-11ea-81aa-727b2667f79e.png)

**Comment by gingervik** [comment]
checked
