### ISSUE TITLE
Add WalletID as a 2FA for wallet transactions

### ISSUE THREAD

**Issue by beam-mw** [BeamMW/beam#1172]
Today, the wallet authentication is done using only the SBBS address, which also serves as a public key for the encryption of the wallet to wallet communications.

To properly support HW wallets and Wallet Service, this is not enough, since SBBS messages could not be handled by HW wallet (too much activity) or could be hijacked, in case of a wallet service.

For this purpose we need to add WalletID, as a second identifier used in wallet communications. WalletID will only be stored in the 'Secret Keeping' part of the software and used to sign and verify wallet to wallet communications

**Comment by anatolse** [comment]
Now, on receive view, UI wallet generates token which contains Sbbs peer ID and wallet identity.
Old wallets should be able to send Beams via this token, ignoring Identity (Payment proof should be done using Sbbs address)
Newer wallets should use identity for signing payment proof

**Comment by Sergei-Beam** [comment]
checked
