### ISSUE TITLE
Fee doesn't change to the one set in the settings for BTC\LTC\QTUM

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1182]
Precondition
Created and opened a wallet, settings are configured node BTC
Steps:
-go to settings>swap
-Insert in the default fee 600 for BTC and click apply
-Click the tab Atomic swap
-Click create offer > BEAM -BTC
-Please note the fee
Expected: fee is changed to the one set in the settings
Actual: fee not changed
[fee.zip](https://github.com/BeamMW/beam/files/3967294/fee.zip)

**Comment by gingervik** [comment]
ok for now
