### ISSUE TITLE
Status display in the table of active offers is shifted to the expiration

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1184]
When setting the date and time format, the region is English(US) 
![Screenshot_332](https://user-images.githubusercontent.com/50007056/70906158-d6014c00-2016-11ea-8ba4-dd1b741cec7f.png)
Statuses 'accept offer' and 'cancel offer' in active offers are shifted closer to expiration
![Screenshot_331](https://user-images.githubusercontent.com/50007056/70906354-37291f80-2017-11ea-8ed8-c64d03b9f4b6.png)

**Comment by VladislavKulyba** [comment]
checked
