### ISSUE TITLE
Create statuses for Atomic Swap: failing and canceling

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam#1185]
We have designed 2 more statuses for Atomic Swap:
- failing
- canceling

https://zpl.io/b6xJ58q

**Comment by gingervik** [comment]
Relates to #1125

**Comment by echoby** [comment]
Impossible to detect "canceling" status.
- first side cancel swap immediately
- second side failing swap, identical no matter the reasons
approved by @sasha-abramovich

**Comment by VladislavKulyba** [comment]
relates to #1444

**Comment by VladislavKulyba** [comment]
Checked
