### ISSUE TITLE
Add "Where to buy BEAM" to main screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam#1187]
1) This is how look non active icon https://zpl.io/2GwZmQ4
2) When click on icon it become active (green) https://zpl.io/2yEn7lp  - but it visible only under shadow with alert. https://prnt.sc/qbohak
3) After click opens alert https://zpl.io/VDdyOqq (as it was before)

**Comment by echoby** [comment]
Provided icon has cutted border.
<img width="626" alt="1" src="https://user-images.githubusercontent.com/1681548/71095806-4d251480-21be-11ea-9da2-feaf0ccef02c.png">
<img width="626" alt="2" src="https://user-images.githubusercontent.com/1681548/71095808-4d251480-21be-11ea-9332-c17de15cfebd.png">

**Comment by dariatarakanova** [comment]
@echoby fixed

**Comment by Roberrtt** [comment]
1.When access permission is enabled, a pop-up appears when you click the(Where to buy BEAM) button.
Expected: Opens the link, pop-up does not appear
![Screenshot_150](https://user-images.githubusercontent.com/50007056/71469424-1bbdd180-27da-11ea-9e35-e05d817fe6e5.png)

2.When we open the link , go to the wallet, the permission is disabled. Expected: allow access - enabled
[video.zip](https://github.com/BeamMW/beam/files/4002053/video.zip)

**Comment by Roberrtt** [comment]
checked
