### ISSUE TITLE
Network status should display which node it is connected to.

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#119]
**Describe the current situation we have**
Currently the status information displays the connectivity status but not the details about the connected node. 

**Describe the solution you'd like**
The status should include the info about which node we are connected to: random node (and IP), specific node (and IP) or a node which is bundled with the wallet (no need for IP).

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova please attach the design (not urgent).

**Comment by alexandrashelenkova** [comment]
Screenshots:
zpl.io/VKolGwW
zpl.io/aREwQzn
zpl.io/awmWMBd

**Comment by alexandrashelenkova** [comment]
zpl.io/blPjJe1

**Comment by alexandrashelenkova** [comment]
We show that info in setting, better not to overload status here.
