### ISSUE TITLE
When importing a file to a mobile wallet, it gives an error.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1192]
When importing this file, the error "incorrect file" appears in the mobile wallet.
Error in logs-E 2019-12-18.09:16:01.657 Transaction [f2de701ac67d4171ab9517a8c7c8927a] was not imported. Invalid myID parameter.
Imported file-[All .zip](https://github.com/BeamMW/beam/files/3977682/All.zip)
Also, if you import this file into CLI wallet, it also gives an error-
![image](https://user-images.githubusercontent.com/45556620/71158693-6e850f80-2255-11ea-9901-4da03f84701b.png)
Imported file in CLI-[All.zip](https://github.com/BeamMW/beam/files/3982628/All.zip)
wallet.db-[wallet.zip](https://github.com/BeamMW/beam/files/3977687/wallet.zip)
seed phrase- dance;cost;stamp;crazy;north;trade;rifle;hungry;wife;wood;discover;oven;

**Comment by anatolse** [comment]
I found the reason of this behavior. It was forgotten hack in deleteTx method which was aimed to avoid zombi transactions. When user selects "Delete transaction " we do not delete all records about transaction, we leave one (TransactionType), this allows us not to accepts already processed transaction.

**Comment by Denis-Asipenko** [comment]
checked
