### ISSUE TITLE
Wrong indicator when system time is not syncronized

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#1196]
when user has error "system time is not syncronized" indicator should be red even if he is connected to his trusted node
![image](https://user-images.githubusercontent.com/28015224/71150829-7d62c680-2243-11ea-875d-8753ff688021.png)
 may be we need red lock icon

**Comment by gingervik** [comment]
https://beam.testquality.com defect [D23](https://beam.testquality.com/project/5267/result/1736568/defect/6045). Do not remove or edit.

**Comment by VladislavKulyba** [comment]
checked
