### ISSUE TITLE
Total amount of transaction is shown incorrectly before sending

### ISSUE THREAD

**Issue by azaidelson** [BeamMW/beam#120]
**Bug description**
I am sending an amount of 67.15 Beam specifying transaction fee of 10 Groth. In the "Send confirmation" window, the total amount shown appears as 67.150010000001
The last digit is not correct. The amount should be 67.15001

**To Reproduce**
Steps to reproduce the behaviour:
1. Start wallet
2. Create a Send transaction, specify amount and fee
3. Chec what appears in the Send window

**Current behaviour**
Amount is wrong

**Expected behaviour**
Amount needs to be correct

**Platform and build**
Windows 10
BEAM Build : 1.0.3056

**Configuration, log, memory dump files (if applicable)**
![wrongamount](https://user-images.githubusercontent.com/21197401/49429614-94a65180-f7b1-11e8-8b6a-7a81abcf5a02.jpg)

[beam v1.0.2516 windows report.zip](https://github.com/BeamMW/beam/files/2643023/beam.v1.0.2516.windows.report.zip)
Add relevant files. The filenames and locations are described here: https://github.com/BeamMW/beam/wiki/Folder-and-file-locations

**Log file(s) (if applicable)**
Add relevant log file(s),  located in the `logs` folder.

**Screenshots (if applicable)**
Add screenshots that illustrate a problem you've found.

**Comment by Sergei-Beam** [comment]
@azaidelson In Testnet_3 we'll fully change this dialog see the attached screenshot bottom
![image](https://user-images.githubusercontent.com/44496108/49436275-c9260780-f7c9-11e8-9c76-9338cd20bbac.png)
