### ISSUE TITLE
Add "Payment Proof" to the Export Transaction History

### ISSUE THREAD

**Issue by RaFuN** [BeamMW/beam#1200]
Payment proof is essential for documentation, in case user claims he didn't revive funds.  

NOTE: this is for UI wallet "Export transaction history" feature
<img width="1027" alt="Снимок экрана 2020-01-08 в 11 10 54" src="https://user-images.githubusercontent.com/28015224/71961116-bc16eb80-3207-11ea-9640-c103db8dabc8.png">

[transactions_history_2020_01_08_11_09_13.csv.zip](https://github.com/BeamMW/beam/files/4034153/transactions_history_2020_01_08_11_09_13.csv.zip)

**Comment by VladislavKulyba** [comment]
"Payment proof" exports for transaction with status "in progress" 
![Snag_81464c](https://user-images.githubusercontent.com/51320829/72892630-0e87fa00-3d28-11ea-9237-b00d3d51c2aa.png)

**Comment by VladislavKulyba** [comment]
Checked
