### ISSUE TITLE
I've Written Updated Mac OS Build Instructions

### ISSUE THREAD

**Issue by breadsax** [BeamMW/beam#1201]
Could you please update the wiki for these Mac build instructions? I am able to reproduce builds with these, but not the current instructions. @nesbox Can you perhaps verify these changes? I can't do a Pull Request to your wiki.

I have based these changes off of .travis.yml from the section # OSX Release and removed some lines not necessary to sign or otherwise build on one's own Mac.

Download the mainnet source code by using: git clone --branch mainnet https://github.com/BeamMW/beam.git
Install Brew Package Manager
Installed necessary packages using:  brew install openssl cmake

Download and Install Static qt5 by using:  sudo git clone --depth=1 https://github.com/nesbox/qt5-static-mac.git /usr/local/qt5-static
Remove any existing brew installations of qt and boost by using:  brew uninstall --ignore-dependencies qt boost
Download compatible version of boost by using:  curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/5da5895add2f6b9320d654dd844d4827f6876c8b/Formula/boost.rb
Install Compatible of boost with Brew by using: brew install ./boost.rb

Set your Environment Variables by using the following:
        - export OPENSSL_ROOT_DIR="/usr/local/opt/openssl@1.1"
        - export PATH=/usr/local/qt5-static/bin:$PATH
        - export QT5_ROOT_DIR="/usr/local/qt5-static"
        - export QML_IMPORT_PATH="/usr/local/qt5-static/qml"

Compile the GUI Wallet by using:  cmake -DCMAKE_BUILD_TYPE=Release -DBEAM_LINK_TYPE=Static -DBRANCH_NAME=Mainnet . && make -j 4

Package to an .dmg file by using: cpack

You'll find binaries in beam/wallet, beam/ui, and beam/explorer subfolders.

The .dmg file will be found in the beam/ui directory

If you don't want to build UI don't install QT5 and add -DBEAM_NO_QT_UI_WALLET=On command line parameter when you are calling cmake.

**Comment by anatolse** [comment]
I've updated build instructions for macOS. But I didn't used strictly yours instructions pulled from .travis.yaml since these instructions are linked to our internal repositories. Please, check if they work for you.

**Comment by gingervik** [comment]
@breadsax please, reopen the issue if you have any questions
