### ISSUE TITLE
Automatically updating comment field in the sender screen

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam#1203]
If there was comment in address, it should be automatically open in the field "Comment", when this address is pasted
Pre-condition:
There are two wallets: Wallet A and Wallet B. Both are running
Steps to reproduce: 
1. Create a receiver address in Wallet B.
2. In Wallet A open Send. Put the address from Wallet B in the Address field. Add some comment. Send some beams to wallet B.
3. Check this address with name in Address Tab in Wallet A.  
4. In Wallet A open Send. Put the address from Wallet B in the Address field.
Expected: In "Comment" field there is previous comment
Actual: There is no comment. If send some money to this address, comment will be re-write.

[2019-12-18_17-45-42.zip](https://github.com/BeamMW/beam/files/3987361/2019-12-18_17-45-42.zip)

**Comment by gingervik** [comment]
already fixed
