### ISSUE TITLE
Add "Create Contact" in Address book on Desktop Wallet

### ISSUE THREAD

**Issue by Temlna** [BeamMW/beam#1210]
**Feature title**
Add shortcut "Create Contact"

**Describe the current situation we have**
I would like to know if we could add a shortcut in the address book tab because I would like to add one of my permanent addresses in my contacts on my desktop wallet but there is no shortcut like on the mobile version 3.2.

**Describe the solution you'd like**
If possible add this feature in the next update.

- Desktop Wallet 4.1.6978 -
![1](https://user-images.githubusercontent.com/59240035/71454373-cd381500-2790-11ea-98a7-44004a658315.png)

- Mobile Wallet 3.2 -
![Screenshot_20191226-032635_Beam Wallet](https://user-images.githubusercontent.com/59240035/71454374-d0330580-2790-11ea-8f95-f41e05852723.jpg)

**Comment by gingervik** [comment]
Hello @Temlna 
To add contact you should on send screen add comment and sent some coins. Receiver will be added in contact list after that

**Comment by gingervik** [comment]
no answer for almost a month. can be closed
