### ISSUE TITLE
Password should be selected when it's invalid for

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam#1224]
Select full password when it's invalid. So user just need to click "delete" without selecting password or holding "delete" button.
![image](https://user-images.githubusercontent.com/47353570/72147026-5a40b800-33a6-11ea-8fbf-44872027d1f6.png)

Good example password on mac:

**Comment by Roberrtt** [comment]
The password is highlighted, but when we click on the "delete" or "backspace" button, the password is not deleted

**Comment by Roberrtt** [comment]
Make it for
1)When we enable/disable the option (ask for a password when sending transactions)
2) when we send a transaction with the "1" option enabled"
![Screenshot_345](https://user-images.githubusercontent.com/50007056/72320020-d0e4fa80-36b1-11ea-8c7c-0a42a2d69185.png)
![Screenshot_346](https://user-images.githubusercontent.com/50007056/72320019-d0e4fa80-36b1-11ea-8d85-8a0526784b90.png)

**Comment by Roberrtt** [comment]
Please add this feature for pop up, (in settings electrum)when clicking
- edit your seed phrase
- generate new seed phrase
- clear seed phrase
- show seed phrase

![Screenshot_348](https://user-images.githubusercontent.com/50007056/72349566-cd6f6480-36ed-11ea-9570-04745aece04c.png)
![Screenshot_349](https://user-images.githubusercontent.com/50007056/72349570-cd6f6480-36ed-11ea-8745-744e4b476df8.png)
![Screenshot_350](https://user-images.githubusercontent.com/50007056/72349572-ce07fb00-36ed-11ea-9faa-42f045762b7c.png)

**Comment by Roberrtt** [comment]
checked
