### ISSUE TITLE
Change the text in pop-up when you turn on ask password for transaction 

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1225]
When we enable the option to ask for a password when sending a transaction, the text header should be " Ask password on every Send"
Actual: Don't ask password on every Send
![Screenshot_321](https://user-images.githubusercontent.com/50007056/72204055-e0cbc700-3484-11ea-9317-38c2dbc0bf9b.png)

**Comment by gingervik** [comment]
already fixed
