### ISSUE TITLE
Implement wallet channels script

### ISSUE THREAD

**Issue by Zeke133** [BeamMW/beam#1244]
Implement wallet channels service broadcasting beam exchange rate and wallet update news.
Service will sign all messages with secure private key.
This service will be divided to 2 parts:
- data collecting script
- CLI utility which will send data using BBS protocol to node
cli utility is located here https://builds.beam.mw/master/latest/Release/linux/broadcaster-masternet.tar.gz

**Comment by anatolse** [comment]
script is available here
https://github.com/BeamMW/notification-script
Please, follow the instructions to run it.

In the desktop wallet log files the lines started from "Exchange rate: 1 " should start to appear

**Comment by Denis-Asipenko** [comment]
Need to correct the rounding in the script.
![image](https://user-images.githubusercontent.com/45556620/76520960-f48bad80-6474-11ea-8d69-f4f261712331.png)

**Comment by iscander01** [comment]
fixed at 64202678fad9c5d4d807061f6ebd47a1fb1b98e2

**Comment by Denis-Asipenko** [comment]
checked
