### ISSUE TITLE
Implement BBS broadcasting utility for CLI

### ISSUE THREAD

**Issue by Zeke133** [BeamMW/beam#1246]
Wallet channels need for service publishing exchange rates and update news.
This service will be divided to 2 parts:
- data collecting script
- CLI utility which will send data using BBS protocol to node

Utility must be able to send messages using BBS protocol to specified node.

USAGE
new version:
broadcaster -n <node> --key <secret key> --msg_type=update --upd_ver="1.8.9" --upd_type=desktop

new rate:

broadcaster -n <node> --key <secret key> --msg_type=exchange --exch_curr="beam" --exch_rate=789654123

**Comment by Denis-Asipenko** [comment]
checked
