### ISSUE TITLE
Make input fields on Send screen on the same level

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam#1248]
Please make input lines and header on the same level for left and right parts. Updated design is here https://zpl.io/boPDpQE
<img width="888" alt="Screenshot 2020-01-22 at 15 49 43" src="https://user-images.githubusercontent.com/7249484/72875371-172ffe80-3d2f-11ea-88cb-287edee0ae2e.png">

**Comment by VladislavKulyba** [comment]
checked
