### ISSUE TITLE
Add WalletID as a 2FA for CLI wallet transactions

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#1251]
Add the same functionality(WalletID) to CLI wallet as we have already done for UI Wallet #1172

**Comment by anatolse** [comment]
to generate a token from command line use "get_token -r <SBBS address you wish to use to receive transaction>"

**Comment by anatolse** [comment]
@Sergei-Beam, check, please,  that cli are not broken, I did a lot of changes there

**Comment by Sergei-Beam** [comment]
1. remove extra spaces and leave only one after :
![image](https://user-images.githubusercontent.com/44496108/73519277-a022f600-4411-11ea-8d0f-00fa0c24584b.png)

2. we shouldn't be able to generate a token with already expired address
![image](https://user-images.githubusercontent.com/44496108/73519224-78339280-4411-11ea-8799-6b07c2c0c91a.png)

3. User shouldn't be able to generate a token using instead of address token in form `get_token -r`
![image](https://user-images.githubusercontent.com/44496108/73519713-ceed9c00-4412-11ea-9989-4ab58768813f.png)

4.  Allow generating a token without using an address
If this case wallet should create the address for token automatically
![image](https://user-images.githubusercontent.com/44496108/73520629-1aa14500-4415-11ea-866e-0b3f2f04df04.png)

5 Add info about my id and peer id if we send tx from UI to CLI for both sides sender and receiver
![image](https://user-images.githubusercontent.com/44496108/73520472-c6966080-4414-11ea-94a0-171bf2360414.png)

6. Payment proof is wrong for TX from UI to CLI it includes usual addresses instead of ID
![image](https://user-images.githubusercontent.com/44496108/73520563-f5143b80-4414-11ea-8d80-f3f10eee6d15.png)

7. Change text since we can paste here both address and token

![image](https://user-images.githubusercontent.com/44496108/73519516-60104300-4412-11ea-92b9-6dad70faf817.png)

**Comment by Sergei-Beam** [comment]
checked
