### ISSUE TITLE
Lost coins

### ISSUE THREAD

**Issue by gator6615** [BeamMW/beam#1255]
**Bug title**
Express the problem in a single concise sentence
I never got my mined coins
**Bug description**

**To Reproduce**
Steps to reproduce the behaviour:
1. Run '....' (with '....' configuration file or command line parameters where applicable)
2. Do '....'
3. Do '....'

**Current behaviour**
A clear and concise description of the erroneous behaviour which currently happens.

**Expected behaviour**

**Platform and build**
* Windows
[beam_ui_19_02_18_09_13_19.log](https://github.com/BeamMW/beam/files/4098860/beam_ui_19_02_18_09_13_19.log)
[beam_ui_19_02_18_09_35_48.log](https://github.com/BeamMW/beam/files/4098861/beam_ui_19_02_18_09_35_48.log)
[beam_ui_19_02_18_12_36_13.log](https://github.com/BeamMW/beam/files/4098862/beam_ui_19_02_18_12_36_13.log)
[beam_ui_19_02_19_02_17_42.log](https://github.com/BeamMW/beam/files/4098863/beam_ui_19_02_19_02_17_42.log)
[beam_ui_19_02_19_03_07_43.log](https://github.com/BeamMW/beam/files/4098864/beam_ui_19_02_19_03_07_43.log)
[beam_ui_19_02_19_06_08_39.log](https://github.com/BeamMW/beam/files/4098865/beam_ui_19_02_19_06_08_39.log)
[beam_ui_19_02_19_09_08_39.log](https://github.com/BeamMW/beam/files/4098866/beam_ui_19_02_19_09_08_39.log)

, Mac, Linux, Android or iOS
* OS version
* BEAM Build number

**Configuration, log, memory dump files (if applicable)**
Add relevant files. The filenames and locations are described here: https://github.com/BeamMW/beam/wiki/Folder-and-file-locations

**Log file(s) (if applicable)**
Add relevant log file(s),  located in the `logs` folder.

**Screenshots (if applicable)**
Add screenshots that illustrate a problem you've found.

**Comment by VladislavKulyba** [comment]
Hello,

You are using an old version of the Wallet, which is not available after Hard Fork (08/15/19).
Please, update your Wallet to the latest version. You can find it on our website https://www.beam.mw/downloads/mainnet-windows 

Regards,
BEAM Support

**Comment by gingervik** [comment]
There is no response from the user for over 2 months. Can be closed

**Comment by gator6615** [comment]
thanks i got them
