### ISSUE TITLE
Changing the designs for screens where SBBS addresses are displayed because we made a new entity Token

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#1258]
We added a new entity Token instead of SBBS address #1172  (Token is generating using SBBS and WalletID).
Now, on receive view, UI wallet generates a token which contains Sbbs peer ID and wallet identity.
There're no SBBS addresses in Newer wallets, but they might get Beams for old entity SBBS address

We need to decide how to show a new entity on the UI Wallet for all screens where SBBS addresses are displayed now.
Such as to 
- send/receive
- transaction data grid ( for all tabs)
- transactions details
- Address book ( for all tabs)
- Edit Address form
- Proof of Payment

But SBBS address should still visible too for a while

**Comment by sasha-abramovich** [comment]
let's discuss during the dev meeting

**Comment by gingervik** [comment]
duplicate
