### ISSUE TITLE
Extract Sbbs Monitor into separate entity

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#1263]
SbbsMonitor is a service which listens to beam node and tries to recognize sbbs messages.
In order to subscribe/unsubscribe to specific SBBS address monitor exposes JSON API (see https://github.com/BeamMW/beam/blob/master/wallet/service/client/monitor_client.js https://github.com/BeamMW/beam/blob/master/wallet/service/client/monitor_unsubscribe.js).

If client keeps connection with monitor it sends notification
 {
               {"id", 0},
                {"method", "new_message"},
                {"params",
                    {
                        {"address",  "<hex addr>")}
                    }
                }
            }

**Comment by chapati** [comment]
This is done
