### ISSUE TITLE
[cli] 'wallet sucessfully opened' goes before 'starting a wallet...' in logs

### ISSUE THREAD

**Issue by andreibaranouski** [BeamMW/beam#1265]
**Bug description**

seems like some logic has been changed and now we have "starting a wallet..." after "wallet sucessfully opened..."

```
/beam-wallet-masternet  swap_init --pass password --wallet_path wallet.db
result:
I 2020-01-29.19:39:17.869 Beam Wallet 4.2.7807 (master)
I 2020-01-29.19:39:17.869 Rules signature: 0-a3855fb3c36dd99c, 30-67662cdc38620bfb
I 2020-01-29.19:39:18.090 wallet sucessfully opened...
I 2020-01-29.19:39:18.090 starting a wallet...
D 2020-01-29.19:39:18.090 Async update started!
E 2020-01-29.19:39:18.090 node address should be specified
D 2020-01-29.19:39:18.090 Async update finished!
```

**Comment by Roberrtt** [comment]
Use the command : 
-info ; -show_swap_settings ; export_owner_key ; export_miner_key ; set_swap_settings ;
There isn't a line "starting a wallet..."
![Screenshot_30](https://user-images.githubusercontent.com/50007056/75091177-88a3dc80-557b-11ea-871c-b33df4a25b3c.png)

**Comment by anatolse** [comment]
it's ok since we don't start a wallet for this command anymore

**Comment by Roberrtt** [comment]
Checked
