### ISSUE TITLE
Ability to set expiration date for addresses

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#127]
User should have the ability to set the expiration date for his address.
Need to discuss what time they can choose as example 24 hours/48 hours/never
If nothing is chosen then by default, address should be created with an expiration date =  24 hours

**Comment by sasha-abramovich** [comment]
After a short talk it was decided to have only 2 expiration options (as of now), the options should be presented as a drop-down list (see https://zpl.io/b63je4K for details):

Expires:
* 24 hours (default)
* Never

**Comment by Sergei-Beam** [comment]
checked
