### ISSUE TITLE
[CLI/API] swap_init gives "Please check your network" because API issues "message corrupted"

### ISSUE THREAD

**Issue by andreibaranouski** [BeamMW/beam#1272]
**Bug description**
I guess it's known issue related to recent changes but let's track it here

```
./beam-wallet-masternet  swap_init --pass password --wallet_path wallet.db -n 127.0.0.1:10006 --amount=0.01 --swap_coin=btc --swap_amount=100000
```

<img width="1121" alt="Screen Shot 2020-02-02 at 13 47 48" src="https://user-images.githubusercontent.com/1714151/73607113-292d5f00-45c3-11ea-81fc-6b0e1dbd695c.png">

**Comment by Roberrtt** [comment]
not fixed

**Comment by Roberrtt** [comment]
API wallet - this isn't node for wallet
