### ISSUE TITLE
Settings - Notification tab

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#1274]
Please, add design and description about Notification settings.

**Comment by gingervik** [comment]
Relates to #1270

**Comment by sasha-abramovich** [comment]
we've talked with @Zeke133, he'll make the notifications tab in settings with separate switches per notification type: "Wallet version", "News", "Transaction status".

**Comment by dariatarakanova** [comment]
Design: https://zpl.io/awXoXO1

1) Please replace Node (should be on right side) and General settings (should be on left side). So Report a problem will be narrower.
2) Make Notifications as separate block.

**Comment by Zeke133** [comment]
Switches in settings should enable and disable popups and notifications appearing on Notifications view.

**Comment by Denis-Asipenko** [comment]
checked
