### ISSUE TITLE
When inserting a token, the amount is invalid

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1277]
When we enter an amount in the send and then insert a token with an exceeding amount than the other wallet the amount in the send becomes invalid

Notes:
If the token is entered a lesser amount, then when sending the amount specified in the token will be valid
Also, when the amount is entered in the send field and the copied token is inserted (without entering the amount) , the send button will not be active

Precondition:
Have 2 wallets(A and B), they are opened, In wallets has some beams

Step:
- in wallet  A go to receive screen
- enter an amount greater than the amount in the B wallet
- click copy transaction token
- in wallet B go to send screen
- enter some number of beams in field send 
- insert token to address

Expected: amount entered is valid
Actual: amount is invalid
[VIDEO.zip](https://github.com/BeamMW/beam/files/4159856/VIDEO.zip)

**Comment by Roberrtt** [comment]
1. When we click on the "add all" button on the sending screen, and insert a token with an amount greater than in the wallet, if we one more time  click on the button,the amount will be highlighted in red
[Video 1.zip](https://github.com/BeamMW/beam/files/4196908/Video.1.zip)

2. If you enter the amount "3" on the sending screen, then insert the token without the amount, and enter the amount "3" again, the send button will don't active.
[Video 2.zip](https://github.com/BeamMW/beam/files/4196919/Video.2.zip)

3. Also, if the token is created without an amount, then on the sending screen, it should don't change entered the amount.
[Video 3.zip](https://github.com/BeamMW/beam/files/4197198/Video.3.zip)

**Comment by Roberrtt** [comment]
1.When we click on the "add all" button on the sending screen, and insert a token with an amount greater than in the wallet, if we one more time click on the button,the amount will be highlighted in red
Expected: The amount is valid and can be sent
Actual: The amount is highlighted in red and cannot be sent
[Video 1.zip](https://github.com/BeamMW/beam/files/4214276/Video.1.zip)

2. If the token has a specified amount, when inserting it in the send field, the "add all" button doesn't overwrite the amount in the token
Expected: The "add all" button overwrites the amount and sends everything
Actual: The "add all" button  doesn't overwrite the amount and sends amount specified in the token 
[Video 2.zip](https://github.com/BeamMW/beam/files/4214278/Video.2.zip)

3.The calculation table is highlighted in red for the amounts that are in the wallet
[Video 3.zip](https://github.com/BeamMW/beam/files/4214279/Video.3.zip)

**Comment by anatolse** [comment]
on newer Qt it's ok, please try to fix on 5.11

**Comment by Roberrtt** [comment]
5  - not fixed

**Comment by Roberrtt** [comment]
If we click the "add all" button , then when the cursor is removed from the "Send" field , the amount disappears. I  can 't send it.
[Video.zip](https://github.com/BeamMW/beam/files/4328958/Video.zip)

build 4.2.8351

**Comment by Roberrtt** [comment]
checked
