### ISSUE TITLE
Displaying the amount in second currency

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam#1279]
Please add second currency amount on next screens:

1) Settings screen - add "Show amounts in" (usd (default) / btc) - https://zpl.io/29198WY
2) Main wallet screen - https://zpl.io/2vkee1J https://zpl.io/2GdMxJ3
3) Send screen (swap send screen) - https://zpl.io/a8edOdd 

Important: 
--- On Accept swap offer screen if we swap BTC - BEAM and second currency BTC - no need to show second currency at all (example - https://zpl.io/agpMXm1). In this case make margins between amount and fee -30 px (if it's possible)
--- If second currency - USD on **Accept swap offer screen** and **Create swap offer screens** display this second currency only under left block:
![image](https://user-images.githubusercontent.com/47353570/74248628-8d9d9c00-4cf0-11ea-865f-f94e1f05fba2.png)

4) Confirmation send screen - https://zpl.io/V11YeGk
5) Receive screen (create swap offer) - https://zpl.io/awXlqvn
6) Transaction details - https://zpl.io/bJxDdnr

For now no need to add it on Atomic Swap main screen - https://zpl.io/anE584A

**Comment by Zeke133** [comment]
1 and 2 are implemented

**Comment by Zeke133** [comment]
3,4 and 5 are ready

**Comment by Zeke133** [comment]
Second currency also should be added to regular send view.

**Comment by Roberrtt** [comment]
Make for" receive " screen
build:4.2.8391
![Screenshot_70](https://user-images.githubusercontent.com/50007056/76963585-4e3b1e80-6932-11ea-8cdd-f33956358dc2.png)

**Comment by Roberrtt** [comment]
checked
