### ISSUE TITLE
Electrum - increase number of change addresses

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#1285]
Now if user has more then 6 change addresses in electrum he will not see balance from all of them. 
We should generate max possible number of addresses (if it can be done)

The original message from user

> I connected my electrum btc wallet to the beam wallet but beam wallet is only showing my btc balances on the normal electrum 'receiving' addresses. The balances on the 'change' addresses are not shown in the beam wallet btc balance.

**Comment by roman-strilets** [comment]
example:
beam-wallet-masternet.exe set_swap_settings --swap_coin=btc --receiving_address=30

beam-wallet-masternet.exe set_swap_settings --swap_coin=btc --change_address=30

**Comment by VladislavKulyba** [comment]
Feature was checked. 
Names of options "receiving_addresses", "change_addresses" should be approved

**Comment by roman-strilets** [comment]
receiving_addresses => addresses_to_receive
change_addresses => addresses_for_change

**Comment by gingervik** [comment]
@VladislavKulyba please checked with renamed commands

**Comment by VladislavKulyba** [comment]
> @VladislavKulyba please checked with renamed commands

Checked
