### ISSUE TITLE
Send screen - Wrong format when entering a decimal number in "Transaction amount"

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#129]
When you enter a decimal number on the "Send" screen after moving the cursor to another field and back amout becomes display as "1e-5"

Steps to reproduce the behaviour:
1. go to Send screen
2. Enter "Transaction amount" (example, 0.00001)
3. Move pointer to fee field
4. Move back to "Transaction amount"
Expected: 0.00001
Actual: 1e-5

Checked on Windows
![bug](https://user-images.githubusercontent.com/45556620/49444322-7d7a5a80-f7d7-11e8-831b-dfc8c0b669a6.png)

**Comment by gingervik** [comment]
already fixed
