### ISSUE TITLE
An unpublished offer doesn't accept in API.

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1296]
1. API doesn't accept a token from the CLI
When we create a offer  in the CLI,copy token and insert all the parameters for acceptance in the API and  try to accept this offer ,we get an error in response

Also, this error response is issued:
-if an offer was created in the UI via button "copy swap token"
-between API wallets if the offer isn't published

![Screenshot_432](https://user-images.githubusercontent.com/50007056/75450902-aeb4ec80-5980-11ea-839a-0acfac2f2139.png)
![Screenshot_433](https://user-images.githubusercontent.com/50007056/75450905-afe61980-5980-11ea-924c-fdf92ab375ee.png)

2. When we accept a token from API and don't agree to the condition.
And repeat the acceptance by agreeing to the condition. The transaction must not fail. 
Actual: if you agree with 2 times, the transaction fails.
![Screenshot_434](https://user-images.githubusercontent.com/50007056/75450958-c5f3da00-5980-11ea-8b58-5fbed91b91bb.png)

**Comment by Roberrtt** [comment]
If you accept an unpublished offer in  API when the wallet of the Creator of the offer is closed. Then when you request the status of the token in API , it's shown that this is our offer.
Also, the token differs from the one inserted in the request.

Step:
- create offer in UI via button 'copy swap token'
- close UI wallet 
- In API accept this offer
- make a request for token  "swap_offer_status"
- pay attention to the fields "is_my_offer" and "token"

Expected: is_my_offer = false and  tokens must be the same
![Screenshot_462](https://user-images.githubusercontent.com/50007056/75966535-96daec80-5edb-11ea-8a47-ef067fdfb2dc.png)

**Comment by roman-strilets** [comment]
please recheck this according with https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-SWAP-API-(BETA)#swap_offer_status

**Comment by Roberrtt** [comment]
1. Change the fields in the response to the "swap_decode_token" query  
- beam_amount to   receive_amount
- is_beam_side   to   receive_currency
- swap_amount  to   send_amount  
- swap_coin        to    send_currency

2.Add an option to the "swap_offer_status " method" 
- If the offer (not ours) is published and is on the board, we will show its status
- If the offer isn't published, an error is written in the response

**Comment by Roberrtt** [comment]
Checked
