### ISSUE TITLE
Beam Wallet Issue Mac OS

### ISSUE THREAD

**Issue by humblediligent** [BeamMW/beam#1297]
Beam Wallet Issue Mac OS - Wallet will not open, stuck at 49% for 12 hours..

I open and sign in to my Beam wallet on Mac OS. It loads to 49% and then freezes.
<img width="1024" alt="Screenshot 2020-03-02 at 00 09 02" src="https://user-images.githubusercontent.com/61669884/75636881-86481f00-5c1a-11ea-9f11-4f0c5c03a837.png">

I am more than happy to provide any and all information needed to make this solvable, but I am not technically minded so plain and simple English please.

Thank you

**Comment by VladislavKulyba** [comment]
Hello! 
Would you mind telling me which version of wallet is it?

**Comment by humblediligent** [comment]
How do I find that out? Total amateur here, please excuse!

**Comment by VladislavKulyba** [comment]
You can use this documentation, to find location to folder with your database file. Name of this folder is version. The highest number is the latest.  https://documentation.beam.mw/en/latest/rtd_pages/user_files_and_locations.html#mac

**Comment by gingervik** [comment]
there is no user's response for more than 6 months
