### ISSUE TITLE
Swap API - Offer hangs in the "in progress" status

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1299]
The transaction hangs in the "in progress" status when we disable \ enable listening to the wallet API

Step:
- create offer in UI (send Beam , receive BTC)
- run API wallet  
- accept this offer in API
- wait for LockTX completed in API
- stop listening
- start listening API wallet when 1-2 block will be passed

Expected: the transaction continues
Actual: Throws an error.
![Screenshot_466](https://user-images.githubusercontent.com/50007056/75988826-3f507700-5f03-11ea-8bf5-239efd9b76ff.png)

Note: In the UI wallet, after 120 blocks, the Refund starts

Transaction : 3f2a2765a5554a5cba75711c2ff1963b
[logs.zip](https://github.com/BeamMW/beam/files/4293291/logs.zip)
[wallet.zip](https://github.com/BeamMW/beam/files/4293458/wallet.zip) pass= 1

Build 4.2.8290 master

**Comment by VladislavKulyba** [comment]
checked
