### ISSUE TITLE
building testnet 2.2 and gpu mining

### ISSUE THREAD

**Issue by entinio** [BeamMW/beam#130]
I've compiled the testnet 2.2 node and wallet from the source provided on github (testnet-2.2.tar.gz) on an ubuntu 16.04 platform.

Unfortunately, it doesn't seem to enable the gpu mining : 

`unrecognised option 'miner_type'`

Testing the compiled node without this option, it works fine... but mining through the CPU.

So, how to compile from the sources to enable the GPU mining ? The CUDA toolkit is already installed on the machine.

**Comment by nesbox** [comment]
Hi, try to add `-DBEAM_USE_GPU=On` option to the cmake paramaters, like this:
`cmake -DCMAKE_BUILD_TYPE=Release -DBEAM_USE_GPU=On .`
and rebuild.

**Comment by entinio** [comment]
Ok thanx :-)
