### ISSUE TITLE
Add icon/button mouse-over tips in the desktop wallet

### ISSUE THREAD

**Issue by beggsdl** [BeamMW/beam#1301]
**Feature title**
To make it more clear what different icons and buttons do, add mouse-over tips

**Describe the current situation we have**
Most icons/buttons do not have any words that describe them, so it can be difficult to know what action will be taken if you click on them. A good example is the payment proof button.

**Describe the solution you'd like**
Add mouse-over tool-tips to the left side navigation icons and the three buttons on the Wallet Transactions screen.  I think this could be especially useful for a new user who might be afraid to "click on the wrong thing".  They might at least then have an idea what the button is for.

**Describe alternatives you've considered (if relevant)**
I could see not adding them to the left navigation.

I am running Win10 with wallet version 4.1.6978.

**Comment by sasha-abramovich** [comment]
We are not big fans of tooltips, we'd rather make our UX self-explanatory. Whenever we need to show additional info (e.g. when to come online to accomplish transaction) we usually place it near the respective UI elements. Also, tooltips are "always there", even after the short learning curve had been accomplished. And, no matter what's on the tooltip, you'll still click on the icon and will understand really fast what happens on the actual screen. There are no wrong things on our app or so we believe, hence - feel free to click and discover features :)
