### ISSUE TITLE
Swap transaction status update notifications

### ISSUE THREAD

**Issue by Zeke133** [BeamMW/beam#1304]
Crash on swap transaction expiration happens.
Swap tx doesn't have PeerID until accepted by the other side.
Swap transactions need special output case.

**Comment by dariatarakanova** [comment]
Added notifications: receiving transaction failed, swap offer failed, swap offer expired, swap offer completed

https://zpl.io/Vkovo1G

**Comment by Denis-Asipenko** [comment]
Notification "swap offer expired" display just like when "swap offer failed".
![image](https://user-images.githubusercontent.com/45556620/76854661-925dee80-6860-11ea-8515-fe1ac2dac7dd.png)

**Comment by Denis-Asipenko** [comment]
checked
