### ISSUE TITLE
Store exchange rates in transaction

### ISSUE THREAD

**Issue by Zeke133** [BeamMW/beam#1305]
Exchange rates of all available second currencies should be stored with the transaction.
Also add this information to CSV file export.

**Comment by Denis-Asipenko** [comment]
The recipient doesn't store exchange rates of all available second currencies with transaction.
![image](https://user-images.githubusercontent.com/45556620/76763658-988e9500-67a4-11ea-9125-b6a3de2484a8.png)
![image](https://user-images.githubusercontent.com/45556620/76763663-9e847600-67a4-11ea-9b50-e94d7fb64490.png)

**Comment by Denis-Asipenko** [comment]
checked
