### ISSUE TITLE
SwapOfferBoard protocol refactoring to use common BroadcastRouter serialization and signature method

### ISSUE THREAD

**Issue by Zeke133** [BeamMW/beam#1315]
SwapOfferBoard use OfferBoardProtocolHandler::createMessage() method to create signed messages which are different from common BroadcastMsgCreator::createSignedMessage() method. Also, message parsing methods diverse.
Idea is to use the same common methods for message processing.
A new protocol version should be added to support a new common method and old deprecated one at the same time. Deprecated could be removed completely after the fork.
Important is that migration can be done only during the fork. Otherwise, we can't remove the old protocol method support.
Also, the SwapOfferConfirmation class should be replaced with the common SignatureHandler class.

**Comment by gingervik** [comment]
checked AS during and after fork2
