### ISSUE TITLE
cpu of  wallet-api is 99% and  wallet-api socket is very slow, about 50s  

### ISSUE THREAD

**Issue by bitcodernull** [BeamMW/beam#1319]
**Bug title**
cpu of  wallet-api is 99% and  wallet-api socket is very slow, about 50s  

**Bug description**

i upgrade my node to Double Doppler 4.1.6978
cpu of  wallet-api is 99% and  wallet-api socket is very slow, about 50s  

**Platform and build**
* Windows, Mac, Linux, Android or iOS
linux
* OS version
16.04
* BEAM Build number
Double Doppler 4.1.6978

**Comment by gingervik** [comment]
hello @bitcodernull 
1. which methods do you use?
2. how many active transactions do you have at one time?
3. how did you receive this "50s" result?
4. can you please provide us logs?

**Comment by bitcodernull** [comment]
which methods do you use?
      wallet_status

how many active transactions do you have at one time?
    no more than 3
how did you receive this "50s" result?
    I use the socket protocol to connect to the node. If I set the timeout below 50s, it will timeout and 50s will return normally.   

can you please provide us logs?
   which log needed？

ps： my wallet have more than 200K utxos （number not amount）

**Comment by gingervik** [comment]
@bitcodernull your api and node logs, please

**Comment by bitcodernull** [comment]
[node_20_03_27_20_25_08.log](https://github.com/BeamMW/beam/files/4394497/node_20_03_27_20_25_08.log)
[api.log](https://github.com/BeamMW/beam/files/4394500/api.log)

**Comment by bitcodernull** [comment]
thanks

**Comment by anatolse** [comment]
Could you please try to get a trace of the API process?
using, for example
sudo strace -p PID > log.txt

**Comment by gingervik** [comment]
there is no user's response for more than 6 months
