### ISSUE TITLE
Add "Cancel" button on "Creating wallet" screen

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#132]
Please, add "Cancel" button on "Creating wallet" screen
![image](https://user-images.githubusercontent.com/28015224/49572181-4a0d0c80-f94c-11e8-918e-71335d6c4430.png)

When user stucks on this screen he can do nothing. Cancel button should back him on Setup node screen and delete created wallet.db (and node)

**Comment by gingervik** [comment]
@sasha-abramovich are you sure? we discussed it on the meeting. When your node has incompatible peer or unreachebal node - you'll stuck. Just believe me. In this case user should be able cancel creation and change his node setup

**Comment by breakphreak** [comment]
We’ll talk soon :)

**Comment by gingervik** [comment]
checked
