### ISSUE TITLE
There is no error if the user is trying to output a non-existent shieldedID. 

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1323]
If the user outputs a nonexistent shieldedID the wallet simply stops without showing any error.
![6](https://user-images.githubusercontent.com/45556620/77307962-43560480-6d0b-11ea-9229-a9dc50d88790.jpg)

**Comment by echoby** [comment]
Fixed with #1330

**Comment by Denis-Asipenko** [comment]
checked
