### ISSUE TITLE
Make a button gray when activated address in notifications.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1331]
When the user sees the notification about the expiration of the address and clicks the "activate" button, please make the button grey and the text in it "activated".
![image](https://user-images.githubusercontent.com/45556620/77326840-73150480-6d2b-11ea-9b7c-aa7d41c081c7.png)

**Comment by Denis-Asipenko** [comment]
Bug: 
When you change the system time on the computer a day ahead, you don't see a notification about the expired address, but in the address book, addresses become expired.

**Comment by Zeke133** [comment]
implemented check of address expiration by timer

**Comment by Denis-Asipenko** [comment]
checked
