### ISSUE TITLE
Failed transactions in your wallet official

### ISSUE THREAD

**Issue by BARUCHER777** [BeamMW/beam#1336]
Windows 10, Wallet version - v. 4.1.6978
![Beam-Error!](https://user-images.githubusercontent.com/18327150/77507622-d6ad4800-6e79-11ea-94e0-c76254a59711.jpg)

**Comment by VladislavKulyba** [comment]
Hello, please, send your log files from Beam wallet. You can find them in Settings. Press save wallet logs and than upload here or send to email (support@beam.mw).

**Comment by BARUCHER777** [comment]
[beam_ui_20_03_23_04_21_13.log](https://github.com/BeamMW/beam/files/4382808/beam_ui_20_03_23_04_21_13.log)
[beam_ui_20_03_24_05_24_31.log](https://github.com/BeamMW/beam/files/4382809/beam_ui_20_03_24_05_24_31.log)
[beam_ui_20_03_25_07_24_36.log](https://github.com/BeamMW/beam/files/4382811/beam_ui_20_03_25_07_24_36.log)
[beam_ui_20_03_25_08_39_59.log](https://github.com/BeamMW/beam/files/4382812/beam_ui_20_03_25_08_39_59.log)
[beam_ui_20_03_25_10_39_52.log](https://github.com/BeamMW/beam/files/4382815/beam_ui_20_03_25_10_39_52.log)

**Comment by VladislavKulyba** [comment]
It seems that transaction was unsuccessful due to one side wasn't online. You should connect with sender side and ask to resend the transaction.
