### ISSUE TITLE
Some swaps stucked in progress during transaction between API and UI

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam#1338]
After unsuccesful swap in UI wallet  three transactions stucked "in progress" status:

txID: b62ee9e59b1c4c7b960865c764344c81
logs from UI:  [1.zip](https://github.com/BeamMW/beam/files/4380274/1.zip)
Logs from API: [1.zip](https://github.com/BeamMW/beam/files/4380309/1.zip)

txID: b643c3ebb3474258beddfc37be6ecba3
logs from UI: [2.zip](https://github.com/BeamMW/beam/files/4380275/2.zip)
Logs from API: [2.zip](https://github.com/BeamMW/beam/files/4380313/2.zip)

txID: 8108d81d238f4b90b32c6e65b54769ac
logs from UI: [3.zip](https://github.com/BeamMW/beam/files/4380276/3.zip)
Logs from API: [3.zip](https://github.com/BeamMW/beam/files/4380314/3.zip)

Wallet database from UI: [UI.zip](https://github.com/BeamMW/beam/files/4380320/UI.zip)
password: 2
Wallet database from API: [API.zip](https://github.com/BeamMW/beam/files/4380317/API.zip)
password: 123

**Comment by anatolse** [comment]
3.  you cannot redeem due to low fee rate, if you will increase it, tx should succeeded. It is intentional behavior, if fee is low we infinitely are trying to complete transaction.

**Comment by anatolse** [comment]
1. there are very strange lines
[b62ee9e59b1c4c7b960865c764344c81][6] 5/6 confirmations for Refund TX are received.
[b62ee9e59b1c4c7b960865c764344c81][6] 0/6 confirmations for Refund TX are received.

Did you change node?

**Comment by anatolse** [comment]
2. On API side swap was cancelled at this moment
D 2020-03-23.14:26:54.792 [b643c3ebb3474258beddfc37be6ecba3][5] 2/6 confirmations for Lock TX are received.
D 2020-03-23.14:28:55.544 [b643c3ebb3474258beddfc37be6ecba3][5] 4/6 confirmations for Lock TX are received.

, but on the UI side we got
 [b643c3ebb3474258beddfc37be6ecba3][5] Bridge internal error: type = 3; message = dust (code 64)

it's is not obvious why DUST had happened here, but anyway,  I've found that we do not check amount for DUST when accept offer in the API, so I've fixed this

**Comment by anatolse** [comment]
Noticed, that we cannot change fee rate in this cases. Need to discuss this issue, from my point of view when we are in REDEEM or REFUND states we should be able to change Fee rate somehow to give user ability to accomplish swap.

**Comment by anatolse** [comment]
to recap:
1. It seems that there are some problems with btc node, and in normal environment such swap should become completed. If you saved original BTC node database, then you can try to complete this swap.
2,3. Infinite 'in progress' state is 'by design' here. BTW, I've found some issues and fixed them. So, you can confirm that my changes have not broken anything and close it or move it to the future sprints for futher investigations.

**Comment by Roberrtt** [comment]
It will be checked when this issue is fixed .https://github.com/BeamMW/beam/issues/1506

**Comment by Roberrtt** [comment]
In UI, we can accept and create  a swap when the fee is more than we get BTC
So of this, the swap completed in the API, and the UI stuck  in progress

tx_id 8d462a363f3046ec8888ce6c96fe6847
tx_id 7cd9185a85af4c099b80acc2032a5195
[API logs.zip](https://github.com/BeamMW/beam/files/4885063/API.logs.zip)
[UI logs.zip](https://github.com/BeamMW/beam/files/4885068/UI.logs.zip)

Password for wallets - 1
[UI wallet.zip](https://github.com/BeamMW/beam/files/4885081/UI.wallet.zip)
[API wallet.zip](https://github.com/BeamMW/beam/files/4885084/API.wallet.zip)

![Screenshot_82](https://user-images.githubusercontent.com/50007056/86787188-83988300-c06d-11ea-8eee-8b6f1141bbd2.png)
![Screenshot_83](https://user-images.githubusercontent.com/50007056/86787310-a034bb00-c06d-11ea-8eba-ac5d6fdac142.png)

**Comment by VladislavKulyba** [comment]
Atomic Swaps are passed only if Transaction fee rate is 90000 sat/kb. In other cases swaps failed with this error message "Failed. Receiver signature is not valid, please send wallet logs to Beam support"

[beam_ui_20_08_19_09_54_02.log](https://github.com/BeamMW/beam-ui/files/5095826/beam_ui_20_08_19_09_54_02.log)
[beam_ui_20_08_19_09_53_10.log](https://github.com/BeamMW/beam-ui/files/5095828/beam_ui_20_08_19_09_53_10.log)

![image](https://user-images.githubusercontent.com/51320829/90624757-232a6300-e221-11ea-92c4-33d9f879ce24.png)

**Comment by roman-strilets** [comment]
fixed in https://github.com/BeamMW/beam-ui/issues/114

**Comment by VladislavKulyba** [comment]
checked
