### ISSUE TITLE
Cli wallet - wrong utso is selected for the transaction

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#1339]
Precon: 
![image](https://user-images.githubusercontent.com/28015224/77619675-c795cb00-6f49-11ea-9b36-772009ff9880.png)

User has next UTXOs
![image](https://user-images.githubusercontent.com/28015224/77619601-9e753a80-6f49-11ea-9e05-b45d421a5247.png)

Steps:
1. Run cli-wallet
2. Try to send 64560,1778569 Beams
AR: there is "no inputs" error
![image](https://user-images.githubusercontent.com/28015224/77619664-c2388080-6f49-11ea-8375-1662605e14aa.png)

**Comment by anatolse** [comment]
I will close this ticket as invalid. The attempt to send beam was made on height 640088-720 = 639368 on this height the last two coins had not been matured yet. 
I have checked on local test that with given list of the coin values wallet is able to select needed amount.
