### ISSUE TITLE
Show error mesages on Wallet creation screen

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#134]
Please, implement warning messages on wallet creation screen (and restore screen).

When user try to connec to incompatible peer or node we should show him message. In this case he can cancel creation (restore) and change setup settings

**Comment by gingervik** [comment]
@sasha-abramovich I thought that we had agreed about our default error display which is shown on the top of the screen

**Comment by breakphreak** [comment]
We’ve agreed for a quick fix as we don’t have enough time now. I’d like
Alexandra to provide a “real” screenshot from UX perspective which we can
utilize later.

**Comment by alexandrashelenkova** [comment]
zpl.io/a3KNdLl

**Comment by gingervik** [comment]
STR:
- click on create wallet or restore wallet
- inut invalid peer on Setup node screen
Actual: no error messages
wallet is created. Logs are awful. User is in panic

checked on master 3740

**Comment by gingervik** [comment]
checked for "connect to specific remote node" option

Separate tasks are opened for other options
