### ISSUE TITLE
Error message when offer is expired

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam#1341]
txID: 817e445f1ee04024b1c04a342a7d1442
wallet.db = [wallet.zip](https://github.com/BeamMW/beam/files/4386180/wallet.zip)
pass = 123
logs = [api_20_03_26_10_39_45.zip](https://github.com/BeamMW/beam/files/4386181/api_20_03_26_10_39_45.zip)

Pre-conditions: API wallet and UI wallet are installed and run
Steps to reproduce:
1. Create an offer in API Wallet using request "swap_create_offer" with given expiration time  (for this transaction=5 blocks).
2. Copy token from API Wallet 
3. Push "Accept offer" button in UI Wallet and paste this token. Accept Swap offer screen is opened
4. In API Wallet send request "swap_offer_status". Remember "height_expired" (for the transaction=154762) in response. 
5. When current state will be on this height (Current state is 154762-f89ca9b0972593cc), accept swap in UI Wallet.

Actual: Failed. Kernel's min height is unacceptable

![Snag_5fc237a](https://user-images.githubusercontent.com/51320829/77629988-6b3ba700-6f5b-11ea-8716-695e82c27259.png)

**Comment by anatolse** [comment]
Discussed with @Aleksandr-Starun,  this is correct message

**Comment by VladislavKulyba** [comment]
It's not a bug
