### ISSUE TITLE
When at the same time wallets send coins channel close.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1345]
If both sides simultaneously send coins to the channel, the channel is closed.
The first side:
![image](https://user-images.githubusercontent.com/45556620/77745266-04d28980-702c-11ea-99e1-4ea7411905e6.png)
Other side: 
![image](https://user-images.githubusercontent.com/45556620/77745370-2f244700-702c-11ea-8935-7de563107c86.png)

**Comment by Roberrtt** [comment]
checked
