### ISSUE TITLE
Additions to Linux build instructions 

### ISSUE THREAD

**Issue by CD0x23** [BeamMW/beam#135]
g++-7 is required to build but there's no information on how to install it. So this might be nice addition to the build wiki.

```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install g++-7 libboost-all-dev libssl-dev -y
```

Set it up so the symbolic links `gcc`, `g++` point to the newer version:
```
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 \
                           --slave /usr/bin/g++ g++ /usr/bin/g++-7 
sudo update-alternatives --config gcc
gcc --version
g++ --version
```

**Comment by nesbox** [comment]
Updated instructions https://github.com/BeamMW/beam/wiki/How-to-build#linux-ubuntu-1404
Thank you.
