### ISSUE TITLE
The channel is hung in the closing status when it is closed on the other side

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1360]
When we close the channel on 1 side (using --laser_drop) and the 2 side doesn't listen to it 1400 blocks. Then the channel will be closed on the 1st side, and the 2nd side will not see that the channel is closed on the 1st side when it starts listening

1side = laser_open:  2side = laser_receive

Step:
- open channel between a parties
- 1 side drop channel
- 2 side doesn't listen channel
- on 1 side the channel will be closed via 1400 blocks
- 2 side start listen channel

Expected: channel begins to close
Actual: 2 side doesn't see that 1 side is closed. 

Note:
If 2 side close the channel using --laser_drop , then it hangs in the "closing" status.

**Comment by echoby** [comment]
Relative commits:
https://github.com/BeamMW/beam/commit/484fe905f596075c1879aa5a7fcf19a03745ddee
https://github.com/BeamMW/beam/commit/368ed4545a9cce095b205ad6101d6a72200feaf7
https://github.com/BeamMW/beam/commit/e2bffc0f25d17b3533bf8d82782806059e6f6de0
https://github.com/BeamMW/beam/commit/70fe8c66f80b92aa5ca795dd8578e35ebd0421e8

**Comment by Roberrtt** [comment]
checked
