### ISSUE TITLE
getStatusStringApi SWAP support

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam#1363]
Add swap support to TxDescription::getStatusStringApi and use it or getStatusString where necessary to get status string.

**Comment by Roberrtt** [comment]
(In API)When we send the amount to the address using the "tx_send" method. If the status request is by txId (tx_status: tx_id), the status_string will be "sending"
Also, if the amount is sent to us, it will have the receiving status
Instead "sending\receiving" should be "in progress"
![Screenshot_168](https://user-images.githubusercontent.com/50007056/79339057-f1328880-7f30-11ea-9f85-626979a87345.png)

**Comment by Roberrtt** [comment]
checked

**Comment by gingervik** [comment]
revert please

**Comment by Roberrtt** [comment]
checked
