### ISSUE TITLE
API: sessions in tx_split

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam#1374]
Currently API docs state that there is sessions support for tx_split method where there is no support in code. Need to implement.

**Comment by anatolse** [comment]
1. Updated `tx_split` documentation with notion, that `session` parameter is not implemented.
2. Also noticed that `session` parameter is accepted by `tx_send` method and it selects coins from the database correctly, but assigning a coin to the session doesn't prevent selecting this coin in another session. 
3. There are two methods in code `lock` and `unlock` they allow to create and delete sessions, but they are not listed in the documentation. I decided not to document them until this feature will be ready.
