### ISSUE TITLE
Assets: disable flags

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam#1381]
Need to decide if we want to add 'disable assets flags' to:

- UI
- API
- CLI

And what these flags would do exactly.

**Comment by chapati** [comment]
All asset transactions are disabled by default everywhere (API, UI, CLI, WebWallet)
To be able to execute any non-BEAM transaction --enable-assets 1 option should be used

**Comment by Denis-Asipenko** [comment]
Everything works. We discussed and agreed that we should immediately output an error when sending assets.
![image](https://user-images.githubusercontent.com/45556620/82197032-243ab400-9903-11ea-968e-5f886adc9911.png)

**Comment by chapati** [comment]
1. In CLI IssueAsset, ConsumeAsset, RegisterAsset, UnregisterAsset, GetAssetInfo, InsertToShieldedPool, ExtractFromShieldedPool, Send for asset should immediately print the following message and do not start anything: 

`Confidential assets are disabled. Add --enable_assets to command line`

2. In API tx_asset_issue, tx_asset_consume, tx_asset_info, tx_split, tx_send should immediately return the following error and do not start anything:

```json
{
  "error": {
    "code": -32005,
    "data": "Confidential assets are disabled. Add --enable_assets to command line.",
    "message": "Feature is not supported"
  },
  "id": 1236,
  "jsonrpc": "2.0"
}
```

**Comment by Denis-Asipenko** [comment]
checked
