### ISSUE TITLE
Assets: UI

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam#1382]
Need to decide how we would handle assets in the UI. At the moment transactions are accepted, BEAM amount is unaffected, assets transactions are displayed as BEAM transactions in the transactions table.

**Comment by chapati** [comment]
Assets are disabled in UI. 
Please handle TODO arised in process in AppModel::startWallet()

**Comment by Roberrtt** [comment]
When you send an asset from CLI\API to UI,  UI wallet crashes
UI wallet doesn't open

 [947af25c93d04b70bb5d3c6513a7b3df]
[logs.zip](https://github.com/BeamMW/beam/files/4629435/logs.zip)
pass 1
[wallet.zip](https://github.com/BeamMW/beam/files/4629436/wallet.zip)

build UI: 5.0.8926.2816
build CLI\API 5.0.8911

**Comment by chapati** [comment]
Crash fixed. Need to decide how to display such failed transactions in UI. May just not display them at all.
![Screenshot-20200514235308-942x571](https://user-images.githubusercontent.com/12074933/81984923-320be300-963e-11ea-9509-3a17be10d898.png)

**Comment by gingervik** [comment]
@chapati you should no display assets' transactions in UI at all. Please, fix

**Comment by Roberrtt** [comment]
If you send asset to UI, transaction will be displayed in notification
![Screenshot_321](https://user-images.githubusercontent.com/50007056/82192025-103f8400-98fc-11ea-9764-2c476b3bab71.png)

**Comment by chapati** [comment]
Notifications about failed asset transaction will be not displayed. If you have such notifications from previous tests they will still remain.

**Comment by Roberrtt** [comment]
not fixed
CLI\API build 5.0.8947
UI 5.0.8946.2827.exe

**Comment by chapati** [comment]
There was a problem with builds. New build is running now. Please wait until it is finished and test again. Thanks.

**Comment by Roberrtt** [comment]
checked
