### ISSUE TITLE
fromByteBuffer and ZeroMemory 

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam#1386]
As a part of fixing wallet_api_test crash on linux the following issue was discovered. fromByteBuffer in wallet/core/common.h on empty buffer zeroes passed object. This causes crash if a complex object is passed as an argument.

```
template<typename T>
bool fromByteBuffer(const ByteBuffer& b, T& value)
{
        if (!b.empty())
        {
            Deserializer d;
            d.reset(b.data(), b.size());
            d & value;
            return true;
        }
        ZeroObject(value); <-- problem is here
        return false;
}
```

I've created a specialized form for std::string to fix build  but function is still used for complex objects on other places. For example for vecors in ExchangeRateProvider::onMessage

```
...
std::vector<ExchangeRate> receivedRates;
if (fromByteBuffer(res.m_content, receivedRates))
...
```
We need to discuss this and find another solution that would fix the rest of the code and prevent future bugs.

**Comment by gingervik** [comment]
can be closed
