### ISSUE TITLE
Add message about the lock time

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1391]
We need to add a message about lock time when the user burned all the issued coins and tries to unreg the asset before 10 blocks are passed.
![image](https://user-images.githubusercontent.com/45556620/80242459-0e243580-866e-11ea-9250-8a848926e571.png)

**Comment by chapati** [comment]
Please check as discussed via call. There seems to be another unrelated bug.

**Comment by Denis-Asipenko** [comment]
The message is displayed to the user. Another error will be investigated in a different issue.
