### ISSUE TITLE
Web Wallet: logs

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam#1392]
1. Both in monitor & service log cleanup default option is 5 (days) but it is not converted to seconds correctly and passed as 5 seconds further.

2. Service doesn't cleanup old logs automatically on start while monitor does. Need to implement in the service the same behavior as  in the monitor. This ensures that logs would be deleted even if service & monitor are crashed or restarted.

**Comment by VladislavKulyba** [comment]
The logs didn't delete as you can see on screenshot. 
![Snag_e51274](https://user-images.githubusercontent.com/51320829/84647931-d36fa880-af0c-11ea-9a87-0ecbac168a4b.png)

**Comment by VladislavKulyba** [comment]
checked
