### ISSUE TITLE
Cli wallet - One side payments

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#1396]
1. add '-r' parameter to  'insert_to_pool' command. Token with voucher should be passed. Without voucher this command should create 'your' shielded utxo, with voucher: shielded utxo will be owned by voucher issuer got , and in this case 'insert_to_pool' command will behave like one  side payment.
2. add '--voucher_count' parameter to 'get_token' command. With this option token with given number of vouchers for one side payment should be created.

**Comment by Denis-Asipenko** [comment]
1. We need to limit the number of vouchers to 20 because the generated 30 do not fit into the string by the number of characters.
2. Add an error message if the user tries to generate more than 20 vouchers.
3. Also, you need to add commands in CLI help.

**Comment by anatolse** [comment]
https://github.com/BeamMW/beam/wiki/Lelantus-CLI

**Comment by Denis-Asipenko** [comment]
checked
