### ISSUE TITLE
No offline indicator when the network is disconnected in random mode

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#140]
In random  mode, when the network is disconnected,  online indicator doesn't switch to offline.
Steps to reproduce the behaviour:
1. go to wallet
2.node setup: connect to random node
3.make sure the indicator is online
4.disconnect network
Expected: offline indicator
Actual:online indicator
![screenshot_4](https://user-images.githubusercontent.com/45556620/49646127-e0adfc00-fa26-11e8-8bb1-ac00569bc1bb.png)

**Comment by jurijakimuk** [comment]
Works OK on masternet, 4279
