### ISSUE TITLE
When you try to burn all the assets at once, an error message appears.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1410]
When a user tries to burn the entire amount of assets, an error appears stating that the user is trying to burn the amount more than they have.
![image](https://user-images.githubusercontent.com/45556620/80578233-d07a3080-8a10-11ea-9971-2e9abf81b6c7.png)
![image](https://user-images.githubusercontent.com/45556620/80578318-f273b300-8a10-11ea-960b-731cb26aee33.png)
[wallet.zip](https://github.com/BeamMW/beam/files/4550671/wallet.zip)

**Comment by chapati** [comment]
This is a floating numbers problem similar we had in the UI.
I've completely rewritten handling of --amount option Please test not only this case but that it works as before in other cases (negative, 0, invalid &c).

**Comment by Roberrtt** [comment]
If we create coins 2 times 10.000.000.000.
The transaction will fail if we want to burn the entire amount of 20,000.000.000.
![Screenshot_291](https://user-images.githubusercontent.com/50007056/81310330-a10c9900-908c-11ea-89a3-7a332ac8eec7.png)
[logs.zip](https://github.com/BeamMW/beam/files/4593810/logs.zip)

**Comment by chapati** [comment]
@Aleksandr-Starun 
Caught your TODO:overflow here

uint32_t get_Slot(Amount v) const
                {
                    uint64_t i = v * s_Factor / m_Goal; // TODO - overflow check!
                    uint32_t res = (i >= s_Factor) ? s_Factor : static_cast<uint32_t>(i);
                    assert(res <= s_Factor + 1);
                    return res;
                }

**Comment by chapati** [comment]
Fixed by @valdok in commit dd860c47f0963a29ab4388a7fff68e3f7242ed41

**Comment by Roberrtt** [comment]
checked
