### ISSUE TITLE
Asset's info is not updated on first receive

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1411]
The wallet doesn't display metadata information in the log when a user is receiving an asset . Also, when the asset is already received when viewing info, there isn't metadata about this asset.
![image](https://user-images.githubusercontent.com/45556620/80587668-9fedc300-8a1f-11ea-9fd3-ff78c6dfab23.png)
![image](https://user-images.githubusercontent.com/45556620/80588554-3b336800-8a21-11ea-8d57-13194e401b5c.png)
[bw.zip](https://github.com/BeamMW/beam/files/4551193/bw.zip)

**Comment by chapati** [comment]
Should be fixed.
Also please check that the following rule is enforced: asset transaction should be rejected by the receiver if asset is still in the lock period (locked)

**Comment by chapati** [comment]
Asset info is always printed now.

**Comment by Denis-Asipenko** [comment]
checked
