### ISSUE TITLE
 WebWallet: tokens 

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam#1413]
1. Web wallet can send only by token. Token cannot be generated in the UI, cannot be generated in the web wallet. Now it is possible to get token only via CLI, so now if you want to send via web wallet receiver must use CLI. We cannot use web wallet with another web wallet and UI with the web wallet.

2. Receive dialog in web wallet allows to copy raw addresses. It is insecure, does not include identity and should be blocked. Web wallet should not show any raw addresses. Also please check in all other applicable places that we do not use raw addresses, only tokens (for example in send).

3. There is no way for the web wallet to generate tokens. Need to implement this.

**Comment by anatolse** [comment]
string getIdentity(string keyIDBase64)
string getSendToken(string sbbsAddressHex, string identityStrHex, string amountBase64)

**Comment by anatolse** [comment]
@iscander01, make your changes in web wallet (1, 2)

**Comment by VladislavKulyba** [comment]
checked
