### ISSUE TITLE
Review desktop UI wallet versioning

### ISSUE THREAD

**Issue by Zeke133** [BeamMW/beam#1414]
Now we use Desktop wallet app version like `"{BEAM_MAJOR}.{BEAM_MINOR}.{BEAM_REVISION}.{BEAM_UI_REVISION}"`, but in notifications we used versions like `"{MAJOR}.{MINOR}.{REVISION}"`.
May be here is not much sense in using adding `{BEAM_REVISION}`, because we can't create UI wallet build with same version using different wallet library revisions.

**Comment by Zeke133** [comment]
TODO:
- finish broadcaster adoptation: check if version in new format is passed and create new message type
- implement output of new type in UI
- disable old type for desktop wallet update notifications in UI if needed
- add support to Android library if needed

**Comment by Denis-Asipenko** [comment]
After the notifications are read, the notification icon shows that there is an unread notification.
![image](https://user-images.githubusercontent.com/45556620/82897730-be80a480-9f60-11ea-8b90-284e41e0e67a.png)

**Comment by Denis-Asipenko** [comment]
checked
