### ISSUE TITLE
Assets & lelantus

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam#1415]
Need to check if we support assets in lelantus transactions at the wallet side.

**Comment by chapati** [comment]
Support of assets added. Example:

./beam-wallet-masternet insert_to_pool --pass 1 -n 127.0.0.1:10000 -a 10 --fee 1100 --asset_id 1 --enable_assets
./beam-wallet-masternet extract_from_pool --pass 1 -n 127.0.0.1:10000 --fee 1100 --shielded_id 1 --enable_assets 

Test that
1) Beam insert & extract are not broken
2) Asset insert & extract works now
3) Extract transaction should use BEAM coins from wallet to pay fee, exact asset amount should be returned (for beam extract Shileded Amount - Fee is returned)
4) unlinked coins are preffered to pay fee, extract transaction first tries to find only unlinked BEAM coins to pay fee. If it is not enough it would have usual behavior

**Comment by Denis-Asipenko** [comment]
need to align the SHIELDED COINS table
![image](https://user-images.githubusercontent.com/45556620/82455429-9bb34380-9abb-11ea-8ad5-0cb0c6cc98fb.png)

**Comment by Denis-Asipenko** [comment]
After the fix, the table still needs to be aligned.
![image](https://user-images.githubusercontent.com/45556620/82660319-d390c700-9c32-11ea-814f-c6210e827060.png)

**Comment by Denis-Asipenko** [comment]
checked
