### ISSUE TITLE
sqlite error code=5, database is locked

### ISSUE THREAD

**Issue by solopool** [BeamMW/beam#1416]
After update from 4.1.6978 to 4.2.8635, sometimes we get an error if the **wallet-api** is running (tcp or http mode) and we try to make a request by **beam-wallet**.

`./beam-wallet info`
`I 2020-04-30.17:15:08.431 Beam Wallet 4.2.8635 (mainnet)`
`I 2020-04-30.17:15:08.431 Rules signature: 0-ed91a717313c6eb0, 321321-6d622e615cfd29d0`
`I 2020-04-30.17:15:08.431 Applying PRAGMA cipher_migrate...`
`D 2020-04-30.17:15:13.433 sqlite error code=5, database is locked`
`E 2020-04-30.17:15:13.434 sqlite error code=5, database is locked`

This worked fine for several months on the previous version (4.1.6978).

**Comment by gingervik** [comment]
hello @AntonArts 
for now we restrict to use one db for different services at the same time

**Comment by AntonArts** [comment]
This is inconvenient for pool operators. For example, we cannot check in manual mode (beam-wallet)  utxo or txs history while **wallet-api** is running.

**Comment by gingervik** [comment]
@AntonArts but you can use api methods for it
https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API#wallet_status
https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API#tx_list
https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API#get_utxo

**Comment by Alteryy** [comment]
> @AntonArts but you can use api methods for it
> https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API#wallet_status
> https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API#tx_list
> https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API#get_utxo

--
I 2020-06-18.19:10:13.855 got {"jsonrpc":"2.0","id":8,"method":"tx_list","params":{"filter":{"status":3,"height":763025}}}
D 2020-06-18.19:10:13.855 List(filter.status = 3)
I 2020-06-18.19:10:14.183 got {"jsonrpc":"2.0","id":6,"method":"wallet_status"}
--
E 2020-06-18.18:18:20.824 [/home/travis/build/BeamMW/beam/wallet/core/wallet_network.cpp] [343] [~WalletNetworkViaBbs] unhandled exception. what = sqlite error code=5, database is locked
E 2020-06-18.18:18:20.827 sqlite error code=5, database is locked
--
use api still get errors！！
how to solve it ？

**Comment by gingervik** [comment]
just do not run wallet-api and cli-wallet on the same db at the same time

**Comment by gingervik** [comment]
there is no user's response for 2 months
