### ISSUE TITLE
Displaying max value of coins

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1418]
If you make issue by max_int 64, 3 times
`beam-wallet-masternet.exe issue --asset_id 4 -a 92233720368 -n 127.0.0.1:10001`
The number of coins will be incorrect

2 times made issue by max_int 64
![Screenshot_259](https://user-images.githubusercontent.com/50007056/80961721-32bda180-8e14-11ea-862a-9a98f0a04082.png)

3 times made  issue by  max_int 64
![Screenshot_260](https://user-images.githubusercontent.com/50007056/80961959-b8415180-8e14-11ea-8a76-a53d5269da74.png)
![Screenshot_261](https://user-images.githubusercontent.com/50007056/80961927-a364be00-8e14-11ea-8d69-88eb556301c1.png)

**Comment by chapati** [comment]
The following changes were made:

1. Maximum per-transaction amount is 184467440737 Assets 9551615 Asset Groths, i.e `-a 184467440737.9551615`

**Comment by chapati** [comment]
Should be OK now. 
Maximum possible assets emission is 2^128 − 1

**Comment by chapati** [comment]
The change also touches API. Please also check updated documentation for wallet_status & get_asset_info and test it. Ty.

**Comment by Roberrtt** [comment]
checked
