### ISSUE TITLE
Can't sync with any peer

### ISSUE THREAD

**Issue by entinio** [BeamMW/beam#142]
My node can't connect and sync from any peer

I have a running node I compiled from the testnet 3 sources on an ubuntu 16.04 platform. Everything works fine, except I get the message "Incompatible peer cfg!" once I connect to any peer : 

```
I 2018-12-07.21:39:15.802 +Peer 3.0.151.23:8100
I 2018-12-07.21:39:16.215 Peer 3.0.151.23:8100 Connected
I 2018-12-07.21:39:16.419 Peer 3.0.151.23:8100 Auth. Type=N, ID=f71a956d7821fcd3
I 2018-12-07.21:39:16.420 3.0.151.23:8100 received PI
I 2018-12-07.21:39:16.420 deleted anonymous PI
I 2018-12-07.21:39:16.420 PI f71a956d7821fcd3--0.0.0.0 New
I 2018-12-07.21:39:16.420 PI f71a956d7821fcd3--0.0.0.0 Address changed to 3.0.151.23:8100
I 2018-12-07.21:39:16.420 PI f71a956d7821fcd3--3.0.151.23:8100 connected, info updated
W 2018-12-07.21:39:16.420 3.0.151.23:8100: Incompatible peer cfg!
I 2018-12-07.21:39:16.420 -Peer 3.0.151.23:8100
```

My own config is pretty simple : 

```
port=10000
wallet_phrases=***;***;***;***;***;***;***;***;***;***;***;***;
mining_threads=1
peer=3.0.151.23:8100
miner_type=gpu
```

What do I miss here?

**Comment by entinio** [comment]
Ok after some tests it's confirmed. The tar.gz files downloadable from the "Testnet 3" releases link on github is : 

`tgz : const std::string PROJECT_VERSION = "1.0.0";`

While using `git clone`, we get : 

`git clone : const std::string PROJECT_VERSION = "1.0.3642";`

So please, when you upload the sources, use the right version ;-) And to anyone, please use the `git clone` command instead.

**Comment by gingervik** [comment]
hi
@entinio 
Please, try to download node app from beam.mw/downloads
