### ISSUE TITLE
Assets: invalid characters

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1420]
![image](https://user-images.githubusercontent.com/45556620/80978523-d4ea8300-8e2e-11ea-8afc-1aef49a618bc.png)

> beam-wallet-masternet asset_reg --pass 1 -n 127.0.0.1:9001 --asset_meta "STD:N=;%:?*(*?:%;SN=!"№;%;UN=Ъ/Э,ЮББЬТЬБЖ;NTHUN=+_)(*?:%;№"

>

**Comment by Denis-Asipenko** [comment]
To create an asset (in the metadata), only letters or numbers must be used.
![image](https://user-images.githubusercontent.com/45556620/81067806-f22f5800-8ee7-11ea-8576-5911ee655257.png)
![image](https://user-images.githubusercontent.com/45556620/81067814-f5c2df00-8ee7-11ea-904c-5721f87dc585.png)

**Comment by chapati** [comment]
For standard fields allowed symbols are digits, characters, space and ".,-_"

**Comment by Denis-Asipenko** [comment]
checked
