### ISSUE TITLE
Update documentation for API

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1427]
If the user creates a coin and after the transaction is completed uses the get_asset_info request, received the response comes isn't updated. The created coin will not be displayed in the balance. To update your asset data need to use a query tx_asset_info. You need to update the API documentation for this point.

**Comment by chapati** [comment]
Added mention about height at which information was received. Also renamed `value` to `emission`. Check `get_asset_info` docs now.

**Comment by Denis-Asipenko** [comment]
checked
