### ISSUE TITLE
Compile code for testnet 3 gives version 1.0.0

### ISSUE THREAD

**Issue by joshbpa** [BeamMW/beam#143]
I downloaded the source and followed directions to build the UI and node for testnet 3. However wallet and node say the vesion is 1.0.0 and seems to be mining an previous testnet. Am I missing something?

**Comment by entinio** [comment]
Same problem here. See issue #142

**Comment by entinio** [comment]
Ok after some tests it's confirmed. The tar.gz files downloadable from the "Testnet 3" releases link on github is : 

`tgz : const std::string PROJECT_VERSION = "1.0.0";`

While using `git clone`, we get : 

`git clone : const std::string PROJECT_VERSION = "1.0.3642";`

So please, when you upload the sources, use the right version ;-) And to anyone, please use the `git clone` command instead.

**Comment by joshbpa** [comment]
Thanks entinio git clone gave new the newer version (1.0.3642) But I don't think it is mining testnet 3 blockchain. Height is only 5116 and I'm getting all the blocks. I have a testnet 3 client on my Mac where the height is 9461. I think the compiled client is mining the wrong chain.
