### ISSUE TITLE
Expired asset transactions

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1432]
This case is being investigated as part of the task https://github.com/BeamMW/beam/issues/1391. During the investigation of this issue, it was found that the height was not updated when sending the transaction, and therefore the current height was higher than the max. kernel height.
![image](https://user-images.githubusercontent.com/45556620/81293233-a8747800-9075-11ea-8653-671d618b20b8.png)

**Comment by chapati** [comment]
To reproduce. Stop wallet. Wait 120+ blocks. Run asset transaction.
Asset transaction would fail as expired. I advise to save wallet.db to be able to reproduce again without waiting 120+ blocks but by restoring old file version.

**Comment by Denis-Asipenko** [comment]
checked
