### ISSUE TITLE
Add versions to generated token

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#1435]
1. Two new public parameters should be added to the transaction parameters:
 - Beam Library version (cli, api)
 - Beam Client version (ui, mobile)
2. On the library level (cli, api), Beam library version should be checked, and warning message should be written to the output if token's version is incompatible or was generated with newer  version of the library
3. Client should check both versions and raise notifications if token's version is different

**Comment by echoby** [comment]
receive client - Beam Wallet UI 5.0.9000.5555 lib - 5.0.9000 :
5QBQJpYTBb2Dob5mSe1Z2hP6DEvG8Y4FnTPgYn4HmzFknZDJvYhWctMqdxGJWpcz9fXhkqQP1j4vi8geVKLheHpuVKNpBrQsL6cNhN95k2nUDTaop8Svre5pGH1okcc8EUjfmECuUjgSpE1waX96x1MWNVGRUkTgH7PaxDd7UHfFUBJLDd

**Comment by echoby** [comment]
swap client - Beam Wallet UI 5.0.9000.5555 lib - 5.0.9000 :
2wPP35Dyri7ErRu1GDXRSMjnMtaKm5o251HTY4EQjaK27w1TSbgcb4ijxb2jfFJDNYYq1Wo7HU79MZ8vCmCQjfkez1F8YPfGGv8pjSh97WwtPsy43X1x2djyu3i2KSTMJFw7mirzo69r2NiPbvfg7tVwZhUxsWn7Wi2BvYPyKbCKVGeSrSq4Ndsukn25WKuZxFCzEBbpn99GvQ6b1e3pPuv43PZCeY6JUP

**Comment by echoby** [comment]
receive lib - 5.0.9000 :
Fp1b6koogFKHf57sFRd4nh6cVmKSFDMks9vBZf5hkWpqvqNRumhip6xb5vVGLgR4VJYjrUAzMkrg8j4MUY9xmTuKmkFqrMzsSXtYDP2W1tts8vREWeVSaeuf9ss9nQB5ur2A1u

**Comment by echoby** [comment]
swap lib - 5.0.9000 :
7XLEpZQqS1nqYjaddwztAfKMYXKtiU478sMp6BvVzzUkw5Tu8y3qQgzViguHgM7rWchQixFmiSVaEcM1qtiW2vW8mPQWLcbokrj1DEMqh5R7iXfq5PweXRjtWdKGKZMXFhhqoCRQ9homVx1P2x96xJWnXntN1HaTM9HS9RnrqLRgvRc74zFNjR

**Comment by Roberrtt** [comment]
There's no message if you make a swap in  CLI/API
swap lib - 5.0.9000 
![Screenshot_333](https://user-images.githubusercontent.com/50007056/82443650-841f8f00-9aaa-11ea-847c-95635c66abd5.png)

**Comment by Roberrtt** [comment]
checked
