### ISSUE TITLE
Wallet Service: Change password method

### ISSUE THREAD

**Issue by iscander01** [BeamMW/beam#1436]
Need to add method for changing password of existing wallet

**Comment by anatolse** [comment]
added new method to change password of the wallet
request:
```json
{
    "jsonrpc":"2.0", 
    "id": 4,
    "method":"change_password", 
    "params":
    {
        "new_pass" : "password244#" 
    }
}
```

response:

```json
{
    "jsonrpc":"2.0", 
    "id": 4,
    "result": 
    {
          "done"
    }
}
```

**Comment by iscander01** [comment]
After changing password create_address method returning error:
error: {code: -32603, message: ""}
code: -32603
message: ""

**Comment by chapati** [comment]
Would you please test on the latest build (check with me if it is deployed for master). It should be fixed now.

Also there are 2 more problems with change password workflow:

*Problem 1*
1) change password
2) service socket is closed/disconnected (service killed for example, network cable unplugged &c.)

Wallet tries to relogin with old password.

{"jsonrpc":"2.0","id":124,"method":"open_wallet","params":{"pass":"1","id":"5c70b5fcc002d27e932b02c524186fe092222a08e4005369f936dff2c3e4a3ec"}}

{"error":{"code":-32012,"data":"File is not a database","message":"Database error"},"id":124,"jsonrpc":"2.0"}

You can use wallet in this situation only if you logout and login again.

*Problem 2*
1) Start changing password, do not click change in the 2nd dialog
2) Wallet service & balancer become inaccessible (unplug network cable/wifi)
3) Click change password

Wallet password changed locally but not remotely.
It is impossible to login into your wallet ever again. Local password check doesn't pass with the old password, extensions expects new password. Remote service expects new password. Wallet becomes inaccesible.

**Comment by iscander01** [comment]
1 and 2 Problems fixed

**Comment by chapati** [comment]
Please test now. Should be fine at last.

**Comment by VladislavKulyba** [comment]
> Please test now. Should be fine at last.

Checked
