### ISSUE TITLE
Duplicate peers can be opened

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#144]
**Bug description**
Duplicate peers with the same IP are allowed to be created in the "Settings".

**Expected behaviour**
A message "peer already exists" should be shown.

**Platform and build**
* All platforms

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/44961099/49687718-a2553180-fb39-11e8-9d0b-b3e13225842e.png)

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova when you'll redesign the "settings" screen please keep in mind to show the error about duplicate peers

**Comment by alexandrashelenkova** [comment]
zpl.io/blPjJe1

**Comment by alexandrashelenkova** [comment]
Error message is on that screen https://zpl.io/blPjJe1

**Comment by chapati** [comment]
Will be fixed here https://github.com/BeamMW/beam/issues/1486
Closing as duplicate
