### ISSUE TITLE
Swap stucked 'in progress' on beam side despite refund on BTC side was finished

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam#1444]
![Snag_bdadfb](https://user-images.githubusercontent.com/51320829/82541561-52b1cc80-9b59-11ea-9d53-a42bfa7b48dd.png)

tx_id: 5b0824181509499fac49477f336c72a8
Beam side
database: 
[wallet1.zip](https://github.com/BeamMW/beam/files/4661489/wallet1.zip)
pass 1
Logs: [beam_ui_20_05_21_10_49_04.log](https://github.com/BeamMW/beam/files/4661472/beam_ui_20_05_21_10_49_04.log)
[beam_ui_20_05_21_09_59_12.log](https://github.com/BeamMW/beam/files/4661474/beam_ui_20_05_21_09_59_12.log)

BTC side
database:[wallet.zip](https://github.com/BeamMW/beam/files/4661492/wallet.zip)
pass 1
Logs: [beam_ui_20_05_21_09_59_17.log](https://github.com/BeamMW/beam/files/4661482/beam_ui_20_05_21_09_59_17.log)

**Comment by echoby** [comment]
Not a bug.
After beam lock time expired, transaction will change status on "expired".
