### ISSUE TITLE
Wallet Summary - shielded coins

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam#1448]
Add shielded outputs to wallet summary. Both for BEAM & ASSETS

**Comment by Roberrtt** [comment]
If coins were taken out of the pool  then after restoring wallet the amount specified in  "Shielded" field is incorrect

before restoring
![Screenshot_356](https://user-images.githubusercontent.com/50007056/82810214-93318300-9e96-11ea-852a-4ce948042bc5.png)

after 
![Screenshot_357](https://user-images.githubusercontent.com/50007056/82810395-118e2500-9e97-11ea-95de-6317097d6dd0.png)

**Comment by Roberrtt** [comment]
checked
