### ISSUE TITLE
Wallet UI - Show Clear Mining Node Status 

### ISSUE THREAD

**Issue by bdevelle** [BeamMW/beam#145]
In Settings, add simple mining node status and very basic statistics - for example: 

Node Status: Mining using GPU / Mining using 6 CPU threads / Not Mining
Hash Rate: XXX / Not Available
Number of Blocks Mined: 10
Total BEAM Mined: 800 BEAM

@breakphreak

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova not necessarily in settings, let's think on where we could display useful stats. Some are shown in UTXO screen (blockchain height, for example), others are suggested here. We'll also have blockchain explorer soon that will display even more params. This is a post-mainnet task (not urgent).

**Comment by bdevelle** [comment]
> @alexandrashelenkova not necessarily in settings, let's think on where we could display useful stats. Some are shown in UTXO screen (blockchain height, for example), others are suggested here. We'll also have blockchain explorer soon that will display even more params. This is a post-mainnet task (not urgent).

It doesn't have to be in settings, but i think it should be on the same screen where you setup the local node; making changes in local node (e.g moving from GPU to CPU or disabling mining) would be represented in the status, without the need for the user to move to a different screen.

**Comment by alexandrashelenkova** [comment]
I think we should show it on Blockchain info screen, not in settings.

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova maybe we need a separate screen for node status and settings twisting? currently the wallet also becomes a node-control-center. I can explain during our call. Not urgent at all.

**Comment by alexandrashelenkova** [comment]
ok

**Comment by sasha-abramovich** [comment]
Wallet is not mining anymore.
