### ISSUE TITLE
Require wallet password to broadcast transaction - windows wallet gui

### ISSUE THREAD

**Issue by bdevelle** [BeamMW/beam#146]
Suggest to require wallet password for each transaction broadcast

@breakphreak

**Comment by gingervik** [comment]
we need design @sasha-abramovich

**Comment by alexandrashelenkova** [comment]
I added screen here zpl.io/2EKDxLv, but with that screen https://zpl.io/bA4YNwn it would be way too much confirmations for transactions - not good for ux. So I think we should remove transaction review screen.

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova this "password confirm" mode should be specifically switched on in settings and if so - the transaction review screen should ask for password, so we won't have 2 screens. How about that?

**Comment by alexandrashelenkova** [comment]
I wouldn't mix review and input screens - it's not good ux too. That's why I didn't put password confirmation field on review screen (not because I didn't think about that).

**Comment by sasha-abramovich** [comment]
Why it's not good to show password re-entry dialog with some extended transaction information?

**Comment by alexandrashelenkova** [comment]
Because review and input are different actions. They better shouldn't be on one alert message.

**Comment by sasha-abramovich** [comment]
are 2 dialogs better? or anything else - I'm really open. this is a secure app and we might need the extra-verification step, so let's think about the tradeoffs and tell what will work :)

**Comment by alexandrashelenkova** [comment]
zpl.io/bA4YNwn

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova we need a design for the relevant slide in the settings.

**Comment by alexandrashelenkova** [comment]
@sasha-abramovich what exactly we have to confirm in settings with that window?

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova we need a slider something like "ask password for every sending transaction" in the settings (sorry for the delayed reply)

**Comment by Sergei-Beam** [comment]
checked on master

**Comment by gingervik** [comment]
@echoby please, make switcher off by default

**Comment by jurijakimuk** [comment]
Can't apply new settings.
**Zipped video**
[apply changes button.zip](https://github.com/BeamMW/beam/files/3120155/apply.changes.button.zip)
@echoby please, take a look

**Comment by echoby** [comment]
recheck, pls

**Comment by jurijakimuk** [comment]
OK on 4814, master build.
