### ISSUE TITLE
SSL support for web sockets

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#1467]
add the ability to set up a secure connection between web-wallet and wallet service instance

**Comment by anatolse** [comment]
postponed for a while, it seems that we don't need this

**Comment by chapati** [comment]
Encryption would be implemented using cloud services. Closing this for now.

**Comment by chapati** [comment]
This is done

**Comment by chapati** [comment]
@iscander01 
Please update build

ng build --configuration=testnet - domain, no port
ng build --configuration=masternet - domain, no port
ng build - local ip:port

**Comment by iscander01** [comment]
done
