### ISSUE TITLE
Self sent INCOME transaction doesn't show in transactions list 

### ISSUE THREAD

**Issue by bdevelle** [BeamMW/beam#147]
When sending BEAM to myself, i am able to see the OUTGOING transaction (e.g. -100 BEAM), however the income tranasaction doesn't show in the list (it does show under UTXO)

![image](https://user-images.githubusercontent.com/8321522/49689391-41256200-fb29-11e8-9054-aa6859fadc3b.png)

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova should the self-send money appear as "sent+received" (2 lines) or as a special single line?

**Comment by gingervik** [comment]
@sasha-abramovich as @anatolse said we display only outcome transaction

**Comment by sasha-abramovich** [comment]
@gingervik this is the current behaviour which might be fine for a while, but I've asked @alexandrashelenkova to prepare the design as-it-should be for the longer run.

**Comment by alexandrashelenkova** [comment]
I think for that kind of transaction we need different UI not only for transaction list (because it's transferring money between own accounts).

**Comment by sasha-abramovich** [comment]
ok, for what else? UTXOs seems to be fine... maybe a hint on the send screen? something like "you are about to send money to yourself"?

**Comment by alexandrashelenkova** [comment]
zpl.io/bWLWYDM
zpl.io/adr47dE

**Comment by gingervik** [comment]
irrelevant. status was changed
