### ISSUE TITLE
Get recommended fee rate from blockchain

### ISSUE THREAD

**Issue by roman-strilets** [BeamMW/beam#1472]
Investigate how to get recommended fee rate from blockchain using of bitcoin core and bitcoin electrum

**Comment by roman-strilets** [comment]
can be checked after https://github.com/BeamMW/beam-ui/issues/66 is done

**Comment by Sergei-Beam** [comment]
Create Swap Offer - fee errors - when wallet cant show fee rate from network https://zpl.io/VqoEKeG
![image](https://user-images.githubusercontent.com/47353570/89016564-98d99800-d321-11ea-891f-e0cc0ba69b81.png)

Need to check these errors here

**Comment by roman-strilets** [comment]
@Sergei-Beam move previous item to https://github.com/BeamMW/beam-ui/issues/66

**Comment by Sergei-Beam** [comment]
> Create Swap Offer - fee errors - when wallet cant show fee rate from network https://zpl.io/VqoEKeG
> ![image](https://user-images.githubusercontent.com/47353570/89016564-98d99800-d321-11ea-891f-e0cc0ba69b81.png)
> 
> Need to check these errors here

Moved to https://github.com/BeamMW/beam-ui/issues/66

**Comment by roman-strilets** [comment]
example:
beam-wallet-masternet.exe estimate_swap_feerate --swap_coin=btc

**Comment by kazaryan-t** [comment]
If swap settings are not initialized, CLI wallet shouldn't show recommended fee rate = 0 (should show an error)
![2](https://user-images.githubusercontent.com/68247034/90632495-2b889b00-e22d-11ea-9913-e422ce95751a.png)

**Comment by kazaryan-t** [comment]
![01](https://user-images.githubusercontent.com/68247034/90763955-3f490580-e2f0-11ea-97ab-ddc3d78587fe.png)

**Comment by kazaryan-t** [comment]
Checked.
