### ISSUE TITLE
After the installation and network sync the wallet is stuck with zero height and user can do nothing

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#148]
**Bug description**
The wallet is stuck unsyncronized, user can't do anything and no error is shown

**To Reproduce**
Steps to reproduce the behaviour:
1. Installed the wallet desktop app
2. Create the wallet
3. Waited for the network sync to complete (it might be that the slider reached 5+K blocks from 7K total)
4. Seen the network sync slider reaching 20% and probably not more.
5. Seen the wallet screen with "online" status and no errors, couldn't receive any money.

**Expected behaviour**
Error messages, re-connects, re-syncs to bring the wallet to the workable state

**Platform and build**
* Mac
* Latest Mojave 10.14.2
* 1.0.3607

**Logs**
Attached. 
[beam_ui_18_12_08_21_28_46.log.gz](https://github.com/BeamMW/beam/files/2660250/beam_ui_18_12_08_21_28_46.log.gz)
[beam_ui_18_12_08_22_09_36.log.gz](https://github.com/BeamMW/beam/files/2660251/beam_ui_18_12_08_22_09_36.log.gz)
[beam_ui_18_12_09_01_39_13.log.gz](https://github.com/BeamMW/beam/files/2660252/beam_ui_18_12_09_01_39_13.log.gz)
[beam_ui_18_12_09_04_39_13.log.gz](https://github.com/BeamMW/beam/files/2660253/beam_ui_18_12_09_04_39_13.log.gz)
[beam_ui_18_12_09_07_39_14.log.gz](https://github.com/BeamMW/beam/files/2660254/beam_ui_18_12_09_07_39_14.log.gz)
[beam_ui_18_12_09_10_41_38.log.gz](https://github.com/BeamMW/beam/files/2660255/beam_ui_18_12_09_10_41_38.log.gz)

**Screenshots**
![image](https://user-images.githubusercontent.com/44961099/49693107-b5e5b400-fb9c-11e8-9431-bf08e11b4254.png)
![image](https://user-images.githubusercontent.com/44961099/49693110-bed68580-fb9c-11e8-873f-4f1d7332d817.png)

**Comment by sasha-abramovich** [comment]
after almost 20 hours the wallet got in sync... strange at least. I've switched torrent off, but it's not that the torrent was consuming all the bandwidth - other apps were working fine (even Telegram voice calls, which was a bit disrupted but still ok).

[beam v1.0.3607 osx report.zip](https://github.com/BeamMW/beam/files/2660350/beam.v1.0.3607.osx.report.zip)

**Comment by beam-mw** [comment]
Can not reproduce
