### ISSUE TITLE
Wallet generate_phrase does not work

### ISSUE THREAD

**Issue by illera88** [BeamMW/beam#149]
**Bug title**
Wallet generate_phrase does not work
**Bug description**
No phrase is printed when using generate_phrase in the wallet
**To Reproduce**
Steps to reproduce the behaviour:
run `./wallet/beam-wallet --command generate_phrase`

**Current behaviour**
A clear and concise description of the erroneous behaviour which currently happens.

**Expected behaviour**
A truly random phrase should be printed

Related with #136

**Comment by gingervik** [comment]
closed as duplicate
https://github.com/BeamMW/beam/issues/136
