### ISSUE TITLE
CA Metadata

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam#1490]
Need to discuss non-mandatory CA metadata fields for assets browser implementation.
Requested by @sasha-abramovich

**Comment by sasha-abramovich** [comment]
https://github.com/BeamMW/beam/wiki/Asset-Descriptor-v1.0 
@chapati please review and update the document

**Comment by chapati** [comment]
Done. Need to update CLI, discuss warning of optional meta.

**Comment by chapati** [comment]
SCHEMA_VER is now enforced

**Comment by VladislavKulyba** [comment]
Bad (non-std) asset metadata for option --asset_meta "STD:SCH_VER=1;N=Luch Coin;SN=LUCH;UN=Luch;NTHUN=Glass"  

![Snag_10ec051](https://user-images.githubusercontent.com/51320829/86585434-23cbaa80-bf8f-11ea-9fbb-46f5b8df96a3.png)

**Comment by Roberrtt** [comment]
If asset was registered before the changes in metadata, then after updating the wallet,  name of the coins and asset disappeared.
![Screenshot_35](https://user-images.githubusercontent.com/50007056/86605678-ac5a4300-bfaf-11ea-9b6e-97ade36f4d12.png)
Note:
If you send  asset, the receiver will see the correct metadata
![Screenshot_70](https://user-images.githubusercontent.com/50007056/86605824-df9cd200-bfaf-11ea-9c3b-2596cbfa380a.png)

**Comment by chapati** [comment]
> Can't registrate asset. Bad (non-std) asset metadata for option --asset_meta "STD:SCH_VER=1;N=Luch Coin;SN=LUCH;UN=Luch;NTHUN=Glass"
> 
> ![Snag_10ec051](https://user-images.githubusercontent.com/51320829/86585434-23cbaa80-bf8f-11ea-9fbb-46f5b8df96a3.png)

This should be fixed on the latest rev.

**Comment by chapati** [comment]
> If asset was registered before the changes in metadata, then after updating the wallet, name of the coins and asset disappeared.
> ![Screenshot_35](https://user-images.githubusercontent.com/50007056/86605678-ac5a4300-bfaf-11ea-9b6e-97ade36f4d12.png)
> Note:
> If you send asset, the receiver will see the correct metadata
> ![Screenshot_70](https://user-images.githubusercontent.com/50007056/86605824-df9cd200-bfaf-11ea-9c3b-2596cbfa380a.png)

Check this too.

**Comment by Sergei-Beam** [comment]
Checked https://github.com/BeamMW/beam/issues/1490#issuecomment-654158898 and https://github.com/BeamMW/beam/issues/1490#issuecomment-654280770

**Comment by Sergei-Beam** [comment]
@chapati 
Need to add a check for max_lengh for 
- OPT_SHORT_DESC= a one-liner, should not exceed 128 characters
- OPT_LONG_DESC= a paragraph, should not exceed 1024 characters

**Comment by chapati** [comment]
New checks (SCH_VER, OPT_SHORT_DESC, OPT_LONG_DESC) are enforced only for asset isue. Other operations alow v5.0 meta to support already issued assets.

**Comment by Sergei-Beam** [comment]
Checked
A separate ticket for adding error messages was created
https://github.com/BeamMW/beam/issues/1547
