### ISSUE TITLE
Remove "address expiration" from notification settings

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam#1493]
Please remove notification "address expiration" 

- from notification settings screen https://zpl.io/bLlyKeJ
- from notification screen

![image](https://user-images.githubusercontent.com/47353570/84636902-d020f080-aefd-11ea-83b2-2ba3526b3083.png)

**Comment by anatolse** [comment]
UI was removed in https://github.com/BeamMW/beam-ui/issues/41

**Comment by anatolse** [comment]
I'm not sure we should remove this feature from the library

**Comment by gingervik** [comment]
done in ui project
