### ISSUE TITLE
Coins selection & lelantus

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam#1498]
1) At the moment for lelantus fee we try to select first unlinked coins and then both unlinked and linked. This might pose a privacy issue. Need to discuss adjustments to it.  May be fail or print warning when both linked & unlinked coins are used to pay fee for pull transaction? Ask user permission?

2) For usual transactions & transactions fees both linked & unlinked coins are used by default. This can spend unlinked coins when user does not want it and when it is not necessary. Do we want to try just linked first and ony if not enough try both linked & unlinked? Do we want to print warning/ask user if usage of linked coins is allowed for usual fees? May be add flag to make transaction use only linked or only unlinked coins?

**Comment by chapati** [comment]
We've decided to block base lelantus operations for user. Push & Pull transactions should be not possible anymore.
TODO: mention this in release notes, advice to finish all lelantus ops before upgrade.

**Comment by Denis-Asipenko** [comment]
Basic lelantus operations disabled. Checked.
