### ISSUE TITLE
Separate commands for init and recovery

### ISSUE THREAD

**Issue by illera88** [BeamMW/beam#150]
I don't understand why a phrase should be provided when doing:
`./wallet/beam-wallet --command init`.

As I see it, it should be an option to ask for it in the case of restoring a wallet but it should be generated randomly at generation time by default.

**Comment by gingervik** [comment]
Hi @illera88 
it was done in https://github.com/BeamMW/beam/issues/136
will be include in next release

**Comment by illera88** [comment]
I saw that option but as stated at #149 it seems not to work.

Anyway what I'm proposing is that the phrase is generated automatically when `init` is run instead of using `generate_phrase` to later use it in `init`.

Cheers

**Comment by gingervik** [comment]
nice idea. we'll realise it.
thank you

**Comment by gingervik** [comment]
@anatolse 
we need add generate_phrase to init command

in this case we'll have --init and --recovery as two separate commands

**Comment by Sergei-Beam** [comment]
checked
