### ISSUE TITLE
Inappropriate maturity for UTXO with 'in progress' status

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam#1500]
Steps to reproduce:
1. Send some UTXO to Web Wallet 
2. In web-wallet go to Utxo Screen
3. Choose 'In progress' tab.

Expected: appropriate maturity for this UTXO
Actual: Inappropriate maturity for this UTXO

![Snag_84f8c58](https://user-images.githubusercontent.com/51320829/85272423-d3c7f080-b484-11ea-8993-3b90dfc97ae8.png)
![image](https://user-images.githubusercontent.com/51320829/85272447-daeefe80-b484-11ea-9b7b-85ebda7198ab.png)

**Comment by chapati** [comment]
This should be fixed in web wallet js code. We shouldn't show maturity for Unavailable & Incoming coin. Same as in the GUI wallet.
![gnome-shell-screenshot-RH5PM0](https://user-images.githubusercontent.com/12074933/85301452-86617880-b4b0-11ea-9ec5-9c18e9185c5b.png)

**Comment by VladislavKulyba** [comment]
checked
