### ISSUE TITLE
Add the "Asset transactions are disabled in the receiver wallet" error message 

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam#1502]
Please, add error message "Asset transactions are disabled in the receiver wallet" for cases when receiver didn't enable assets. For example, assets enabled in the sender wallet, but transaction failed. The error message is uncleared.
![Snag_166b2c8](https://user-images.githubusercontent.com/51320829/85324982-858e0e00-b4d3-11ea-89fc-5a1819f2915a.png)

**Comment by VladislavKulyba** [comment]
Waiting fix of #1490

**Comment by VladislavKulyba** [comment]
It's reproduced when receiver is an old version. Please, fix it.

**Comment by VladislavKulyba** [comment]
![image](https://user-images.githubusercontent.com/51320829/87436878-49435e80-c5f6-11ea-9620-4db47e08e8b5.png)

Both error messages are the same. The error message in the sender wallet is correct right now (Asset transactions are disabled in the receiver wallet). But in the receiver wallet, it should be "Asset transactions are disabled in your wallet" (or ...in this wallet, ...in current wallet).

**Comment by echoby** [comment]
Not reproduced
<img width="1326" alt="1" src="https://user-images.githubusercontent.com/1681548/89050571-9d22a700-d35b-11ea-9256-098a78988a35.png">
<img width="1326" alt="2" src="https://user-images.githubusercontent.com/1681548/89050581-9f850100-d35b-11ea-8d9f-7cd429055123.png">

**Comment by VladislavKulyba** [comment]
Checked

build 5.0.9426
