### ISSUE TITLE
Missing fund after resacn  Desktop Wallet (windows)

### ISSUE THREAD

**Issue by koventheboy** [BeamMW/beam#1505]
Please help to troubleshoot my balance issue.

1. Failed to send my fund from the Desktop Wallet (windows)
2. Rescanned the wallet and got updated.
3. Only about half of the fund was shown.
4. Deleted the whole "Beam Wallet" folder and restored my wallet form seed phrase from scratch.
5. Still, the wrong amount of the balance was shown.

Thank you very much.

**Comment by VladislavKulyba** [comment]
Hello, it seems that we investigate this issue. Did we discussed your issue in Discord?

**Comment by koventheboy** [comment]
@VladislavKulyba  Yes, you have assisted me in Discord and it is ongoing . Thank you very much.

**Comment by VladislavKulyba** [comment]
You're welcome. I close this issue here and we'll continue dicuss in Discord
