### ISSUE TITLE
Beam side gets an error after the lock btc "Bridge internal error: type = 3;"

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1506]
The swap doesn't end on beam side.
The beam side locks the BTC and then gets an error 
`Bridge internal error: type = 3; message = non-mandatory-script-verify-flag (Witness program was passed an empty witness) (code 64)`

Used:
2 UI wallets build 5.0.9142.2887
bitcoin-core 0.17.0

{BTC side}  Amounts for create swap : 
send BTC = 0.002354
receive Beam = 10
Beam fee =100 Groth
BTC fee rate = 90 000 sat/kb 

{Beam side}
Accept this offer with BTC fee rate =  90 000 sat/kb : Beam fee =100 groth

Transaction ID : 54c5ad459e924fac85bb9cfcddb1a794

BTC side -swap completed
[BTC side logs.zip](https://github.com/BeamMW/beam/files/4819767/BTC.side.logs.zip)

Beam side -swap in progress 
[Beam side logs.zip](https://github.com/BeamMW/beam/files/4819772/Beam.side.logs.zip)

**Comment by roman-strilets** [comment]
it's fixed at 3dbaba41436ad307560320a08cad1eba9763ef66

**Comment by roman-strilets** [comment]
need to discuss

**Comment by Aleksandr-Starun** [comment]
discussed.

**Comment by Roberrtt** [comment]
checked
