### ISSUE TITLE
nvidia 1060 6gb gpu mined coins not credited/mined !

### ISSUE THREAD

**Issue by karanpatel863** [BeamMW/beam#151]
**Bug title**
cant mine any beam using nvidia 1060 6gb.

**Bug description**
I have been trying to mine beams using Beam wallet with my nvidia 1060 6gb which is a supported graphic card. unfortunately, I was not able to mine any coins since 5 hours.
I have installed latest drivers of motherboards and gpu.
pleased help me in solving it ! 

**To Reproduce**
Steps to reproduce the behaviour:
1. Run 'beam wallet' (as admin)
2. Do ' go to settings & select local node with with gpu mining selected'

**Current behaviour**
unable to mine any coins since start

**Expected behaviour**

**Platform and build**
* Windows 10
[beam v1.0.3607 windows report.zip](https://github.com/BeamMW/beam/files/2660281/beam.v1.0.3607.windows.report.zip)

* BEAM wallet latest testnet 3 build

**Comment by sasha-abramovich** [comment]
do you have the most recent drivers please?

**Comment by karanpatel863** [comment]
@sasha-abramovich yes the latest one which I installed yesterday

**Comment by karanpatel863** [comment]
@sasha-abramovich sorry I closed the issue by mistake. reopened now

**Comment by sasha-abramovich** [comment]
Np, the team will look at it tomorrow.

**Comment by karanpatel863** [comment]
hello,

I have deleted the wallet file and restored it.
it worked by reconfiguring everything from start.

thanks anyways :)
