### ISSUE TITLE
Sometimes "generate_electrum_seed" generates 11 words

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1512]
Using this command` beam-wallet-masternet.exe set_swap_settings --swap_coin btc --electrum_addr electrum3.hodlister.co:50002 --active_connection electrum` ,  CLI wallet issued 11 words instead of 12
![Screenshot_9](https://user-images.githubusercontent.com/50007056/86104450-b919fb00-bac6-11ea-9735-af30604e3a33.png)

build :5.0.9169

**Comment by roman-strilets** [comment]
fixed at 8872a5b3b657a9b8bb8a76550acb97a223023485

**Comment by Roberrtt** [comment]
checked
