### ISSUE TITLE
Cannot download the Beam Desktop Wallet for Windows

### ISSUE THREAD

**Issue by RFB-Ripple** [BeamMW/beam#1514]
Hello:

I have tried Brave browser and Chrome on 2 different computers and I cannot download the Beam Desktop wallet for windows.   I get a error: builds.beam.mw sent an invalid response.   ERR_SSL_PROTOCOL_ERROR

How can I fix?
Thanks,
Rich

**Comment by SomethingGettingWrong** [comment]
Hey,

The wallet is actually in the windows store as well if you would like to check that out :)

**Comment by gingervik** [comment]
@RFB-Ripple hi, please, try to download wallet from github https://github.com/BeamMW/beam-ui/releases/tag/beam-5.0.9328.2865
