### ISSUE TITLE
Add warning if user tries to send BEAMs from expired SBBS address

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#1515]
We don't check that sender's address is valid. It is not related to UI wallet, and CLI since we automatically generate a new address, but in API this is important.

**Comment by anatolse** [comment]
BTW, there is a check in API which should return 
  error: {
    code: -32003,
    data: 'Sender address is expired.',
    message: 'Invalid address.'

**Comment by anatolse** [comment]
updated wallet API wiki with the errors list
https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API#errors

**Comment by Denis-Asipenko** [comment]
checked
