### ISSUE TITLE
Transaction sent to myself failed

### ISSUE THREAD

**Issue by azaidelson** [BeamMW/beam#152]
**Bug title**
Transaction sent to myself failed

**Bug description**
I sent 100 beam to myself, but transaction appears as "Failed"

**To Reproduce**
Steps to reproduce the behaviour:
1. Start Beam Wallet
2. Click "Receive", then click "Copy"
3. Click "Send". Paste the address into the "Send To:", click Send
4. Transaction immediately appears as "Failed"

**Current behaviour**
Transaction fails

**Expected behaviour**
Transaction should succeed

**Platform and build**
* Windows 10
* BEAM Build number: 1.0.3607

**Configuration, log, memory dump files (if applicable)**
[beam v1.0.3607 windows report.zip](https://github.com/BeamMW/beam/files/2660619/beam.v1.0.3607.windows.report.zip)

**Screenshots (if applicable)**
![screenshot](https://user-images.githubusercontent.com/21197401/49698803-71284000-fbd1-11e8-9e61-70c37f09c529.png)

**Comment by beam-mw** [comment]
Can not reproduce in M1 flows

**Comment by ChrisFrench** [comment]
I had a transaction sent from Hotbit. 

<img width="945" alt="screen shot 2019-01-23 at 5 55 20 am" src="https://user-images.githubusercontent.com/210848/51611404-022e4e80-1ed4-11e9-9bc0-83af2184a44f.png">

**Comment by offchainforker** [comment]
i had beam transaction from hotbit aswell and also failed. how did you solve that?

> 
> 
> I had a transaction sent from Hotbit. Which failed.
> 
> <img alt="screen shot 2019-01-23 at 5 55 20 am" width="945" src="https://user-images.githubusercontent.com/210848/51611404-022e4e80-1ed4-11e9-9bc0-83af2184a44f.png">

i had beam transaction from hotbit aswell and also failed. how did you solve that?
