### ISSUE TITLE
Stratum server job difficulty seems incorrect

### ISSUE THREAD

**Issue by deh8551** [BeamMW/beam#1522]
**Bug title**
The stratum server in the beam node offers jobs with a difficulty that seems too high

**Bug description**
Running a local beam-node built from mainnet and performing local mining.  The difficulty for the jobs offered by the built-in stratum server is running around 42.1M, same as it was prior to the hard fork.  it doesn't seem to offer jobs matching the current difficulty of the chain 

**To Reproduce**
Steps to reproduce the behaviour:
Run local node
Connect miner, GMINER of BMINER to local node

**Current behaviour**
Stratum job difficulty seems too high.

**Expected behaviour**
Expecting job difficulty to match chain difficulty

**Platform and build**
Docker build from mainnet git commit 7f26e0c8225cbda9d973d08363bdad10659a06d1

**Log file(s) (if applicable)**
TCPDUMP of job

20:59:18.366280 IP (tos 0x0, ttl 63, id 35066, offset 0, flags [DF], proto TCP (6), length 210)
    10.0.1.21.10002 > 10.0.1.23.50714: Flags [P.], cksum 0xc3e5 (correct), seq 2400674226:2400674384, ack 661625030, win 227, options [nop,nop,TS val 2007631 ecr 4188157007], length 158
        0x0000:  4500 00d2 88fa 4000 3f06 9c00 0a00 0115  E.....@.?.......
        0x0010:  0a00 0117 2712 c61a 8f17 61b2 276f 98c6  ....'.....a.'o..
        0x0020:  8018 00e3 c3e5 0000 0101 080a 001e a24f  ...............O
        0x0030:  f9a2 344f 7b22 6469 6666 6963 756c 7479  ..4O{"difficulty
        0x0040:  223a 3432 3037 3038 3732 352c 2268 6569  ":420708725,"hei
        0x0050:  6768 7422 3a37 3932 3336 342c 2269 6422  ght":792364,"id"
        0x0060:  3a22 3333 3222 2c22 696e 7075 7422 3a22  :"332","input":"
        0x0070:  6438 3966 6132 3133 3562 6633 3961 6465  d89fa2135bf39ade
        0x0080:  3631 3063 3537 3366 3835 3633 3566 3264  610c573f85635f2d
        0x0090:  3363 3635 3939 6337 6139 6337 6533 3334  3c6599c7a9c7e334
        0x00a0:  3631 3662 3963 3930 3838 6166 3134 3835  616b9c9088af1485
        0x00b0:  222c 226a 736f 6e72 7063 223a 2232 2e30  ","jsonrpc":"2.0
        0x00c0:  222c 226d 6574 686f 6422 3a22 6a6f 6222  ","method":"job"
        0x00d0:  7d0a                                     }.

**Comment by Lolliedieb** [comment]
This is more a display bug of GMiner then a bug in the node.
The value send out can not be read as an Integer, because it is a floating point format that needs to be converted to the real difficulty before usage. GMiner and BMiner seem to not translate this before printing (but after, since they send shares with the right difficulty).

Here you can see the conversion done in the reference miner:
https://github.com/BeamMW/opencl-miner/blob/BeamHashIII/stratum/beamStratum.cpp#L242

**Comment by deh8551** [comment]
Thank you for the clarification.
