### ISSUE TITLE
Wallet - "changing" status for max privacy transaction

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam#1528]
Status flow for Max privacy transaction status:
changing - in progress - sent

1) Wallet https://zpl.io/2ENXQ7M
![image](https://user-images.githubusercontent.com/47353570/87426738-56f1e780-c5e8-11ea-8122-e3abc0979ee1.png)

2) Transaction details https://zpl.io/amkG3zA
![image](https://user-images.githubusercontent.com/47353570/87426759-62451300-c5e8-11ea-8209-1d565cb96858.png)

**Comment by anatolse** [comment]
Shielded transaction doesn't have changing stage. Closing
