### ISSUE TITLE
Have to jump from g++ 7 to g++ 6 then g++ 7 again when compiling

### ISSUE THREAD

**Issue by entinio** [BeamMW/beam#153]
Have to jump from g++ 7 to g++ 6 then g++ 7 again when compiling

The project is asking to install and use g++ 7 to compile it. Ok, here we go, compiling the testnet 3 on an ubuntu 18.04 platform. Then I get this error : 

```
In file included from /usr/include/host_config.h:50:0,
                 from /usr/include/cuda_runtime.h:78,
                 from <command-line>:0:
/usr/include/crt/host_config.h:121:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
 #error -- unsupported GNU version! gcc versions later than 6 are not supported!
```

Big LOL here. Requesting g++ 7 but then refusing it ? Ok, switching to g++ 6. I'm going through the previous step, but then here comes the g++ 6 problem : 

```
/home/user/beam3/beam-testnet3/3rdparty/crypto/equihash.tcc:33:35: error: array subscript is above array bounds [-Werror=array-bounds]
                 if (!checked_index[y] && indices.get()[z] == indices.get()[y]) {
                      ~~~~~~~~~~~~~^
```

Yep, g++ 7 requested to move on. Switching back to g++ 7 and then the project is compiled successfully.

```
[100%] Linking CXX executable BeamWallet
[100%] Built target beam-wallet-ui
```

Can you correct the project so we don't have to dance around the gcc/g++ versions ? That would help ;-) Thank you

**Comment by illera88** [comment]
Weird, I didn't have that problem and compiled with the same environment you did. 

I just used gcc7

**Comment by illera88** [comment]
Actually you can see that travis only uses gcc7 https://travis-ci.org/BeamMW/beam/jobs/469553751

**Comment by entinio** [comment]
Just realised it comes from an include and not from your project. I wonder what should be updated to avoid this problem though.
But yeah, weird. Anyway, I still compile it successfully switching to 6 then back to 7.

```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

**Comment by illera88** [comment]
I think your error comes from having cuda9 instead of cuda10. Can you check which cuda sdk do you have?

**Comment by entinio** [comment]
Yep, Cuda9.2 (which is why I have to compile it). For some reasons (some other projects I work on), I can't go to Cuda10 though. Anyway, there's still a workaround.

**Comment by nesbox** [comment]
We are using OpenCL instead of CUDA at the moment, I think, the problem became not relevant.
Closing...
