### ISSUE TITLE
Sources version issue

### ISSUE THREAD

**Issue by entinio** [BeamMW/beam#154]
Sources version issue

When downloading the sources (tar.gz) from the testnet 3 releases link, we get the 1.0.0 version (see issue #142 ). Testnet 3 seems to be the 1.0.3607 version.

When using git clone, I get the 1.0.3642 version. But enough a difference to keep getting the "`Incompatible peer cfg!`" message while trying to sync'.

What hash should I git clone to get the right version to compile ? Thank you

**Comment by gingervik** [comment]
Hi @entinio 
version 1.0.3607
commit hash: 15da99d376db968e8bda701c78cf276173b85950
