### ISSUE TITLE
Sending UTXO that is in maturation.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1542]
At the moment, if we want to send a specific UTXO that is in the maturation, then the wallet takes any other available coin and sends it. We need to decide whether to display a message that the specific coin selected is at the stage of maturation and cannot be sent or leave everything as it is.

**Comment by Sergei-Beam** [comment]
Checked
Currently, sending unavailable coins (**maturing** status) is forbidden
![image](https://user-images.githubusercontent.com/44496108/90056882-449ec280-dce8-11ea-8cd5-75739feb8211.png)
