### ISSUE TITLE
Inconsistency: change_address_expiration default value

### ISSUE THREAD

**Issue by dahifi** [BeamMW/beam#1543]
I found an inconsistency between the documentation and the CLI wallet. Per the docs, p. 134, `./beam-wallet change_address_expiration --address=x` should change the expiration to 'never', but actually sets it to 24hs instead. 

That said, there are additional typos in the documentation, and I would like to contribute some edits, but don't know which repo the PDF is built from.

**Comment by Sergei-Beam** [comment]
Hello @dahifi you are right there are some typos and out to date information in Docs.
Changed some information according to your request

As for your first question to make the address `never` expired you need to use the additional flag `--expiration_time`
For example:
`./beam-wallet change_address_expiration --address=<sbbs address> --expiration_time=never`

**Comment by dahifi** [comment]
@Sergei-Beam yea, I figured that out simply enough. Just want to reiterate my offer to proofread the documentation and fix some of the rendering issues. I assume the source is in one of the repos?

**Comment by gingervik** [comment]
@dahifi yes, you can made a pull request here https://github.com/BeamMW/beam-docs
