### ISSUE TITLE
Update electrum servers list.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1549]
Some electrum servers are no longer working at the moment. we need to update the list of current servers in our wallet.
[Checking electrum servers..zip](https://github.com/BeamMW/beam/files/4989266/Checking.electrum.servers.zip)

**Comment by Roberrtt** [comment]
Remove addresses for BTC mainnet
-"satoshi.fan:50002"
-"thanos.xskyx.net:50002",
- "bitcoin.lukechilds.co:50002", (1 from 2 because they are repeated)

**Comment by Roberrtt** [comment]
checked
