### ISSUE TITLE
Unsupported Video Card

### ISSUE THREAD

**Issue by Byevets** [BeamMW/beam#155]
**Bug title**
Unsupported Video Card

**Bug description**
I am using Six 1080TI's and one 1080
(I know Multi GPU Support is not here yet)

**To Reproduce**
Steps to reproduce the behaviour:
1. try to make a wallet with GUI APP

**Current behaviour**
Not allowing me to use any of my GPU's for mining

**Expected behaviour**
Be able to mine with GPU's listed as supported on beams download page

**Platform and build**
* Windows 8.1 Pro Build 9600
* Testnet3

**Comment by gingervik** [comment]
Hi. @byevets
Please,try to update you videodrivers

**Comment by Byevets** [comment]
According with windows update driver button they are all up to date, maybe I should try a different method to update them.

**Comment by Byevets** [comment]
Yes, I was able to get a node going after upgrading to windows 10 and installing the latest drivers from Nvidia. Windows 8.1 would not allow the latest drivers to be installed.

**Comment by gingervik** [comment]
thank you for your update!
