### ISSUE TITLE
Max-privacy transactions are failing -(Key keeper malfunctioned)

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1553]
When we send few transactions to token with params max-privacy(Online or Offline) . After 2-3 transactions fail with an error Key keeper malfunctioned

Step:
- copy token with params (Max-privacy , Offline token)
- go to send screen
- send few(2-4) transactions on the offline token

Actual: transactions failed 
Expected: transations are sent

**Comment by anatolse** [comment]
Need re-check, with the latest changes in the wallet

**Comment by Roberrtt** [comment]
checked
