### ISSUE TITLE
Cli wallet - if tx has shielded inputs fee should be appropriate 

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#1555]
connected to [beam-ui/issue/88](https://github.com/BeamMW/beam-ui/issues/88)

If user sends a tx which includes shielded utxos we should use appropriate fee
* if a user didn't enter any amount of fee - show a warning  that fee will be <amount> because of using shielded utxos and take the necessary amount of fee
* if a user entered fee < necessary - show a warning that fee is less than needed and abort txs

**Comment by echoby** [comment]
fixed at https://github.com/BeamMW/beam/commit/f0722300a82a9caaf6c26140838a7e34bd19df51

**Comment by KatsiarynaV** [comment]
Will be checked when task  #1554 is done

**Comment by Roberrtt** [comment]
1)  If fee isn't entered, the transaction must be sent and take the necessary fee
- also, show a warning that fee will be because of using shielded utxos  
2) Change the minimum value for the fee from 1000030 to 1200000
![Screenshot_148](https://user-images.githubusercontent.com/50007056/91838137-abfbc280-ec55-11ea-9970-7ccd34d0a680.png)

**Comment by echoby** [comment]
Minimum fee value changed.
If fee isn't entered, only show warning. Transactions with shielded inputs has increased fee, and user must confirm it.

**Comment by Roberrtt** [comment]
The fee is increased by 0.01 each time you try to send a shielded coin from cli  to UI the max privacy address 
![Screenshot_174](https://user-images.githubusercontent.com/50007056/92708854-1cde6100-f35f-11ea-99aa-2324e387faa0.png)
![Screenshot_175](https://user-images.githubusercontent.com/50007056/92708859-1e0f8e00-f35f-11ea-8db7-671f916f8bee.png)

**Comment by Roberrtt** [comment]
checked
