### ISSUE TITLE
Incorrect error when we send from CLI wallet more coins than we have in the wallet. 

### ISSUE THREAD

**Issue by kazaryan-t** [BeamMW/beam#1558]
If we try to send from CLI wallet more coins than we have, the transaction fails with incorrect error. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the CLI wallet.
2. Send a transaction with more coins than you have in the wallet.
3. Pay attention to the error that appears. 

**Actual result**
Error that appears: Missing 1 assets 100 agroth.

**Expected result**
Error that should appear: You only have 1 beam 0 groth.

![8](https://user-images.githubusercontent.com/68247034/89408785-99ab6900-d729-11ea-9c9e-131442e26fa8.png)

**Comment by chapati** [comment]
As discussed 'missing' is left unchanged. Assets/BEAMs should be displayed correctly now.

**Comment by kazaryan-t** [comment]
Checked on master 5.0.9458.3072
