### ISSUE TITLE
mining result rollback

### ISSUE THREAD

**Issue by karanpatel863** [BeamMW/beam#156]
**Bug title**
Encountered erroe while mining in GUI Wallet
"mining result rollback"

**Bug description**
all the blocks are unavailable for couple of hours encountering error " Unavilable- mining result rollback ". this happened twice since yesterday

**To Reproduce**
Steps to reproduce the behaviour:
1. Run beam wallet gui

**Current behaviour**
its normal for now

**Platform and build**
* Windows 10
* BEAM testnet 3 gui wallet

**Screenshots (if applicable)**
images attached.
![screenshot 1](https://user-images.githubusercontent.com/37545404/49709680-96619080-fc5b-11e8-9649-2df287cb0bb9.png)

**Comment by gingervik** [comment]
Hi @karanpatel863 
rollback - it's okay
it means that you mined for a while and then received info from some peer which was more quick then you.
