### ISSUE TITLE
After adding ability to set confirmations count parameter, assets coins can be in "maturing" status.

### ISSUE THREAD

**Issue by echoby** [BeamMW/beam#1561]
1) set confirmations count
2) receive asset coin
3) assert(!c.isAsset())

**Comment by echoby** [comment]
#1532

**Comment by echoby** [comment]
@chapati, Please recheck all info views for assets with "maturing" status

**Comment by chapati** [comment]
Now asset info shows maturity for assets in CLI

**Comment by Denis-Asipenko** [comment]
checked
