### ISSUE TITLE
Two transactions were created for one token at the same time

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam#1562]
When sender used token for sending assets, the were created two transactions with id 2793b6a673fc4ed0aae35cdc1cc2a417 and f9be3fe8cf8e4c4494f397bec5bfc7e4 at the same time. Transaction 2793b6a673fc4ed0aae35cdc1cc2a417 was successful, f9be3fe8cf8e4c4494f397bec5bfc7e4 was failed.
Logs from sender: 
[wallet_20_08_14_16_49_17.zip](https://github.com/BeamMW/beam-ui/files/5083464/wallet_20_08_14_16_49_17.zip)
Logs from receiver:
[logs.zip](https://github.com/BeamMW/beam-ui/files/5083462/logs.zip)

**Comment by KatsiarynaV** [comment]
When sending transaction from CLI wallet to UI wallet via one-time regular token two transaction were created witn id 583bbe12e2b44fb5931c2d8cb25cb50d (successful) and 60f2c5abea5e4732898bba85c554ea03 (stucked in progress in UI wallet and failed in CLI wallet).
Wallets
[beam-wallet-cli-masternet 1.zip](https://github.com/BeamMW/beam/files/5095767/beam-wallet-cli-masternet.1.zip)
[Wallet UI.zip](https://github.com/BeamMW/beam/files/5095769/Wallet.UI.zip)
Password for wallets 1

UI wallet
![1](https://user-images.githubusercontent.com/68267190/90624037-03df0600-e220-11ea-821e-963feb482aa4.jpg)
![3](https://user-images.githubusercontent.com/68267190/90624193-3f79d000-e220-11ea-9264-d09573627859.jpg)
CLI wallet
![2](https://user-images.githubusercontent.com/68267190/90624043-05a8c980-e220-11ea-88b9-6b8a79a0036c.jpg)
![4](https://user-images.githubusercontent.com/68267190/90624045-06d9f680-e220-11ea-95b9-f3dfce192141.jpg)

**Comment by VladislavKulyba** [comment]
Can't check. Transactions stuck in maturing status for CLI wallet when max privacy transactions are sent from UI to CLI. 
![Snag_ad3c54d](https://user-images.githubusercontent.com/51320829/92381004-bf55d480-f112-11ea-8c3d-fd06095c3a6e.png)
logs from node
[logs.zip](https://github.com/BeamMW/beam/files/5182727/logs.zip)
logs from UI 
[beam_ui_20_09_07_11_49_16.log](https://github.com/BeamMW/beam/files/5182730/beam_ui_20_09_07_11_49_16.log)

Step to reproduce: 
1. Generate online max privacy token through command:
beam-wallet-masternet get_token --max_privacy
2. Send some beam from UI to CLI using this token.
3. Do the listen command in CLI: beam-wallet-masternet listen -n ...
4. Do the info command.

Expected: The coins in available status
Actual: The coins in maturing status. Can't be used in other transactions.

The same for an offline token which created with the command: 
beam-wallet-masternet get_token get_token --voucher_count=3

[databases.zip](https://github.com/BeamMW/beam/files/5182817/databases.zip)

Wallet version:
UI Wallet 5.0.9544.3157
CLI wallet 5.0.9546

**Comment by VladislavKulyba** [comment]
still reproduced. build 5.09547.

![Snag_15c0022](https://user-images.githubusercontent.com/51320829/92477748-cf8cb300-f1e9-11ea-89c4-00b3445a6496.png)

[logs.zip](https://github.com/BeamMW/beam/files/5188322/logs.zip)
stuck transaction txId 679b27de22ff4ebdb564048504930689
passed transaction txId 15c10376ba684150951501d08a5b9335

**Comment by VladislavKulyba** [comment]
checked
