### ISSUE TITLE
Max privacy - disable the ability to send to yourself this type of transaction. 

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1564]
**Bug description**
When sending transactions with maximum privacy to yourself, the UTXO screen displays the wrong height, and the "unknown" status is displayed in the transaction list. In "from" field displays the address, not the shielded pool.
![image](https://user-images.githubusercontent.com/45556620/90493307-e1c78400-e14a-11ea-9ab1-dfb69776f322.png)
![image](https://user-images.githubusercontent.com/45556620/90494861-9e6e1500-e14c-11ea-9179-4fa4d32e6169.png)

**Comment by Aleksandr-Starun** [comment]
Done at https://github.com/BeamMW/beam-ui/commit/ac9687b279fb240b9e926d05dc1ede671193955d

**Comment by Denis-Asipenko** [comment]
checked
