### ISSUE TITLE
UI Wallet crashes, when we create new transaction to offline UI Wallet with swap "in progress" and then re-open closed wallet.

### ISSUE THREAD

**Issue by kazaryan-t** [BeamMW/beam#1565]
**Bug description**
When we try to send some coins to offline wallet that has swap "in progress" and then re-open closed wallet, it crashes. 
The reciever wallet has swap "in progress" (node connection) and the sender wallet has the same swap in "failed" status (also node connection).

**To Reproduce**
1. Open two UI Wallets - sender and reciever (UI version 5.0.9484.3083)
2. Send some coins from sender to closed reciever wallet
3. Re-open the reciever wallet, when the sender wallet has transaction status "Waiting for reciever"

**Actual**
Reciever wallet is crashed

**Expected**
Reciever wallet is opened and transaction status in both wallets is "In progress"

[logs sender wallet.zip](https://github.com/BeamMW/beam/files/5095182/logs.sender.wallet.zip)
[wallet.db sender.zip](https://github.com/BeamMW/beam/files/5095185/wallet.db.sender.zip)

[Beam Wallet Masternet DMP.zip](https://github.com/BeamMW/beam/files/5095189/Beam.Wallet.Masternet.DMP.zip)
[logs reciever wallet.zip](https://github.com/BeamMW/beam/files/5095190/logs.reciever.wallet.zip)
[wallet.db reciever.zip](https://github.com/BeamMW/beam/files/5095191/wallet.db.reciever.zip)

Sender wallet password - 1
Reciever wallet password - 1

**Comment by Aleksandr-Starun** [comment]
The problem is with incompatible swap settings. I'm not sure how this happened. Please, try to reproduce it again.

**Comment by kazaryan-t** [comment]
Сannot reproduce.
Сhecked on master 5.0.9504.3103ю
