### ISSUE TITLE
Explorer node. Extend Explorer node API with Atomic Swap and Lelantus info.

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#1568]
1. Draft list of the data we need to expose:
Atomic Swaps data: 
- Show the entire swaps offers (with CTA - want to swap Beam - download  the wallet )
- Total swaps 
- total Beam offered / total BTC offered. 
- Swap history 

Unrelated to swaps: 
- Add price to each block.

Lelantus: 
- show the pool size 
- rate of TX (how quickly the pool is being filled - how quickly youll get the desired anon set)

2. Add wallet instance to the expolrer node  in order to monitor SBBS messages
3. Update https://github.com/BeamMW/beam/wiki/Beam-Node-Explorer-API

**Comment by Roberrtt** [comment]
1. When the explorer-node syncs from null and make a request "GET http://x.x.x.x:port/status " the process stops
2. If you make a " GET " request http://127.0.0.1:8888/blocks?height=256500&n=0", and if n=0, the process is hang 
3. There's no message (want to swap Beam - download the wallet ) in the response

**Comment by Roberrtt** [comment]
checked
