### ISSUE TITLE
Add online Indicator to settings screen

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#157]

**Comment by alexandrashelenkova** [comment]
zpl.io/blPjJe1

**Comment by sasha-abramovich** [comment]
@azaidelson we are adding online indicator to all screens just as agreed. In zeplin, the Settings screen was the only one without the indicator. The implementation is planned to follow.

**Comment by alexandrashelenkova** [comment]
Settings screen already updated in zeplin.

**Comment by sasha-abramovich** [comment]
Before implementing let's consider the design for a second

**Comment by gingervik** [comment]
already done
