### ISSUE TITLE
Allow wallet to recieve the best peers from the node

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#1570]
Now, wallet connects to the single node always, and by default this is one of ours bootstrap nodes. It's not good in case when we have a dns problem. Wallet should get a list or best peers from the bootstrap node and use them to connect to the network.

**Comment by Sergei-Beam** [comment]
checked

**Comment by Denis-Asipenko** [comment]
If you delete the settings.ini file and open the wallet the peers deducted are not displayed in the UI - the screen of the settings looks broken (it is attached to the remote node, but the address and port are empty and an error is written in them)
![image](https://user-images.githubusercontent.com/45556620/118301431-b44a1400-b4eb-11eb-9558-9fc5f504c70a.png)

**Comment by anatolse** [comment]
@Denis-Asipenko, I don't understand the problem. As we can see the wallet is connected to the network, this means that fallback peers mechanism works properly. In the same time, wallet doesn't have user preferences(settings.ini) and doesn't show them. I don't think that we should make a decision for the user)

**Comment by Denis-Asipenko** [comment]
invalid
> If you delete the settings.ini file and open the wallet the peers deducted are not displayed in the UI - the screen of the settings looks broken (it is attached to the remote node, but the address and port are empty and an error is written in them)
> ![image](https://user-images.githubusercontent.com/45556620/118301431-b44a1400-b4eb-11eb-9558-9fc5f504c70a.png)
