### ISSUE TITLE
Error when downloading Windows Desktop v. 5.0.9328.2867 - builds.beam.mw sent an invalid response.

### ISSUE THREAD

**Issue by RFB-Ripple** [BeamMW/beam#1575]
Hi:

Can't download Windows Desktop v. 5.0.9328.2867 - builds.beam.mw sent an invalid response.

Thanks!

**Comment by gingervik** [comment]
Hi @RFB-Ripple 
Please, try to download from https://github.com/BeamMW/beam-ui/releases/tag/beam-5.0.9328.2867
