### ISSUE TITLE
MacOS:Wallet looks awful in fullscreen mode

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#158]
White frames around the wallet in fullscreen

![screenshot_8](https://user-images.githubusercontent.com/45556620/49736523-1a833a80-fc93-11e8-9d57-bd6d05cbdf1e.png)

**Comment by echoby** [comment]
fixed with https://github.com/BeamMW/beam/issues/693

**Comment by gingervik** [comment]
checked
