### ISSUE TITLE
Exolix instant exchange - please, add to the listing

### ISSUE THREAD

**Issue by Exolix-com** [BeamMW/beam#1581]
Hello,

We are Exolix, a secure and anonymous crypto exchange service with fixed rates. We noticed that your website lists exchanges that support BEAM trading and we would like to express our interest in adding our service to listing related to cryptocurrency exchanges on the website as we have BEAM already listed on Exolix for exchange.  

Looking forward to mutual cooperation!

If you have any questions please do not hesitate to contact us.

Best Regards,
Exolix Team
https://exolix.com/

![logo_exolix](https://user-images.githubusercontent.com/56387346/92716002-e86ea300-f366-11ea-8733-4234edfccc8d.png)

**Comment by gingervik** [comment]
added
