### ISSUE TITLE
Incorrect  display of the status of canceled transactions .

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1582]
**Bug description**
The sender sent transactions when the recipient's wallet was offline. Sent the transactions were canceled. After a while, the recipient's transactions status changed to " pending ".

 **Current behaviour:**
The transactions with the "pending"  status.

**Expected behaviour:**
The transactions with the "canceled" status.

**Screenshots (if applicable)**

![image](https://user-images.githubusercontent.com/45556620/92728634-c0d50600-f379-11ea-8f38-f45e30c52bca.png)

**Platform and build:**

- Windows
- OS version: 10 pro
- BEAM Build number: 5.0.9547.3161.

**The base of the wallet and the logs file**
[Recipient.zip](https://github.com/BeamMW/beam/files/5201580/Recipient.zip)
[Sender.zip](https://github.com/BeamMW/beam/files/5201582/Sender.zip)

**Comment by anatolse** [comment]
fixed in https://github.com/BeamMW/beam/commit/e16c77fc60721b73eeab8ed6f576300789cfb61e

**Comment by Denis-Asipenko** [comment]
checked
