### ISSUE TITLE
Add shielded transaction to csv file

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1584]
1. Add shielded transaction to CSV file
2. Fee isn't correctly specified in CSV for sent shielded coins
![Screenshot_182](https://user-images.githubusercontent.com/50007056/92928549-ed575380-f447-11ea-978b-6913d27a3d3d.png)

**Comment by VladislavKulyba** [comment]
**Description**: Every time when I try to make an export, the wallet shows an error message: "Failed to start wallet. Please check your wallet data location". The exported file wasn't created.

**Wallet database**: [wallet.zip](https://github.com/BeamMW/beam/files/5369873/wallet.zip), pass=1

**Logs**: [logs_export.zip](https://github.com/BeamMW/beam/files/5369855/logs_export.zip)

**Build version**: 5.2.9691.3245

**Screenshot**:  ![Snag_852c28c](https://user-images.githubusercontent.com/51320829/95832705-567dff80-0d43-11eb-9e36-c09711ac4eef.png)

**Video**: [2020-10-13_10-59-16.zip](https://github.com/BeamMW/beam/files/5369817/2020-10-13_10-59-16.zip)

**Comment by VladislavKulyba** [comment]
checked
