### ISSUE TITLE
Could not find org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72.

### ISSUE THREAD

**Issue by darnel868** [BeamMW/beam#1589]
Could not find org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72.
Searched in the following locations:
    https://maven.google.com/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.72/kotlin-stdlib-jdk8-1.3.72.pom
    https://maven.google.com/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.72/kotlin-stdlib-jdk8-1.3.72.jar
    https://dl.bintray.com/kotlin/kotlin-eap/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.72/kotlin-stdlib-jdk8-1.3.72.pom
    https://dl.bintray.com/kotlin/kotlin-eap/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.72/kotlin-stdlib-jdk8-1.3.72.jar
    https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.72/kotlin-stdlib-jdk8-1.3.72.pom
    https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.72/kotlin-stdlib-jdk8-1.3.72.jar
Required by:
    project :app > com.android.tools.build:gradle:4.0.1
    project :app > com.android.tools.build:gradle:4.0.1 > com.android.tools.build:builder:4.0.1
    project :app > com.android.tools.build:gradle:4.0.1 > com.android.tools.build:aaptcompiler:4.0.1
    project :app > com.android.tools.build:gradle:4.0.1 > com.android.tools.lint:lint-gradle-api:27.0.1
    project :app > com.android.tools.build:gradle:4.0.1 > com.android.tools.build:gradle-api:4.0.1
    project :app > com.android.tools.build:gradle:4.0.1 > androidx.databinding:databinding-compiler-common:4.0.1
    project :app > com.android.tools.build:gradle:4.0.1 > com.android.tools.build:builder:4.0.1 > com.android.tools:sdk-common:27.0.1
    project :app > com.android.tools.build:gradle:4.0.1 > com.android.tools.build:builder:4.0.1 > com.android.tools:common:27.0.1
    project :app > com.android.tools.build:gradle:4.0.1 > com.android.tools.build:builder:4.0.1 > com.android.tools.build:manifest-merger:27.0.1
    project :app > com.android.tools.build:gradle:4.0.1 > com.android.tools.build:builder:4.0.1 > com.android.tools.analytics-library:tracker:27.0.1
    project :app > com.android.tools.build:gradle:4.0.1 > com.android.tools.build:builder:4.0.1 > com.android.tools:sdklib:27.0.1 > com.android.tools:repository:27.0.1
    project :app > com.android.tools.build:gradle:4.0.1 > com.android.tools.build:builder:4.0.1 > com.android.tools:sdk-common:27.0.1 > com.android.tools.analytics-library:shared:27.0.1

**Comment by DenisDemyanko** [comment]
Use our gradle setting.

ext.ver_kotlin = '1.3.30'
implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$ver_kotlin"

**Comment by halima154** [comment]
I get error like below


Gradle sync failed: Could not find org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72.
					Searched in the following locations:
					- https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.72/kotlin-stdlib-jdk8-1.3.72.pom
					If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
					Required by:
					project : > com.android.tools.build:gradle:4.0.2
					project : > com.android.tools.build:gradle:4.0.2 > com.android.tools.build:builder:4.0.2
					project : > com.android.tools.build:gradle:4.0.2 > com.android.tools.build:aaptcompiler:4.0.2
					project : > com.android.tools.build:gradle:4.0.2 > com.android.tools.lint:lint-gradle-api:27.0.2
					project : > com.android.tools.build:gradle:4.0.2 > com.android.tools.build:gradle-api:4.0.2
					project : > com.android.tools.build:gradle:4.0.2 > androidx.databinding:databinding-compiler-



Please mention how can you solve in your case.
