### ISSUE TITLE
Support an upgrade-friendly beam-wallet.cfg location

### ISSUE THREAD

**Issue by DavidBurkett** [BeamMW/beam#1590]
Currently, Beam Wallet looks for `beam-wallet.cfg` in the installed location, typically `C:\Program Files\Beam Wallet` on windows[1]. Anytime a new version of Beam Wallet is installed, it overwrites the contents of the Beam Wallet folder, requiring users to recreate their beam-wallet.cfg.

It would be better to use a more permanent location for the config file. It makes sense to just use the `%localappdata%\Beam Wallet` directory, which is not replaced with each upgrade.

[1] https://documentation.beam.mw/en/latest/rtd_pages/user_files_and_locations.html?highlight=beam-wallet.cfg#windows

**Comment by gingervik** [comment]
will be fixed in next release

**Comment by gingervik** [comment]
fixed. now cfg is not overwritten on update/upgrade
