### ISSUE TITLE
Beam Wallet requires administrator privileges on windows for no obvious reason

### ISSUE THREAD

**Issue by DavidBurkett** [BeamMW/beam#1591]
When opening `Beam Wallet.exe`, I am prompted by UAC to allow privilege escalation. It seems unnecessary and dangerous for a crypto wallet to require administrator access. I'm assuming it's requiring that privilege because Beam Wallet.exe probably modifies files in `C:\Program Files`, but that behavior should be reserved for an installer. Simply running the already-installed app should only ever make modifications to the standard "user data" folders, like `%appdata%`, `%userprofile%`, or `%localappdata%`.

![image](https://user-images.githubusercontent.com/24623306/93515110-14090480-f8f6-11ea-9ba8-ac78a7258f5b.png)

**Comment by anatolse** [comment]
It's very strange. Beam Wallet does not require privileges elevation. It seems that the problem is in the shortcut link, which is made by the installer. I will check it. Thank you, David!

**Comment by Webonnix** [comment]
[Uploading Beam-Wallet-5.1.9898.3222-fix.zip…]()

**Comment by Webonnix** [comment]
[Beam-Wallet-5.1.9898.3222-fix.zip](https://github.com/BeamMW/beam/files/5343552/Beam-Wallet-5.1.9898.3222-fix.zip)

**Comment by gingervik** [comment]
there is no user's response for 2 months
