### ISSUE TITLE
Public offline address support in the wallet

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#1592]

**Comment by Roberrtt** [comment]
When sending to  public address, the "address" field is empty in info --tx_history"
![Screenshot_252](https://user-images.githubusercontent.com/50007056/94801556-e1c7ce80-03ee-11eb-83e0-22fa06002026.png)
![Screenshot_251](https://user-images.githubusercontent.com/50007056/94801560-e2606500-03ee-11eb-86fc-66c4201d12a1.png)

**Comment by Roberrtt** [comment]
Remove the ability to send transactions to own public address
![Screenshot_261](https://user-images.githubusercontent.com/50007056/95084804-0f7e8180-0727-11eb-8ec1-968a5f011c14.png)

**Comment by anatolse** [comment]
@BigRomanov decided to allow to send to make shielded transactions to own addresses

**Comment by Denis-Asipenko** [comment]
1. Please do not show kernel for transactions to the public offline address
2. Need to display the appropriate status. (received public offline)
![image](https://user-images.githubusercontent.com/45556620/97883424-e78a3a00-1d35-11eb-8a5b-af0a0f3ffce0.png)

**Comment by Denis-Asipenko** [comment]
Transaction details aren't displayed for transactions sent to a public offline address
![image](https://user-images.githubusercontent.com/45556620/98832769-447ca300-244e-11eb-9567-ba2dd9a83d30.png)

**Comment by Denis-Asipenko** [comment]
checked
