### ISSUE TITLE
The 'waiting for receiver' status doesn't change to expired after 720 blocks

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam#1595]
**Description**
During the regression issue with status 'waiting for receiver' was identified. After 720 blocks the status doesn't change and transaction stuck in this status.

**Pre-conditions**:
There are Wallet A and Wallet B with enough funds for regular transaction.

**Steps to reproduce**

1. Copy an expired address from wallet B
2. Send transaction from wallet A using this address.
3. Wait 720 blocks
4. Check status in the wallet A 

**Expected**: The status is 'expired'
**Actual**: The status is 'waiting for receiver'

**Attachments**:

![Snag_1ef935fd](https://user-images.githubusercontent.com/51320829/94040015-1923f300-fdd1-11ea-811d-16217989b0ee.png)

logs:
[logs.zip](https://github.com/BeamMW/beam-ui/files/5269427/logs.zip)
wallet database:
[wallet.zip](https://github.com/BeamMW/beam-ui/files/5269437/wallet.zip)

**Environment**

OS Name: Ubuntu 20.04.1 LTS
OS Type: 64-bit
Gnome version: 3.36.3

Wallet version: 5.1.9889.3215 (Mainnet)

**Comment by Roberrtt** [comment]
checked
