### ISSUE TITLE
Offline transactions from CLI to UI wallet are sending as online ones 

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/beam#1596]
**Bug description:**
Offline transactions from CLI to UI wallet are sending as online ones 

**Precondition:**
There are two wallets: CLI wallet (sender), UI wallet (receiver)

**Steps to reproduce the behavior:**

1. From UI wallet copy an offline address. Close the wallet
2. In CLI wallet send transaction to copied offline address 

**Current behavior:**
Transaction is sending to UI wallet as online when we reopen UI wallet

**Expected behavior:**
Transaction is sending to UI wallet as offline one

**Platform and build:**
Windows
OS version: 10 pro
BEAM Build number: UI - 5.1.9896.3222 (mainnet), CLI - 5.1.9896 (mainnet)
![10](https://user-images.githubusercontent.com/68267190/94438143-61635c80-01a7-11eb-9002-69a09ba7c605.jpg)

**Comment by Roberrtt** [comment]
When you send it again to offline address , an error is displayed "sqlite error code=19, UNIQUE constraint failed: vouchers.Voucher" Please remove the output these are errors.
![Screenshot_240](https://user-images.githubusercontent.com/50007056/94526024-928e6c00-023d-11eb-83ec-01f9332ada52.png)

**Comment by Roberrtt** [comment]
checked
