### ISSUE TITLE
Swaps fall for BCH

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1608]
Swaps fall for BCH

Precondition
There're 2 wallets A and B , node BCH  is configured

Step:

(A) Create offer
(B) Accept this offer
in A wallets swap failed with error  "
Bridge internal error: type = 3; message = Method not found Failed. Side chain bridge has internal error"
![Screenshot_279](https://user-images.githubusercontent.com/50007056/95980550-fca23600-0e25-11eb-9bea-9feb54dd2df7.png)

Version Bitcoin ABC:0.17.1

**Comment by roman-strilets** [comment]
fixed at #1607

**Comment by roman-strilets** [comment]
use bitcoin abc version 21 and higher

**Comment by Roberrtt** [comment]
When use bitcoin abc version 0.21.10 and higher swap fails, hangs in the 'waiting for counterparty' status,

**Comment by roman-strilets** [comment]
fixed at d4fbb4dae434357ae85da1a9dc83723e57b5e604

**Comment by Roberrtt** [comment]
Checked
