### ISSUE TITLE
With small amounts, the swap  stuck in the in progress(Dogecoin)

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1609]
If  small amount is specified for the Dogecoin coin , the swap is stuck in the process on the BEAM side

Precondition:
There're 2 wallets A and B, nodes are configured for Dogecoin coin in 2 wallets

Step:
- A create offer (send 1.09 Dogecoin,receive 0.01 Beam)
- B accept this offer
- Wait for 6/6 confirmations
- A swap completed
- B swap stuck in progress 

tx_id 5f90fd065bcc40b9a68a93f62a34ef27

[wallet B logs.zip](https://github.com/BeamMW/beam/files/5402865/wallet.B.logs.zip)
[wallet A logs.zip](https://github.com/BeamMW/beam/files/5402871/wallet.A.logs.zip)

**Comment by roman-strilets** [comment]
dust:
- btc - 546
- bch - 546
- bsv - 546
- ltc - 5460
- doge - 100 000 000
- qtum - 72800
- dash - 546

**Comment by Roberrtt** [comment]
checked
