### ISSUE TITLE
Change min fee for DASH

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1610]
If the fee is specified below 2500 the swap is stuck on the Beam side

Precondition:
There're 2 wallets A and B, nodes are configured for DASH coin in 2 wallets

Step:

- A create offer (send 0.0025  DASH, receive 1 Beam) and fee for DASH 2500 duff/kb
- B accept this offer
- Wait for 6/6 confirmations
- A swap completed
- B swap stuck in progress

tx_id 
- 4895bd6a6ada4db891edc02d346e68fe (2100)
- 99503c2df692484c88672a6ce44bea66 (2000)
[B logs.zip](https://github.com/BeamMW/beam/files/5408444/B.logs.zip)
[A logs.zip](https://github.com/BeamMW/beam/files/5408452/A.logs.zip)

Password: 1
[DB wallet B.zip](https://github.com/BeamMW/beam/files/5408449/DB.wallet.B.zip)
[DB wallet A.zip](https://github.com/BeamMW/beam/files/5408451/DB.wallet.A.zip)

**Comment by roman-strilets** [comment]
Min fee rate:
- BTC - 1000
- LTC - 10000
- BCH - 1000
- BSV - 1000
- QTUM - 400000
- DOGE - 100 000 000

**Comment by roman-strilets** [comment]
please discuss with me

**Comment by Roberrtt** [comment]
checked
