### ISSUE TITLE
There's no warning about fee when create\accept swap in cli  when spending shielded coins

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1611]
If the wallet only has shielded coins, then when accepting\creating  swap , there's no warning about charging 1000100 fee for 1 shielded coin.
Note: 
- Swap takes the correct amount of fee for the shielded coin.
- If we open db via UI fee will be specified in details in 100 fee

Precondition:
In wallet only has shielded coins and any node is configured 

Step:
- create offer where we beam_side 

Actual:  there's a warning "This transaction will spend shielded coins. The minimum fee is 1000100 GROTH."
Expected: no warning

db opened via UI, fee should be 5000100 GROTH
![Screenshot_294](https://user-images.githubusercontent.com/50007056/96700650-595a9f00-1398-11eb-9fcd-f3c83ff33a35.png)

Build: 5.2.9711
Password: 1 
[db and logs.zip](https://github.com/BeamMW/beam/files/5414909/db.and.logs.zip)

**Comment by echoby** [comment]
https://github.com/BeamMW/beam-ui/commit/8663ec1397810a2ce2afe3b6140c047e8c5fde50
ui part

**Comment by Roberrtt** [comment]
checked
