### ISSUE TITLE
Min fee B4rTo: neu

### ISSUE THREAD

**Issue by db4rTo** [BeamMW/beam#1612]
Min fee rate:
- BTC - 1000
- LTC - 10000
- BCH - 1000
- BSV - 1000
- QTUM - 400000
- DOGE - 100 000 000

_Originally posted by @roman-strilets in https://github.com/BeamMW/beam/issues/1610#issuecomment-714796170_

**Comment by db4rTo** [comment]
@db4rTo

**Comment by gingervik** [comment]
fixed
