### ISSUE TITLE
Swap to electrum address stuck in progress (BCH)

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1613]
When we make swap with an electrum node, the swap  stuck in progress 

- If wallet A uses node version 0.21 and wallet B uses the electrum address
this error is displayed in the Electrum logs
![Screenshot_310](https://user-images.githubusercontent.com/50007056/97402096-071efe00-1903-11eb-98f0-8fa62789b31c.png)
- If wallet A uses node version 0.19 and wallet B uses the electrum address
this error is displayed in the Electrum logs
![Screenshot_311](https://user-images.githubusercontent.com/50007056/97402147-1c942800-1903-11eb-9665-821026c503d3.png)

Build: 5.2.9721.3292

**Comment by roman-strilets** [comment]
please, discuss with me

**Comment by Roberrtt** [comment]
checked
