### ISSUE TITLE
Add  warning when using a fee higher than the limit

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1614]
We need to display an error if user tries to use fee higher than the limit
BTC = = 10.000.000
DASH = 10.000.000 
DOGECOIN = 1.000.000.000
same for other coins

If we make a transaction with higher than this value, the swap will get stuck in progress with error
- Bridge internal error: type = 3; message = the transaction was rejected by network rules.

**Comment by roman-strilets** [comment]
0.01 BTC/kb = 1'000'000 Sat/kb
0.01 LTC/kb = 1'000'000 Ph/kb
0.01 DASH/kb = 1'000'000 Duff/kb
25 Doge/kb = 25 * 100'000'000 Sat/kb
1 QTUM/kb = 1'000'000 Qsat/kb

**Comment by Roberrtt** [comment]
When sending bitcoin, there's  no text about the max fee
![Screenshot_67](https://user-images.githubusercontent.com/50007056/102458695-adf75f00-4055-11eb-9d3d-a71497973f91.png)

**Comment by roman-strilets** [comment]
I forgot to update wallet core. It's done

**Comment by roman-strilets** [comment]
fixed

**Comment by Roberrtt** [comment]
checked
