### ISSUE TITLE
Add max privacy as in UI wallet

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#1615]

**Comment by chapati** [comment]
Need to clarify

**Comment by Roberrtt** [comment]
Add address type or rename  "tx_type_string" in API and Type in cli 
 TYPE____________________ | -----------CLI-----------| ------------API--------------**| ---------UI--------- |**
 Regular transaction_____ | ----simple---------------| -----simple---------------- **| -----regular-------- |**
 Offline transaction _____ | -----lelantus mw push --| ----lelantus mw push---- **| -----offline---------|**
 Max privacy transaction |------lelantus mw push --| ----lelantus mw push----- **| -----max privacy---|**

Add DAAP name and rename conctract_id to shader_id
 TYPE____________________ | -----------CLI-----------| ------------API--------------**| ---------UI--------- |**
 Contract________________ | -------conctract-------- | ----------contract-----------**| -----DAAP name--|**

**Comment by anatolse** [comment]
I think we need to preserve 'tx_type_string' as is and add a new field 'tx_address_type'
`contract_id` is a correct term here, I believe

**Comment by sasha-abramovich** [comment]
"Max privacy" was renamed to "Max anonymity set", just FYI
