### ISSUE TITLE
Contacts: when we resend transaction to the max privacy address - it fails

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/beam#1617]
Contacts: when we resend transaction to the max privacy address - it fails
![01](https://user-images.githubusercontent.com/68267190/97432401-f2576000-192c-11eb-8d88-48d0a42be8ff.jpg)
![02](https://user-images.githubusercontent.com/68267190/97432554-3480a180-192d-11eb-8114-4f0c317f8644.jpg)

**Comment by Maxnflaxl** [comment]
The max privacy address is intended for one time usage.
