### ISSUE TITLE
Remove the limit for sending shielded coins

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1618]
When there are only shielded coins in the wallet and there are more than 20 utxo, then when sending an amount containing more than 20utxo, the transaction will fail 

Precondition:
In wallet has more than 20 shielded utxo

Step:
- go to send screen
- click on "add all" button 
- pay attention amount indicated (amount is less than it is in the wallet)
- specify amount higher than amount specified after clicking "add all" button and send it to another wallet

Actual: trasaction is failed

![Screenshot_314](https://user-images.githubusercontent.com/50007056/97489308-75e67080-1970-11eb-9af6-7de0c7065883.png)
![Screenshot_315](https://user-images.githubusercontent.com/50007056/97489314-77b03400-1970-11eb-96dd-f582fe404acd.png)

**Comment by anatolse** [comment]
We cannot simply remove the limit, it is the mean of controlling the size of the block. I suppose we should re-think  "add all" feature

**Comment by anatolse** [comment]
Need to check why selectCoins doesn't return an error in this case

**Comment by Roberrtt** [comment]
1.The 'Send' button is active if you specify a higher than the limit.
![Screenshot_351](https://user-images.githubusercontent.com/50007056/98737107-cde09680-23b6-11eb-96a8-da0c62859f54.png)
2. if you change the fee when sending to the maxprivacy address, the error will calculate 1000100 more
![bandicam-2020-11-11-00-42-07-562](https://user-images.githubusercontent.com/50007056/98738185-61ff2d80-23b8-11eb-888a-329189f1e845.gif)

**Comment by Roberrtt** [comment]
The 'Send' button is active if change the fee to less than specified
![Screenshot_356](https://user-images.githubusercontent.com/50007056/98943536-b7deed00-2500-11eb-86db-4de431f85c56.png)

**Comment by Roberrtt** [comment]
checked
