### ISSUE TITLE
Fee calculation & Assets in CLI

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam#1619]
Need to check what's going on with fees calculation for shielded/max privacy txs that include assets. At the moment fee is calculated incorrectly (asset input & output is ignored) and max privacy transaction would not work correctly. cli.cpp/int Send(const po::variables_map& vm)

Check 
1) CalcShieldedCoinSelectionInfo
2) kErrorNotEnoughtCoins ifs. May be introduce flag enough/not enough.
3) For send transaction in the UI shielded coins are always selected for all send operations, in CLI only when max privacy flag is present. Need to make behavior the same in UI & CLI. I'm not sure but it seems that CLI behavior is incorrect.

**Comment by Denis-Asipenko** [comment]
1. Assets don't send on max_privacy address with the flag --max_privacy or not. The wallet closes and doesn't show any warning messages.
![image](https://user-images.githubusercontent.com/45556620/98806239-edfd6d80-2429-11eb-9318-6ef6f110bc7f.png)
2. Also we need the display the correct status for assets transactions.
For example: when user sends assets to offline addresses then transaction history should be showing the status "sent offline" but at the moment showing "sent max privacy".
![image](https://user-images.githubusercontent.com/45556620/98814481-c9f45900-2436-11eb-954c-dadc9369b925.png)

**Comment by Denis-Asipenko** [comment]
Point 3 will be fixed in  https://github.com/BeamMW/beam/issues/1644
checked
