### ISSUE TITLE
Build a miner documentation

### ISSUE THREAD

**Issue by illera88** [BeamMW/beam#162]
AFAIK there is no documentation about building a standalone miner (without the node part) but there is an option to download the prebuilt binary of the miner.

Can you please add instructions to only build the miner?

Thank you

**Comment by gingervik** [comment]
Hi @illera88 
Our devs will add documentation in next several days
Thank you

**Comment by roman-strilets** [comment]
please check it https://github.com/BeamMW/opencl-miner (topic "How to build")
