### ISSUE TITLE
Problem with connection to own node on different platforms

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#1622]
Event::Type enum is serialized differently on different platforms(compilers): on clang &gcc it is unsigned int, on MSVC - signed.
But, released mobile wallets understand signed values only, so if they get the unsigned value they throw an exception and close connection.
Before fork, we cannot force users to update their nodes, so, the wallet library should be able to handle both cases.
Also, make Event::Type explicitly unsigned

**Comment by Denis-Asipenko** [comment]
When IOS connected to a remote node(OS Linux cloud VM) then the indicator shows that the wallet is connected to the node and then after a few seconds wallet doesn't have a connection.
![E3794659-2094-4052-9065-C0D166D9E1CF](https://user-images.githubusercontent.com/45556620/98102231-73ba6f80-1ea4-11eb-928c-028d6c64ad34.GIF)

**Comment by anatolse** [comment]
please, check connection to 5.1 and 5.2 node versions

**Comment by Denis-Asipenko** [comment]
checked
