### ISSUE TITLE
Add ability to validate new address format in API

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#1628]
For now users cannot validate with API new addresses (not SBBS. "token" format)

**Comment by anatolse** [comment]
there are no changes in API

{
			jsonrpc: '2.0',
			id: 123,
			method: 'validate_address',
			params: 
			{
			    "address": "VnodAMahC2nTGmLYDqLpuPzzp568GGGGRuVPnN4TZg8AebKnPu5MgMMTCin2xJrgNPyuMm7GT9uZRj37tFt6wxBRW5n85kGH8J6swEtcX2K47j5EYMgTSohgPpV6fZPyH7MT8mQQXLRFECcqdD5uA79pPXzCEBFmhbGiCkG3bjxSzGJfnpEXw7V"
			}
		}

**Comment by Sergei-Beam** [comment]
checked
