### ISSUE TITLE
Wallet closes when trying sending assets on max privacy address

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1633]
Assets don't send on max_privacy address with the flag --max_privacy or not. The wallet closes and doesn't show any warning messages.
![image](https://user-images.githubusercontent.com/45556620/98819899-81d93480-243e-11eb-9d1e-d5d67570d056.png)

**Comment by anatolse** [comment]
please, re-check these transactions in UI also

**Comment by Denis-Asipenko** [comment]
Error for transactions  max privacy with beams and assets
![image](https://user-images.githubusercontent.com/45556620/98961897-1d3dd880-2517-11eb-92cc-bf9b72758877.png)
![image](https://user-images.githubusercontent.com/45556620/98961938-26c74080-2517-11eb-995e-f86057950136.png)

**Comment by Denis-Asipenko** [comment]
checked
