### ISSUE TITLE
Received assets to an public offline address are displayed as received beams

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1636]
**Bug description**
Sent assets to the receiver public offline address in the transaction history are displayed as received beams.
![image](https://user-images.githubusercontent.com/45556620/98916191-e7c7c980-24db-11eb-8a91-ba36952db749.png)

**Comment by echoby** [comment]
not actual

**Comment by Denis-Asipenko** [comment]
At the moment, this task has become irrelevant
