### ISSUE TITLE
Display the fee that is taken for create\deposit\withdraw\destroy

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1641]
We need to display the Commission that is taken or so that users can specify the required fee for create\deposit\withdra\destroy

**Comment by anatolse** [comment]
We print "Total fee: " is it enough? @Roberrtt

**Comment by anatolse** [comment]
@Roberrtt, we print "Total fee:". its it enoght?

**Comment by Roberrtt** [comment]
Yes that's enough
