### ISSUE TITLE
Show which arguments can be used for --shader_args

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1643]
We need to show which arguments can be used for --shader_args

At the moment there are:

--shader_args="role=manager ,action= create | destroy | view "
--shader_args="role=my_account, action=deposit | withdraw | view"
--shader_args="role=all_accounts, action=view"

**Comment by beam-mw** [comment]
If you launch the contract without --shader_args it prints the json of all possible parameters

**Comment by beam-mw** [comment]
Done
