### ISSUE TITLE
When sending shielded assets the fee is charged with regular coins

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1644]
**Bug description**
For sending transactions in the UI shielded coins are always selected for all send operations, in CLI selected regular coins. Need to make behavior the same in UI & CLI. In CLI wallet behavior is incorrect.
**Screenshots (if applicable)**
 - Sending transaction on max privacy address:
![image](https://user-images.githubusercontent.com/45556620/99415549-f7467880-2908-11eb-85da-803d0d652921.png)
![image](https://user-images.githubusercontent.com/45556620/99415608-088f8500-2909-11eb-8c9a-af116b368bde.png)
![image](https://user-images.githubusercontent.com/45556620/99415627-0deccf80-2909-11eb-9d96-d1bd870ab8f1.png)
![image](https://user-images.githubusercontent.com/45556620/99415723-2a890780-2909-11eb-962a-30c5e3ed25a0.png)
- Sending transaction on public offline address:
![image](https://user-images.githubusercontent.com/45556620/99416437-e21e1980-2909-11eb-90ba-b8b8df1c8bb4.png)
![image](https://user-images.githubusercontent.com/45556620/99416041-7a67ce80-2909-11eb-8691-b36c57b950eb.png)
![image](https://user-images.githubusercontent.com/45556620/99416234-b1d67b00-2909-11eb-990d-5631ee80c97b.png)

**Comment by echoby** [comment]
Not actual, now all fees charged in BEAMs

**Comment by Denis-Asipenko** [comment]
The selection coins for the transaction fee doesn't work correctly in the case of sending assets in the CLI wallet. When sending a transaction, shielded coins should be selected first for the fee. 
> Not actual, now all fees charged in BEAMs

**Comment by Denis-Asipenko** [comment]
invalid
