### ISSUE TITLE
Show the contract Cid if it was created

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1647]
If the user creates contract, show the contract Cid when the transaction is completed.
Also, if you destroy the contract, show that this Cid is destroyed

**Comment by AndreyDyakonov** [comment]
When we create a new contract, the Cid of the contract we created is displayed in the "Shader Output" - everything is OK, but when we destroy this contract, another contract Cid is displayed

example :
Create new contract:
**Shader output: {}
Creating new contract invocation tx on behalf of the shader
Contract ID: 1b159f621282601f338cc3a36e3117ed397014b38e5112bd0973e9f1e8da8419
Comment: create Faucet contract Total fee: 1100000 GROTH**

Destroy this contract:
Shader output: {}
**Creating new contract invocation tx on behalf of the shader
Contract ID: 3de22e9aaece32a559ad1e1027f518c36bf1ade6fedae08f4b30d951be560bbb
Comment: destroy Faucet contract        Total fee: 1100000 GROTH**

**Comment by Roberrtt** [comment]
There is no contract cid in linux
Version:  Beam Wallet 6.3.12510 (master)
![2022-03-15_12-14_1](https://user-images.githubusercontent.com/50007056/158345159-2a80f911-3072-48e9-a200-c369906b8f18.png)

**Comment by AndreyDyakonov** [comment]
Checked
