### ISSUE TITLE
When receive shielded assets, they aren't displayed in the asset summary.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1648]
![image](https://user-images.githubusercontent.com/45556620/99636004-e0606d00-2a53-11eb-8e4f-e21c10809ca2.png)
![image](https://user-images.githubusercontent.com/45556620/99636035-ec4c2f00-2a53-11eb-8ab5-df3c26935b16.png)

**Comment by echoby** [comment]
No actual.
Note: you can receive shielded coin only with own node

**Comment by Denis-Asipenko** [comment]
At the moment, this task has become irrelevant
