### ISSUE TITLE
Allow user to restore wallet using seed phrase if he forgot password

### ISSUE THREAD

**Issue by bdevelle** [BeamMW/beam#165]
At the moment, if user forgets his password, there is no visible way for him to recover access (even if he has the mnemonic phrase).

I suggest (if this isn't planned already) to add recover / restore wallet option on the main screen

@breakphreak

**Comment by sasha-abramovich** [comment]
Good thought. We have it on our roadmap of course. "Forgot password" button should lead to the restore flow.

**Comment by jurijakimuk** [comment]
Related: #598

**Comment by gingervik** [comment]
@nesbox please, remove "Forgot password" snd rename "open another wallet" to "restore wallet"

**Comment by Sergei-Beam** [comment]
checked
