### ISSUE TITLE
Failed to register transaction with the blockchain, see node logs for details

### ISSUE THREAD

**Issue by Alteryy** [BeamMW/beam#1652]
**Bug description**
$result = $this->request( 'tx_send',
			array(
				'value'=>$amount*$this->unit,
				//'fee'=>10,
				//'from'=>$amount,
				'address'=>$address,
				//'comment'=>''
			)
		);
transfer always failed

**Platform and build**
Linux iZt4ng4wnaglyc7phawmf6Z 4.4.0-117-generic #141-Ubuntu SMP Tue Mar 13 11:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Eager-Electron-5.1.9898/

**Log file(s) (if applicable)**
node_20_11_21_18_55_43.log
I 2020-11-21.19:10:43.179 Peer 13.228.238.102:10000 Tip: 986616-dc06836c6d21b282
I 2020-11-21.19:10:43.218 Peer 139.99.62.126:8100 Auth. Type=N, ID=e65d57c692bf7495
I 2020-11-21.19:10:43.218 139.99.62.126:8100 received PI
W 2020-11-21.19:10:43.218 Peer 139.99.62.126:8100 uses older ext: 5
I 2020-11-21.19:10:43.218 Peer 139.99.62.126:8100 Tip: 986616-dc06836c6d21b282
I 2020-11-21.19:10:43.249 Peer 18.162.206.232:8100 Connected
I 2020-11-21.19:10:43.287 Peer 18.162.206.232:8100 Auth. Type=N, ID=1abda28a1e2d1249
I 2020-11-21.19:10:43.287 18.162.206.232:8100 received PI
W 2020-11-21.19:10:43.287 Peer 18.162.206.232:8100 uses older ext: 5
I 2020-11-21.19:10:43.287 Peer 18.162.206.232:8100 Tip: 986616-dc06836c6d21b282
I 2020-11-21.19:10:44.174 +Peer 206.189.151.227:31000
I 2020-11-21.19:10:44.174 +Peer 209.58.173.154:19340
I 2020-11-21.19:10:44.174 +Peer 18.136.108.158:8100
I 2020-11-21.19:10:44.177 Peer 18.136.108.158:8100 Connected
I 2020-11-21.19:10:44.177 Peer 206.189.151.227:31000 Connected
I 2020-11-21.19:10:44.178 Peer 18.136.108.158:8100 Auth. Type=N, ID=d3823f4099855a47
I 2020-11-21.19:10:44.178 18.136.108.158:8100 received PI
W 2020-11-21.19:10:44.178 Peer 18.136.108.158:8100 uses older ext: 5
I 2020-11-21.19:10:44.178 Peer 18.136.108.158:8100 Tip: 986616-dc06836c6d21b282
I 2020-11-21.19:10:44.179 Peer 206.189.151.227:31000 Auth. Type=N, ID=35d3e0f045c845fb
I 2020-11-21.19:10:44.179 206.189.151.227:31000 received PI
W 2020-11-21.19:10:44.179 Peer 206.189.151.227:31000 uses older ext: 5
I 2020-11-21.19:10:44.179 Peer 206.189.151.227:31000 Tip: 986616-dc06836c6d21b282
I 2020-11-21.19:10:44.179 Peer 209.58.173.154:19340 Connected
I 2020-11-21.19:10:44.180 Peer 209.58.173.154:19340 Auth. Type=N, ID=d594a1039e9fc5ec
I 2020-11-21.19:10:44.180 209.58.173.154:19340 received PI
I 2020-11-21.19:10:44.181 Peer 209.58.173.154:19340 Tip: 986616-dc06836c6d21b282
I 2020-11-21.19:12:11.594 Tx f4cfcfbee31a125e
        I: 5c0b5a25fbab4173
        I: 64146df28da46901
        O: 7e904abb35f67422
        O: c09f8e49530e2e8b
        K: 9d3f245af58f3eb8139b36eb3251958dfea5f150ac9f5d4d83d9dd4625e73e2d Fee=100
        Status: 1
W 2020-11-21.19:12:27.474 127.0.0.1:37134: end of file
I 2020-11-21.19:12:27.474 -Peer 127.0.0.1:37134
W 2020-11-21.19:12:31.634 127.0.0.1:33728: end of file
I 2020-11-21.19:12:31.634 -Peer 127.0.0.1:33728
I 2020-11-21.19:12:37.175 Node stopping...
I 2020-11-21.19:12:37.175 -Peer 47.93.48.197:10000
I 2020-11-21.19:12:37.175 -Peer 13.251.164.100:8100
I 2020-11-21.19:12:37.175 -Peer 18.163.0.104:8100
I 2020-11-21.19:12:37.175 -Peer 39.106.136.81:10000
I 2020-11-21.19:12:37.175 -Peer 52.74.179.212:10000
I 2020-11-21.19:12:37.175 -Peer 139.99.62.126:8200
I 2020-11-21.19:12:37.175 -Peer 18.162.105.23:8100
I 2020-11-21.19:12:37.175 -Peer 13.228.238.102:10000
I 2020-11-21.19:12:37.175 -Peer 139.99.62.126:8100
I 2020-11-21.19:12:37.175 -Peer 3.1.37.246:8100
I 2020-11-21.19:12:37.175 -Peer 18.162.206.232:8100
I 2020-11-21.19:12:37.175 -Peer 206.189.151.227:31000
I 2020-11-21.19:12:37.175 -Peer 209.58.173.154:19340
I 2020-11-21.19:12:37.175 -Peer 18.136.108.158:8100
I 2020-11-21.19:12:37.177 Node stopped

**Comment by gingervik** [comment]
@Alteryy please, add wallet logs

**Comment by Crypto2** [comment]
We're getting this same issue as well, with the same kind of logs as above:

Tx 10767eb53f6fb4a6
        I: ec9700452402047a
        O: 16112592554adf2a
        O: 3b829728d5646287
        O: 48f09477f6f7e148
        O: 9985ac62f87586e0
        O: cc513e3494dd9fd9
        K: d594c785f3c454ea4691ea6b90129393d68b70816336eafcc91af2602b4fab16 Fee=100
        Status: 1

**Comment by Crypto2** [comment]
We also tried to send to an offline address:

I 2021-01-22.03:07:30.339 got {"method":"tx_send","params":{"address":"xxx","value":3493790000},"id":1,"jsonrpc":"2.0"}
D 2021-01-22.03:07:30.396 Send(id = 1 asset_id = 0 amount = 3493790000 fee = 100 address = xxx)
I 2021-01-22.03:07:30.431 [b6d15bb263a44b1986354279536e6381] Sending to shielded pool 34 BEAMs 93790000 GROTH (fee: 100 GROTH)
D 2021-01-22.03:07:40.411 [b6d15bb263a44b1986354279536e6381][1] sending tx for registration
D 2021-01-22.03:07:40.447 [b6d15bb263a44b1986354279536e6381][1] register status 20
E 2021-01-22.03:07:40.449 [b6d15bb263a44b1986354279536e6381] Failed. Transaction is not valid, please send wallet logs to Beam support
I 2021-01-22.03:07:40.451 [b6d15bb263a44b1986354279536e6381] Transaction failed. Rollback...

**Comment by gingervik** [comment]
hello @Crypto2 @Alteryy 
do you still have any problems with sending txs? 
Sorry for long responce

**Comment by Crypto2** [comment]
No worries, I ended up fixing it by doing a full rescan of the wallet. I'm guess it just had some UTXOs not in the right state or something.
