### ISSUE TITLE
When swapping fail due to low fee the wallet make future swaps will fail too

### ISSUE THREAD

**Issue by RaFuN** [BeamMW/beam#1658]
**Bug title**
ongoing Swap fail due to low fee in the first swap
**Bug description**
initial swap (DASH -> BEAM) fee was too low, causing all future swap to fail too (altho the fee was above the highest recommended fee)

issue solved after restarting the wallet 

**To Reproduce**
Steps to reproduce the behaviour:
1. issue a DASH to BEAM swap 
2. stick to the default suggested fee (which is also always too low in DASH case)
3. TX will fail after a short time 
4. issue another Swap with the a higher fee (according to this: https://api.blockcypher.com/v1/dash/main) 
5. swap will fail too
6. restart the wallet and do a swap with the high fee according to the link above 

**Current behaviour**
swap fail instantly with this error: Side chain bridge has internal error
on logs: Bridge internal error: type = 3; message = not enough coins

**Expected behaviour**
Swap to be completed 

**Platform and build**
* Mac
* OS version - Catalina
* BEAM Build number - 5.2

**Configuration, log, memory dump files (if applicable)**
was sent to Starun 

**Log file(s) (if applicable)**
Add relevant log file(s),  located in the `logs` folder.
[beam v5.2.10113.3424 osx report.zip](https://github.com/BeamMW/beam/files/5672339/beam.v5.2.10113.3424.osx.report.zip)

**Screenshots (if applicable)**
Add screenshots that illustrate a problem you've found.

**Comment by roman-strilets** [comment]
changed min fee rate:
- bitcoin to 20'000 sat/kb
- litecoin to 20'000 phat/kb

**Comment by RaFuN** [comment]
the issue was in DASH too. I believe the min fee rate there should be adjusted too

**Comment by Roberrtt** [comment]
checked
