### ISSUE TITLE
Wallet shows "online" always upon initial wallet login

### ISSUE THREAD

**Issue by bdevelle** [BeamMW/beam#166]
really minor
On every login, the wallet shows "online" , despite the testnet being offline or having no peers configured. 
After a few seconds, online status updates to offline. 

Windows 1.0.3607

@breakphreak

**Comment by sasha-abramovich** [comment]
That's fine. Short delay is reasonable as we try to be optimistic and allow some re-connect time before alerting the user with flicker-ish status.

**Comment by bdevelle** [comment]
@sasha-abramovich that's exactly the problem described in this ticket; the current way it works its alerting the user with flicker-ish status changes

Currently it works like this:
online > offline > online

instead it should be 
connecting > online / offline

**Comment by sasha-abramovich** [comment]
@bdevelle it's on our roadmap: https://github.com/BeamMW/beam/issues/34. "help wanted", btw :)))
