### ISSUE TITLE
API - add creation of new type online addresses

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#1661]
add a function which allows user to creat new type of online addresses (not sbbs)

**Comment by anatolse** [comment]
updated wallet API documentation
https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API#create_address

**Comment by Roberrtt** [comment]
The wallet API doesn't see lelantus coins and transactions

**Comment by Roberrtt** [comment]
API wallet doesn't see shielded coins
Also in the request tx_list not displayed lelantus transactions
build: 5.2.9821 (eager_electron_5.2RC_API)
![Screenshot_105](https://user-images.githubusercontent.com/50007056/103273249-e55bf900-49cf-11eb-82a2-8bc51ec46264.png)

**Comment by Roberrtt** [comment]
checked
