### ISSUE TITLE
Add support for Ethereum, DAI, USDT and WBTC

### ISSUE THREAD

**Issue by Aleksandr-Starun** [BeamMW/beam#1662]

**Comment by roman-strilets** [comment]
ethereum_address - ethereum node address (ganache or infura)
ethereum_seed - seed phrase
account_index - account index. it's unsigned integer. ethereum address is generated from it 
should_connect - connect to node (true or false)
eth_contract_address - swap contract address (aggregation)
erc20_contract_address - erc20 swap contract address
dai_contract_address - DAI contract address
wbtc_contract_address - WBTC contract address 
usdt_contract_address - USDT contract address
eth_swap_amount - ethereum swap amount in ethereum
eth_gas_price - gas price in gwei

Examples:
set ethereum settings:
beam-wallet-masternet.exe set_swap_settings --swap_coin=eth --ethereum_address=127.0.0.1:7545 --ethereum_seed="urge shift robust wife chaos depend wide sentence excite write repair panel" --account_index=0 --should_connect=true --eth_contract_address="0x0CA46349E8ceB41e0Da21C201Db5b7AdAe061b57"

set DAI settings (ethereum settings should be set):
beam-wallet-masternet.exe set_swap_settings --swap_coin=dai --dai_contract_address="0x677bD37419562141EB853632A1922503d66ff515" --erc20_contract_address="0x19d3eA2c2F746E482e9BBbFcdE31403f8475E2f0" --should_connect=true

init Ethereum swap:
beam-wallet-masternet.exe swap_init --swap_coin=eth -n 127.0.0.1:11001 -a 1 --eth_swap_amount 1 --eth_gas_price=20

init DAI swap:
beam-wallet-masternet.exe swap_init --swap_coin=dai -n 127.0.0.1:11001 -a 1 --eth_swap_amount 1 --eth_gas_price=20

accept swap:
beam-wallet-masternet.exe swap_accept -n 127.0.0.1:11002 --eth_gas_price=20 --fee=300 --swap_token=3C5QpXWByDknvFwdzSSgZsSZNuoDeHXqwyTyDHqvGWD4ijQUT9y31QtoVjD3EQrjbnN75HiVxR55YQAB21SeEAHwja8AwwYghB16o5cCWq8tPaEgqA7bB12VKYR5v3A6S46faiurcikj17gjPcFE9LjjnniCHYUVwoeAjUdRUeESgnQDbijurjHyg

**Comment by roman-strilets** [comment]
infura_project_id - infura project id
ethereum_seed - seed phrase
account_index - account index. it's unsigned integer. ethereum address is generated from it
should_connect - connect to node (true or false)
eth_swap_amount - ethereum swap amount in ethereum
eth_gas_price - gas price in gwei

Examples:
set ethereum settings:
beam-wallet-masternet.exe set_swap_settings --swap_coin=eth --infura_project_idd=34343sddsdsdsdsccscd --ethereum_seed="urge shift robust wife chaos depend wide sentence excite write repair panel" --account_index=0 --should_connect=true

init Ethereum swap:
beam-wallet-masternet.exe swap_init --swap_coin=eth -n 127.0.0.1:11001 -a 1 --eth_swap_amount 1 --eth_gas_price=20

init DAI swap:
beam-wallet-masternet.exe swap_init --swap_coin=dai -n 127.0.0.1:11001 -a 1 --eth_swap_amount 1 --eth_gas_price=20

accept swap:
beam-wallet-masternet.exe swap_accept -n 127.0.0.1:11002 --eth_gas_price=20 --fee=300 --swap_token=3C5QpXWByDknvFwdzSSgZsSZNuoDeHXqwyTyDHqvGWD4ijQUT9y31QtoVjD3EQrjbnN75HiVxR55YQAB21SeEAHwja8AwwYghB16o5cCWq8tPaEgqA7bB12VKYR5v3A6S46faiurcikj17gjPcFE9LjjnniCHYUVwoeAjUdRUeESgnQDbijurjHyg

**Comment by Roberrtt** [comment]
checked
