### ISSUE TITLE
Move calculation of rawMaturityTimeLeft() into WalletClient

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#1665]
These calculations should be the same for UI, Mobile, CLI, API. Please move them to the library and client.
Do it on the eager_electron_5.2RC branch first, then merge into eager_electron_5.3RC

Also, move     beam::TxoID getTotalShieldedCount() const;
    beam::TxoID getShieldedPer24h() const;
    uint8_t getMPLockTimeLimit() const;
    bool hasShielded() const;
to WalletClient

**Comment by Denis-Asipenko** [comment]
checked
