### ISSUE TITLE
Seed phrase from UI is not valid in CLI, for ethereum

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1669]
If we take a seed phrase generated in the ui and try to connect it in the cli the wallet returns an error that the phrase is not valid
![Screenshot_76](https://user-images.githubusercontent.com/50007056/102757811-ec0cbf80-4382-11eb-9b40-bfba77f11041.png)

**Comment by Aleksandr-Starun** [comment]
Incorrect seed phrase format, please use: --ethereum_seed="weather hen detail region misery click wealth butter immense hire pencil social"

**Comment by Roberrtt** [comment]
checked
