### ISSUE TITLE
Compiled Beam Wallet does not connect to testnet 3

### ISSUE THREAD

**Issue by joshbpa** [BeamMW/beam#167]
I have compiled the Beam Wallet client and beam-node in Ubuntu 18.04. I have entered testnet 3 IP addresses for peers. It does not connect to the testnet 3 chain. It starts to mine a new chain where the client or node mines every block starting with number one. 

How do I get the compiled client to connect to the testnet 3 chain?

**Comment by joshbpa** [comment]
I used the correct hash to compile source code for version 1.0.3607. It is the correct version, and I'm using testnet 3 peers. It still says incompatible peer and does not connect to testnet 3 chain.

**Comment by joshbpa** [comment]
I 2018-12-11.21:52:33.629 Rules signature: 26c67db2de4b6739
I 2018-12-11.21:52:33.629 starting a node on 10000 port...
I 2018-12-11.21:52:33.682 Node ID=6f33f075c50ff9fd
I 2018-12-11.21:52:33.682 Initial Tip: 0-0000000000000000
I 2018-12-11.21:52:33.682 Sync mode
I 2018-12-11.21:52:33.682 Searching for the best peer...
I 2018-12-11.21:52:33.682 PI 0000000000000000--0.0.0.0 New
I 2018-12-11.21:52:33.682 PI 0000000000000000--0.0.0.0 Address changed to 3.121.
25.231:8100
I 2018-12-11.21:52:34.629 +Peer 3.121.25.231:8100
I 2018-12-11.21:52:34.842 Peer 3.121.25.231:8100 Connected
I 2018-12-11.21:52:34.949 Peer 3.121.25.231:8100 Auth. Type=N, ID=3f59dc4f8b24ef
a6
I 2018-12-11.21:52:34.949 3.121.25.231:8100 received PI
I 2018-12-11.21:52:34.949 deleted anonymous PI
I 2018-12-11.21:52:34.949 PI 3f59dc4f8b24efa6--0.0.0.0 New
I 2018-12-11.21:52:34.949 PI 3f59dc4f8b24efa6--0.0.0.0 Address changed to 3.121.
25.231:8100
I 2018-12-11.21:52:34.949 PI 3f59dc4f8b24efa6--3.121.25.231:8100 connected, info
 updated
W 2018-12-11.21:52:34.949 3.121.25.231:8100: Incompatible peer cfg!
I 2018-12-11.21:52:34.950 -Peer 3.121.25.231:8100
I 2018-12-11.21:52:34.950 PI 3f59dc4f8b24efa6--3.121.25.231:8100 Rating 1024 -> 
0
E 2018-12-11.21:52:34.950 on_new_message int(type)=0 ret=0
I 2018-12-11.22:02:35.314 PI 3f59dc4f8b24efa6--3.121.25.231:8100 Rating 0 -> 1
I 2018-12-11.22:02:35.314 +Peer 3.121.25.231:8100
I 2018-12-11.22:02:35.538 Peer 3.121.25.231:8100 Connected
I 2018-12-11.22:02:35.646 Peer 3.121.25.231:8100 Auth. Type=N, ID=3f59dc4f8b24ef
a6
I 2018-12-11.22:02:35.646 3.121.25.231:8100 received PI
W 2018-12-11.22:02:35.646 3.121.25.231:8100: Incompatible peer cfg!
I 2018-12-11.22:02:35.646 -Peer 3.121.25.231:8100
I 2018-12-11.22:02:35.646 PI 3f59dc4f8b24efa6--3.121.25.231:8100 Rating 1 -> 0
E 2018-12-11.22:02:35.646 on_new_message int(type)=0 ret=0
I 2018-12-11.22:12:35.837 PI 3f59dc4f8b24efa6--3.121.25.231:8100 Rating 0 -> 1
I 2018-12-11.22:12:35.837 +Peer 3.121.25.231:8100
I 2018-12-11.22:12:36.047 Peer 3.121.25.231:8100 Connected
I 2018-12-11.22:12:36.155 Peer 3.121.25.231:8100 Auth. Type=N, ID=3f59dc4f8b24ef
a6
I 2018-12-11.22:12:36.155 3.121.25.231:8100 received PI
W 2018-12-11.22:12:36.155 3.121.25.231:8100: Incompatible peer cfg!
I 2018-12-11.22:12:36.155 -Peer 3.121.25.231:8100
I 2018-12-11.22:12:36.155 PI 3f59dc4f8b24efa6--3.121.25.231:8100 Rating 1 -> 0
E 2018-12-11.22:12:36.155 on_new_message int(type)=0 ret=0
I 2018-12-11.22:22:36.833 PI 3f59dc4f8b24efa6--3.121.25.231:8100 Rating 0 -> 1
I 2018-12-11.22:22:36.833 +Peer 3.121.25.231:8100
I 2018-12-11.22:22:37.038 Peer 3.121.25.231:8100 Connected
I 2018-12-11.22:22:37.136 Peer 3.121.25.231:8100 Auth. Type=N, ID=3f59dc4f8b24ef
a6
I 2018-12-11.22:22:37.136 3.121.25.231:8100 received PI
W 2018-12-11.22:22:37.136 3.121.25.231:8100: Incompatible peer cfg!
I 2018-12-11.22:22:37.136 -Peer 3.121.25.231:8100
I 2018-12-11.22:22:37.136 PI 3f59dc4f8b24efa6--3.121.25.231:8100 Rating 1 -> 0
E 2018-12-11.22:22:37.136 on_new_message int(type)=0 ret=0
I 2018-12-11.22:32:37.302 PI 3f59dc4f8b24efa6--3.121.25.231:8100 Rating 0 -> 1
I 2018-12-11.22:32:37.302 +Peer 3.121.25.231:8100
I 2018-12-11.22:32:37.509 Peer 3.121.25.231:8100 Connected
I 2018-12-11.22:32:37.606 Peer 3.121.25.231:8100 Auth. Type=N, ID=3f59dc4f8b24ef
a6
I 2018-12-11.22:32:37.607 3.121.25.231:8100 received PI
W 2018-12-11.22:32:37.607 3.121.25.231:8100: Incompatible peer cfg!
I 2018-12-11.22:32:37.607 -Peer 3.121.25.231:8100
I 2018-12-11.22:32:37.607 PI 3f59dc4f8b24efa6--3.121.25.231:8100 Rating 1 -> 0
E 2018-12-11.22:32:37.607 on_new_message int(type)=0 ret=0
I 2018-12-11.22:36:58.000 Node stopping...
I 2018-12-11.22:36:58.000 Node stopped

**Comment by gingervik** [comment]
Your Rules signature differs from our "6af2277005b4a43a"
This means that your build differs from ours.

**Comment by joshbpa** [comment]
The Beam node binary from the Beam.mw website core dumps with illegal instruction. I've tried to compile from source in Ubuntu 14.04, 16.04 and 18.04. 

I have followed the instructions on the website to build from source. To get the correct beam source (1.0.3607), I run

git clone https://github.com/BeamMW/beam.git
cd beam
git checkout 15da99d 

The code compiles and the software runs, but the Rules signature is different from your build. **How do I compile to get the same Rules signature?** Can you update the build instructions on Git Hub? I'm trying very much to get this to work.

**Comment by entinio** [comment]
I've compiled the sources as well on my ubuntu platform. I get "Rules signature: 26c67db2de4b6739" as well. There's no way to get your "6af2277005b4a43a" signature! I tried compiling from the github "15da99d" hash as provided by your team in issue #154 

```
const std::string GIT_COMMIT_HASH = "15da99d376db968e8bda701c78cf276173b85950";
const std::string PROJECT_VERSION = "1.0.3607";
```

```
root@RIG2:~/beam/beam# ./beam-node
I 2018-12-12.17:57:06.387 Rules signature: 26c67db2de4b6739
I 2018-12-12.17:57:06.395 starting a node on 10000 port...
I 2018-12-12.17:57:06.405 Node ID=19d0054f39e7bcab
```

So, again, what should we compile to have a testnet3 working node? No need to ask us to download binaries, this is a *compiling* question.

**Comment by joshbpa** [comment]
I was able to get a compiled beam node running on Ubuntu 18.04 on testnet3 by removing the if/endif statement in the CMakeLists.txt file and leaving only the line add_definitions(-DBEAM_TESTNET). Now the node is on the testnet3 chain with the correct blockchain height. The how-to-build directions should be updated to say that you must do a git clone and then a git checkout testnet3. Also I think the make file should be updated because the if statement is not working correctly even with the testnet3 branch checked out.

**Comment by entinio** [comment]
Same. Working fine now after removing the IF statement at the line 111 of the CMakeLists.txt line.

**Comment by gingervik** [comment]
enabled testnet by default
