### ISSUE TITLE
Revise the number of confirmations for transactions

### ISSUE THREAD

**Issue by Aleksandr-Starun** [BeamMW/beam#1671]

**Comment by Aleksandr-Starun** [comment]
Minimum number of confirmations for the Lock transaction is set to:
  BTC - 1 confirmation
  LTC - 6 confirmations
  QTUM - 10 confirmations
  DOGE - 6 confirmations
  DASH - 6 confirmations
  ETH & ERC20 - 12 confirmations
Minimum number of confirmations for the withdraw transaction - 1 confirmation.

**Comment by Sergei-Beam** [comment]
checked
