### ISSUE TITLE
Max privacy coins when received aren't in a state of maturing

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1677]
For some reason, they are recorded in shielded, and before they were in maturingMP.maturingMP - maturing max privacy empty 
![image](https://user-images.githubusercontent.com/45556620/103219871-e2a9c700-492f-11eb-8acb-f3d9681ebb45.png)

**Comment by Denis-Asipenko** [comment]
it was fixed with the transition to a new version of the database

**Comment by Denis-Asipenko** [comment]
reproduces on the testnet

**Comment by anatolse** [comment]
I suppose, nodes on testnet we doesn't have ShieldedOutputsAt message

**Comment by Denis-Asipenko** [comment]
after updating the nodes, the issue was fixed
