### ISSUE TITLE
When creating a mobile wallet disable the protocol mobile node

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1682]
When a user creates a completely new wallet, the mobile node protocol must be disabled. The wallet must be created quickly.

**Comment by anatolse** [comment]
Body requests (according to mobile node protocol are disabled by default). And on a fresh wallet, everything should be ok. But if a wallet has previously set enableBodyRequests(true), on new account it should set enableBodyRequests(false),

**Comment by Denis-Asipenko** [comment]
checked
