### ISSUE TITLE
Increase minimum gas price

### ISSUE THREAD

**Issue by roman-strilets** [BeamMW/beam#1686]
Change to 15 gwei.

**Comment by Roberrtt** [comment]
checked

**Comment by roman-strilets** [comment]
testnet: min gas price = 1gwei
mainnet: min gas price = 15 gwei

**Comment by Sergei-Beam** [comment]
- Checked 
testnet: min gas price = 1gwei
- Will be checked when mainnet build will be ready
mainnet: min gas price = 15 gwei

**Comment by Sergei-Beam** [comment]
Checked
mainnet: min gas price = 15 gwei
