### ISSUE TITLE
Explorer-API Node the ability  to search and return new coins DAI,USDT,ETH,WBTC

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#1687]
To have the ability to show new coins on explorers we need to add to explorer node the ability  to search and return new coins DAI, USDT, ETH, WBTC via API

**Comment by Aleksandr-Starun** [comment]
Please check that it is enough for backend.

**Comment by Denis-Asipenko** [comment]
If you set the sorting of coins to BTC then the WBTC is also displayed along with them
![image](https://user-images.githubusercontent.com/45556620/105727297-ff8be700-5f3b-11eb-89fb-661a5bfeda5e.png)

**Comment by Denis-Asipenko** [comment]
checked
