### ISSUE TITLE
The wallet doesn't recognize the received vouchers

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1688]
When sending from desktop wallet (5.3) offline transactions to the mobile wallet (5.2) the mobile wallet doesn't recognize received additional vouchers.
Also, when the mobile wallet uses the mobile node then when sending from the mobile wallet (5.2) offline transactions to the desktop wallet (5.3)  the desktop wallet doesn't receive additional vouchers. But if disable the mobile node in the mobile wallet then the desktop wallet receives additional vouchers.
![image](https://user-images.githubusercontent.com/45556620/104717006-bd8fc380-5739-11eb-9e06-5bee888fd491.png)

**Comment by Denis-Asipenko** [comment]
The mobile wallet still cannot recognize the additional vouchers received.
Also when I send one by one offline transaction they fail:
I 2021-01-15.18:29:19.380 ShieldedInput window N=64, Wnd0=17819, iIdx=63, TxoID=17882, PoolSize=17883
I 2021-01-15.18:29:19.380 [8d1fd1a3271b4048be7a5dff5da57fe1] Get shielded list, start_index = 17819, count = 73
E 2021-01-15.18:29:19.530 [8d1fd1a3271b4048be7a5dff5da57fe1] Failed. Unexpected reason, please send wallet logs to Beam support
I 2021-01-15.18:29:19.535 [8d1fd1a3271b4048be7a5dff5da57fe1] Transaction failed. Rollback...


It is worth noting that the desktop wallet now receive additional vouchers requested from the mobile wallet when the mobile node is turned on but now the desktop wallet does not receive vouchers if you do not use the mobile node in the mobile wallet

**Comment by DenisDemyanko** [comment]
Fixed on client side.

**Comment by Denis-Asipenko** [comment]
сhecked
