### ISSUE TITLE
Transaction stucks in in_progress state and doesn't appear in the recipient's wallet

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#169]
After closing the sender's wallet while sent transaction have  Pending OR in_progress status. -The transaction stucks and doesn't appear in the recipient's wallet

Steps to reproduce behaviour:
1 create 2 wallets and generate the addresses
2. go to send screen on wallet_1
3. quickly send multiple transactions from wallet_1 to wallet_2
4. close the wallet_1 while the last outgoing transaction has  "pending/in_progress" status
5. run the wallet_1
Expected: after run wallet-1 again the transaction appears on wallet_2 and continue progress
Actual: The last transaction on wallet_1 stucks in in_progress state and on wallet_2 it doesn't appear at all.
Checked on Windows
![photo_2018-12-11_18-43-00](https://user-images.githubusercontent.com/45556620/49811668-6655e280-fd6c-11e8-9685-4e021bbede7a.jpg)

**Comment by Sergei-Beam** [comment]
Cannot reproduce
