### ISSUE TITLE
Explorer - Incorrect display of send(btc)/receive(beam) offers

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1690]
In the explorer, offers are displayed only as send(beam)/receive(btc) 

![Screenshot_205](https://user-images.githubusercontent.com/50007056/105158095-a75d7b00-5b1e-11eb-8593-33b5f04c1168.png)
![Screenshot_204](https://user-images.githubusercontent.com/50007056/105158099-a88ea800-5b1e-11eb-9b55-57b6725cec73.png)

**Comment by Denis-Asipenko** [comment]
checked
