### ISSUE TITLE
macOS build instructions: add cpack example

### ISSUE THREAD

**Issue by jonathancross** [BeamMW/beam#1704]
Please add `cpack` command example to https://github.com/BeamMW/beam/wiki/How-to-build#mac

**Comment by echoby** [comment]
Simply call _cpack_ command from Beam project folder, without any params.
Instructions updated
https://github.com/BeamMW/beam/wiki/How-to-build#mac

**Comment by jonathancross** [comment]
Uh, yeah, I tried that.
```
> cpack
CPack Error: CPack generator not specified
```

**Comment by anatolse** [comment]
Please, check you cmake installation.
Also, ensure that you call cpack from correct folder
Notice, that all build steps described in github actions script
and can use it to understand what is going wrong in you case
https://github.com/BeamMW/beam-ui/blob/master/.github/workflows/build.yml
