### ISSUE TITLE
Windows 7 latest wallet Beam-Wallet-5.3.10396.3625 doesn't work

### ISSUE THREAD

**Issue by supernova2033** [BeamMW/beam#1706]
**Bug title**
The procedure entry point CreateDXGIFFactory2 could not be located in the dynamic link library dxgi.dl

**Bug description**
Error **The procedure entry point CreateDXGIFFactory2 could not be located in the dynamic link library dxgi.dll** appears. Wallet doesn't start

**Platform and build**
* Windows
* Windows 7
* BEAM Build number 5.3.10396.3625
* Nvidia drivers 461.40

**Screenshots (if applicable)**
Add screenshots that illustrate a problem you've found.
![beam_er](https://user-images.githubusercontent.com/16432110/108792493-73003300-7592-11eb-900d-92a5a7d3fb76.jpg)

**Comment by gingervik** [comment]
Hi! we are working on this problem. The fix will be released soon

**Comment by gingervik** [comment]
please, try to download the last version https://builds.beam.mw/mainnet/2021.02.25/Release/win/signed/Beam-Wallet-5.3.10410.3657.exe

**Comment by supernova2033** [comment]
works now. you can close issue
