### ISSUE TITLE
Implement thread pool

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#1709]
1. Web wallet have to define the exact number of web workers to emulate pthreads
2. Our code doesn't have a thread pool, we use raw std::thread and use std::thread::hardware_concurrency() to determine the number of cores.
3. Thread pool will allow us to control how many running threads(workers) we have

**Comment by anatolse** [comment]
With newer WASM there should no warnings about "therad pool exhausted.." in browser console

**Comment by Denis-Asipenko** [comment]
сhecked
