### ISSUE TITLE
Windows Wallet stops mining periodically

### ISSUE THREAD

**Issue by mscheetz** [BeamMW/beam#171]
**Bug title**
Windows Wallet stops mining periodically

**Bug description**
Running Windows Wallet on Windows 10. I have the miner open and it mines. I go to work and then come home about 10 hours later and the miner has stopped mining. Last block found was at 11863 and matured at 11923, current block height is 12253.

This happened yesterday and today.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Windows wallet
2. Select 'Run local node' & 'Use GPU' on setting page
3. Let miner run for some number of hours

**Current behaviour**
I got home from work today and the miner had stopped.

**Expected behaviour**
I was expecting the miner to still be mining.

**Platform and build**
* Windows 10 
* Home edition
* 1.0.3607

**Configuration, log, memory dump files (if applicable)**
Add relevant files. The filenames and locations are described here: https://github.com/BeamMW/beam/wiki/Folder-and-file-locations

**Log file(s) (if applicable)**
Add relevant log file(s),  located in the `logs` folder.

**Screenshots (if applicable)**
Add screenshots that illustrate a problem you've found.

**Comment by gingervik** [comment]
Hi @mscheetz 
Your miner cannot mine ALL blocks. If someone run more effective miner than he'll mine most of blocks.

**Comment by mscheetz** [comment]
What about this example: https://imgur.com/0avPxgz

My wallet stopped mining for almost 1000 blocks.
