### ISSUE TITLE
CLI wallet - incorrect display of the fee when sending shielded coins

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1710]
**Bug description**
When sending shielded coins, the wallet displays an incorrect fee. maybe the changes https://github.com/BeamMW/beam/issues/1555 were broken.

**Screenshots (if applicable)**
Example 1
The wallet has 2 shielded beams and 97999900 GROT.
![image](https://user-images.githubusercontent.com/45556620/109635873-ed652000-7b5b-11eb-9447-6b8fddac65e1.png)

Example 2
The wallet has 2 shielded beams and 1 beam.
![image](https://user-images.githubusercontent.com/45556620/109635886-f1913d80-7b5b-11eb-9233-02c9ce8c3e19.png)

**Platform and build:**

- macOS
- OS version: Big Sur 11.1
- BEAM Build number: 6.0.10769.

**Comment by anatolse** [comment]
I've discussed this issue with @valdok , and I believe, that this behavior is correct.
 Before HF3 we have an implicit fee for each shielded input, after HF3 we have no fee in this case.
 But we tried to make users pass this implicit fee into the app (CLI, UI) to smooth the difference in the tx amounts.
 With the upcoming HF3 we decided to remove all this ugly logic from the code.

**Comment by Denis-Asipenko** [comment]
after discussion, it was decided to close the issue because it became irrelevant
