### ISSUE TITLE
CLI wallet - incorrect fee error when sending a transaction

### ISSUE THREAD

**Issue by kazaryan-t** [BeamMW/beam#1711]
When sending a transaction in CLI wallet, it displays an error with incorrect fee required.

1. For regular transactions, it should be 100K groth

![1](https://user-images.githubusercontent.com/68247034/109807218-a566fb80-7c36-11eb-93da-e9baa0103958.png)

2. For offline/max privacy transactions, it should be 1Mln groth (0.01 Beams)

![2](https://user-images.githubusercontent.com/68247034/109807860-7d2bcc80-7c37-11eb-81e0-f964abb2f35f.png)

**Comment by anatolse** [comment]
It seems that you tried to send after HF3 on masternet. The minimal fee after HF3 is 100000

**Comment by KatsiarynaV** [comment]
Incorrect fee error when sending transaction to an **offline/max privacy** address. It should be: "The minimum fee is **1100000** Groth"
![27](https://user-images.githubusercontent.com/68267190/111112780-d0741800-8571-11eb-9d70-2dd0e30d091f.jpg)
![26](https://user-images.githubusercontent.com/68267190/111112784-d23ddb80-8571-11eb-916c-8f488c94e641.jpg)

**Comment by kazaryan-t** [comment]
Checked.
