### ISSUE TITLE
CLI and API wallet doesn't send coins 

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1720]
The wallet doesn't send coins, there's no information in the cli wallet, the api gives an error
build:  6.0.10857
![Screenshot_456](https://user-images.githubusercontent.com/50007056/111784188-27f4e980-88cc-11eb-8f8b-c865dc8919a2.png)
![Screenshot_455](https://user-images.githubusercontent.com/50007056/111784192-288d8000-88cc-11eb-9fa5-0f5b52268d6e.png)

**Comment by Sergei-Beam** [comment]
checked
