### ISSUE TITLE
AVX instruction set requirement in the mainnet

### ISSUE THREAD

**Issue by wirtz1284** [BeamMW/beam#173]
If the AVX instruction set will remain to be a requirement in the mainnet, some of us will have to purchase new processor. Such investment can be prevented if the requirement of AVX instruction set is removed in the mainnet. Since many of us want to start mining from the beginning of the mainnet, we need this information as soon as possible.

**Will you remove the requirement of AVX instruction set in the mainnet miner?**

I am unable to get this information from Discord and I do not want to spam there any more.

**Comment by gingervik** [comment]
Hi @wirtz1284 
For now there is a requirement only for SSE3 as I remember

What OS do you often use?
Did you try to run beamWallet on it?
What is you processor?

**Comment by wirtz1284** [comment]
Hello @gingervik,
The release notes for Testnet 3 say:
> [fix] Miner: Improved error handing with CPUs that lack AVX instruction set on Linux.
I use Ubuntu 18.04 and beamWallet from the binary release produces Illegal Instruction error as soon as I run it. After I compiled it myself, it runs fine only until I start GPU mining.
My processor is Intel® Celeron® Processor G1850. It supports SSE3, but it does not support AVX.

**Will the requirement for SSE3 be dropped in the mainnet release?**
