### ISSUE TITLE
Add the ability to switch wallets on GUI and Mobile versions.

### ISSUE THREAD

**Issue by argonatorUberTF** [BeamMW/beam#1730]
Add the ability to switch wallets on GUI and Mobile versions.
Add an icon to the start screen to select wallets already created for Windows 10 and Mac OS.
Phone if possible.

The user would have to backup the wallet.db file, and overwrite the current one with wallet #2,3,4etc into the user's data directory manually with a file manger.  Although it is user error prone since the wallets are named the same filename, wallet.db.
If a user is not careful, they might mistake one wallet for another and arbitrarily move/delete/archive the wrong wallet.db.
The user might not be able to track by last date/time accessed or creation date/time on the wallet.db file.

It would be nice if the create wallet feature would allow the user to name the wallet with a short, friendly name using characters only allowed to make legit folders, and put it into a sub directory labelled with that name. 
That way the gui wallet can just scan for subdirectories for the wallet selected. Maybe encode the friendly name into the wallet.db file and do the switching automatically.
This is a feature similar to Electron Wallets for other coins in the crypto world.

Advise and warn the user that you cannot address the same wallet concurrently with multiple programs running the same wallet. 
(for example phone and desktop)

**Comment by sasha-abramovich** [comment]
Multiple wallets within the same wallet are a nice-to-have feature, but currently, we have much higher priorities for more essential DeFi-related tasks.
