### ISSUE TITLE
Invalid password when user upgrade wallet from v 1.1.4202 to v.5.3.10410.3657

### ISSUE THREAD

**Issue by simonf-dev** [BeamMW/beam#1731]
Title:
Invalid password when user update wallet from v 1.1.4202 to v.5.3.10410.3657

Bug description:
User has working wallet on the version 1.1.4202 and tries to upgrade 5.3.10410.3657. After upgrade password isnt working anymore. I know this is really big version difference, but it should still work. It looks like a regression of:
https://github.com/BeamMW/beam/issues/788

Platform and build:
Tried on Ubuntu and Windows too

**Comment by ya-shy** [comment]
Hello! 

Thank you very much for bringing this up. We are aware of this issue and have created a workaround with few updates in the middle in order to avoid this, however, it is on our to-do list to issue a fix. 

Best regards.

**Comment by simonf-dev** [comment]
Hello, does exist a way how to update 1.1.4202 to 5.3.10410.3657 properly right now?

**Comment by ya-shy** [comment]
Hello, sure
Please try these steps:
 
 1. Copy all the wallet folders(wallet.db file) to a separate location
 2. - Windows __/Users{your User name}/AppData/LocalBeam Wallet
 3. - Mac __/Users/{your User name}/Library/Application Support/Beam Wallet
 4. - Linux __/home/{your User name}/.local/share/Beam Wallet/
 5. Delete only the folder with the latest version 5.3
 6. Install this version (https://github.com/BeamMW/beam/releases/tag/beam-4.2.8635) of the wallet, run the wallet, make the migration, close it
 7. Install the next version (https://github.com/BeamMW/beam/releases/tag/beam-5.0.9146)  of the wallet, run the wallet, make migration
 8. Install the latest version of the wallet from this link https://beam.mw/downloads/ and run the wallet
