### ISSUE TITLE
Get the block header from wallet cli and wallet api

### ISSUE THREAD

**Issue by roman-strilets** [BeamMW/beam#1734]
Implement new command for cli and wallet api to get block header information

**Comment by roman-strilets** [comment]
cli:
beam-wallet-masternet.exe -n <address to node> block_details --block_height=100

wallet api request:
{
	jsonrpc: '2.0',
	id: 123,
	method: 'block_details',
	params: {
		"height": 104
	}
}

**Comment by Sergei-Beam** [comment]
Need to add understandable messages if the user tries to request  non-existent height
![image](https://user-images.githubusercontent.com/44496108/114833937-c0ea2800-9dd8-11eb-80c2-8b62795672de.png)

![image](https://user-images.githubusercontent.com/44496108/114833903-b9c31a00-9dd8-11eb-81fe-931bdcebfddb.png)

**Comment by Sergei-Beam** [comment]
checked
