### ISSUE TITLE
Atomic swap REST API not listed in wallet REST API wiki

### ISSUE THREAD

**Issue by Virepri** [BeamMW/beam#1740]
[Wiki: Beam wallet protocol API](https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API) lacks all methods under [wallet_api_defs.h:33](https://github.com/BeamMW/beam/blob/381ce32a2cc0b0185a553d37856acdcaea6110cf/wallet/api/v6_0/wallet_api_defs.h#L33)

**Comment by anatolse** [comment]
please, check this https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-SWAP-API-(BETA)

**Comment by Virepri** [comment]
Oh! I stand corrected.
