### ISSUE TITLE
Processing new addresses(tokens)

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1743]
**API**

-  if use command addr_list displays new addresses (tokens ), not just SBBS
-  add the ability to delete an address using a new address (token)

**CLI**

-  if use command address_list displays new addresses (tokens ), not just SBBS

**Comment by chapati** [comment]
Test also that edit, delete & send in API accept all address types generated via create_address

**Comment by Denis-Asipenko** [comment]
checked
