### ISSUE TITLE
The wallet returns an error when sending to SBBS address

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1744]
This error is only reproduced when trying to send to this address
error = sqlite error code=19, UNIQUE constraint failed: addresses.Address
address = 7205bb0f1b383f90722594212dcae7e98be518e7eb160d33906627824317ed9d56
![Screenshot_14](https://user-images.githubusercontent.com/50007056/115578312-daeea380-a2cd-11eb-8f8f-ec3eb76b4fb5.png)
![Screenshot_13](https://user-images.githubusercontent.com/50007056/115578322-dcb86700-a2cd-11eb-85c1-0dd2c9a6d760.png)

Wallets
pass = 1
Wallet where was address created [wallet.zip](https://github.com/BeamMW/beam/files/6352021/wallet.zip)
[wallet.zip](https://github.com/BeamMW/beam/files/6352035/wallet.zip)

**Comment by chapati** [comment]
Should be fixed, as a part of the same bug in UI

**Comment by Roberrtt** [comment]
checked
