### ISSUE TITLE
Cannot start wallet on Windows VM - missing OpenGl 

### ISSUE THREAD

**Issue by mountassir** [BeamMW/beam#1748]
Hi, 

I just installed the latest wallet version 5.3.10410.3657 and it is now showing the following error message 
`failed to create opengl context for format qsurfaceformat...`

This is running on a Windows VM with a basic display adapter. Any way to by-pass this limitation? Maybe a way to run the wallet with low graphics requirements?

Thanks.

**Comment by anatolse** [comment]
it seems that we removed opengl32sw.dll from installer
you can get it from https://wiki.qt.io/Cross_compiling_Mesa_for_Windows

**Comment by anatolse** [comment]
as quick fix: this file is from my local qt distro
[opengl32sw.zip](https://github.com/BeamMW/beam/files/6405218/opengl32sw.zip)
