### ISSUE TITLE
Fix Incorrect Windows/Mac Logos

### ISSUE THREAD

**Issue by Megawatt7** [BeamMW/beam#1749]
![image](https://user-images.githubusercontent.com/41215180/116596700-b8264580-a8f2-11eb-881a-bec2f623d041.png)

![image](https://user-images.githubusercontent.com/41215180/116596753-caa07f00-a8f2-11eb-89cf-7cea17e55406.png)

**https://beam.mw/downloads/testnet**

**Comment by gingervik** [comment]
good morning. already fixed
