### ISSUE TITLE
Blockchain explorer should be linked from the desktop wallet

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#175]
Blockchain explorer should be linked from our app (maybe from the "welcome" or "settings" screens).

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova please update the screens. Later on we'll embed the blockchain explorer directly into the wallet. Meanwhile let's just publish the link.

**Comment by alexandrashelenkova** [comment]
zpl.io/bWLg9Lx

**Comment by sasha-abramovich** [comment]
We can make the Transaction IDs clickable as well.

**Comment by alexandrashelenkova** [comment]
Done
