### ISSUE TITLE
Assets - minting huge amounts warning

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam#1754]
When after issuing asset in CLI total amount (get asset info from DB) would be or issuing amount is larger than 1 transaction can support (beam::Amount) need to print warning. 'Warning. Total amount of asset would be larger that can be sent in one transaction (xxxxx ASSET). You would be forced to send using several transactions."

**Comment by chapati** [comment]
Please move out warning code from  WalletAsset::LogInfo

1) This method is used to print info about asset, not any warnings and is called in many places. When sending asset, when refreshing info &c. This warning should be displayed only when minting new coins.
2) Use std::cout to display warning, not LOG_INFO

**Comment by Roberrtt** [comment]
1) When we select amounts from the warning(only Asset without groth) and send this amount to the wallet, we get the Error" Failed. Key keeper malfunctioned"
command: `beam-wallet-masternet.exe send --asset_id=7 -a 184467440737 -r 1ecf17215ad197f05ec5e8b7ed57e2a728f2153d5d5e13246ce06b33881a1eb8dfc -n 127.0.0.1:10005`
![Screenshot_693](https://user-images.githubusercontent.com/50007056/147091002-3d12d893-e33a-440c-a919-bd12633ba152.png)

2) And when we select amount with groth , we get error that amount is too big
command: `beam-wallet-masternet.exe send --asset_id=7 -a 184467440737.9551615 -r 1ecf17215ad197f05ec5e8b7ed57e2a728f2153d5d5e13246ce06b33881a1eb8dfc -n 127.0.0.1:10005`
![Screenshot_694](https://user-images.githubusercontent.com/50007056/147091179-cb7a53cd-8e7a-418c-877e-16c4b5972d45.png)

pass=1

[wallet.zip](https://github.com/BeamMW/beam/files/7762523/wallet.zip)

**Comment by Sergei-Beam** [comment]
checked
