### ISSUE TITLE
Restore wallet .recovery phrases are not deleted.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#178]
Recovery phrases are not deleted if you go back to screen entering phrases.
Steps to reproduce the behaviour:
1.go to wallet.
2.restore wallet.
3.enter recovery phrases.
4.go to the next screen (enter password).
5.go to back ( entering  phrases screen)
Expected: Recovery phrases deleted if you go back to screen entering phrases.
Actual: Recovery phrases are not deleted
Checked on Windows

**Comment by beam-mw** [comment]
Not a problem. Closing
