### ISSUE TITLE
Wasm crashed with error "memory access out of bounds"

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#1797]
**Steps:**
- install extension
- wait while wallet synced
- go to settings and click remove wallet
- create a new wallet and start sync
_Note:_ the next error appeared  ![image](https://user-images.githubusercontent.com/44496108/122789044-94aec400-d2bf-11eb-92b1-6c81209a9bdb.png)
- close extension and run again

**Actual:**  the next error appeared 
![image](https://user-images.githubusercontent.com/44496108/122786264-cd00d300-d2bc-11eb-9843-236ea95f9abe.png)

Looks like the final error related to incorrectly deleted database

**Comment by anatolse** [comment]
changes in web part https://github.com/BeamMW/web-wallet/commit/94e9964f3877a9e5f899c2050af156a74bbca39b

**Comment by AndreyDyakonov** [comment]
Web-wallet started and synced

Steps:

- click button "Lock Wallet" 
- in starting window click button "Restore wallet or create a new one"
- in next window type your seed phrase 
- then create password and click "start using your wallet"

Actually:
wallet doesn't restore 
in devtools  - error 
![bug-web-restore](https://user-images.githubusercontent.com/85252690/123808343-55a0f400-d8f9-11eb-9fb1-1d7505427d65.png)

Expected:
wallet restored
