### ISSUE TITLE
Make Regular address shorter

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#1798]
Regular addresses generated by Desktop UI are longer than 500 bytes, some exchanges have a limitation on address size and it's less or equal than 500 bytes.
Remove redundant or optional info from the address

**Comment by anatolse** [comment]
offline address should be somewhere about 466 chars. Please, verify that app detects addresses generated with newer versions of the wallet

**Comment by Sergei-Beam** [comment]
new wallet crashed when I tried to send transactions for an older version of the wallet either regular or max privacy
![image](https://user-images.githubusercontent.com/44496108/125842457-28f2394f-919c-4156-9ecc-64b083ac5acc.png)

**Comment by Sergei-Beam** [comment]
checked
