### ISSUE TITLE
Linux - Segmentation fault (core dumped) if channel wasn't saved in db

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1799]
If we run this command, then in the response we see "Segmentation fault (core dumped)" 
OS: Linux 
```
beam-wallet-masternet laser --pass password --wallet_path wallet.db --laser_delete 01000000000000000000000000000000  --node_addr=127.0.0.1:10000
result:
```

![Screenshot_404](https://user-images.githubusercontent.com/50007056/124781245-ead06800-df4b-11eb-964d-12710ba6145e.png)

**Comment by Sergei-Beam** [comment]
checked
