### ISSUE TITLE
Make the "Next" button selected by default after entering phrases to restore  wallet

### ISSUE THREAD

**Issue by sinaizd** [BeamMW/beam#180]
![screenshot_21](https://user-images.githubusercontent.com/45556620/49955207-ef0a8500-ff0a-11e8-9876-49106472ce1d.png)

**Comment by kaminskyelina** [comment]
Same with the Create new wallet screen after entering phrases 
<img width="967" alt="screen shot 2019-01-01 at 14 12 41" src="https://user-images.githubusercontent.com/45590119/50572735-7d1db100-0dcf-11e9-93f1-e7a890f9aaa4.png">

**Comment by kaminskyelina** [comment]
And Create Password screen also
