### ISSUE TITLE
Desktop atomic swaps. Option to show the exchange rate as USD.

### ISSUE THREAD

**Issue by xcelente** [BeamMW/beam#1802]
Title says it all really. I can relate to some exchanges rate pairs easily but if I could see all the rates as USD I could easily deduce which pairs had the best rates.

Thanks

**Comment by gingervik** [comment]
@sasha-abramovich please, take a look

**Comment by sasha-abramovich** [comment]
@gingervik we have a task on that - should be reopened: https://github.com/BeamMW/beam-ui/issues/391
this task I am closing as duplicate
