### ISSUE TITLE
cli: ugly transactions table with new addresses (non sbbs)

### ISSUE THREAD

**Issue by echoby** [BeamMW/beam#1803]
![photo_2021-07-26_13-00-10](https://user-images.githubusercontent.com/1681548/126970992-24e8ee9c-913e-4877-8910-de21d22f765e.jpg)

**Comment by Roberrtt** [comment]
1. Please make a table in 1 format:

 | datetime | height| direction | amount, assets | status  | ID | Kernel ID | Address

OR

datetime:
height:
direction :
amount, assets:
status:
ID:

2. The address fields are missing in transactions with the asset.

![Screenshot_497](https://user-images.githubusercontent.com/50007056/129850253-eb6491d1-5960-4167-bd3f-90ef91a36e4a.png)

**Comment by Roberrtt** [comment]
checked
