### ISSUE TITLE
cli: ugly assets info with long long assets names

### ISSUE THREAD

**Issue by echoby** [BeamMW/beam#1804]
![photo_2021-07-26_12-46-56](https://user-images.githubusercontent.com/1681548/126971711-f001f962-ddd3-4039-9a3b-31c5747af1bf.jpg)

**Comment by Roberrtt** [comment]
Table with utxo ( info --utxo_list)
![Screenshot_498](https://user-images.githubusercontent.com/50007056/129850842-53091e1f-29af-49fe-bc03-6a0a57fe1630.png)

**Comment by Roberrtt** [comment]
checked
