### ISSUE TITLE
Asset ticker max length should be 6 chars

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#1805]
https://github.com/BeamMW/beam/wiki/Asset-Descriptor-v1.0 SN parameter max length should be limited in CLI

**Comment by chapati** [comment]
Now if SN is > 6 "Bad (non-std) asset metadata" error should be printed on asset registration. All other operations (issue, consume, unreg &c) will allow more characters to support assets that were registered before.

**Comment by Roberrtt** [comment]
Please make these changes as well in the "asset creation helper"
https://master-net.explorer.beam.mw/assets/create

**Comment by chapati** [comment]
@iscander01

**Comment by Roberrtt** [comment]
checked
