### ISSUE TITLE
Broadcaster always gets all bbs messages for the last 12 hours

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#1806]
The timestamps of the received messages are not saved for broadcaster. This is already implemented in the wallet. We need to re-use existing functionality

**Comment by anatolse** [comment]
for QA: UI wallet should not be flooded by exchange rates messages on start time. Please, check for regressions in news channel, rates, swap offers

**Comment by anatolse** [comment]
Also there should no flooding if the wallet was offline for a long period of time

**Comment by Sergei-Beam** [comment]
checked
