### ISSUE TITLE
Running beam-node on Centos 7 requires glibc 2.18

### ISSUE THREAD

**Issue by GoodEn0ugh** [BeamMW/beam#181]
**Bug title**
It is currently not possible to run the beam-node binary on a clean CentOS 7 install, as the latest version of glibc available in CentOS 7 is 2.17.

**Bug description**
When attempting to run beam-node, I get the following:

./beam-node: /usr/lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./beam-node)

This is not fixable without some major changes in CentOS 7.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download the latest binaries from https://downloads.beam.mw/linux/beam-node-1.0.3607.tar.gz
2. Run beam-node with any options
3. See the above error.

**Current behaviour**
Unable to run beam-node on CentOS 7.

**Expected behaviour**
Able to run beam-node on CentOS 7.

**Platform and build**
* Linux
* CentOS 7.6 (3.10.0-957.1.3.el7.x86_64)
* 1.0.3607

**Comment by gingervik** [comment]
Hi @GoodEn0ugh 
Our devs will answer you soon (in several days I hope)

**Comment by beam-mw** [comment]
We are not supporting CentOs at the moment
