### ISSUE TITLE
Apple Silicon M1 - not working - stuck on Requesting block 0-0000000000000000

### ISSUE THREAD

**Issue by jTd7bPLFb** [BeamMW/beam#1824]
**Bug title**
Can not get the wallet working on Apple Silicon M1

**Bug description**
Wallet (GUI) starts, I go through all the steps (new wallet, or restore existing), and then it is just stuck.
In log file, I see
Requesting block 0-0000000000000000
and no further messages

**To Reproduce**
Steps to reproduce the behaviour:
1. Run MAC wallet on Apple Silicon M1 mac
2. New wallet or restore wallet

**Current behaviour**
Stuck on Requesting block 0-0000000000000000 in log file. Now syncing.

**Expected behaviour**
Should be working and syncing.

**Platform and build**
* Mac
* OS Latest
* BEAM MAC wallet binary from Github

**Comment by tgbv** [comment]
Try to add a default peeer in the configuration file:
```
peer=eu-nodes.mainnet.beam.mw:8100
```

"settings.ini" file should be located in beam folder in AppData/Local. I don't know the equivalent for Apple.

**Comment by jTd7bPLFb** [comment]
done that, no change.
Yes, Apple Silicon M1 is running MacOS, just not on x64 hardware but on aarch64. It's the new macbooks and mac mini which came beginning 2021.
So settings.ini same location as any x64 Mac.

**Comment by rojomisin** [comment]
might be a big sur, security issue, have to allow it as an unsigned app
![Screen Shot 2021-09-12 at 11 06 12 PM](https://user-images.githubusercontent.com/3313148/133032290-202c41d9-c8ba-4cb2-93f8-37b16ee83b98.png)
![Screen Shot 2021-09-12 at 11 06 00 PM](https://user-images.githubusercontent.com/3313148/133032292-b0f94dbf-69f5-4f9b-a8b0-0ddb1b17cf56.png)

**Comment by gingervik** [comment]
hello, @jTd7bPLFb do you still have this problem? 
COuld you please provide logs?

**Comment by ya-shy** [comment]
Hello, thank you for your reply. Could you please elaborate on your Mac model and version? In addition, please send us your full logs via the wallet Settings-Report a problem. Thank you!

**Comment by jonathancross** [comment]
Is this still an issue in 2023?

**Comment by jTd7bPLFb** [comment]
No idea. Gave up, moved to linux under qemu. 
so, feel free to close.
