### ISSUE TITLE
Hey uh your get coins isn’t working and it’s saying i already got it but my thing is still at 0. I am refreshing it and closing out of the app but it won’t work.

### ISSUE THREAD

**Issue by RonanTheHacker** [BeamMW/beam#1825]
**Bug title** 1fc54f612e8011589fc484b4ab62f969b89b84593d36aa9778f1ed37522b1aeb496 is my address 
Express the problem in a single concise sentence

**Bug description**

**To Reproduce**
Steps to reproduce the behaviour:
1. Run '....' (with '....' configuration file or command line parameters where applicable)
2. Do '....'
3. Do '....'

**Current behaviour**
A clear and concise description of the erroneous behaviour which currently happens.

**Expected behaviour**

**Platform and build**
* Windows, Mac, Linux, Android or iOS
* OS version
* BEAM Build number

**Configuration, log, memory dump files (if applicable)**
Add relevant files. The filenames and locations are described here: https://github.com/BeamMW/beam/wiki/Folder-and-file-locations

**Log file(s) (if applicable)**
Add relevant log file(s),  located in the `logs` folder.

**Screenshots (if applicable)**
Add screenshots that illustrate a problem you've found.

**Comment by ya-shy** [comment]
Hello! Thank you for getting in touch! 
Could you please elaborate on the issue you are facing and if possible, provide your logs (Settings - Report a problem) to our Support email support@beam.mw 
Thank you! 
Best regards, 
Beam Team
