### ISSUE TITLE
Add an error when sending  offline/max privaсy transactions about min fee in API

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1829]
When we send  to an offline/max privaсy address and if fee is specified in 100000, a transaction is created and it falls
Add an error if (offline: true) params  is specified and the commission is less than 100000 and if sending to the max privaсy address and the commission is specified 100000

Add this error:

`{
  "error": {
    "code": -32602,
    "data": "Failed to initiate the operation. The minimum fee is 1100000 GROTH.",
    "message": "Invalid parameters."
  },
  "id": 2,
  "jsonrpc": "2.0"
}`

**Comment by kovaletskaterina** [comment]
Checked
