### ISSUE TITLE
Allow to create wasm client without seed phrase

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#1836]
we need to have light wallet, without need to sync, but with ability to made requests to the node

**Comment by chapati** [comment]
Everything works with the latest changes.
I'm marking this done. The rest will happen in web apps.

**Comment by anatolse** [comment]
docs https://github.com/BeamMW/beam/wiki/WASM-wallet-client#headless-constructor

**Comment by KatsiarynaV** [comment]
Checked
