### ISSUE TITLE
The gallery generates big sized logs (Gigabytes)

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#1839]
the gallery generates big sized logs (Gigabytes) because a lot of debugging information comes from the gallery application.
Need to truncate them

**Comment by chapati** [comment]
Also there is no way to set log_level in api cli. Need to fix this

**Comment by chapati** [comment]
1) Now contract logs are not LOG_DEBUG (default) but LOG_VERBOSE. Check that when running cli/desktop/api with default options no excessive logs appear
2) --log_level option added to wallet api. Check that it works (--log_level verbose displays contract logs)
3) There were significant changes in wallet api startup. Check that wallet api is not broken and prints correct output on startup.

@anatolse please review my changes

**Comment by anatolse** [comment]
seems ok
