### ISSUE TITLE
Rebuild the "Unconfirmed" panel to "In progress"

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#184]
![image](https://user-images.githubusercontent.com/44496108/49993794-c03af000-ff98-11e8-814c-b8e50f15a2ea.png)
Rebuild the "Unconfirmed" panel to "In progress" according to the screen bottom
![image](https://user-images.githubusercontent.com/44496108/49993725-810c9f00-ff98-11e8-9f77-7768f020a5b8.png)
Note: on new version, unconfirmed coins should be split into special groups receiving OR sending
https://zpl.io/bWLWYDM

**Comment by gingervik** [comment]
checked
![image](https://user-images.githubusercontent.com/28015224/50544961-18b7f180-0c17-11e9-8312-9db51c381858.png)
