### ISSUE TITLE
Delete the ability to set 24h expiration time for SBBS address

### ISSUE THREAD

**Issue by kovaletskaterina** [BeamMW/beam#1840]
Need to delete the ability to set 24 hours expiration time for the SBBS address via command "**beam-wallet-masternet new_addr --expiration_time=24h**"
![photo_2021-11-15_12-12-10](https://user-images.githubusercontent.com/83376495/141768781-f5a85be6-fa2a-4e4f-9856-a2fbc9c52947.jpg)

**Comment by beam-mw** [comment]
Wont fix. It's ok as it is
