### ISSUE TITLE
Contract logs for mobile wallet

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#1843]
For a mobile wallet need to optimize the contract logs by leaving only important information(probably now a lot of debugging information), since complete information can generate big size logs.
related to the task https://github.com/BeamMW/beam/issues/1839

**Comment by chapati** [comment]
Implemented in #1839 
Wait until it is tested then test on mobile

**Comment by Denis-Asipenko** [comment]
checked
