### ISSUE TITLE
Offline transaction stuck in waiting status 

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1847]
When we send 2 transactions, 1 - max privacy 2 - offline and they are in the same block, then max privacy get an error message(Failed to get parameter: 7) but completes successfully, but the offline transaction gets stuck waiting
![Screenshot_664](https://user-images.githubusercontent.com/50007056/144192936-92a41fec-83ff-4e78-b022-ad6d49d33dd1.png)
![Screenshot_665](https://user-images.githubusercontent.com/50007056/144192943-07a6f2cf-36ff-4462-bd89-f27c0bbb5dd4.png)

**Comment by anatolse** [comment]
the were 2 problems:
- incorrect exception is thrown when you try to update transaction after voucher response
- api doesn't store vouchers
All are fixed

**Comment by Roberrtt** [comment]
Checked
