### ISSUE TITLE
Allow Wallet Recovery if password forgotten

### ISSUE THREAD

**Issue by azaidelson** [BeamMW/beam#185]
**Feature title**
Allow Wallet Recovery if password forgotten

**Describe the current situation we have**
Currently if the user forgets the wallet password, she is stuck. While the screen says "restore wallet.db or delete it", the user may not know how to do that 

**Describe the solution you'd like**
When user enters a wrong password, inform them that the password is wrong, show the location of Wallet.DB file (can be a hyperlink opening the File Explorer/Finder in the right folder or link to the github page listing the file locations), and also add a button "Restore using your passphrase".
When restoring from passphrase, a new wallet.db file can be created (and the previous one copied with a different name next to it). The user should also be informed that their transaction history will be lost.

A MINIMAL solution would be just to add link to file locations so that users can delete wallet db. They are completely lost otherwise.

**Describe alternatives you've considered (if relevant)**
Another alternative would be to add "delete wallet.db" button, but this sounds too risky

**Additional context**

**Comment by sasha-abramovich** [comment]
We have this feature on our roadmap:

https://zpl.io/bAEmmjB when user will select "forgot password" he will see the warning about the transaction history https://zpl.io/awmNklj 

Good point about still keeping the `wallet.db` file "for future try one sunny day".

**Comment by azaidelson** [comment]
If we can add some textual info (or link) to location of the files before mainnet, that would be awesome. Again, currently the user is 100% stuck.

**Comment by sasha-abramovich** [comment]
We have the wallet.db location currently in the settings:
![image](https://user-images.githubusercontent.com/44961099/50003825-99e87500-ffd7-11e8-8a97-34181033eff0.png)

**Comment by azaidelson** [comment]
Well if I forgot my password, the wallet won't even open and I can't get to the Settings screen...

**Comment by sasha-abramovich** [comment]
*Gotcha!!!* If so, we need to prioritise this task for the Mainnet.

**Comment by azaidelson** [comment]
I would suggest just to change the text.

Now:
"Invalid password or wallet data unreadable
Restore wallet.db from latest backup or delete it and reinitialize the wallet"

I suggest:
"Invalid password or corrupt wallet database file.
If you backed up walled.db file, restore it from backup and try again.
If not, delete wallet.db file and use your 12-words recovery phrase to initialize the wallet.
Walled.dd file location: <Path to file, if can be 'selectable' - great>"

**Comment by sasha-abramovich** [comment]
You are mentioning an adjacent scenario that would worth to be opened in a separate thread, yet allow me to respectfully disagree here. We'll work on a user flow when a simple user won't need to manipulate the files by himself, neither he'll need to read long tech instructions. Actionable buttons and reserved backups of the `wallet.db`. We'd like to be as much simple user friendly as possible all the way along the Desktop App UX. 

As about the text from the English perspective - I hope Nina will pick it up application-wise (preceding your question, under our supervision :) ), her English is at the native level.

**Comment by Denis-Asipenko** [comment]
Recovery phrases are not deleted if you go back to screen entering phrases.

**Comment by gingervik** [comment]
checked

**Comment by disa59** [comment]
Hi. I forgot password and tried to reinit wallet with 12 word phrase after delete wallet.db. It was reinitialized sucsessfully. But now it has another adress for receiving coins, differ from previos. How could i get coins from pool whitch was gained with previous  wallet number?

**Comment by gingervik** [comment]
hi @disa59 
you can import address ([instructions](https://beam-docs.readthedocs.io/en/latest/rtd_pages/user_cli_wallet_guide.html#export-and-import-sbbs-addresses)) from old data base if you still have it. If no - contact pool and change your address in it. During restore process your addresses are gone

**Comment by disa59** [comment]
pool sayed that they already paied. But my restored wallet has zero balance.

**Comment by gingervik** [comment]
@disa59 coins cannot just disappear. If you received it on your old wallet it should be in your new wallet after restore.
If pool sent your coins when your old address has already gone transaction cannot be completed.
Please, go to https://t.me/BeamSupport if you have any questions
