### ISSUE TITLE
Command line node and ui wallet connectivity

### ISSUE THREAD

**Issue by joshbpa** [BeamMW/beam#186]
I am running the cli beam-node on Linux. I can connect the cli wallet to the node and view the blocks I've mined.

I can connect the UI wallet to the cli node and see the current chain height. However I do not see any mined blocks in the UI wallet. I can only see the mined blocks in the cli wallet.

I am using the same seed_phrase in both the UI wallet and the cli wallet.

**Comment by gingervik** [comment]
@joshbpa 
in mainnet you should use 
./beam-wallet restore --seed_phrase="your phrase"
