### ISSUE TITLE
tx_list & tx_status - rates

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam#1861]
Need to add rates stored in transaction to tx_info. Necessary for web wallet.

**Comment by Sergei-Beam** [comment]
It blocked the task on web 
- https://github.com/BeamMW/web-wallet/issues/218

**Comment by chapati** [comment]
Doc are in https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API-v6.3 tx_list

**Comment by kovaletskaterina** [comment]
The rates in API doesn't shown.
![image](https://user-images.githubusercontent.com/83376495/157444967-64ce65cd-ae27-4d15-a177-32c51991e371.png)
![image](https://user-images.githubusercontent.com/83376495/157444989-22c91d88-7579-4f16-99c5-7ee571db22dc.png)
![image](https://user-images.githubusercontent.com/83376495/157445019-5169c695-dc3e-4c29-99e2-2a1fcbd41f00.png)
Walelt DB: [wallet.zip](https://github.com/BeamMW/beam/files/8215290/wallet.zip)

**Comment by chapati** [comment]
This is what is shown on provided wallet.db for the transaction above on my pc:

![gnome-shell-screenshot-8067at](https://user-images.githubusercontent.com/12074933/157900236-e4ad6ef2-eb87-4b83-bad7-320dd0972eba.png)

At the moment of transaction there were no rates available, so the rates are empty and this is correct behavior. Rates that are outlined with the red frame above came after transaction and should not make any influence on the transaction. Please test again and ensure that

1) You use the latest builds from master for UI
1) You use the same wallet db in  api & UI
2) That UI and API show different results

Behavior of UI & API should be the same (rates available/not available)

**Comment by kovaletskaterina** [comment]
Checked
