### ISSUE TITLE
Wallet API: add ability to monitor status of connection to the node

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#1862]
extend https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API-v6.1#ev_system_state
with `is_node_connected` flag

**Comment by anatolse** [comment]
Deсided to add separate event type for connection changes

**Comment by anatolse** [comment]
updated documentation https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API-v6.3#ev_connection_changed

**Comment by Roberrtt** [comment]
node_connected is displayed as 1 or 0 , change to True or False
![2022-03-10_10-48](https://user-images.githubusercontent.com/50007056/157613501-0a22f2eb-657c-4d6a-b47c-16f876c16349.png)

**Comment by anatolse** [comment]
technically `node_connected` is a number of connected nodes

**Comment by Roberrtt** [comment]
https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API-v6.3#ev_connection_changed
In our doc, `node_connected` looks like a boolean value
![2022-03-23_10-58](https://user-images.githubusercontent.com/50007056/159651143-33b09e2e-4594-441b-a8a2-0e132a1fda41.png)

**Comment by Roberrtt** [comment]
checked
