### ISSUE TITLE
[API] Need to add the address_type field to the tx_status response

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#1865]
To complete the
- https://github.com/BeamMW/web-wallet/issues/219

we need to have the "address_type" value into the tx_status response
![image](https://user-images.githubusercontent.com/44496108/151544524-bb6984a2-8a9f-4541-823c-751ae6328eda.png)

**Comment by anatolse** [comment]
updated docs https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API-v6.3#tx_list
