### ISSUE TITLE
Wallet API. Add ability to sign user message 

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#1868]
Wallet API clients may use public keys generated by app shaders as a part of the authentication protocol. Now it is not possible to do in the correct way.
We need two more API methods:
1. sign_message 
2. verify_signature

**Comment by anatolse** [comment]
https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API-v6.3#sign_message
https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API-v6.3#verify_signature

**Comment by Roberrtt** [comment]
checked
