### ISSUE TITLE
[API] Need to add the info about asset's coins into the wallet_status response

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#1870]
To complete the
- https://github.com/BeamMW/web-wallet/issues/180
![image](https://user-images.githubusercontent.com/44496108/155314710-13fab8e1-8c62-4707-ac65-4703ff30b750.png)

we need to have the info about asset's coins into the wallet_status response (I suppose):
Available:
- regular
- max anonymity 

Locked
- maturing
- change
- max anonymity 

But currently, it missed
https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API-v6.3#wallet_status

**Comment by chapati** [comment]
https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API-v6.3, new fields are in wallet_status method

**Comment by Sergei-Beam** [comment]
checked
