### ISSUE TITLE
GPU Miner runtime error - out of memory

### ISSUE THREAD

**Issue by joshbpa** [BeamMW/beam#189]
GPU miner core dumps with out of memory error. I am using testnet3  version 1.0.3607.

I 2018-12-16.20:45:21.828 solving job id=31 with nonce=89cabea204a8ca0b and difficulty=09-7421d7(744.264)
terminate called after throwing an instance of 'std::runtime_error'
  what():  GPUassert: out of memory /home/josh/Downloads/beam/3rdparty/equihash_gpu.cu 979
Aborted (core dumped)

**Comment by Sergei-Beam** [comment]
@joshbpa hi, can you provide what video card are you using?

**Comment by joshbpa** [comment]
EVGA **GeForce GTX 1070** SC GAMING ACX 3.0 Black Edition, 8GB GDDR5, LED, DX12 OSD Support (PXOC) 08G-P4-5173-KR

**Comment by gingervik** [comment]
@joshbpa hi
do you still have this problem on mainnet?
