### ISSUE TITLE
UPDATED OLD BEAMWALLET AND LOST ALL MY COINS AND OLD ADDRESS

### ISSUE THREAD

**Issue by GalaxyX17** [BeamMW/beam#1896]
Ive been mining since 2021 and I decided to never keep update with BEAM. I eventually updated BEAM wallet (6-26-22) and received a "Failed to start node" and immediately saved my wallet logs. I did alot of trial and errors and nothing came close to reviving my old wallet. I do have my "block height", and my miner address that I used for over a year and 1 year old "wallet logs" from when I first started. I do have approximately 364 BEAM in that account that I had mine and I am pissed. Please help me. I did what the technical chat gave me but nothing worked.

**Comment by Galaxia-mk** [comment]
You should have gotten answered. You probably have tried this already but have you tried reviving it with your 12 word secret recovery phrase. People are often sent to their telegram for support. This link may help https://t.me/BeamSupport
