### ISSUE TITLE
Transactions stuck in Confirming state after the address is expired

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#190]
Steps:
    

- create 2 local wallets: wallet_1, wallet_2
- generate address on wallet_1 with expires: 24 hours
- send 2 transaction from wallet 1 to wallet 2
- open wallet_2 and while transactions have In_progress state close the wallet
- go to PC settings and change date&time to make the address expired
- run the waqllet_2
Expected: we should process the transactions if they were sent when the address was alive(excluding the case in ticket #170 )  
Actual: the transactions stuck in confirming forever
<img width="1413" alt="default" src="https://user-images.githubusercontent.com/44496108/50093950-0f945100-0223-11e9-818a-96ec91808d38.png">

**Comment by Aleksandr-Starun** [comment]
Not a bug, because addresses (which participated in transactions) will expire after 24 hours and in real  conditions, transactions will go to the "Failed" state, as the height of the blockchain will also change.
