### ISSUE TITLE
Failed to start node,please save wallet logs and contact support

### ISSUE THREAD

**Issue by lijixy** [BeamMW/beam#1906]
Failed to start node,please save wallet logs and contact support, version 7.1.13105.5426

**Comment by lijixy** [comment]
Data configuration: b5a8b6b3617812c0, Fork didn't happen at 1920000

**Comment by r45ku1** [comment]
please see [this message](https://t.me/BeamSupport/26724) in our support channel

**Comment by jonathancross** [comment]
Pasting support info here:
-----------------------
OK. There is a fix for the 'failed to start node' problem.

This is caused when a user did not update their wallet before the fork happened, so the old wallet node doesn't have the required fork height in the mechanics.

1. close your Beam Wallet
2. find your node.db files.  Location can be found here: https://beam.mw/beampedia-item/data-directory
3. remove the three node files:
 * `node.db`
 * `node-utxo-image.bin`
 * `node.db-journal` (didn't exist in my case)
 
4. restart your wallet
