### ISSUE TITLE
Add Assets Swaps in API

### ISSUE THREAD

**Issue by AndreyDyakonov** [BeamMW/beam#1907]
It is necessary to add the ability to use the assets swaps in API

**Comment by KatsiarynaV** [comment]
Add assets swap transactions to tx_list

![05](https://user-images.githubusercontent.com/68267190/191034707-d88f10b7-5ae3-4784-961b-5984dc352474.jpg)

**Comment by KatsiarynaV** [comment]
As creator of asset swap doesn't pay fee so he should be able to create a swap offer when his Beam balance is 0 and there are other assets in his wallet

![02](https://user-images.githubusercontent.com/68267190/191288771-66095708-29bd-4018-b3a5-87329a41a927.jpg)
