### ISSUE TITLE
Add Assets Swaps in CLI

### ISSUE THREAD

**Issue by AndreyDyakonov** [BeamMW/beam#1908]
It is necessary to add the ability to use the assets swaps in CLI

**Comment by kovaletskaterina** [comment]
1. Forbid to create swap, when the exchange is between the same tokens or assets (with the same ID).
![image](https://user-images.githubusercontent.com/83376495/194557136-839af524-3180-4313-b639-3136df8f7554.png)
2. Forbid to enter 0 balance for _--send_amount_ or _--receive_amount_ options. The argument for both of these options shouldn't be equal to 0.
![image](https://user-images.githubusercontent.com/83376495/194559743-4fa87df7-ade9-4bca-b7c0-b40c4f8f9317.png)
![image](https://user-images.githubusercontent.com/83376495/194571956-14ce14f8-7c8b-4fe4-9b11-e20622f40ddc.png)

**Comment by kovaletskaterina** [comment]
Checked
