### ISSUE TITLE
Add new transaction type on UTXO screen when the user sends the transaction to itself

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#191]
Discuss new transaction type on UTXO screen with @anatolse  @sasha-abramovich @vain-onnellinen

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova is working on the screenshots as we speak :)

**Comment by alexandrashelenkova** [comment]
zpl.io/V4lOkwp

**Comment by sasha-abramovich** [comment]
should it be UTXO screen or transaction screen? let's discuss please @anatolse

**Comment by gingervik** [comment]
already done
