### ISSUE TITLE
wallet api meet jsonrpc error

### ISSUE THREAD

**Issue by BeyongSpringWater** [BeamMW/beam#192]
![image](https://user-images.githubusercontent.com/6032172/50142370-edfb9e00-02e4-11e9-8776-99ca70a50cbd.png)
![image](https://user-images.githubusercontent.com/6032172/50142425-18e5f200-02e5-11e9-9988-8a81a0e15219.png)

**Comment by gingervik** [comment]
@nesbox please, help

**Comment by nesbox** [comment]
@BeyongSpringWater you are sending JSON request using HTTP POST, but not enabled it in API.
Please add `--use_http=1` parameter.
