### ISSUE TITLE
 ./beam-wallet  send send meet Segmentation fault

### ISSUE THREAD

**Issue by BeyongSpringWater** [BeamMW/beam#193]
**Bug title**
Express the problem in a single concise sentence

**Bug description**

root@iZ2zeb7o9hu1q78d990rnsZ:~/beam/wallet_www# ./beam-wallet --command=send -n 127.0.0.1:10000 -r 5ec426078bcf647e38f2ae7a1909bd3e86624249c17c1440f4303f0371c94324 -a 1.3 -f 0.2
I 2018-12-18.16:56:07.723 Rules signature: 6af2277005b4a43a
I 2018-12-18.16:56:07.723 starting a wallet...
Enter password: ***
I 2018-12-18.16:56:10.629 wallet sucessfully opened...
Segmentation fault

**Log file(s) (if applicable)**
t.me/BeamPrivacy/19303
.....
t.me/BeamPrivacy/19312

**Screenshots (if applicable)**
Add screenshots that illustrate a problem you've found.
![image](https://user-images.githubusercontent.com/6032172/50142463-387d1a80-02e5-11e9-8984-a2fb2e67f95b.png)

**Comment by gingervik** [comment]
Hi @BeyongSpringWater 
your description is about beam-wallet
your screenshots - about wallet-api (which is not released yet)


Do you still get Segmentation fault  now?

**Comment by BeyongSpringWater** [comment]
> Hi @BeyongSpringWater
> your description is about beam-wallet
> your screenshots - about wallet-api (which is not released yet)
> 
> Do you still get Segmentation fault now?



![image](https://user-images.githubusercontent.com/6032172/50222759-2b8b2480-03d4-11e9-9e53-93cd4f97efdb.png)
now still get Segmentation fault！
I am sorry first screenshots is wrong， right screenshots is upside picture。

**Comment by gingervik** [comment]
@BeyongSpringWater we are working on it
seems like your wallet has not default address
please, create new one using command=new_addr
and after that try to recend coins

**Comment by BeyongSpringWater** [comment]
> Hi @BeyongSpringWater
> your description is about beam-wallet
> your screenshots - about wallet-api (which is not released yet)
> 
> Do you still get Segmentation fault now?

I sorry，

**Comment by gingervik** [comment]
fixed in testnet4

**Comment by BeyongSpringWater** [comment]
> fixed in testnet4
 does it testnet4 publish？

**Comment by gingervik** [comment]
@BeyongSpringWater not yet. will be published soon
