### ISSUE TITLE
Mine utxo unavailable on 7.3.14027

### ISSUE THREAD

**Issue by solopool** [BeamMW/beam#1940]
Hello!

All utxos with type 'mine' unavailable for always.

**Versions:**
linux-beam-node-7.3.14027
linux-wallet-api-7.3.14027
linux-beam-wallet-cli-7.3.14025

**Api 'get_utxo' results:**

`{
  amount: 4000000000,
  asset_id: 0,
  createTxId: '',
  id: '000000000013b2c96d696e650100000000000000ee6b2800',
  maturity: 18446744073709552000,
  spentTxId: '',
  status: 0,
  status_string: 'unavailable',
  type: 'mine'
}
{
  amount: 4000000000,
  asset_id: 0,
  createTxId: '',
  id: '00000000001075b26d696e650100000000000000ee6b2800',
  maturity: 18446744073709552000,
  spentTxId: '',
  status: 0,
  status_string: 'unavailable',
  type: 'mine'
}`

**beam-wallet info**

Current height............2255785
Current state ID..........cf57b452ef5f7cad

Available.................3,335.64372662 BEAM
Maturing..................0 BEAM
In progress...............0 BEAM
Unavailable...............1,680.3773229 BEAM
Available coinbase........3,320 BEAM
Total coinbase............678,960 BEAM
Available fee.............0.66158 BEAM
Total fee.................248.20305952 BEAM
Total unspent.............3,335.64372662 BEAM

**Comment by oneevil** [comment]
Confirmed, same situation
