### ISSUE TITLE
Improve the text in "Forgot Password" dialog

### ISSUE THREAD

**Issue by azaidelson** [BeamMW/beam#195]
**Bug description**
The current text is somewhat ambigous, saying "all transaction history will be lost" 
A user may understand that this means all their coins will be lost.
This is a very traumatic experience.

**To Reproduce**
Click "Forgot password" on wallet launch screen 

**Expected behaviour**
Need to change the text to notify the user that their COINS will be restored, but transaction history will be lost. Suggested text:
"You can restore your wallet using your recovery phrase. All the coins you own will be restored from the blockchain. Your transaction history is only saved locally, and thus will not be restored."

Please feel free to modify the text, but it is important to tell the user that all their coins will be restored.
**Platform and build**
All

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova let's think what we can do without having too long instructions for the user. In general when user gets to the screen he should know that he's going to restore the balance but not the transaction history. Maybe we can write "Your balance will be restored, but you will lose the transaction history as it's only saved locally." ?

@anatolse please watch this task as we might need to modify the dialog.

@azaidelson we plan to go over the UX anyways with Nina later on and refine all the prompts as planned. There are many places we want to improve. Probably now it's not the right time to start opening and managing the bugs of this kind. Just thinking out loud.

**Comment by alexandrashelenkova** [comment]
I would say "You can restore you wallet using your recovery phrase. Your balance will be restored, but all transaction history will be lost."

**Comment by sasha-abramovich** [comment]
I think we need to explain that the history is stored locally, that's why it can't be restored.

**Comment by sasha-abramovich** [comment]
maybe

"Your transaction history is stored locally and is encrypted with your password. Therefore it can't be restored. The system will proceed to restoring your balance from the blockchain."

too long :(

**Comment by alexandrashelenkova** [comment]
"You can restore you wallet using your recovery phrase. Your balance will be restored, but all transaction history will be lost because it's only stored locally."

**Comment by alexandrashelenkova** [comment]
Not much shorter but nothing else to do here. It's a lot of info so there's no way to explain it all in 5 words phrase.

**Comment by sasha-abramovich** [comment]
In the version I've suggested we explain also that the DB is encrypted with the password that was forgotten. Isn't that important?

"Your _transaction history_ is stored locally and is encrypted with your password, hence it _can't be restored_. **Your balance** will be **fully restored** from the blockchain."

Do you like that? :)

**Comment by alexandrashelenkova** [comment]
I think it is all clear as long as we got to that screen from "Forgot password" link, but can add if you think that it would be better :)

**Comment by sasha-abramovich** [comment]
Yeah, let's add the full text - in these cases it's better to overdo than underdo :) And something similar or even identical for the restore flow maybe?

**Comment by alexandrashelenkova** [comment]
Done

**Comment by azaidelson** [comment]
This is not good. 
You should first inform the user that their coins will be restored. Then say that transaction history will not. 
Because if I first see "transaction history can't be restored", I am already heaving a heart attack. 
And "balance" is also not clear.

Let's start with "Coins will be restored" and then "history will not"

"Your coins will be res

**Comment by sasha-abramovich** [comment]
![image](https://user-images.githubusercontent.com/44961099/50193482-673cd480-0369-11e9-93f3-061c1e2cfea3.png)
![image](https://user-images.githubusercontent.com/44961099/50193508-7cb1fe80-0369-11e9-8a5f-f58e891c0aba.png)
![image](https://user-images.githubusercontent.com/44961099/50193670-285b4e80-036a-11e9-8023-08d145005eaf.png)
![image](https://user-images.githubusercontent.com/44961099/50193693-4032d280-036a-11e9-9012-c55f583cfc9a.png)

@azaidelson as you can see - "funds", "assets" or "balance" are the terms used in the industry. We will switch to "funds" and mention "assets" when CA will be supported. We will also ask more users to validate the heart attack assumption. We will find the right phrase when the resources will allow.

**Comment by sasha-abramovich** [comment]
Your funds will be fully restored from the blockchain. The transaction history is stored locally and is encrypted with your password, hence it can't be restored. 

That's the final version till the future validation and process.

**Comment by azaidelson** [comment]
That’s great.
