### ISSUE TITLE
Change the link to the documentation

### ISSUE THREAD

**Issue by sinaizd** [BeamMW/beam#1958]
New link
https://beam.mw/docs

Old link
https://documentation.beam.mw/

**Comment by Maxnflaxl** [comment]
Hello,

I have already done this: 
https://github.com/BeamMW/android-wallet/pull/636
https://github.com/BeamMW/ios-wallet/pull/581

**Comment by sinaizd** [comment]
Hello
I do not know why your commit did not work, but the link on the new build (7.5) remains the same

https://github.com/BeamMW/beam/assets/45556620/ca24ab97-f165-47ed-89ef-aed0111f0bb5

**Comment by Maxnflaxl** [comment]
Maybe because it wasn't merged into master yet? I assume the 7.5 version is built from the master branch
CC @DenisDemyanko @anatolse

**Comment by sinaizd** [comment]
Anyway, this will be done in the next release🙂👍
