### ISSUE TITLE
Add new type for Transactions when the user sends the transaction to itself

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#196]

**Comment by gingervik** [comment]
related to https://github.com/BeamMW/beam/issues/191

**Comment by alexandrashelenkova** [comment]
Transaction statuses are here https://zpl.io/2ERlRGn

**Comment by gingervik** [comment]
@alexandrashelenkova "sending to own address" is too long name for status. there will be problems in displaying in our desktop wallet

**Comment by alexandrashelenkova** [comment]
@gingervik we can use two lines for this statuses, in that case it should fit fine.
<img width="463" alt="Screenshot 2019-07-10 at 17 32 57" src="https://user-images.githubusercontent.com/7249484/60958425-eced9500-a338-11e9-963f-9aa26a19fead.png">

**Comment by gingervik** [comment]
already done
