### ISSUE TITLE
Explorer node: Add block duration (relative and absolute) to the 'hdrs' request

### ISSUE THREAD

**Issue by dbadol** [BeamMW/beam#1983]
**Current situation**
The new 'hdrs' request feature allows requesting a series of values, both in relative and absolute terms. However, the duration of each block is not part of the provided information, although it's an interesting information for both users, developers and miners.

**Solution we propose**
In the frame of #1982, we propose to add parameter 't' for the period of time covered by the block (i.e. time in seconds since the previous block) and 'T' for its absolute (cumulative) value, which is then the total age of the blockchain, in seconds.

**Comment by Arekss** [comment]
Hi
