### ISSUE TITLE
testnet peer connection timed out

### ISSUE THREAD

**Issue by xwen01** [BeamMW/beam#200]
I downloaded linux-beam-node-1.0.3607 and tried to run beam-node but got "connection timed out":

I 2018-12-19.03:15:02.193 +Peer 128.199.145.212:8101
I 2018-12-19.03:15:02.194 +Peer 104.248.186.25:8101
I 2018-12-19.03:15:02.194 +Peer 138.68.163.99:8101
I 2018-12-19.03:15:02.194 +Peer 188.166.15.205:8101
I 2018-12-19.03:15:02.194 +Peer 206.189.3.9:8101
I 2018-12-19.03:15:02.194 +Peer 128.199.142.41:8101
I 2018-12-19.03:15:02.194 +Peer 178.128.225.252:8101
I 2018-12-19.03:15:02.195 +Peer 138.68.130.189:8101
I 2018-12-19.03:15:02.195 +Peer 188.166.148.169:8101
W 2018-12-19.03:17:09.475 128.199.145.212:8101: connection timed out
I 2018-12-19.03:17:09.476 -Peer 128.199.145.212:8101
I 2018-12-19.03:17:09.476 PI 0000000000000000--128.199.145.212:8101 Rating 896 -> 768
W 2018-12-19.03:17:09.476 104.248.186.25:8101: connection timed out
I 2018-12-19.03:17:09.476 -Peer 104.248.186.25:8101
I 2018-12-19.03:17:09.476 PI 0000000000000000--104.248.186.25:8101 Rating 896 -> 768
W 2018-12-19.03:17:09.476 138.68.163.99:8101: connection timed out
I 2018-12-19.03:17:09.477 -Peer 138.68.163.99:8101
I 2018-12-19.03:17:09.477 PI 0000000000000000--138.68.163.99:8101 Rating 896 -> 768
W 2018-12-19.03:17:09.477 188.166.15.205:8101: connection timed out
I 2018-12-19.03:17:09.477 -Peer 188.166.15.205:8101
I 2018-12-19.03:17:09.477 PI 0000000000000000--188.166.15.205:8101 Rating 896 -> 768
W 2018-12-19.03:17:09.477 206.189.3.9:8101: connection timed out
I 2018-12-19.03:17:09.477 -Peer 206.189.3.9:8101
I 2018-12-19.03:17:09.477 PI 0000000000000000--206.189.3.9:8101 Rating 896 -> 768
W 2018-12-19.03:17:09.477 128.199.142.41:8101: connection timed out
I 2018-12-19.03:17:09.477 -Peer 128.199.142.41:8101
I 2018-12-19.03:17:09.478 PI 0000000000000000--128.199.142.41:8101 Rating 896 -> 768
W 2018-12-19.03:17:09.478 188.166.148.169:8101: connection timed out
I 2018-12-19.03:17:09.478 -Peer 188.166.148.169:8101
I 2018-12-19.03:17:09.478 PI 0000000000000000--188.166.148.169:8101 Rating 896 -> 768
W 2018-12-19.03:17:09.478 138.68.130.189:8101: connection timed out
I 2018-12-19.03:17:09.478 -Peer 138.68.130.189:8101
I 2018-12-19.03:17:09.478 PI 0000000000000000--138.68.130.189:8101 Rating 896 -> 768
W 2018-12-19.03:17:09.478 178.128.225.252:8101: connection timed out
I 2018-12-19.03:17:09.478 -Peer 178.128.225.252:8101
I 2018-12-19.03:17:09.478 PI 0000000000000000--178.128.225.252:8101 Rating 896 -> 768

Any suggestions? Thanks

**Comment by gingervik** [comment]
Hi @xwen01 
You peers look strange
please, use 3.0.151.23:8100
3.0.112.100:8100
52.76.251.61:8100
3.0.82.115:8100
13.250.70.207:8100

3.121.25.231:8100
52.29.133.183:8100
3.122.16.126:8100
3.122.5.247:8100
18.197.244.193:8100 

52.52.228.242:8100
13.52.69.164:8100
52.52.207.165:8100
13.52.91.89:8100
54.177.6.19:8100

**Comment by xwen01** [comment]
Thanks a lot. That worked.

**Comment by xwen01** [comment]
Thanks a lot. That worked.
