### ISSUE TITLE
Progress bar hangs at 30-50 % the first time you connect to a local node

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#204]
When you recover via local node progress bar hangs at 30-50 %, while the wallet is restored and working.
Steps to reproduce the behaviour:
1.Creat new  or restore the wallet
2.Select "Run local node" on setup node screen
![screenshot_10](https://user-images.githubusercontent.com/45556620/50214275-86972a00-0388-11e9-8050-832bf4a41475.png)

**Comment by gingervik** [comment]
checked
