### ISSUE TITLE
UX - Introduce loading screens when creating new wallet or restoring existing wallet

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#21]
The actions, mentioned in the subject, usually imply a heavy and trustworthy mechanisms. Hence when creation time is shorter than 2 seconds, a loading bar should be applied for 2 seconds at least while the actual action happens:

Creation: https://zpl.io/bJv7K6D
![image](https://user-images.githubusercontent.com/44496108/48197302-6d04ca80-e366-11e8-9cfe-531a05d6ddb5.png)

Restore: https://zpl.io/29yO6eA
![image](https://user-images.githubusercontent.com/44496108/48197302-6d04ca80-e366-11e8-9cfe-531a05d6ddb5.png)

**Comment by gingervik** [comment]
Checked. Separate bug for cancel button will be opened
