### ISSUE TITLE
Add the generated hash ID for the UTXO entity.

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#212]
we need to add the generated hash ID for the utxo entity into both CLI and UI wallet.
At first, it needs to continue  @vain-onnellinen work.
Later we will add it to UTXO screen as well
https://zpl.io/V4lOkwp
![image](https://user-images.githubusercontent.com/44496108/50291861-bde90200-0480-11e9-84c2-040fa6aa22cf.png)

**Comment by beam-mw** [comment]
Please update design.

Suggestion: maybe like in transactions, the UTXO will expand to reveal additional information?
