### ISSUE TITLE
Application icon missing in 'Program and Features' screen

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#215]
**Bug description**
Beam application is missing its icon in the list of the installed applications.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the desktop applicatoin.
2. Open Window's "Program and Features" screen via Control Panel.
3. Find the Beam application.

**Current behaviour**
The Beam icon is missing.

**Expected behaviour**
The Beam icon is displayed.

**Platform and build**
* Windows
* 10 x64
* Beam-Wallet-1.0.3770.exe (http://builds.beam-mw.com/master/2018.12.20/Release/win)

**Screenshot**
![image](https://user-images.githubusercontent.com/41323026/50333406-4cf42980-0516-11e9-91b0-c73cbddaae86.png)

**Comment by gingervik** [comment]
fixed with new installer
