### ISSUE TITLE
Beam Node with Stratum Server

### ISSUE THREAD

**Issue by xwen01** [BeamMW/beam#218]
I am trying to run Beam Node with Stratum Server, command as follows:

./beam-node --port 10000 --peer 3.0.151.23:8100 --stratum_port 10001 --stratum_secrets_path stratum_secrets/

I downloaded test.crt and test.key and stored in stratum_secrets directory. I got error:

E 2018-12-21.16:45:40.277 SSL_CTX_use_certificate_file failed, /home/ray/beam/stratum_secrets/stratum.crt
E 2018-12-21.16:45:40.277 stratum server cannot start server: io::Exception: code=-4099 (EC_SSL_ERROR : SSL error) restarting in  1000 msec

What am I doing wrong here? Thanks in advance.

**Comment by gravityfails** [comment]
I am having same issue. Running on windows, getting error:  

E 2019-01-03.19:09:37.795 SSL_CTX_use_certificate_file failed, c:/beam\stratum.crt
E 2019-01-03.19:09:37.795 stratum server cannot start server: io::Exception: code=-4099 (EC_SSL_ERROR : SSL error) restarting in  1000 msec

I assume this has to do with the escape character for the path to the .crt file. \ vs /
But I cannot seem to fix. 
Tested with:  --stratum_secrets_path=.

**Comment by gingervik** [comment]
@xwen01 @gravityfails do you still have this problem?
Use our instructions please
https://documentation.beam.mw/en/agile-atom-4194/rtd_pages/user_beam_node_guide.html#mining-mode

**Comment by xwen01** [comment]
Problem solved. Thanks!

**Comment by AndroidDev77** [comment]
What was the solution, that link is dead

**Comment by jikong39** [comment]
I got same error, can anyone help?  Thanks!

--------------
"E 2021-05-10.08:54:00.119 SSL_CTX_use_PrivateKey_file failed ~./stratum_secrets/stratum.key
E 2021-05-10.08:54:00.119 stratum server cannot start server: io::Exception: code=-4099 (EC_SSL_ERROR : SSL error) restarting in  1000 msec
--------------

**Comment by gingervik** [comment]
@jikong39 please, read https://documentation.beam.mw/en/latest/rtd_pages/user_beam_node_guide.html#mining-mode

**Comment by jikong39** [comment]
Hello @gingervik @xwen01  
 Thanks for the reply! 
 I already read the guide you sent me. 
 I do have stratum_use_tls=on, stratum_secrets_path=./stratum_secrets/ in beam-node.cfg, and have test.crt and test.key under folder ./stratum_secrets/.  However when I start ./beam-node, I still get this error.
