### ISSUE TITLE
Screen setup node connectivity-incorrect display of the interface

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#219]
Creating / restoring a wallet. On screen "setup node connectivity"  in the "enter manning threads" setting, 4 core selection is not displayed(the computer has 4 cores). In the settings is displayed
![photo_2018-12-22_13-45-42](https://user-images.githubusercontent.com/45556620/50373430-e7706d80-05e7-11e9-98e0-f1fe5cc0e7c7.jpg)
![photo_2018-12-22_13-45-48](https://user-images.githubusercontent.com/45556620/50373431-e7706d80-05e7-11e9-8002-667876f86a27.jpg)

**Comment by sasha-abramovich** [comment]
@gingervik closing this one, please reopen if I'm wrong.
