### ISSUE TITLE
Show utxo status acording to elements to display

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#22]
https://zpl.io/V4lOkwp
[BEAMUX-Elementstodisplay-081118-1151.pdf](https://github.com/BeamMW/beam/files/2561586/BEAMUX-Elementstodisplay-081118-1151.pdf)

![image](https://user-images.githubusercontent.com/28015224/48197347-945b9780-e366-11e8-8d3c-800857ea6421.png)

**Comment by Sergei-Beam** [comment]
Checked
