### ISSUE TITLE
Remote node wallet displays "online" status while target node is NOT running.

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#220]
**Bug description**
When Node A is disconnected, the wallet running a remote node that targets Node A displays "Connected" status.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a local node wallet and keep it open.
2. Remember its IP and port.
3. Create a remote node wallet and keep it open.
4. Set target IP and port (from Step 2) in the remote node wallet.
5. Verify that remote node wallet shows online status.
6. Close all the wallets.
7. Give some time for the processes to end (up to 30 seconds).
8. Open the remote node wallet.
9. Check the remote node wallet's status.

**Current behaviour**
The status is online.

**Expected behaviour**
The status is offline.

**Notes**
1. After step 9 if to change the node to Local and back to remote - the status displays "Wallet is not connected to the node" which is correct. So the issue is seen only when first opening the remote node wallet. 
2. See the logs and video attached.

**Platform and build**
* Windows.
* 10 x64
* 1.0.3775, testnet4.

**Log files**
[local.log](https://github.com/BeamMW/beam/files/2705212/local.log)
[remote.log](https://github.com/BeamMW/beam/files/2705213/remote.log)

**Video (Zipped)**
[online_status_while_node_offline.zip](https://github.com/BeamMW/beam/files/2705228/online_status_while_node_offline.zip)

**Comment by gingervik** [comment]
1. wrong error when node stoped and wallet was restarted
![image](https://user-images.githubusercontent.com/28015224/50545160-79492d80-0c1b-11e9-8ed9-9add627c1daf.png)

**Comment by jurijakimuk** [comment]
Retested on 3904, masternet. Works as expected.
