### ISSUE TITLE
Suspicious memory leak in the desktop wallet

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#225]
**Bug description**
Left the wallet to run for the few days, the system started to alert about too much memory consumed.

**To Reproduce**
* No exact scenario, the wallet was on, the WiFi was on and off and so the laptop. The wallet was run on the background.
* After restarting the wallet the system alerts continued soon even with bigger amount of memory consumed.

**Current behaviour**
See screenshots

**Expected behaviour**
Desktop wallet should consume reasonable amount of memory.

**Platform and build**
* Mac
* OS version 10.14.3 public beta
* BEAM Build number: 1.0.3607

**Log file(s) (if applicable)**
Add relevant log file(s),  located in the `logs` folder.
[beam v1.0.3607 osx report.zip](https://github.com/BeamMW/beam/files/2706889/beam.v1.0.3607.osx.report.zip)

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/44961099/50394837-cc8e2c80-0792-11e9-8833-69f71ccabd1d.png)

after restart
![image](https://user-images.githubusercontent.com/44961099/50394849-dd3ea280-0792-11e9-8ed6-3c6c99f4b88d.png)

Settings screen
![image](https://user-images.githubusercontent.com/44961099/50394818-92248f80-0792-11e9-8abf-d101f34dbd24.png)

**Comment by roman-strilets** [comment]
It's not  bug. It's normal situation.

**Comment by gingervik** [comment]
Our wallet require 2-3GB memory for every thread.
Acc to configuration were used 8 threads
this laptop cannot provide this amount of memory, so error was shown

Will be added a requirement into documentation
Also will be added warning message when user try to use more than 2 threads
