### ISSUE TITLE
Remove some options from beam-node.cfg and beam-wallet.cfg

### ISSUE THREAD

**Issue by beam-mw** [BeamMW/beam#227]
Remove from beam-node.cfg the following options:

# secret key generation seed
# wallet_seed=some_secret_string

# phrase to generate secret key according to BIP-39. <wallet_seed> option will be ignored
# wallet_phrase=

# Block pack to import treasury from
# treasury_path=treasury.mw

# number of threads for cryptographic verifications (0 = single thread, -1 = auto)
# verification_threads=-1

All all the consensus rules (last section )

Remove from beam-wallet.cfg

# amount to send (in Beams, 1 Beam = 100 000 000 groth)
# amount=10
# fee (in Beams, 1 Beam = 100 000 000 groth)
# fee=1
# tx id
# tx_id=
# label for new own address
# label=
# treasury operation: 0=print ID, 1=plan, 2=response, 3=import, 4=generate, 5=print
# tr_op=0
# treasury WalletID
# tr_wid=
# treasury percent of the total emission, designated to this WalletID
# tr_pecents=
# treasury custom message
# tr_comment
# child key index. 0 == Master key
# subkey=0

And all the consensus rules (the last section)

**Comment by gingervik** [comment]
please, remove also
# address of receiver
# receiver_addr=

from beam-wallet.cfg
and edit log_level and file_log_level default values (as I remember it was changed)

**Comment by gingervik** [comment]
checked
