### ISSUE TITLE
BEAM - Terms of Use (wallet) 

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/beam#233]
BEAM - Terms of Use (wallet)

Please review and after that add to the Wallet installation process, or/and allow additional visibility in the wallet 

[BEAM - Terms of Use (wallet) - December 16 2018 (1).pdf](https://github.com/BeamMW/beam/files/2708861/BEAM.-.Terms.of.Use.wallet.-.December.16.2018.1.pdf)

**Comment by kaminskyelina** [comment]
After short discussion with Sasha:

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova will provide a screenshot

**Comment by alexandrashelenkova** [comment]
zpl.io/2pn4q7y

**Comment by gingervik** [comment]
checked in installer
orher options will be added later

**Comment by sasha-abramovich** [comment]
https://zpl.io/2pn4q7y

Terms of Use should be shown only once per installation right after the user clicks on at least one button on the following screen:

https://zpl.io/bAq0P56

**Comment by gingervik** [comment]
can be closed
