### ISSUE TITLE
Wallet crashes when cliсking on "save logs"

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#237]
Checked on master and testnet4
mac/win/linux

Steps:
1. Run wallet
2. Settings - Save logs
Actual: crashdump is not created
Wallet is closed
Archive is created in appdata/local/beam Wallet

Error message on Linux:
![image](https://user-images.githubusercontent.com/44496108/50473005-57a63700-09cc-11e9-9406-e46f51a04476.png)

Linux crash dump:

https://drive.google.com/open?id=1gJJY7jYgeeGquDEjQaLnSEdL8xzPS-bp

**Comment by Sergei-Beam** [comment]
Checked on Mac/Linux/Win
