### ISSUE TITLE
We should indicate that wallet is mining

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#238]
For UI wallet
When user is mining we should indicate it (message, animation, indicator color, smth like that)

@sasha-abramovich please, provide a solution

**Comment by birdboxven** [comment]
hello, I installed the wallet with the included miner and activate the gpu and the local node, I can see that the gpu is working and is in more than 60 degrees of temperature, that is 24 hours ago and I can not see any work, all this blank and I do not know how to see the progress of mining, the same thing happened to a server of 5 rxvega 64 and in 24 hours I could not progress, status or progress, I do not know the current network load of the currency and the truth is that this is frustrating, this seems to be an act of faith.

**Comment by sasha-abramovich** [comment]
Not anymore.
