### ISSUE TITLE
UX - Transaction's action menu has incorrect binding

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#24]
Steps:

create 2 wallets

send a few transactions from wallet 1 to wallet 2

when the first transaction appears to open the actions menu

wait while the second transaction appears too

click cancel
Actual: System canceled the second transaction instead of the first. it looks like the menu is bound to the interface, not to the interface object
Note: It reproduced only if both have in_progress status

**Comment by Sergei-Beam** [comment]
Checked
