### ISSUE TITLE
GUI Wallet :: Incorrect message shown when port not available

### ISSUE THREAD

**Issue by beam-mw** [BeamMW/beam#240]
In Beam Wallet version 3830 (probably happens on all platforms)

Steps to reproduce:
1. Launch beam-node on port 10000, connect to master net
2. Launch Beam Wallet (GUI) with default settings (same port)
3. Try to connect to master net

Expected result: Error message that port is taken
Actual result: Error on incompatible peer shown in UI (the real error is written in the log)

[beam_ui_18_12_27_16_14_22.log](https://github.com/BeamMW/beam/files/2712668/beam_ui_18_12_27_16_14_22.log)
<img width="1136" alt="incompatible_peer_screen" src="https://user-images.githubusercontent.com/37414225/50484164-c5b42380-09f7-11e9-8948-82a1552c04e6.png">

**Comment by beam-mw** [comment]
Also, even after I change the port, the wallet does not try to reconnect properly

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova so far we've decided to try the following message:

The port xxx is already in use. Check if a wallet is already running on this machine or change the port settings.

What do you think please?

**Comment by Aleksandr-Starun** [comment]
![image](https://user-images.githubusercontent.com/2501619/51608685-3da73800-1f29-11e9-946c-26e0b00357bc.png)

**Comment by Sergei-Beam** [comment]
We need to change the status for user clearly understand the problem
Steps
- create 2 different wallets separately on port 10005
- run 1st wallet on port 10005
- try to run 2nd wallet on port 10005
Expected: 
Actual: The error that the port already in use is shown
![photo_2019-01-24_15-16-07](https://user-images.githubusercontent.com/44496108/51826170-76635a80-22f7-11e9-8c7e-8aef80bb8e91.jpg)

**Comment by alexandrashelenkova** [comment]
@sasha-abramovich the text looks okay for me. I would only change icon on "change settings" to gear wheel.

**Comment by Sergei-Beam** [comment]
> We need to change the status for user clearly understand the problem
> Steps
> 
> * create 2 different wallets separately on port 10005
> * run 1st wallet on port 10005
> * try to run 2nd wallet on port 10005
>   Expected:
>   Actual: The error that the port already in use is shown
>   ![photo_2019-01-24_15-16-07](https://user-images.githubusercontent.com/44496108/51826170-76635a80-22f7-11e9-8c7e-8aef80bb8e91.jpg)

Moved to #449

**Comment by Sergei-Beam** [comment]
Checked
