### ISSUE TITLE
Can't restore cli wallet from seed phrase

### ISSUE THREAD

**Issue by joshbpa** [BeamMW/beam#245]
I can't restore a the cli wallet from a seed phrase in version 1.0.3860.  See the message below. 

./beam-wallet restore --seed_phrase=model;unusual;pipe;jar;sketch;immense;decrease;eye;check;banana;elevator;cheese;
I 2018-12-28.23:39:29.887 Rules signature: 3284aa6102cdefa4
I 2018-12-28.23:39:29.887 starting a wallet...
Enter password: ********
E 2018-12-28.23:39:34.190 Invalid seed phrases provided: model
E 2018-12-28.23:39:34.190 Please, provide seed phrase for the wallet.

**Comment by gingervik** [comment]
hi, @joshbpa 
if you use linux please try to run 
./beam-wallet restore --seed_phrase="model;unusual;pipe;jar;sketch;immense;decrease;eye;check;banana;elevator;cheese;"
