### ISSUE TITLE
Wallet cli: better error message when enter wrong  password

### ISSUE THREAD

**Issue by frankcoderL** [BeamMW/beam#248]
**Bug title**
beam-wallet-cli-1.0.3860 (Testnet 4): better error message when enter wrong  password

**Bug description**
When entering a wrong wallet password for `./beam-wallet` CLI (beam-wallet-cli-1.0.3860) you will get a bizar error message
> sqlite error code=26, file is not a database
E 2018-12-30.18:46:01.085 Wallet data unreadable, restore wallet.db from latest backup or delete it and reinitialize the wallet

 
**To Reproduce**
Steps to reproduce the behaviour:
1. Run `./beam-wallet`
2. Give a wrong wallet password
3. Bizar error message as result

**Current behaviour**
Bizar error message when giving a wrong wallet password.

**Expected behaviour**
When entering a wrong password show a better error message to the user.

**Platform and build**
* Linux
* (L)Ubuntu 10.10 
* beam-wallet-cli-1.0.3860  (Testnet 4 release)

**CLI output**

````
~/beam-wallet-cli-1.0.3860$ ./beam-wallet listen -n 127.0.0.1:10000
I 2018-12-30.18:45:56.939 Rules signature: 3284aa6102cdefa4
I 2018-12-30.18:45:56.939 starting a wallet...
Enter password: ********
D 2018-12-30.18:46:01.085 sqlite error code=26, file is not a database
E 2018-12-30.18:46:01.085 Wallet data unreadable, restore wallet.db from latest backup or delete it and reinitialize the wallet

~/beam-wallet-cli-1.0.3860$
````

**Comment by azaidelson** [comment]
Agreed. Error message can say "Please check your password. If password is lost, restore wallet.db from latest backup or delete it and and restore from seed phrase."

**Comment by frankcoderL** [comment]
Is easy to fix in ./beam/wallet/cli.cpp in line 565

![cli-pasword-error-message](https://user-images.githubusercontent.com/29205075/50627525-0c43d980-0f34-11e9-8662-7a8aaa458022.png)

**Comment by Sergei-Beam** [comment]
@echoby Please remove typo from the new message. Remove one of "and" word
![image](https://user-images.githubusercontent.com/44496108/54908004-f53fd280-4ef7-11e9-9495-2f5b688ce9fb.png)

**Comment by Sergei-Beam** [comment]
checked
