### ISSUE TITLE
Command Line Wallet and Node - Inconsistent param names

### ISSUE THREAD

**Issue by azaidelson** [BeamMW/beam#249]
In CLI wallet, there are operations called export_miner_key and export_owner_key

In Node, the corresponding parameters are called key_mine and key_owner, respectively

For consistency, they should be named miner_key and owner_key in the Node

**Comment by beam-mw** [comment]
Do not remove old names, Add new ones as alias

**Comment by jurijakimuk** [comment]
@echoby  Please, change the following texts:
"key_owner" parameter was deprecated, use "owner_key"
to
The "key_owner" parameter is deprecated, use "owner_key" instead.
and
"key_mine" parameter was deprecated, use "miner_key"
to
The "key_mine" parameter is deprecated, use "miner_key" instead.

**Comment by jurijakimuk** [comment]
Tested on 4661, master. Works OK.
