### ISSUE TITLE
Testnet4 - same wallet but no more Beam

### ISSUE THREAD

**Issue by marangone** [BeamMW/beam#250]
**Bug title**
Testnet4 - same wallet but no more Beam

**Bug description**
On Testnet3 I've 49360 Beam. On Testnet4 I've 0 Beam, same wallet

**To Reproduce**
Steps to reproduce the behaviour:
Just Install on the same or on a new machine, import the wallet, but no Beam are found.

**Current behaviour**
I've 5 miners with version 1.0.3607, 49360 Beam on Testnet3
I've also 5 other miners with version 1.0.3860, 0 Beam on Testnet4 same wallet .

**Expected behaviour**
Change software versione, update, upgrade, change Testnet or Mainnet and mantein Beam

**Platform and build**
* Windows 
* 7, 10, 2012R2, 2016
* BEAM Build 1.0.3860 loose Beam
![screenshot 5](https://user-images.githubusercontent.com/46270492/50552290-3f663e80-0c90-11e9-96c7-9744fb964d2a.jpg)
![screenshot 4](https://user-images.githubusercontent.com/46270492/50552291-3f663e80-0c90-11e9-9953-a6dbfa3d1298.jpg)

**Configuration, log, memory dump files (if applicable)**
Add relevant files. The filenames and locations are described here: https://github.com/BeamMW/beam/wiki/Folder-and-file-locations

**Log file(s) (if applicable)**
Add relevant log file(s),  located in the `logs` folder.

**Screenshots (if applicable)**
Add screenshots that illustrate a problem you've found.

**Comment by gingervik** [comment]
@marangone Testnet3 and testnet 4 - different blockchains.
Your wallets have different databases
There are also mo complicated settings for miner in testnet 4
please, see our documentation 
https://beam-docs.readthedocs.io/en/latest/rtd_pages/user_mining_beam.html#creating-cli-wallet-for-mining-rewards
