### ISSUE TITLE
No GPU on 1.0.3860 Testnet4

### ISSUE THREAD

**Issue by marangone** [BeamMW/beam#251]
**Bug title**
No "USE GPU" on 1.0.3860 Testnet4

**Bug description**
"USE GPU" Option is Missing on Settings

**To Reproduce**
Upgrade 1.0.3607 to 1.0.3860. Node won't start (and you must edit manually settings with notepad to open GUI Wallet). "Use GPU" is no more present. 

**Current behaviour**
Unusable GPU. You should use CPU only. Again, Testnet4 shows no transactions, less blocks (obviously), no earned Beam. I've uninstalled and I'm still using Testnet3 on some hardware. This happens either with an Unsupported GPU or with a Supported GPU (like Nvidia 1080Ti I0m using on another hw)
![screenshot 2](https://user-images.githubusercontent.com/46270492/50552364-d54e9900-0c91-11e9-9598-cd4643ce136f.jpg)
![screenshot 3](https://user-images.githubusercontent.com/46270492/50552365-d7185c80-0c91-11e9-984f-e09caf34cbbc.jpg)

**Expected behaviour**
Use GPU again

**Platform and build**
* Windows
* 10x64 Pro Eng
* BEAM 1.0.3860.

**Configuration, log, memory dump files (if applicable)**
Add relevant files. The filenames and locations are described here: https://github.com/BeamMW/beam/wiki/Folder-and-file-locations

**Log file(s) (if applicable)**
Add relevant log file(s),  located in the `logs` folder.

**Screenshots (if applicable)**
Add screenshots that illustrate a problem you've found.

**Comment by gingervik** [comment]
Hi @marangone 
"Use GPU" option was removed from our GUI wallet before mainnet. 
For now you can use external miner
Please, use our documentation
https://beam-docs.readthedocs.io/en/latest/rtd_pages/user_mining_beam.html#creating-cli-wallet-for-mining-rewards
