### ISSUE TITLE
Issue when swithing between local and remote node

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#256]
STR:
- create wallet connected to local node
- switch to remote node - apply changes
- switch again to remote node - apply changes
Actual: 
![image](https://user-images.githubusercontent.com/28015224/50560156-f903f480-0d0e-11e9-9680-6e15de0081a1.png)
![image](https://user-images.githubusercontent.com/28015224/50560157-00c39900-0d0f-11e9-9bb6-ec3150e2e0aa.png)

**Comment by Denis-Asipenko** [comment]
checked
