### ISSUE TITLE
Unable export miner_key

### ISSUE THREAD

**Issue by marangone** [BeamMW/beam#257]
**Bug title**
Unable export miner_key

**Bug description**
When you try to export miner_key to use an external miner with gpu, no every kind of option works. Each time the program starts or send a different popup message. I've also renamed "Beam Wallet.exe" to beam-wallet.exe, tried / option, - option -- option space option, changed folder. It doesn't work on Windows.  See many exemples

**To Reproduce**
Simply try to export the key on Windows and really try to use Minenet4 with GPU. 

**Current behaviour**
Unable to use GPU with Mainnet4 and 1.0.3860. With over 30 cores on many machines testnet shows alway 0 Beam. Testnet3 still works good

**Expected behaviour**
Better explanations on help

**Platform and build**
* Windows
*10
*BEAM Build number 1.0.3860

**Configuration, log, memory dump files (if applicable)**
Add relevant files. The filenames and locations are described here: https://github.com/BeamMW/beam/wiki/Folder-and-file-locations

**Log file(s) (if applicable)**
Add relevant log file(s),  located in the `logs` folder.

**Screenshots (if applicable)**
Add screenshots that illustrate a problem you've found.
![screenshot 1](https://user-images.githubusercontent.com/46270492/50560451-2e094a80-0d01-11e9-8da8-2893cf4ce375.jpg)
![screenshot 2](https://user-images.githubusercontent.com/46270492/50560461-49745580-0d01-11e9-99af-a6f98fc0de4c.jpg)

**Comment by gingervik** [comment]
you should export key from cli version of wallet 
https://builds.beam.mw/testnet4/2018.12.28/Release/win/beam-wallet-cli-1.0.3860.zip
