### ISSUE TITLE
Beam CLI wallet does not work with "restore" argument

### ISSUE THREAD

**Issue by pcdinh** [BeamMW/beam#261]
Beam wallet raised an error when executing the following command

```
./beam-wallet restore --seed_phrase=siren;chair;delay;ride;else;lesson;movie;design;strategy;promote;chef;summer;
```

Expected: the command should world. The wallet should be restored

Actual: 

```
./beam-wallet restore --seed_phrase=siren;chair;delay;ride;else;lesson;movie;design;strategy;promote;chef;summer;
-bash: syntax error near unexpected token `else'
```

System:

- Beam testnet4 build
- Ubuntu 18.04

**Comment by pcdinh** [comment]
Oh,

The generated seed passphrase by Beam included an "else". That's why the command refused to execute.

**Comment by egyptianbman** [comment]
quote the phrase, i.e. `--seed_phrase="siren;chair;delay;ride;else;lesson;movie;design;strategy;promote;chef;summer;"`
