### ISSUE TITLE
Testnet 4 (3860): CPU miner seems not to work anymore

### ISSUE THREAD

**Issue by frankcoderL** [BeamMW/beam#262]
**Bug title**
Testnet 4 (3860): CPU miner seems not to work anymore

**Bug description**
On Testnet 3 the CPU miner worked without any problem.
On Testnet 4 the CPU miner doesn't work anymore, Beam mining stays at 0 even after 12 hours or more.
Tested on different computers that worked on Testnet 3, both GUI en CLI.
I know that Equihash is increased from n=144, k=5 to n=150, k=5 , but I espect at least some CPU mining. 
Do I overlook something?
Thanks.

**To Reproduce**
Steps to reproduce the behaviour:
1a. Run Beamwallet GUI-CPU mining
1b. Or Beamnode CLI-CPU mining
2.  Let it work for a half day
3.  No Beams are minded

**Current behaviour**
No Beams ar minded with CPU.
I tried several numbers of CPU cores (low and high numbers), it doens't resolve the problem.
GPU stratum mining with GeForce GTX 1070 works on same configuration on Beamnode CLI.

**Expected behaviour**
To mine Beams with CPU

**Platform and build**
* Linux
* (L)Ubuntu 10.10 and (L)Ubuntu 10.04 LTS 
* BEAM Build number: 3860  Testnet 4 

**Configuration, log, memory dump files (if applicable)**
GUI Beamwallet
[settings.ini.txt](https://github.com/BeamMW/beam/files/2719224/settings.ini.txt)
[beam_ui_18_12_31_00_14_29.log.txt](https://github.com/BeamMW/beam/files/2719226/beam_ui_18_12_31_00_14_29.log.txt)

CLI Beamnode, without stratum GPU mining
[beam-node.cfg.txt](https://github.com/BeamMW/beam/files/2719228/beam-node.cfg.txt)
[node_19_01_01_02_28_35.log.txt](https://github.com/BeamMW/beam/files/2719230/node_19_01_01_02_28_35.log.txt)

**Comment by clefru** [comment]
Can confirm this. No beam mined for more than a day on a Threadripper 1950X, 16 core machine.

**Comment by jeffreyrufino** [comment]
CPU isn't powerful enough to mine.

**Comment by frankcoderL** [comment]
Why than provide CPU mining support if CPU isn't powerful enough to mine?

**Comment by gingervik** [comment]
CPU mining will be removed in next release
