### ISSUE TITLE
Beam node stratum does not respond to login & share

### ISSUE THREAD

**Issue by Lolliedieb** [BeamMW/beam#263]
Beam node stratum does not respond to login & share

When a miner client logs in or sends a share the integrated stratum server in the testnet 4 node software does not send a response "method":"result" according to the protocol specified in https://github.com/BeamMW/beam/wiki/Beam-mining-protocol-API-(Stratum)

The only exception is when the login at node fails.

For future the response messages may help to develop 3rd party mining software - in the development phase a detailed response if shared got accepted or not (and if not: why) is mandatory.

**Comment by Sergei-Beam** [comment]
we should remove "nonceprefix" from all replies except for "login"

**Comment by Sergei-Beam** [comment]
checked
