### ISSUE TITLE
3*2^n Groths are detected as (3*2^n) -1 Groths when sent in CLI wallet 

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#268]
**Bug description**
When user tries to send 3x2^n Groths (n >= 0) via CLI wallet - it appears that the wallet is sending (3x2^n) -1 Groths.

**To Reproduce**
Steps to reproduce the behaviour:
Precondition: A CLI wallet is created with the amount of Beams in it >= 3 Groths.
1. Send 3 Groths from this CLI Wallet to another wallet, i.e. 
`beam-wallet send -n 127.0.0.1:10000 -r 1b7af4cdfee0125d3595985f75e914f9920af8018ca6baa5bc8446c112f1ba887 -a 0.0000003`
2. Confirm the action by providing the wallet password.

**Current behaviour**
2 Groth are actually sent.

**Expected behaviour**
3 Groths are sent.

**Platform and build**
* Windows
* 10
* beam-wallet-cli-1.0.3954, beam-node-1.0.3954, master

**Log file(s) (if applicable)**
[logs (wallet).zip](https://github.com/BeamMW/beam/files/2720506/logs.zip)
[logs (node).zip](https://github.com/BeamMW/beam/files/2720508/logs.node.zip)

**Screenshots (if applicable)**
![2 3](https://user-images.githubusercontent.com/41323026/50588963-938e4000-0e95-11e9-9576-8b6e8a5673fc.jpg)
![image](https://user-images.githubusercontent.com/41323026/50593025-b32e6400-0ea7-11e9-9fe5-6a29d16270a8.png)
![image](https://user-images.githubusercontent.com/41323026/50593649-2e911500-0eaa-11e9-98af-38e07111d490.png)
![image](https://user-images.githubusercontent.com/41323026/50595717-a19e8980-0eb2-11e9-9c16-8c08bbefd785.png)
![image](https://user-images.githubusercontent.com/41323026/50595708-99464e80-0eb2-11e9-85b2-a514b610397e.png)

**Notes**
When 6 (or 3x2^1) Groths are provided - 5 Groth are sent actually.
When 12 (or 3x2^2) Groths are provided - 11 Groth are sent actually.
When 24 (or 3x2^3) Groths are provided - 23 Groth are sent actually and so on.

**Comment by gingervik** [comment]
checked
