### ISSUE TITLE
Records not aligned in transactions history table

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#270]
**Bug description**
In a CLI wallet when running the following command: `beam-wallet info --tx_history` - the records in the transactions history table are not aligned with the column headers.

**To Reproduce**
Steps to reproduce the behaviour:
Preconditions: A CLI wallet is created and running. There are some transactions performed in the wallet.
1. Run the command: `beam-wallet info --tx_history` .
2. Confirm the action by providing the wallet password.

**Current behaviour**
The table records are **not** aligned with the column headers.

**Expected behaviour**
The table records are aligned with the column headers.

**Platform and build**
* Windows
* 10 x64
* 3954, master

**Screenshot**
![image](https://user-images.githubusercontent.com/41323026/50625810-790ea200-0f3b-11e9-9ab9-931fb254cfff.png)

**Comment by VladislavKulyba** [comment]
Checked
