### ISSUE TITLE
Can't start the wallet after changing random node to local without providing peer address.

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#271]
**Bug description**
When wallet settings are incorrectly configured for local node and the changes are saved - the wallet is stuck on downloading data.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a wallet on remote node.
2. Go to settings and change remote node to local node, select threads > 0 and save the changes without entering any peer addresses.
3. Close the wallet.
4. Run the wallet.
5. Enter the password to the wallet and click "show my wallet" button.

**Current behaviour**
The wallet is stuck on downloading data.
The settings file says **peer is invalid**:
```
[localnode]
run=true
port=10005
mining_threads=1
peers=@Invalid()

[node]
address=127.0.0.1:10010
```

**Expected behaviour**
Not specified. 
Some ideas:
1. User should be able to run the wallet even if he/ she configured the wallet incorrectly, so the app could undo the changes automatically on starting the wallet and when the wallet is started, i.e. show a pop up "Wallet configuration has been restored due to .... ."
2. User is prompted to restore/ re-install the wallet due to the issue with configuration, i.e. some information pops up, explaining what has happened and why user needs to restore/ re-install the wallet.
3. Simply do NOT allow the user to save the changes in Settings if they are incorrect or missing some data, i.e. no peers are selected when they are essential.

**Platform and build**
* Windows
* 10 x64
* 3969, steadynet

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova will this dialog be ok? https://zpl.io/29orWre (just replace the two buttons with "OK" button, for example)

**Comment by gingervik** [comment]
![image](https://user-images.githubusercontent.com/28015224/52414876-8a2c6f00-2af6-11e9-9ce2-d7d1a054ca75.png)

**Comment by sasha-abramovich** [comment]
"Please add at least one peer" - that should be the text, no dialog is required.

**Comment by Sergei-Beam** [comment]
We shouldn't show the warning message if user using random node, also the button shouldn't be disabled for random node as well
![image](https://user-images.githubusercontent.com/44496108/52464670-dde99780-2b8c-11e9-8267-65cc26308e08.png)

**Comment by gingervik** [comment]
checked

**Comment by Sergei-Beam** [comment]
Checked
