### ISSUE TITLE
Wrong groths amount displayed in transaction history.

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#272]
**Bug description**
CLI wallet displays wrong amount of groths in the transaction history.

**To Reproduce**
Steps to reproduce the behaviour:
Preconditions: CLI wallet is set up and running.
1. Make a transaction of 50000 groth, i.e. `beam-wallet send -n 127.0.0.1:10000 -r 18614ecab065bc178a99d5bcd15e69f7d6ae28e1a430db0aea45f8ecc1f027e935 -a 0.0005`
2. Check the transaction history: `beam-wallet info --tx_history`.
3. Verify the sent amount.

**Current behaviour**
The amount of groths displayed is "0.50000", which looks like 0.5 beams.

**Expected behaviour**
The amount of groths displayed is "0.0005".

**Platform and build**
* Windows
* 10 x64
* 3975, steadynet

**Screenshots**
![image](https://user-images.githubusercontent.com/41323026/50641909-88611000-0f7a-11e9-8bf1-0233e54069e7.png)
![image](https://user-images.githubusercontent.com/41323026/50641561-6024e180-0f79-11e9-80e9-2134476a76b5.png)

**Comment by Sergei-Beam** [comment]
Checked
