### ISSUE TITLE
Incorrect Sha256Sum on website

### ISSUE THREAD

**Issue by moeadham** [BeamMW/beam#273]
**Bug title**
Published Sha256 for CLI Linux wallet is incorrect

**Bug description**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `https://www.beam.mw/downloads`
2. Copy the url for the Linux CLI wallet (https://builds.beam.mw/mainnet/2019.01.03/Release/linux/Beam-Wallet-1.0.3976.deb)
3. Get the file: `wget https://builds.beam.mw/mainnet/2019.01.03/Release/linux/Beam-Wallet-1.0.3976.deb`
4. Get the sha256: 
```
sha256sum Beam-Wallet-1.0.3976.deb
ac5fce080df0a21ede3d13bd5a8366374be969ceeab6bb685a224385f1b14adc  Beam-Wallet-1.0.3976.deb
```
4. Realize that the sha256 is for the Linux "wallet desktop app" and not the "linux CLI wallet"
`SHA256: b6be6f95848ba439ea3d1f17da0d5523d7087abbe973fdbe584c56bfff8a1b2a`

**Current behaviour**
The website either has an incorrect URL or an incorrect sha256

**Expected behaviour**
I should get the same sha256 when I download a file.

**Platform and build**
* Ubuntu 18.04

**Comment by moeadham** [comment]
Okay it seems that the URL on your website is wrong. I downloaded the *gz from github and get the correct shasum:

```
wget https://github.com/BeamMW/beam/releases/download/mainnet-release/linux-beam-wallet-cli-1.0.3976.tar.gz
sha256sum linux-beam-wallet-cli-1.0.3976.tar.gz
b6be6f95848ba439ea3d1f17da0d5523d7087abbe973fdbe584c56bfff8a1b2a  linux-beam-wallet-cli-1.0.3976.tar.gz
```

**Comment by gingervik** [comment]
sha256 were updated on site
