### ISSUE TITLE
Desktop wallet CPU mining not working

### ISSUE THREAD

**Issue by skyfarm221** [BeamMW/beam#275]
Hey guys, I'm running the desktop wallet on Mac os x. I am connected to the mainnet. Local port is 10005 and peers are node 2, 3, and 4. The app isn't mining for some reason. Any idea what the issue is?

**Comment by gingervik** [comment]
Hello @skyfarm221 CPU mining is not efficient indeed. You need many-many days in average ti=o mine one block with CPU with current difficulty

**Comment by bit2017user** [comment]
Neither CPU or GPU mining is working for me.
Looks like my 1050TI isn't recognized.
[beam v1.0.4028 windows report.zip](https://github.com/BeamMW/beam/files/2728815/beam.v1.0.4028.windows.report.zip)

**Comment by gingervik** [comment]
@bit2017user have you tried to update your drivers? or download cuda toolkit?

**Comment by bit2017user** [comment]
Hello
Both claymore miner and most of nemos miners are working fine.
Regards

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
