### ISSUE TITLE
OpenCL Miner Crashes after card detection.

### ISSUE THREAD

**Issue by hanisaiahyoon** [BeamMW/beam#276]
As soon as I get a job the miner crashes, along with my entire computer. Oddly, I don't get a BSOD, but a white screen of death.

Windows 10, running eight RX-580's. Any idea whats up?

**Comment by gingervik** [comment]
@hanisaiahyoon hi
do you still have this problem?

**Comment by gingervik** [comment]
there is no user's response for 3 weeks. can be closed
