### ISSUE TITLE
No GPU mining option in the Windows wallet with supported GPU

### ISSUE THREAD

**Issue by bhickenbottom** [BeamMW/beam#278]
On the Windows wallet, under settings, there's no option for GPU mining even though I have a supported GPU (Nvidia GTX 1070).

**Comment by Krustbox** [comment]
Same here. Just went out and bought a GTX 1060 to try it out. I don't see any option for GPU. Will keep searching and check back later.

**Comment by raresolid** [comment]
I am having the same problem too. There is no option for the GPU mining when running the Windows wallet. GTX 1080.

**Comment by gingervik** [comment]
Hello guys
For now you cannot do GPU mining via GUI wallet (will be added very soon). 
You should use OpenCL/Cuda external miner.
All instructions you can fine here https://beam-docs.readthedocs.io/en/latest/rtd_pages/user_mining_beam.html#mining-using-external-miner
