### ISSUE TITLE
UX - Change the font for Linux (render it properly)

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#28]
We use SFProDisplay
![image](https://user-images.githubusercontent.com/28015224/48197789-d933fe00-e367-11e8-926f-7ad6c7acf59e.png)
![image](https://user-images.githubusercontent.com/28015224/48197804-e5b85680-e367-11e8-9d21-f9c4c266d0e8.png)

**Comment by nesbox** [comment]
fixed with #43

**Comment by Sergei-Beam** [comment]
Checked
