### ISSUE TITLE
beam-node crashed if DNS lookup of one peer fail

### ISSUE THREAD

**Issue by YihaoPeng** [BeamMW/beam#288]
**Bug title**
beam-node crashed if DNS lookup of peer fail

**Bug description**
```
# ./beam-node
I 2019-01-04.21:14:45.930 Rules signature: ed91a717313c6eb0
E 2019-01-04.21:14:46.564 unable to resolve: us-node01.mainnet.beam.mw:8100
I 2019-01-04.21:14:46.564 Node stopping...
terminate called after throwing an instance of 'std::runtime_error'
  what():  sqlite err 21, out of memory
[1]    7122 abort (core dumped)  ./beam-node
```

This made me mistakenly think that the database is corrupted, so I removed `node.db`. But the same error still occur. Finally, I removed the peer from beam-node.cfg and the error disappeared.

**To Reproduce**
Run beam-node with some right peer domains and at least one wrong peer domain:
```
peer=ap-node01.mainnet.beam.mw:8100
peer=us-node01.mainnet.beam.mw:8100
peer=eu-node01.mainnet.beam.mw:8100
peer = a.b.cd:1111
```

**Current behaviour**
```
I 2019-01-04.21:14:45.930 Rules signature: ed91a717313c6eb0
E 2019-01-04.21:14:46.564 unable to resolve: a.b.cd:1111
I 2019-01-04.21:14:46.564 Node stopping...
terminate called after throwing an instance of 'std::runtime_error'
  what():  sqlite err 21, out of memory
[1]    7122 abort (core dumped)  ./beam-node
```

**Expected behaviour**
Ignore the DNS failure and keep running.
It is a P2P blockchain client and has more than one bootstrap peers in the configure.
In addition, once it is connected to a P2P network, it can discover hundreds of other peers and no longer need to rely on these bootstrap nodes.
So it should not denial of service because of such a small error.

**Platform and build**
* Windows, Linux
* OS version: all
* BEAM Build number: 1.0.3976

**Comment by YihaoPeng** [comment]
And your website is done and all nodes in your website are not work. What happened?
```
# nslookup ap-node03.mainnet.beam.mw
** server can't find ap-node03.mainnet.beam.mw: NXDOMAIN

# nslookup us-node01.mainnet.beam.mw
** server can't find us-node01.mainnet.beam.mw: NXDOMAIN

# nslookup eu-node04.mainnet.beam.mw
** server can't find eu-node04.mainnet.beam.mw: NXDOMAIN
```

**Comment by gingervik** [comment]
@YihaoPeng if wrong peer is your only peer your node cannot get "hundreds of alternative nodes in its database". Will be added more default nodes soon

try to use ipconfig /flushdns if you on windows

**Comment by SwimmingTiger** [comment]
No, I just restarted the node and it crashed.
When DNS was normal, it had found hundreds of nodes.
If I remove this peer from the configuration file, it is completely normal.
So the problem is not that I can't find any peer. The problem is that the program should not crash when the DNS is abnormal.

**Comment by SwimmingTiger** [comment]
From another perspective, if I fill in a wrong IP address in the peer configuration, the node will not crash.
But filling a wrong domain name will crash the node.

If the domain name was good before, but suddenly it's down, then my node cannot be restarted after I close it. But in fact, it can work without relying on the peer in the configuration file at this situation. The only thing the node need to do is to ensure itself not crash when a DNS exception occurs.

**Comment by taw00** [comment]
Ditto. Running into the same issue for all nodes listed on the website:
https://www.beam.mw/downloads

**Comment by nesbox** [comment]
**Changes**: ignoring DNS failure and keep running b17371b

**Comment by Sergei-Beam** [comment]
checked
