### ISSUE TITLE
Change Wallet/Chain Folder: Provide --datadir parameter OR via GUI

### ISSUE THREAD

**Issue by gaia** [BeamMW/beam#290]
**Feature title**
Change Wallet/Chain Folder (Windows Desktop) to use non default location

**Describe the current situation we have**
Seems that the wallet folder cannot be changed

**Describe the solution you'd like**
Allow Change Wallet/Chain Folder either via --datadir parameter OR via GUI

**Describe alternatives you've considered (if relevant)**
N/A

**Comment by dink** [comment]
I agree. Preferably let the user choose a location on install screen in case they don't have space on the default one.

**Comment by gingervik** [comment]
hi @gaia @dink 
If you want to change where all dbs are located use param "appdata" in beam-wallet.cfg (located in Program files/beam wallet as default)
example:
appdata=C:\data

**Comment by gaia** [comment]
Thanks! I did that, but C:\Users\gaia\AppData\Local\Beam Wallet\cache\qmlcache remained in place. This is minor, as it is not such a large folder, but is it possible to move it?

**Comment by SkybuckFlying** [comment]
Thanks this worked, little note for noobies:

in beam-wallet.cfg the # in front of "appdata" must be removed (this is to "uncomment it"
