### ISSUE TITLE
No API Started & 0/0 Sol/s

### ISSUE THREAD

**Issue by dave-dm** [BeamMW/beam#292]
No sure what the problem is.

    ubuntu@ip-111-111-111-111:~$ ./beam-cuda-miner --server beam-eu.sparkpool.com:2222 --key asdfasdfasdfasdfasdfasdfasdfasdfsdfasdf
    beam-cuda-miner version 1.0.0.82
    17:28:36 [Info ]: No API started
    17:28:39 [Info ]: Connecting to beam-eu.sparkpool.com:2222 ...
    17:28:39 [Info ]: GPU:0: GRID K520
    17:28:39 [Info ]: GPU:1: GRID K520
    17:28:39 [Info ]: GPU:2: GRID K520
    17:28:39 [Info ]: GPU:3: GRID K520
    17:28:39 [Info ]: Connected to beam-eu.sparkpool.com:2222
    17:28:39 [Info ]: New job #1 at difficulty 100
    17:28:49 [Info ]: GPU:0: A:0/R:0, t:34C P:47W fan:0% 0/0 Sol/s
    17:28:49 [Info ]: GPU:1: A:0/R:0, t:37C P:46W fan:0% 0/0 Sol/s
    17:28:49 [Info ]: GPU:2: A:0/R:0, t:33C P:46W fan:0% 0/0 Sol/s
    17:28:49 [Info ]: GPU:3: A:0/R:0, t:36C P:45W fan:0% 0/0 Sol/s
    17:28:49 [Info ]: Total: A:0/R:0 0/0 Sol/s (4.39e+04/4.39e+04 H/s)
    17:28:59 [Info ]: GPU:0: A:0/R:0, t:35C P:48W fan:0% 0/0 Sol/s
    17:28:59 [Info ]: GPU:1: A:0/R:0, t:39C P:47W fan:0% 0/0 Sol/s
    17:28:59 [Info ]: GPU:2: A:0/R:0, t:34C P:46W fan:0% 0/0 Sol/s
    17:28:59 [Info ]: GPU:3: A:0/R:0, t:36C P:45W fan:0% 0/0 Sol/s
    17:28:59 [Info ]: Total: A:0/R:0 0/0 Sol/s (4.9e+04/4.64e+04 H/s)
    17:29:09 [Info ]: GPU:0: A:0/R:0, t:36C P:48W fan:0% 0/0 Sol/s
    17:29:09 [Info ]: GPU:1: A:0/R:0, t:40C P:47W fan:0% 0/0 Sol/s
    17:29:09 [Info ]: GPU:2: A:0/R:0, t:35C P:46W fan:0% 0/0 Sol/s
    17:29:09 [Info ]: GPU:3: A:0/R:0, t:37C P:45W fan:0% 0/0 Sol/s
    17:29:09 [Info ]: Total: A:0/R:0 0/0 Sol/s (5.08e+04/4.79e+04 H/s)
    17:29:19 [Info ]: GPU:0: A:0/R:0, t:36C P:48W fan:0% 0/0 Sol/s
    17:29:19 [Info ]: GPU:1: A:0/R:0, t:41C P:47W fan:0% 0/0 Sol/s
    17:29:19 [Info ]: GPU:2: A:0/R:0, t:36C P:46W fan:0% 0/0 Sol/s
    17:29:19 [Info ]: GPU:3: A:0/R:0, t:38C P:44W fan:0% 0/0 Sol/s
    17:29:19 [Info ]: Total: A:0/R:0 0/0 Sol/s (4.76e+04/4.78e+04 H/s)
    17:29:29 [Info ]: GPU:0: A:0/R:0, t:37C P:48W fan:0% 0/0 Sol/s
    17:29:29 [Info ]: GPU:1: A:0/R:0, t:41C P:47W fan:0% 0/0 Sol/s
    17:29:29 [Info ]: GPU:2: A:0/R:0, t:37C P:46W fan:0% 0/0 Sol/s
    17:29:29 [Info ]: GPU:3: A:0/R:0, t:39C P:45W fan:0% 0/0 Sol/s
    17:29:29 [Info ]: Total: A:0/R:0 0/0 Sol/s (4.89e+04/4.8e+04 H/s)

**Comment by gingervik** [comment]
hi @dave-dm 
do you have all needed driver? have you tried to use open-cl miner? is you problem still reproduced?
