### ISSUE TITLE
Windows GUI wallet stuck at block #2099.

### ISSUE THREAD

**Issue by mountassir** [BeamMW/beam#293]
**Bug description**
I have had the wallet open since launch, this morning I checked and saw that it was stuck at block number 2099.

**Configuration, log, memory dump files (if applicable)**
I checked settings.ini and found that the wallet had an invalid peer.

`[localnode]
run=true
port=10005
mining_threads=1
peers=@Invalid()`

I manually changed the peer to one of the mainnet nodes and the wallet synced correctly to the latest block.

**Platform and build**
* Windows
* BEAM Build number 1.0.3976

**Comment by gingervik** [comment]
hi @mountassir 
it's not a bug.if user wants to run local node there should be a peer
Later we will add a warning which prevent such situations
