### ISSUE TITLE
Expired address cannot be charged, this is not scientific!

### ISSUE THREAD

**Issue by webees** [BeamMW/beam#294]
I can't receive the money from the mining pool right now. Can I solve it by modifying the system time?

I want to modify the wallet.db file, maybe this way can be solved，but the database requires a password.

**Comment by gingervik** [comment]
hi @webees 

To make sure you send and receive transaction correctly follow the procedure:

1. Make sure you use permanent SBBS address (address with expire = never) when registering with pool

2. Whether you run a wallet or a node:

MAKE SURE THE TIME ON YOUR MACHINE IS CORRECT. 

USE AUTOMATIC TIME SYNCHRONIZATION OR SET THE CORRECT TIME MANUALLY. 

IF YOUR MACHINE TIME IS NOT SET CORRECTLY YOU WILL EXPERIENCE PROBLEMS WITH SENDING AND RECEIVING TRANSACTIONS

3. Make sure the wallet is online until the transaction is 'Completed'

**Comment by webees** [comment]
Thanks
