### ISSUE TITLE
Add the block height on Mining stratum 

### ISSUE THREAD

**Issue by appkoders** [BeamMW/beam#295]
**Feature title**
Please add the block height on Mining stratum jobs that the node sends to miners.

example

> { 
> "difficulty":3441671469,
> **"height": 3001,**
> "id":"212",
> "input":"636b90cc38bc7a347f074d9ca97c3a2158330f6844f8f52075a38a15ab483223",
> "jsonrpc":"2.0",
> "method":"job"
> }

**Describe the current situation we have**
Right now when developing a mining pool there is no clear/easy way to get the block height of the current job that is being mined. If the pool finds a block you still have to find a way to check what block height you mined. It can be done but why complicate things when it can be easily sent together with the Job. 

**Describe the solution you'd like**
Just add the height param together with the job sent by the stratum.

**Comment by Sergei-Beam** [comment]
Checked
