### ISSUE TITLE
Wallet 1.0.4028 does not show Beam or transactions

### ISSUE THREAD

**Issue by marangone** [BeamMW/beam#297]
**Bug title**
Wallet 1.0.4028 does not show Beam or transactions

**Bug description**
I've 7 Windows machines mining. 6 with 1.0.3976 and 1 with 1.0.4028. Same wallet with same seed and password. The last one is unable to see Beam and the trasactiion

**To Reproduce**
Steps to reproduce the behaviour:
Simply install last Windows Wallet version

**Current behaviour**
Does not seen Beam or transactions. Restoring version 1.0.3976  after a clean installation solves the problem

**Expected behaviour**
Syncronized with previous version

**Platform and build**
* Windows
* 10
* 1.0.4028 

**Configuration, log, memory dump files (if applicable)**
Add relevant files. The filenames and locations are described here: https://github.com/BeamMW/beam/wiki/Folder-and-file-locations

**Log file(s) (if applicable)**
Add relevant log file(s),  located in the `logs` folder.

**Screenshots (if applicable)**
![screenshot 1](https://user-images.githubusercontent.com/46270492/50734307-95aa1480-119d-11e9-9a50-1d319a4ff78a.jpg)
![screenshot 2](https://user-images.githubusercontent.com/46270492/50734308-95aa1480-119d-11e9-81c1-232c2deed3d4.jpg)

**Comment by gingervik** [comment]
hi @marangone 
your wallet can restore all your utxos only if you run it with local node

**Comment by gingervik** [comment]
we do not recommend use two wallets with the same seed at the same time
problem with decoys is fixed in 1.2
