### ISSUE TITLE
Transaction  stuck at Status: "Confirming" after more than 1 day

### ISSUE THREAD

**Issue by mrfisherguz** [BeamMW/beam#298]
**Bug title**
Transaction  stuck at Status: "Confirming" after more than 1 day

**Bug description**
The fact is that I sent a man 3 beam and in his wallet this transaction was confirmed but I have not confirmed more then a day.

**To Reproduce**
1. Install Beam GUI wallet for Linux from the beam website (Beam-Wallet-1.0.3976.deb).
2. Generate new wallet.
3. Wait for blockchain to sync.
4. Leave wallet running.
5. Sent 3 Beam to adress 1a6c29c8722b315fe63417c50a937bf9edbc99d9aa432a91c323dab39ee458c281
6. And i have status "confirming" every time on this transaction.
7. Because of that 66.21568433 Beam has been frozen and has state "RECEIVING" every time too.

**Current behaviour**
1. Transaction status is stuck at status "Confirming" after many time.
2. 66.21568433 Beam has been frozen and has state "RECEIVING" every time.

**Expected behaviour**
1. Incoming transaction status changes to "Confirmed"..
2. Get 66.21568433 Beam to "Avalible" balance.

**Platform and build**
 Linux Ubuntu 18.04

* BEAM Build number 1.0.39.76

**Configuration, log, memory dump files (if applicable)**
[beam v1.0.3976 ubuntu report.zip](https://github.com/BeamMW/beam/files/2730353/beam.v1.0.3976.ubuntu.report.zip)

**Log file(s) **
[logs.zip](https://github.com/BeamMW/beam/files/2730333/logs.zip)

**Screenshots**
![_999 363](https://user-images.githubusercontent.com/43968280/50734825-0d843900-11b6-11e9-9c5b-12733f6358fb.png)

![image](https://user-images.githubusercontent.com/43968280/50734757-fb55cb00-11b4-11e9-8195-85c2317e1e4e.png)

![image](https://user-images.githubusercontent.com/43968280/50734768-1f191100-11b5-11e9-8324-39d649abbf27.png)

**Comment by gingervik** [comment]
hi @mrfisherguz
Have you tried to restart wallet?
seems like you sent transaction when you had not finished sync
I can suggest you to restore your wallet. But in this case you will lost of your transaction history and addresses

**Comment by gingervik** [comment]
if you affraid to loose your coins you can try to backup current beam folder https://beam-docs.readthedocs.io/en/latest/rtd_pages/user_files_and_locations.html and then try to restore

**Comment by mrfisherguz** [comment]
my wallet was online every time and synced. There are no problems now. 


>Вторник,  8 января 2019, 10:02 +03:00 от Vika Khodichenko <notifications@github.com>:
>
>if you affraid to loose your coins you can try to backup current beam folder  https://beam-docs.readthedocs.io/en/latest/rtd_pages/user_files_and_locations.html and then try to restore
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

==

**Comment by gingervik** [comment]
ok. so I close isue if there are no problems now

**Comment by mrfisherguz** [comment]
yep


>Вторник,  8 января 2019, 14:45 +03:00 от Vika Khodichenko <notifications@github.com>:
>
>ok. so I close isue if there are no problems now
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

==
