### ISSUE TITLE
 Implement extended transaction view

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#30]
Screenshots: https://zpl.io/a7Ewlkj, https://zpl.io/2vYm4R7
![image](https://user-images.githubusercontent.com/28015224/48197861-14363180-e368-11e8-81d9-e2cf1c2f1f1f.png)
![image](https://user-images.githubusercontent.com/28015224/48197874-1e583000-e368-11e8-9b4c-8268032a8d79.png)

**Comment by anatolse** [comment]
not relevant
