### ISSUE TITLE
Transaction Failed: Peer's signature not valid

### ISSUE THREAD

**Issue by leifliddy** [BeamMW/beam#301]
**Bug title**
Transaction Failed: Peer's signature not valid

**Bug description**
I'm not able to receive a payment.
In the wallet log, I see:
#############################################
Receiving 16 beams 64398963 groth  (fee: 10 groth )
Invitation accepted
....
Received PeerSig:     fdada604f5a4b8b9
Failed. Peer's signature in not valid
Transaction failed. Rollback...
#############################################

**Platform and build**
Receiver:
beam-wallet-cli-1.0.3976
beam-node-1.0.3976

Sender:
I'm not sure what platform the sender's using, does it matter?

I'm just trying to sort out what the nature of the error is. What exactly does 'Peer's signature in not valid' mean, and how do I remedy that?

**Comment by gingervik** [comment]
@leifliddy hi
can you please send us your settings and full log?
which peer address are you using?

**Comment by gingervik** [comment]
[wallet_19_01_07_07_35_49.log](https://github.com/BeamMW/beam/files/2740198/wallet_19_01_07_07_35_49.log)

**Comment by leifliddy** [comment]
I was running a full node and just using random peer addresses. But, I'd like to take a step back and first learn to run a light wallet via the command line. The goal is to have a wallet that's online all the time. I don't really see the benefit of running a full node as there's really no incentive with this coin to do that. 

What would be the recommended way of doing that?
Should this systemd configuration work?

```
[Unit]
Description=beam-wallet service
After=network.target

[Service]
User=coin
Group=coin

Type=simple

WorkingDirectory=/opt/beam
ExecStart=beam-wallet --wallet_path /opt/beam/wallet.db --pass 'xxx' listen -n ap-node01.mainnet.beam.mw:8100 

[Install]
WantedBy=multi-user.target
```

I'll test this out later today and will report back.

**Comment by gingervik** [comment]
@leifliddy when you run your wallet with your local node it's more secure and mean that you can restore all your utxos in future.
So I recommend you to use local node
all instructions https://beam-docs.readthedocs.io/en/latest/rtd_pages/user_cli_wallet_guide.html
all IPs https://www.beam.mw/downloads

**Comment by leifliddy** [comment]
I believe this issue was ultimately caused by some (ISP-related) networking issues. I do appreciate the explanation of why running local node is beneficial.

**Comment by gaia** [comment]
Do you not get the same benefits (more secure, can restore all utxos) if you run a wallet on windows and a full (private, FW blocked) node on Linux?

**Comment by gingervik** [comment]
@gaia hello your question in closed issue is not good way to get some answers)

full node means history of all blockchain.
you can restore your utxo using node on the same PC or even GUI version (with built-in node)
