### ISSUE TITLE
Send API leaves transaction in "Confirming" state

### ISSUE THREAD

**Issue by mmorrell** [BeamMW/beam#302]
**Bug title**
Calling "send" in wallet-api does not fully confirm the transaction.

**Bug description**
When calling the "send" api in wallet-api binary to a recipient with a running GUI wallet, the recipient sees "Confirming" and the sender wallet sees "In Progress" for an indefinite amount of time. The recipient sees a Kernel ID of 000000.

However, I am able to remedy the issue manually by restarting "./beam-wallet listen" on the sender CLI.
After restarting ./beam-wallet listen, it produces a log like this, which actually generates the Kernel ID for the recipient:
`D 2019-01-07.13:10:42.622 Received PeerSig:     3831e5411219aa4f
D 2019-01-07.13:10:43.341 Received PeerSig:     3831e5411219aa4f
I 2019-01-07.13:10:43.363 Get proof for kernel: 1b4b344be9e0c2d2`

**To Reproduce**
Steps to reproduce the behaviour:
1. Sender runs the following 3 binaries on Linux: ./beam-node, ./beam-wallet, and ./wallet-api
e.g.
./beam-wallet listen -n 127.0.0.1:10000
./wallet-api --node_addr=127.0.0.1:10000 -p 10001
./beam-node --peer eu-node01.mainnet.beam.mw:8100,eu-node02.mainnet.beam.mw:8100,eu-node03.mainnet.beam.mw:8100,eu-node04.mainnet.beam.mw:8100 --mining_threads 0 --file_log_level debug (keys omitted)
2. Recipient runs Beam Wallet for Windows with an indefinite receive address.
3. Sender calls beam api through telnet or direct socket (use your own recipient address): `{"jsonrpc":"2.0", "id": 2,"method":"send", "params":{"session" : 123, "value" : 1337,"fee" : 10,"address" : "1eb7a92df50a5d1fac695a7228ba5400f705dfe17103dbf344892401c2b37bfd12","comment" : "thank you!"}}`
4. Windows recipient sees a new "Confirming" transaction appear with a Kernel ID of 000000.
5. The transaction never confirms.

> 6. To remedy, restart the sender's beam-wallet binary (Linux).
> 7. Windows recipient now sees a non-zero Kernel ID and receives the confirmed transaction.

**Current behaviour**
Recipient sees a new "Confirming" transaction appear with a Kernel ID of 000000. Recipient does not receive transaction.

**Expected behaviour**
Recipient sees a new "Confirming" transaction appear with a Kernel ID of NOT 000000. Recipient eventually receives transaction upon next block mine.

**Platform and build**
* Windows and Linux
* Windows 7, Ubuntu 16
* 1.0.4028
* rules signature ed91a717313c6eb0

**Comment by gingervik** [comment]
Hi @mmorrell 
Thank you for your suggestions
wallet-api is not released yet. so there are a lot of bugs.
Don not use it now
