### ISSUE TITLE
Integrated Miner - Add Indication for solution per second in wallet UI

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/beam#303]
Integrated Miner - Add Indication for solution per second in wallet UI

**Comment by gingervik** [comment]
@sasha-abramovich provide design please

**Comment by sasha-abramovich** [comment]
@kaminskyelina how many miners can be active at the same time? can you please attach the screenshot how it looks like currently? do we have a miner per GPU? etc

**Comment by sasha-abramovich** [comment]
closing as there is no miner in the wallete
