### ISSUE TITLE
Windows GUI wallet, reinstalled it, now my address will be expired

### ISSUE THREAD

**Issue by erkange** [BeamMW/beam#304]
**Bug title**
My address will be expired even i choose never when creating

**Bug description**
I format my pc, and reinstall it. Then i download wallet and re-install it with my secret words.
Now it says my address will be expired.
I was mining to it with sparkpool.
how i can make this address stays forever?

**Comment by gingervik** [comment]
hi @erkange 
new wallet - new addresses
when you restore your wallet you cannot restore your addresses and transactions list
We are sorry. Generate new address in your new wallet and send it to the pool

**Comment by wilba84** [comment]
@gingervik 
I also had this issue after going from the windows wallet to the newer version with the gpu miner. Unfortunately there was no warning about this address issue, Not sure how to retrieve coins now as the pool pays to the address it was mined with...

**Comment by gingervik** [comment]
@wilba84 did you restore your new wallet with GPU?
You can try to connect to your previous wallet.db
For this go to AppData (windows) or https://beam-docs.readthedocs.io/en/latest/rtd_pages/user_files_and_locations.html

And backup (it's necessary) your wallet db from folder 1.0.4028 and place there db from 1.0.3976. Than try to run your wallet

**Comment by wilba84** [comment]
@gingervik This worked perfectly, Thank you very much @erkange I suggest you follow the same instructions, should restore your permanent address, Good luck!

**Comment by wilba84** [comment]
@gingervik how do I check my earnings when using the wallet miner? I normally check poolside

**Comment by erkange** [comment]
> @gingervik This worked perfectly, Thank you very much @erkange I suggest you follow the same instructions, should restore your permanent address, Good luck!

I did the same and solved. I take my backup files from external hdd. And put them on original files. Now my wallet is alive again.
