### ISSUE TITLE
API return messy code

### ISSUE THREAD

**Issue by EremitCash** [BeamMW/beam#305]
![image](https://user-images.githubusercontent.com/46362202/50804898-07fc2f80-132b-11e9-8167-60d08004063f.png)
![image](https://user-images.githubusercontent.com/46362202/50804924-23ffd100-132b-11e9-92cd-ca7b8c67a2cd.png)

**Comment by gingervik** [comment]
Hi
@EremitCash @litterGuy 
wallet-api is not released yet. so there are a lot of bugs.
Don not use it now
