### ISSUE TITLE
Wallet API doesn't listen for incoming txs on addresses that have been generated in the currently running API instance

### ISSUE THREAD

**Issue by alesito85** [BeamMW/beam#315]
An API restart is required.

**Comment by gingervik** [comment]
@alesito85 our Wallet-api is not released yet

**Comment by alesito85** [comment]
I've opened an issue because I'm in touch with your dev and he asked for me to open the issue here.

**Comment by gingervik** [comment]
@alesito85 I am sorry

**Comment by nesbox** [comment]
already fixed here f5ed206d
