### ISSUE TITLE
BEAM Wallet Issue

### ISSUE THREAD

**Issue by Suyneej** [BeamMW/beam#316]
I have the windows version of the wallet installed. Yesterday I sent 6 Beam coin to another wallet and it has been stuck "confirming" and "sending" for over 24 hours. Restarting wallet does nothing. 

Kernel ID for the transaction is: 
"4924446816566b700f5158cf228d5a7b42bb4c82c77a66dbf63ba6124f36f40d"

**Comment by Suyneej** [comment]
Just wokeup and it appears the transaction failed. Was able to resend it successfully a few minutes ago.

**Comment by gingervik** [comment]
@Suyneej is new transaction completed? can we close this issue?

**Comment by Suyneej** [comment]
yes all is good now. Thanks.
