### ISSUE TITLE
Add adility to make expired address alived forever

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#318]
In cli and Ui versions
1. user should be able to make expired address as active with expiration = never
2. change expiration for address from 24 hours to never
3. do it for all addresses
4. wallet should receive all transactions which for sent for expired address when he mafe it "never" again (for last 12h)

**Comment by roman-strilets** [comment]
example:
beam-wallet.exe change_address_expiration --address=a5199ee46a6d654d62155b9d4a8061b1194f2a8c0ebaafc731d59da2b6cef4173 

beam-wallet.exe change_address_expiration --address=*  - change expiration for all address from wallet

**Comment by roman-strilets** [comment]
branch change_address_expiration

**Comment by Sergei-Beam** [comment]
checked

**Comment by adriadrop** [comment]
Hi, wondering if this is going to be in live wallets and when? I have a case where I would need to restore my expired address. thank you
