### ISSUE TITLE
JSON RPC request returns parse error on wallet-api

### ISSUE THREAD

**Issue by CD0x23** [BeamMW/beam#319]
**Bug title**
Making a post request to the wallet-api returns empty reply(52), and logs as json parse error on the wallet-api logs.
**Bug description**
Making a post request to the wallet-api logs as json parse error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start wallet-api 
2. Make a post request using one of the wallet-api commands. 
```
curl -d '{
        "jsonrpc":"2.0",
        "id": 1,
        "method":"create_address",
        "params":
        {
                "lifetime": 24,
                "metadata": "string encoded JSON metadata"
        }
}' 'localhost:10001'
```
3. Check wallet-api logs of the request 

**Current behaviour**
Returns empty reply(52) on the request side, and logged as parse error on the wallet-api
**Expected behaviour**
Return info about the JSON RPC request

**Platform and build**
* Linux
* 18.04 Bionic
* BEAM Build number: latest binaries in the downloads page

**Configuration, log, memory dump files (if applicable)**
Add relevant files. The filenames and locations are described here: https://github.com/BeamMW/beam/wiki/Folder-and-file-locations

**Log file(s) (if applicable)**
```
E 2019-01-09.14:53:20.867 on_new_message int(type)=0 ret=0
D 2019-01-09.14:53:22.243 +peer 127.0.0.1:40868
D 2019-01-09.14:53:22.243 on_stream_accepted
I 2019-01-09.14:53:22.244 got POST / HTTP/1.1
E 2019-01-09.14:53:22.244 json parse: [json.exception.parse_error.101] parse error at 1: syntax error - invalid lit
eral; last read: 'P'
POST / HTTP/1.1
I 2019-01-09.14:53:22.244 stream corrupted
```
**Screenshots (if applicable)**
http://prntscr.com/m4ygmd

**Comment by gingervik** [comment]
hi @CD0x23 
our wallet-api weas not released yet. so there are a lot of bugs and problems, we are working on it.
Please, wait for official release.
Thank you
