### ISSUE TITLE
Return empty Kernel_id if transaction was failed or cancelled

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#320]
When the transaction was failed or cancelled kernel_id looks incorrect in transaction info
![image](https://user-images.githubusercontent.com/44496108/50909661-5b5ea280-143d-11e9-9a6b-d3974426e8cb.png)
![image](https://user-images.githubusercontent.com/44496108/50910077-2141d080-143e-11e9-83f9-a062697a119f.png)

**Comment by gingervik** [comment]
already fixed
