### ISSUE TITLE
Wallet API - successfully validates an address with a letter g, which isn't a hex character.

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#332]

**Comment by nesbox** [comment]
Vadim Grigoruk, [11.01.19 11:58]
[In reply to Aleš Grm]
Hi, just checked the address you provided 118dca231ba9838f82ae51127d8d8332c9542bdbe82305488e795cdc7add719ceg with validate_address api and it return false, as invalid address

Aleš Grm, [11.01.19 11:59]
Ok thanks
