### ISSUE TITLE
Config files sometimes disappear for UI and Cli wallets and node

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#333]
When user installs wallet or node not on default folder config files sometimes disappear
![photo_2019-01-11_10-29-37](https://user-images.githubusercontent.com/44496108/51020482-bef8e500-158f-11e9-8d32-ab9c6857cff5.jpg)

**Comment by Sergei-Beam** [comment]
Reproduced 
Steps:
- run local node or UI wallet on port 10005
- create new or restore UI Wallet on a specific folder on the same port=10005
- when "Connection error" pop-up appeared click "change settings"
Actual: Config and sometimes other files on folder disappears
![photo_2019-05-16_12-39-36](https://user-images.githubusercontent.com/44496108/57843909-b9c6d380-77d7-11e9-8aae-75a11bf523eb.jpg)
![photo_2019-05-16_12-39-41](https://user-images.githubusercontent.com/44496108/57843911-ba5f6a00-77d7-11e9-9702-8c86ae1036b6.jpg)

**Comment by gingervik** [comment]
Resolution:
if wallet cannot be created we should remove only wallet.db, node.db and settings.ini (all files which will be re-created).
All other files we should not delete

**Comment by gingervik** [comment]
checked
