### ISSUE TITLE
Sending to address generated in Receive screen without closing it is NOT possible.

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#334]
**Bug description**
There are two wallets: Wallet A and Wallet B. Both are running on different remote nodes. In Wallet B  the receive screen screen is open. The address is generated there. This address is copied without closing the Receive window. This address is used to send Beams from Wallet A to Wallet B.
As a result the transaction is stuck in "In Progress" in Wallet A.
Restarting of Wallet B doesn't always help (seen different cases) and most often this transaction stays in "In Progress" forever. 
When the Receive screen is closed and a new transaction is made to the same address - then it's going well and appear as "Confirming" on both sides.
Still, despite the fact that the new transaction succeeds, the old one which used the same address is still in "In Progress" status. Even after the restart of Wallet B. See the screenshots, video and the logs attached below.

**To Reproduce**
Steps to reproduce the behaviour:
Preconditions: Wallet A and Wallet B are installed and running on the remote nodes from the official mainnet list of nodes.
1. In Wallet B open the "Receive" screen.
2. Copy the generated address there. Don't close that window.
3. In Wallet A send some coins to Wallet B using the address above.

**Current behaviour**
The transaction hangs in "In Progress" status forever.

**Expected behaviour**
Expected: The transaction succeeds.

**Platform and build**
* Windows
* 10 x64
* mainnet, 3976.

**Log file(s)**
[receiver logs.zip](https://github.com/BeamMW/beam/files/2748876/receiver.logs.zip)
[sender logs.zip](https://github.com/BeamMW/beam/files/2748877/sender.logs.zip)

**Screenshots, videos**
![bug](https://user-images.githubusercontent.com/41323026/51024124-b86f6b00-1599-11e9-96d4-4f8a2688ae3d.png)
[address not activated for receiving money.zip](https://github.com/BeamMW/beam/files/2748885/address.not.activated.for.receiving.money.zip)

**Comment by gingervik** [comment]
duplicate

**Comment by gingervik** [comment]
кreproduced in BB 2.0

**Comment by gingervik** [comment]
the same issue when receiver did not close receive tab and restarted wallet.
Sender - waiting for receiver
receiver - receiving

**Comment by gingervik** [comment]
would not be fixed
