### ISSUE TITLE
Address in Receive screen is not saved straight away when generated

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#335]
**Bug description**
When the Receive screen is open, the address that is generated is not being either listened to or saved as active addresses straight away. In order to make it active - the user needs to go to some other tab or close the Receive window.

**To Reproduce**
Steps to reproduce the behaviour:
Preconditions: A wallet is installed and running.
1. Open the Receive screen.
2. Save the generated address somewhere, but do not close the Receive window.
3.  Close the wallet.
4. Run the wallet again.
5. Check if the generated address was saved by going to Contacts > My Active Addresses.

**Current behaviour**
The address was not saved.

**Expected behaviour**
The address was saved.

**Platform and build**
* Windows
* 10 x64
* mainnet, 3976

**Comment by Aleksandr-Starun** [comment]
Fixed at 086033166232e829d4709f1d230d9b9a735a0676 (Restored fix from adbd3b1e1445456ff7f0fd60753ef8954b09d477 (fixed ui crash))

**Comment by jurijakimuk** [comment]
Works OK, tested on master, 4146, master, Win x64
