### ISSUE TITLE
Empty lines of addresses and contacts can be dragged over the columns' names

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#337]
**Bug description**
In the Addresses screen the empty lines that have a lighter color can hide the columns' names if dragged over them.

**To Reproduce**
Steps to reproduce the behaviour:
Preconditions: A wallet is created and running.
1. Navigate to the Addresses screen.
3. Left click somewhere on the list of addresses, don't release the mouse button.
4. Drag the list up so the empty records cover the columns' names.

**Current behaviour**
The lighter empty lines cover the names of the columns.

**Expected behaviour**
Not specified exactly, but this doesn't look normal.
Suggestions:
The lighter empty lines do NOT cover the names of the columns, just like the darker ones.
OR
Get rid of the default empty lines if they don't contain any data. Only display a line in the table if a new record is created. 

**Notes**
Reproducible for both Addresses and Contacts tabs.
Reproducible for those empty lines only that have a lighter color.
Looks like an issue with priority of the object layers in the screen.

**Platform and build**
* Windows
* 10 x64
* 4101, masternet

**Screenshot and video**
Add screenshots that illustrate a problem you've found.
![image](https://user-images.githubusercontent.com/41323026/51032242-4eae8b80-15b0-11e9-8f4f-a92958b23bff.png)
![image](https://user-images.githubusercontent.com/41323026/51033038-1a889a00-15b3-11e9-83ab-808b43e7d94a.png)

[drag the list.zip](https://github.com/BeamMW/beam/files/2749475/drag.the.list.zip)

**Comment by jurijakimuk** [comment]
The same bug is seen in the wallet.db migration screen:
Zipped video: [wallet db screen.zip](https://github.com/BeamMW/beam/files/2754220/wallet.db.screen.zip)

**Comment by gingervik** [comment]
irrelevant
