### ISSUE TITLE
Two transactions from pools to wallet are failed under some unknowable bugs

### ISSUE THREAD

**Issue by apqqaaa** [BeamMW/beam#341]
**Bug title**
Two transactions from pools to wallet are failed under some unknowable bugs

**Bug description**
I was mining BEAM in beepool in the last month. Two transactions were confirmed in beepools state that with the Blockchain height, as show in picture.

![image](https://user-images.githubusercontent.com/15520098/51073775-eb585280-16b0-11e9-8cea-69e0fd7b1ea7.png) Two confirmed..

![image](https://user-images.githubusercontent.com/15520098/51073781-f9a66e80-16b0-11e9-9959-84bc8b9c2929.png)26723ad88aa2794cd38fb6f565b3f93f447cd2eadad94fc9c53c04b9ce2b46da

![image](https://user-images.githubusercontent.com/15520098/51073783-ff9c4f80-16b0-11e9-9066-50a1132602a5.png)18a8b827c3b1d38252d3293c7f1be2884c6374b7954056670d01e7af8e13524b

The confusing things happened... This is show in one of my computers with same wallet
![image](https://user-images.githubusercontent.com/15520098/51073810-73d6f300-16b1-11e9-8298-fc6f647f99d2.png)
![image](https://user-images.githubusercontent.com/15520098/51073828-a2ed6480-16b1-11e9-8ae2-c1ec9cdf54d3.png)

Than i think the wallet balances are wrong and that i restored it by the words.
![image](https://user-images.githubusercontent.com/15520098/51073842-e9db5a00-16b1-11e9-8e69-0620a6dd189e.png)

Two beepool transactions had never show in the wallet in high 8113 and 11030
8113： id 18a8b827c3b1d38252d3293c7f1be2884c6374b7954056670d01e7af8e13524b
11030：id 26723ad88aa2794cd38fb6f565b3f93f447cd2eadad94fc9c53c04b9ce2b46da

Two transactions are show in blockchain and never show in my wallet.
Why???? 

The 8113 high shows this in my wallet..... i can't understand why it is spent. than 11030 never shows again after i restore my wallet.
![image](https://user-images.githubusercontent.com/15520098/51073942-d4b2fb00-16b2-11e9-842c-96d4e7166807.png)

**Platform and build**
* Windows
* BEAM Build number :1.0.3976

**Comment by apqqaaa** [comment]
dev????

**Comment by gingervik** [comment]
heloo @apqqaaa 
Seems like you are using two wallet with the same seed, right?

**Comment by apqqaaa** [comment]
@gingervik yes at that time but after that I tried to restore my wallet the balance are wrong

**Comment by gingervik** [comment]
@apqqaaa We ask user do not use several copies of one wallet.
At the current implementation each wallet.db file should be managed by only a single wallet instance. Any case involving manual transfer of the wallet database is not supported.

Seems loke one of your wallets spent coins

**Comment by apqqaaa** [comment]
@gingervik yes, but i was spent 16.1656 in this computer
![image](https://user-images.githubusercontent.com/15520098/51112967-7b2a0800-183b-11e9-808f-920ae3ce9c7b.png)
and that i don't know why happened in there 
![image](https://user-images.githubusercontent.com/15520098/51112995-8e3cd800-183b-11e9-8954-f750de06f97f.png)

anyone don't make senses

**Comment by gingervik** [comment]
@apqqaaa it's not the same utxo

**Comment by apqqaaa** [comment]
@gingervik  but it is the same wallet that restore by the same words.
today 2019-01-14 i updated my wallet, the 16.1656 are shows up.
![image](https://user-images.githubusercontent.com/15520098/51113233-55e9c980-183c-11e9-836c-21efba44009d.png)
but still can't find the 16.2577 balance           explore trade id :
18a8b827c3b1d38252d3293c7f1be2884c6374b7954056670d01e7af8e13524b

![image](https://user-images.githubusercontent.com/15520098/51113289-7fa2f080-183c-11e9-8549-e594086c03a1.png)

**Comment by gingervik** [comment]
I can recommend you to restore your wallet and check your balance. But be careful, during restore you will lost all your transactions' history and addresses
