### ISSUE TITLE
QR code for address should be available in Address book also

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#342]
Users want to be able to use QR code for "never" expired addresses several times. Not only when they click on Receive for first time
@sasha-abramovich please, provide design

**Comment by sasha-abramovich** [comment]
I like it! 
@alexandrashelenkova should we have some menu like "show QR code" for every address? (same applies for mobile).

**Comment by sasha-abramovich** [comment]
PS: not urgent whatsoever.

**Comment by sasha-abramovich** [comment]
@kaminskyelina we probably need that functionality in mobile wallets. Please open respective tasks for @alexandrashelenkova. We can prioritise it together later.

**Comment by gingervik** [comment]
Duplicate of #629
