### ISSUE TITLE
Wallet cannot wake-up quickly after Locking screen

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#347]
Wallet with running local node
STR:
- run wallet
- select lock screen in 5 minutes
- wait before scree is locked
- enter password
Actual: wallet is loading too long. At that time there is 0 balance and no transactions, heihgt and else.
If user at this momet changes from 5 min to never - everythig is appeared

**Comment by jurijakimuk** [comment]
Tested on 4255, masternet. Works OK,
