### ISSUE TITLE
Balance is not updated

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#348]
Steps:
- create 2 UI wallets:
1st connected to Random node
2nd local node via UI
- generate the address on 2nd wallet
- send the transaction from 1st to 2nd with all available amount
Actual: Balance doesn't update
Expected: Balance should be updated

Sender's log:
[beam_ui_19_01_16_17_17_50.log](https://github.com/BeamMW/beam/files/2765151/beam_ui_19_01_16_17_17_50.log)

Receiver's log:
[beam_ui_19_01_16_16_00_32.log](https://github.com/BeamMW/beam/files/2765152/beam_ui_19_01_16_16_00_32.log)

**Comment by gingervik** [comment]
checked
