### ISSUE TITLE
What part of appdata needs to be backed up?

### ISSUE THREAD

**Issue by gaia** [BeamMW/beam#349]
To restore the wallet from a backup, I need to backup all the files in folders in appdata except

tempmb_*
logs/*
cache/*

Is this correct?

**Comment by gingervik** [comment]
@gaia you need only wallet.db

**Comment by gaia** [comment]
i have plenty of backup space and would like to avoid having to download the chain again. do I need those three folders to restore the chain from the point of last backup?

sorry, i should have been more specific. i don't want to restore just the chain.

**Comment by gingervik** [comment]
@gaia in this case you need
wallet.db
node.db
tempmb_*
