### ISSUE TITLE
No sorting in the Contacts tab

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#354]
<p><strong>Bug description</strong><br>Sorting functionality is missing in the Addresses &gt; Contacts tab.</p><p><strong>To Reproduce</strong><br>Precondition: A desktop wallet is installed and running.</p><ol><li>Navigate to Addresses.</li><li>Select the Contacts tab.</li><li>Try to sort the records in the list by clicking on the column headers.</li></ol><p><strong>Current behaviour</strong><br>Sorting doesn&#39;t work.</p><p><strong>Expected behaviour</strong><br>The records are sorted respectively to the chosen column.</p><p><strong>Platform and build</strong></p><ul><li>Windows</li><li>10 x64</li><li>4185, mainnet branch</li></ul><p>**Screenshots (if applicable)** ![image](https://user-images.githubusercontent.com/41323026/51308072-55c31700-1a52-11e9-8280-d7c148e1468a.png)</p>

**Comment by gingervik** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D9. Do not remove or edit.` [D9](https://beam.testquality.com/project/5267/result/1067087/defect/3815)

**Comment by gingervik** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D10. Do not remove or edit.` [D10](https://beam.testquality.com/project/5267/result/1067088/defect/3816)

**Comment by gingervik** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D12. Do not remove or edit.` [D12](https://beam.testquality.com/project/5267/result/1252182/defect/4378)

**Comment by gingervik** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D13. Do not remove or edit.` [D13](https://beam.testquality.com/project/5267/result/1252183/defect/4379)

**Comment by alexandrashelenkova** [comment]
Design is here https://zpl.io/amyZDDK

**Comment by Roberrtt** [comment]
checked
