### ISSUE TITLE
Ubuntu cli wallet failed to transfer to windows gui wallet

### ISSUE THREAD

**Issue by whothinkyouare** [BeamMW/beam#358]
When I trans some beams from cli wallet to gui wallet,I found cli transaction status is always "sending",gui wallet has nothing received.Cli and gui are two different wallets,and I'm sure the receive address is right.
![bug_report](https://user-images.githubusercontent.com/46782213/51317966-f2f26f80-1a93-11e9-9568-b6e9da4bd82f.png)

**Comment by gingervik** [comment]
hi @whothinkyouare 
did you use node parameter when sending? can you send us your logs and examples of used commands?

**Comment by gingervik** [comment]
can not reproduce now.
no user response for 21 days
