### ISSUE TITLE
UI wallet crashes if logs folder  don't exist in the system folder 

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#359]
Steps:
* go to C:\Users{user name}\AppData\Local
* delete Beam Wallet folder if it exists
* install the Beam Wallet into another place than default
* go to folder where wallet was installed and filled in the appdata parameter
* save
* try to run wallet
Actual: Wallet crashes 
Expected: Wallet successfully started

**Comment by gingervik** [comment]
checked
