### ISSUE TITLE
The sum in error message must include a fee

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#360]
**Bug description**
When sending UTXO's and there are no available funds - the error message that shows the available amount of funds does not take into accout the fee.

**To Reproduce**
Preconditions: 
A desktop wallet is installed and running.
There are some funds in the wallet.

1. Navigate to the Send screen.
2. Enter the amount that is slightly higher than available and a fee.
3. Check the amount specified in the error message below the entered sum.

**Current behaviour**
The fee is not taken into account.

**Expected behaviour**
The fee is taken into account.

**Platform and build**
* Windows
* 10 x64
* 4193 masternet

**Screenshots (if applicable)**
![actual_amount](https://user-images.githubusercontent.com/41323026/51324099-e3b2f800-1a7a-11e9-84af-a4543d9175b5.png)
![error_amount](https://user-images.githubusercontent.com/41323026/51324111-e877ac00-1a7a-11e9-8b69-ceb739b4a36d.png)

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova please provide a screenshot on how it should be done.

**Comment by sasha-abramovich** [comment]
suggested wording so far: 
_Insufficient funds: you would need XXX groth to complete the transaction._

**Comment by alexandrashelenkova** [comment]
Here are some ideas that we might have use in the future
var 1
zpl.io/boKJnpZ
zpl.io/a3grZAY
zpl.io/2vKjLR7

var 2
zpl.io/bldO4KG
zpl.io/awW5BzM
zpl.io/29oGgmy

**Comment by jurijakimuk** [comment]
@sasha-abramovich Please see the screenshot below and decide how we display the amount in the warning message: 
![image](https://user-images.githubusercontent.com/41323026/52262830-9ec60700-293e-11e9-90f7-79d632cb5315.png)
**8_500_000_010 groths** or  **85 beams 10 groths** ?
Thanks.

**Comment by sasha-abramovich** [comment]
When the amount is more than 5 digits groths please use beams - the devs should be aware of that "agreement"  :)

**Comment by jurijakimuk** [comment]
@anatolse  Anatol, please implement the logic of how the amount in the warning message is displayed. **The amount up to 99999 groths is displayed in groths**, e.g. "Insufficient funds: you would need 99999 groths to complete the transaction." _(for 99999  groths)_ or "Insufficient funds: you would need 22 groths to complete the transaction." _(for 22 groths)_
**The amount more than 99999 groths is displayed in beams**, e.g. "Insufficient funds: you would need 0.01000055 beams to complete the transaction." _(for 1000055 groths)_ or "Insufficient funds: you would need 2.00204444 beams to complete the transaction." _(for 200204444 groths)_

**Comment by jurijakimuk** [comment]
Works OK, tested on 4357, master
