### ISSUE TITLE
Mac GUI wallet slows mining when looses focus

### ISSUE THREAD

**Issue by dirspb** [BeamMW/beam#365]
**Mac GUI wallet slows mining when looses a focus**

**Bug description**
macOs starts throttling a CPU if mining process is in background.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run Mac GUI wallet
2. Turn on mining
3. Switch to any other application

**Current behaviour**
After about 1 minutes, macOS slows down CPU and stops fans

**Expected behaviour**
miner keep running with maximum CPU & fan speed 

**Platform and build**
* Macbook Pro 13" 2015
* MacOs 10.14.2
* beam 1.1.1494

**Solution**
`sudo sysctl debug.lowpri_throttle_enabled=0`
http://osxdaily.com/2016/04/17/speed-up-time-machine-by-removing-low-process-priority-throttling/

**Comment by gingervik** [comment]
Hi @dirspb 
CPU mining is not very effective and will be removed in next release
https://github.com/BeamMW/beam/issues/361
