### ISSUE TITLE
agile-atom-1.1.4194: funds no longer safu

### ISSUE THREAD

**Issue by hammuh1911** [BeamMW/beam#367]
I upgraded to the latest wallet agile-atom-1.1.4194 from the previous version on  Ubuntu 18.04. Things seemingly worked okay until I received payment from a pool. Sometime after that payment, all of the previously received transactions became "failed" and my available balance is now a lot lower than it should be. See attached screenshot.
![screenshot from 2019-01-18 22-12-52](https://user-images.githubusercontent.com/33618375/51421680-c3b13080-1b6f-11e9-8277-56982a3febb8.png)
I 2019-01-19.01:10:22.904 [160b11d0ee4e49d9814cfffcef198ae7] Transaction expired. Current height: 22636, max kernel height: 21787
E 2019-01-19.01:10:22.904 [160b11d0ee4e49d9814cfffcef198ae7] Failed. Transaction has expired
I 2019-01-19.01:10:22.936 [160b11d0ee4e49d9814cfffcef198ae7] Transaction failed. Rollback...
D 2019-01-19.01:10:22.953 Received PeerSig:	9d15802fa86db09e
I 2019-01-19.01:10:23.013 Get proof for kernel: 65e339141f80b190
I 2019-01-19.01:10:23.013 [16efafe7f3cc419a8f10a44931edee1b] Transaction expired. Current height: 22636, max kernel height: 10985
E 2019-01-19.01:10:23.014 [16efafe7f3cc419a8f10a44931edee1b] Failed. Transaction has expired
I 2019-01-19.01:10:23.039 [16efafe7f3cc419a8f10a44931edee1b] Transaction failed. Rollback...
D 2019-01-19.01:10:23.058 Received PeerSig:	9c50aeeff622a405
I 2019-01-19.01:10:23.112 Get proof for kernel: 3d617df8e9841289
I 2019-01-19.01:10:23.113 [1c83003e93f64c689521206e62e6c8f1] Transaction expired. Current height: 22636, max kernel height: 18999
E 2019-01-19.01:10:23.113 [1c83003e93f64c689521206e62e6c8f1] Failed. Transaction has expired
I 2019-01-19.01:10:23.136 [1c83003e93f64c689521206e62e6c8f1] Transaction failed. Rollback...
D 2019-01-19.01:10:23.154 Received PeerSig:	721e8f10f70ba01c
I 2019-01-19.01:10:23.216 Get proof for kernel: 21ced296c3c8a761
I 2019-01-19.01:10:23.217 [1db77ff8076b4d2c95c09486615842ae] Transaction expired. Current height: 22636, max kernel height: 17628
E 2019-01-19.01:10:23.218 [1db77ff8076b4d2c95c09486615842ae] Failed. Transaction has expired
I 2019-01-19.01:10:23.241 [1db77ff8076b4d2c95c09486615842ae] Transaction failed. Rollback...
D 2019-01-19.01:10:23.259 Received PeerSig:	48ff4070fed54c12
I 2019-01-19.01:10:23.312 Get proof for kernel: 71a0240f2fda9d0d
I 2019-01-19.01:10:23.313 [1f4f40338ef8487b8da924f2156e394a] Transaction expired. Current height: 22636, max kernel height: 7972
E 2019-01-19.01:10:23.313 [1f4f40338ef8487b8da924f2156e394a] Failed. Transaction has expired
I 2019-01-19.01:10:23.345 [1f4f40338ef8487b8da924f2156e394a] Transaction failed. Rollback...
D 2019-01-19.01:10:23.359 Received PeerSig:	8ce083bf641dc622
I 2019-01-19.01:10:23.410 Get proof for kernel: 0b30787c3cfd95b2
I 2019-01-19.01:10:23.411 [1f927537d7c44f15b6b998766c0f80b2] Transaction expired. Current height: 22636, max kernel height: 12447
E 2019-01-19.01:10:23.411 [1f927537d7c44f15b6b998766c0f80b2] Failed. Transaction has expired
I 2019-01-19.01:10:23.440 [1f927537d7c44f15b6b998766c0f80b2] Transaction failed. Rollback...
D 2019-01-19.01:10:23.457 Received PeerSig:	b56b8d5980786ac6
I 2019-01-19.01:10:23.514 Get proof for kernel: deadd235304e7547
I 2019-01-19.01:10:23.515 [356bdda7963a40118b5f6dd027f67151] Transaction expired. Current height: 22636, max kernel height: 14184
E 2019-01-19.01:10:23.515 [356bdda7963a40118b5f6dd027f67151] Failed. Transaction has expired
I 2019-01-19.01:10:23.536 [356bdda7963a40118b5f6dd027f67151] Transaction failed. Rollback...
D 2019-01-19.01:10:23.551 Received PeerSig:	457481f6eaef5a93
I 2019-01-19.01:10:23.596 Get proof for kernel: e18331bc06a3565f
I 2019-01-19.01:10:23.597 [592df40ee6dc415c8adbc2a09d4e3f02] Transaction expired. Current height: 22636, max kernel height: 14071
E 2019-01-19.01:10:23.597 [592df40ee6dc415c8adbc2a09d4e3f02] Failed. Transaction has expired
I 2019-01-19.01:10:23.619 [592df40ee6dc415c8adbc2a09d4e3f02] Transaction failed. Rollback...
D 2019-01-19.01:10:23.631 Received PeerSig:	1ab8514f04a2b9ef
I 2019-01-19.01:10:23.689 Get proof for kernel: da2536c2c6a676d6
I 2019-01-19.01:10:23.691 [842c3a27cb8749799464869a282b3953] Transaction expired. Current height: 22636, max kernel height: 13881
E 2019-01-19.01:10:23.691 [842c3a27cb8749799464869a282b3953] Failed. Transaction has expired
I 2019-01-19.01:10:23.712 [842c3a27cb8749799464869a282b3953] Transaction failed. Rollback...
D 2019-01-19.01:10:23.725 Received PeerSig:	b440a1e14180ce2b
I 2019-01-19.01:10:23.770 Get proof for kernel: a566fc07122790be
I 2019-01-19.01:10:23.771 [89f92d7233e543a3ad07484e7ced50f7] Transaction expired. Current height: 22636, max kernel height: 16714
E 2019-01-19.01:10:23.771 [89f92d7233e543a3ad07484e7ced50f7] Failed. Transaction has expired
I 2019-01-19.01:10:23.790 [89f92d7233e543a3ad07484e7ced50f7] Transaction failed. Rollback...
D 2019-01-19.01:10:23.802 Received PeerSig:	c4fe27f592f2e110
I 2019-01-19.01:10:23.842 Get proof for kernel: 41f3515bdee1bf3a
I 2019-01-19.01:10:23.842 [8d220f9f0e4043a6aec101bde46d1612] Transaction expired. Current height: 22636, max kernel height: 18162
E 2019-01-19.01:10:23.843 [8d220f9f0e4043a6aec101bde46d1612] Failed. Transaction has expired
I 2019-01-19.01:10:23.866 [8d220f9f0e4043a6aec101bde46d1612] Transaction failed. Rollback...
D 2019-01-19.01:10:23.879 Received PeerSig:	e984b909dbc90406
I 2019-01-19.01:10:23.936 Get proof for kernel: 46673adf832f9331
I 2019-01-19.01:10:23.936 [948249e78b2d4616949f2762764cfcfd] Transaction expired. Current height: 22636, max kernel height: 16190
E 2019-01-19.01:10:23.936 [948249e78b2d4616949f2762764cfcfd] Failed. Transaction has expired
I 2019-01-19.01:10:23.959 [948249e78b2d4616949f2762764cfcfd] Transaction failed. Rollback...
D 2019-01-19.01:10:23.973 Received PeerSig:	6d6aa048a0f86537
I 2019-01-19.01:10:24.030 Get proof for kernel: 3c159f5301417f53
I 2019-01-19.01:10:24.030 [96896fc2f0634984b6433c0cb60fd627] Transaction expired. Current height: 22636, max kernel height: 20503
E 2019-01-19.01:10:24.031 [96896fc2f0634984b6433c0cb60fd627] Failed. Transaction has expired
I 2019-01-19.01:10:24.051 [96896fc2f0634984b6433c0cb60fd627] Transaction failed. Rollback...
D 2019-01-19.01:10:24.063 Received PeerSig:	444306258cab3c79
I 2019-01-19.01:10:24.102 Get proof for kernel: 27f6dba7716860bb
I 2019-01-19.01:10:24.102 [9f4a86c14af749b4af242ad6026d2741] Transaction expired. Current height: 22636, max kernel height: 8116
E 2019-01-19.01:10:24.103 [9f4a86c14af749b4af242ad6026d2741] Failed. Transaction has expired
I 2019-01-19.01:10:24.122 [9f4a86c14af749b4af242ad6026d2741] Transaction failed. Rollback...
D 2019-01-19.01:10:24.134 Received PeerSig:	9a011bbef3110fca
I 2019-01-19.01:10:24.176 Get proof for kernel: 61f0a64714daee7f
I 2019-01-19.01:10:24.176 [9f7dd483ac95494a9e633cc92670db26] Transaction expired. Current height: 22636, max kernel height: 15310
E 2019-01-19.01:10:24.176 [9f7dd483ac95494a9e633cc92670db26] Failed. Transaction has expired
I 2019-01-19.01:10:24.196 [9f7dd483ac95494a9e633cc92670db26] Transaction failed. Rollback...
D 2019-01-19.01:10:24.209 Received PeerSig:	29d258e0c1545db5
I 2019-01-19.01:10:24.248 Get proof for kernel: 701d4677ac2e4116
D 2019-01-19.01:10:24.260 Received PeerSig:	af93e86aa0f93399
I 2019-01-19.01:10:24.310 Get proof for kernel: 5d2b96b7956184fb
I 2019-01-19.01:10:24.311 [abf2d4dec5e346678db77edbda913c42] Transaction expired. Current height: 22636, max kernel height: 20309
E 2019-01-19.01:10:24.311 [abf2d4dec5e346678db77edbda913c42] Failed. Transaction has expired
I 2019-01-19.01:10:24.331 [abf2d4dec5e346678db77edbda913c42] Transaction failed. Rollback...
D 2019-01-19.01:10:24.344 Received PeerSig:	2721854a7c0f3eb5
I 2019-01-19.01:10:24.384 Get proof for kernel: de4ea949228c1b2a
I 2019-01-19.01:10:24.385 [add095357ce6474bbff35d21a3e3c218] Transaction expired. Current height: 22636, max kernel height: 9571
E 2019-01-19.01:10:24.385 [add095357ce6474bbff35d21a3e3c218] Failed. Transaction has expired
I 2019-01-19.01:10:24.407 [add095357ce6474bbff35d21a3e3c218] Transaction failed. Rollback...
D 2019-01-19.01:10:24.419 Received PeerSig:	2c4c2a4834f06dd1
I 2019-01-19.01:10:24.455 Get proof for kernel: 276025ca058be377
I 2019-01-19.01:10:24.457 [b4854b38352e4418ae43ae206dc3c3a3] Transaction expired. Current height: 22636, max kernel height: 19710
E 2019-01-19.01:10:24.457 [b4854b38352e4418ae43ae206dc3c3a3] Failed. Transaction has expired
I 2019-01-19.01:10:24.477 [b4854b38352e4418ae43ae206dc3c3a3] Transaction failed. Rollback...
D 2019-01-19.01:10:24.489 Received PeerSig:	b94886477da418ba
I 2019-01-19.01:10:24.528 Get proof for kernel: 486983ecb5a1c08e
I 2019-01-19.01:10:24.528 [cebcce36a90844cca88258cd3a221f2a] Transaction expired. Current height: 22636, max kernel height: 19330
E 2019-01-19.01:10:24.529 [cebcce36a90844cca88258cd3a221f2a] Failed. Transaction has expired
I 2019-01-19.01:10:24.547 [cebcce36a90844cca88258cd3a221f2a] Transaction failed. Rollback...
D 2019-01-19.01:10:24.559 Received PeerSig:	62a230393776dfd3
I 2019-01-19.01:10:24.610 Get proof for kernel: e7ba6337ca871d0a
I 2019-01-19.01:10:24.612 [e209642c056544049f78c97e66035604] Transaction expired. Current height: 22636, max kernel height: 17192
E 2019-01-19.01:10:24.613 [e209642c056544049f78c97e66035604] Failed. Transaction has expired
I 2019-01-19.01:10:24.631 [e209642c056544049f78c97e66035604] Transaction failed. Rollback...
D 2019-01-19.01:10:24.643 Received PeerSig:	1e050c4067f076b8
I 2019-01-19.01:10:24.679 Get proof for kernel: 101eb910b535d4de
I 2019-01-19.01:10:24.680 [e3d487fadd8b42d98d9aa73ee644ef1b] Transaction expired. Current height: 22636, max kernel height: 11769
E 2019-01-19.01:10:24.680 [e3d487fadd8b42d98d9aa73ee644ef1b] Failed. Transaction has expired
I 2019-01-19.01:10:24.698 [e3d487fadd8b42d98d9aa73ee644ef1b] Transaction failed. Rollback...
D 2019-01-19.01:10:24.708 Received PeerSig:	8f281aef706c75fd
I 2019-01-19.01:10:24.744 Get proof for kernel: 36e97ae7742141f7
I 2019-01-19.01:10:24.745 [ec310e8b50ad4f209f10f2a49fbd388e] Transaction expired. Current height: 22636, max kernel height: 15143
E 2019-01-19.01:10:24.745 [ec310e8b50ad4f209f10f2a49fbd388e] Failed. Transaction has expired
I 2019-01-19.01:10:24.762 [ec310e8b50ad4f209f10f2a49fbd388e] Transaction failed. Rollback...
D 2019-01-19.01:10:24.772 Received PeerSig:	7656abd8485089fd
I 2019-01-19.01:10:24.803 Get proof for kernel: 1dd02b4280796b4f
I 2019-01-19.01:10:24.804 [edd0e7956fbb4b76a933401d575f6fb7] Transaction expired. Current height: 22636, max kernel height: 4329
E 2019-01-19.01:10:24.804 [edd0e7956fbb4b76a933401d575f6fb7] Failed. Transaction has expired
I 2019-01-19.01:10:24.827 [edd0e7956fbb4b76a933401d575f6fb7] Transaction failed. Rollback...
D 2019-01-19.01:10:24.840 Received PeerSig:	9d85ed4bdf9a8447
I 2019-01-19.01:10:24.872 Get proof for kernel: 8f324e7cc36516ed
I 2019-01-19.01:10:24.872 [ef516edc57d44a379f2c5f92323ae331] Transaction expired. Current height: 22636, max kernel height: 16075
E 2019-01-19.01:10:24.873 [ef516edc57d44a379f2c5f92323ae331] Failed. Transaction has expired
I 2019-01-19.01:10:24.901 [ef516edc57d44a379f2c5f92323ae331] Transaction failed. Rollback...

**Comment by markwpirie** [comment]
I have exactly same issue.

**Comment by MiWCryptoCurrency** [comment]
My understanding is this is a display bug -- there was a premature confirmed transaction expiry which is clearing out the tx so they report failed and rolled back . The UTXOs are of course still on the blockchain where you left them safe. I was able to get the tx's to appear as confirmed again by re-migrating from the 1.0.3976 wallet, however I expect they will 'expire' again when it kicks in.

The recommendations from the team is to stop using this for now and a new wallet that fixes the expiry bug will be out soon.

**Comment by nerdy2188** [comment]
All of my previously confirmed transactions are all now showing as failed, except the 2nd to last transaction which is still completed. The newest transaction shows failed in wallet but still showing as confirming for the last 9 hours on the poolside. Only the 1 completed transaction shows up on the UTXO interface.

**Comment by MiWCryptoCurrency** [comment]
I can confirm that the latest dev builds of the wallets correct migrate the failed tx's, populate the UTXO set. The scan operation in the wallet is fast, and will correctly identify any transactions marked as failed to completed. Funds were always safe.

**Comment by nerdy2188** [comment]
If i open with 1.1.4194 all failed but one. If i open with 1.0.3976 then everything is correct except it says to check my node configuration. re opened with  1.1.4194 and still fail.

**Comment by gingervik** [comment]
fixed in ver 1.1.4201 and checked
@nerdy2188  @MiWCryptoCurrency @hammuh1911 @markwpirie please, update your wallets and make rescan
