### ISSUE TITLE
Transaction failed

### ISSUE THREAD

**Issue by AlexCryptoFun** [BeamMW/beam#368]
**Transaction receiving failed**
Express the problem in a single concise sentence

**I withdraw from Hotbit exchange and they confirmed the transaction but on my wallet it failed**

**To Reproduce**
Steps to reproduce the behaviour:
1. Run my wallet
2. Did the withdraw from exchange
3. Transaction pending for a while
4. Transaction failed

**Current behaviour**
A clear and concise description of the erroneous behaviour which currently happens.

**Expected behaviour**

**windows 10**
* Windows, Mac, Linux, Android or iOS
* OS version
* BEAM Build number 1.0.3976
![cattura](https://user-images.githubusercontent.com/46840879/51426301-0531f200-1be9-11e9-9515-db3fcd49a69f.JPG)

**Configuration, log, memory dump files (if applicable)**
Add relevant files. The filenames and locations are described here: https://github.com/BeamMW/beam/wiki/Folder-and-file-locations

**Log file(s) (if applicable)**
Add relevant log file(s),  located in the `logs` folder.

**Screenshots (if applicable)**
Add screenshots that illustrate a problem you've found.

**Comment by MiWCryptoCurrency** [comment]
See issue #367 -- no need to worry. Its just an internal accounting display error. The latest development wallet correctly will migrate these 'failed' transactions and a rescan (new option) will update these to completed. Unfortunately there was a logic bug in how the wallet expired transactions. The actual UTXO (the monies) are safe onchain.

**Comment by AlexCryptoFun** [comment]
Let's hope so. I am s big fan and I want to believe that BEAM will revolutionize the crypto world. So all I need to do is to install the new version of the wallet?

**Comment by gingervik** [comment]
fixed in ver 1.1.4201 and checked
@AlexCryptoFun @MiWCryptoCurrency please, update your wallets

**Comment by AlexCryptoFun** [comment]
If I install the new version, the wallet addresses will be different?
Because the exchange support told me not to close my wallet and not to
change my wallet address.

Il giorno Dom 20 Gen 2019, 09:47 Vika Khodichenko <notifications@github.com>
ha scritto:

**Comment by AlexCryptoFun** [comment]
I installed the new wallet but the transaction is still label as failed.

**Comment by AlexCryptoFun** [comment]
> fixed in ver 1.1.4201 and checked
> @AlexCryptoFun @MiWCryptoCurrency please, update your wallets and make rescan

I did and nothing. Still label as failed transaction.

**Comment by AlexCryptoFun** [comment]
> Yes, I also have this problem. Two transactions went from completed to failed. I upgraded the wallet and still showing failed.
> ![image](https://user-images.githubusercontent.com/5732913/51447156-43aed600-1ce9-11e9-94bb-c38dc478d649.png)

In my case the problem was from the exchange. The wallet seems to be ok. The exchange gave me my BEAM back on the exchange wallet. Maybe it is the same for you too.

**Comment by ChrisFrench** [comment]
<img width="945" alt="screen shot 2019-01-23 at 5 55 20 am" src="https://user-images.githubusercontent.com/210848/51611592-7668f200-1ed4-11e9-9f14-f41630b69118.png">
I have the same problem. 

Contacted Hotbit for help. I only bought a little bit but was excited to play around with it test it out

**Comment by AlexCryptoFun** [comment]
The hotbit exchange seems to be un honest one. You have to have patience and to write them every day 😅. Tell them to put your BEAM back on the exchange wallet. It is easier for them.

**Comment by ChrisFrench** [comment]
Hahaha, yea I wrote them I only bought a little bit to test I know the
crypto is only a few weeks old.

I basically assume it is gone Beamed out of existence.
