### ISSUE TITLE
UI/UX - Text “Login to another wallet” is incorrect. Should be “Restore your wallet using seed phrase or create a new wallet”

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/beam#371]
**Bug title**
Text “Login to another wallet” is incorrect. Should be “Restore your wallet using seed phrase or create a new wallet”

![screen shot 2019-01-20 at 11 34 53](https://user-images.githubusercontent.com/45590119/51437466-6f10d100-1ca7-11e9-891a-473a7e61be49.png)

**Comment by alexandrashelenkova** [comment]
"Restore wallet or create a new one"?

**Comment by alexandrashelenkova** [comment]
Text updated
zpl.io/2pne1MM

**Comment by alexandrashelenkova** [comment]
@sasha-abramovich to who I should assign that task?

**Comment by sasha-abramovich** [comment]
assigned :) should be as simple as edit a text file now.

**Comment by Sergei-Beam** [comment]
Checked
