### ISSUE TITLE
Upgrade flow - change request regarding DB selection

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/beam#372]
**Bug title**
There is no need in wallet db selection screen

**Bug description**
There is no need in wallet db selection screen.  It invites user to do silly things. If there is only one wallet, it should be automatically restored. And if there is more than one, the latest should be used. Sophisticated users who know what they are doing will just replace the wallet.db file manually

*Reported by Alex Zaidelson

**Comment by sasha-abramovich** [comment]
I think all we need is "automatic migration" button vs "manual migration" button. Assigning @anatolse to discuss with me :)

**Comment by sasha-abramovich** [comment]
clone of https://github.com/BeamMW/beam/issues/90 ?
