### ISSUE TITLE
Allow wallet to run in background when window closed

### ISSUE THREAD

**Issue by azaidelson** [BeamMW/beam#374]
**Describe the current situation we have**
When user closes the Wallet window, the wallet stops running. This may result in transactions not coing thru (especially if the user sent their address to someone before closing).

**Describe the solution you'd like**
When the user clicks the "x" button on the window, a message box should appear:
Option 1: Ask the user whether to quit or to run in background (default - run in background)
Option 2: Just inform the user that wallet will run in the background

When running in the backrgound, a tray icon should appear in tray (windows/mac), and the icon context menu should have the "Quit" option.

When the user chooses "Quit", she should be notified (with a "don't show me again" that "Please note that if you are expecting any transfers in the coming hours, it is recommended to keep your wallet running" or similar/

**Comment by nerdy2188** [comment]
Option 3: Add minizie on close and minimze to system tray instead of the taskbar  options on the settings tab.
