### ISSUE TITLE
UI Wallet - Rescan Dialog is not clear

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/beam#377]
**Bug title**
Express the problem in a single concise sentence

**Bug description**
Rescan dialog – when clicking rescan, a dialog appears
The dialog asks “are you sure” and only shows a “Yes” button.
The text in the dialog is confusing, does not explain anything. Why should I rescan? What problem does it solve? Will it retrieve my transaction data from the blockchain (how exactly, we don’t store the transaction data?). The text should be updated to answer all those questions.

**Current behaviour**
A clear and concise description of the erroneous behaviour which currently happens.

**Expected behaviour**

* BEAM Build number
1.1.4201

![image](https://user-images.githubusercontent.com/45590119/51437790-95d10680-1cab-11e9-9983-ecfae4847052.png)

**Comment by alexandrashelenkova** [comment]
Okay, links are in my comment above

**Comment by jurijakimuk** [comment]
Tested on 4343, master. Button renamed accordingly.
