### ISSUE TITLE
UI Wallet - Send Screen “Remaining” vs “Change” is not clear

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/beam#378]
**Feature title**
Send Screen “Remaining” vs “Change” is not clear for the user

One option is – change to “Remaining UTXOs” and “Change UTXO”. It may also be good to add a question mark icon with popup tooltip explaining this in more detail like this:

“Remaining UTXOs” – the total sum of all UTXOs that are not involved in creating this transactions. Those funds will be immediately available for other transactions”

“Change UTXO” – the change remaining from the transaction. For each transaction, Beam Wallet chooses one or more Input UTXOs that you own so that the total amount is greater than what you want to send.

The difference between the sum of Input UTXOs and the amount you want to send is the Change. The Change UTXO is not available to you before the transaction is completed. It will appear as “in progress” in your UTXO screen

![image](https://user-images.githubusercontent.com/45590119/51437996-eb5ae280-1cae-11e9-8670-ddd0f1f6856f.png)

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova pure user feedback to consider. I would also add "available" to this information. Somehow.

**Comment by alexandrashelenkova** [comment]
Will consider this idea during Send screen redesign
