### ISSUE TITLE
Not all details filled properly, so the uninstall / reconfigure will look decent on Windows-> Programs and Features

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/beam#380]
**Bug title**
Not all details filled properly, so the uninstall / reconfigure will look decent on Windows-> Programs and Features

**Bug description**
No Beam icon
Name should be Beam Wallet 
Size is missing
Vendor name - Beam Development Limited and not "Beam Vendor"

![photo_2019-01-20 12 57 25](https://user-images.githubusercontent.com/45590119/51438451-f87ad000-1cb4-11e9-99c3-8c1b36ab8981.jpeg)

**Comment by nesbox** [comment]
changed Beam -> Beam Wallet
Beam Vendor -> Beam Development Limited

**Comment by gingervik** [comment]
@jurijakimuk please, check what is done and open separate task in next sprint for the rest

**Comment by jurijakimuk** [comment]
Checked on master, 4632. 
Name and Publisher changed acc. to the changes requested. The rest will be opened in a separate task. Closing.
