### ISSUE TITLE
PGP signatures missing -- cannot verify release

### ISSUE THREAD

**Issue by jonathancross** [BeamMW/beam#387]
**Bug title**
Latest [release agile-atom-4202](https://github.com/BeamMW/beam/releases/tag/agile-atom-4202) does not provide OpenPGP signatures for binaries.

**To Reproduce**
Steps to reproduce the behaviour:
1. Visit https://github.com/BeamMW/beam/releases/tag/agile-atom-4202
2. Follow **Verifying release binaries** instructions.

**Current behaviour**
`.asc` files <s>do not exist</s> are invalid, so binaries cannot be verified.

**Expected behaviour**
`.asc` files should be part of every legitimate release.

**Platform and build**
* Windows, Mac, Linux, Android or iOS
* BEAM Build agile-atom-4202

Edit: asc files are now available, but are invalid.

**Comment by jonathancross** [comment]
@beam-mw  I now see `.asc` files have been [added to the release](https://github.com/BeamMW/beam/releases/tag/agile-atom-4202).

However there is something wrong... these files should only contain a pgp signature which is about 310 bytes or so.

Example command to create the asc files:
```
gpg --detach-sign -o Beam-Wallet-1.1.4202.dmg.asc Beam-Wallet-1.1.4202.dmg
```

**Comment by jonathancross** [comment]
Or these 2 commands to sign **all** files:
```bash
FILEZ=(Beam-Wallet-1.1.4202.deb Beam-Wallet-1.1.4202.dmg Beam-Wallet-1.1.4202.with.gpu.support.deb BeamWallet-1.1.4202.exe BeamWallet-1.1.4202.with.gpu.support.exe linux-beam-node-1.1.4202.tar.gz linux-beam-wallet-cli-1.1.4202.tar.gz mac-beam-node-1.1.4202.tar.gz mac-beam-wallet-cli-1.1.4202.tar.gz win-beam-node-1.1.4202.zip win-beam-wallet-cli-1.1.4202.zip)

for F in ${FILEZ[@]}; do gpg --detach-sign -o ${F}.asc ${F};done
```

**Comment by jonathancross** [comment]
Seems the latest tagged release from @gingervik also has invalid `asc` files which are hundreds of times larger than they should be.

**Comment by vcorem** [comment]
Those asc files are actually encrypted version of the binaries, you can
decrypt with beammw public key (it's a keybase pgp key)

**Comment by jonathancross** [comment]
Hi @vcorem,
A file that is encrypted to a particular PGP public key, can only be decrypted with the _private_ key.  That is the whole point of encryption -- to make sure that only the recipient can access the data.
Why encrypt files that are public, there is no reason to hide information?
What we need is _digitally signed_ files to prove authenticity, encryption has no place here.

**Comment by jonathancross** [comment]
From what I can gather, the `asc` files provided for release `agile-atom-1.2.4419` are signed, ASCII-armored versions of the binaries.  I converted `Beam-Wallet-1.2.4419.dmg.asc` back into `Beam-Wallet-1.2.4419.dmg` however the disk image was corrupted and could not be opened on my MacOS High Sierra system.

Final size of the binary was incorrect:

* Expected size: 17,655,861 bytes
* Actual size: 17,588,505 bytes

The last 2 releases since then don't provide `.asc` files at all.

**Comment by jonathancross** [comment]
[Latest release](https://github.com/BeamMW/beam/releases/tag/api_2.0.4431) finally has proper signatures.

**Comment by jonathancross** [comment]
Hmmm, no signatures have been created yet for the desktop wallet.
I'll reopen this issue until that is taken care of.

**Comment by jonathancross** [comment]
Latest release [testnet_bb_2.0](https://github.com/BeamMW/beam/releases/tag/testnet_bb_2.0) doesn't have any signatures, but @gingervik still included the verification instructions...  `¯\_(ツ)_/¯`

**Comment by gingervik** [comment]
thank you @jonathancross 
verification instructions were removed from testnet release

**Comment by jonathancross** [comment]
![delete-verification-instructions](https://user-images.githubusercontent.com/5115470/54940487-1a016d80-4f2b-11e9-9d0c-089518340ff4.jpg)

**Comment by beam-mw** [comment]
We do not sign testnet releases as of now.
