### ISSUE TITLE
Auto rescan on Beam Wallet start

### ISSUE THREAD

**Issue by larry128** [BeamMW/beam#389]
**Feature title**
Auto rescan on Beam Wallet start

**Describe the current situation we have**
Rescan button is somewhere in the application but there is no clear information about when/why to use it.

**Describe the solution you'd like**
As it seems rescan fixes a plethora of issues commonly encountered by users, the rescanning could be done automatically on wallet start.

**Describe alternatives you've considered (if relevant)**
Make it very clear when it is advisable to do a rescan and move the button to a more prominent place, maybe the transactions page.

**Additional context**
Mr Alexander Zaidelson seems to think this would be a useful feature.
![capture](https://user-images.githubusercontent.com/6809096/51521435-eb7dee00-1e26-11e9-8b48-088285acfadd.PNG)

**Comment by gingervik** [comment]
won't fix
