### ISSUE TITLE
Node protocol error when changing lock screen settings

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#391]
**Bug description**
When lock screen settings are changed and applied - the indicator in the main screen shows "Node protocol error!" In  a few seconds, the status gets back to "online".

**To Reproduce**
Steps to reproduce the behaviour:
Preconditions: A desktop wallet is installed and running.
1. Navigate to Settings.
2. Change lock screen settings, i.e. "never" to "1 minute".
3. Apply the changes.
4. Navigate to the main screen.

**Current behaviour**
The status indicator is showing "Node protocol error!" text for a few seconds than goes "online".

**Expected behaviour**
The status indicator is showing "online".

**Platform and build**
* Windows
* 10 x64
* 4255, masternet

**Log file(s) (if applicable)**
[beam_ui_19_01_22_11_05_46.log](https://github.com/BeamMW/beam/files/2782240/beam_ui_19_01_22_11_05_46.log)

**Video**
[node must not be restarted if lock screen settings changed.zip](https://github.com/BeamMW/beam/files/2782241/node.must.not.be.restarted.if.lock.screen.settings.changed.zip)

**Comment by gingervik** [comment]
cann't reproduce on new design
