### ISSUE TITLE
Testnet-need clear indication for users that differentiates between Testnet and Mainnet

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/beam#392]
**Feature title**
Need clear indication for users that explains that Testnet is only "playing money"

**Describe the current situation we have**
Now when we will manage Testnet in parallel with Mainnet, we need very clear indication for user that he uses Testnet version

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova we need your help here please. We need to visually differentiate between testnet and mainnet software. Therefore, (at least) the following things should be different:
- Wallet icons
- Something in the wallet (for example, background in Testnet should be a bit different)
- Same visual differentiator on the Downloads page (for example, background) 

All the visual differentiators should be consistent with each other (for example, if it's an orange background it should be the same on website, app, mobile wallet and on the icon.

**Comment by alexandrashelenkova** [comment]
Downloads page (testnet) zpl.io/awW5GgD
Wallet screen (testnet) zpl.io/aRWRA5e
App icons are here https://drive.google.com/open?id=1kHB9JXOulXJJtZxlae0Lxh4O_USAkXfL
(changed bg colours a bit more)

**Comment by kaminskyelina** [comment]
Design is ready- reassign on Anatoly for implementation

**Comment by gingervik** [comment]
@roman-strilets please change icon to one with testnet on it, please

**Comment by alexandrashelenkova** [comment]
https://drive.google.com/open?id=1qvI3_6QiR8vHaZ1n6VR8zaVvN0BaUuvp

**Comment by kaminskyelina** [comment]
![image](https://user-images.githubusercontent.com/45590119/52174888-58887080-27a3-11e9-9c1b-bf5bb653dd75.png)

**Comment by gingervik** [comment]
good on windows
bad on Mac

**Comment by gingervik** [comment]
checked on mac
