### ISSUE TITLE
beam-agile-atom-4202 wallet-api validate_address not correct

### ISSUE THREAD

**Issue by bebest2010** [BeamMW/beam#393]
**Bug title**
beam-agile-atom-4202 wallet-api validate_address not correct

**Bug description**
send 	jsonrpc: "2.0",
            id : 12345,
            method:"validate_address",
            params:
            {
            		"address" : "wagagel"
            }
receive 
{ id: 12345,
  jsonrpc: '2.0',
  result: { is_mine: false, is_valid: true } }

but in the version
commit 1e627126a600826eb97b2e43c71df26b457c681a (HEAD -> mainnet, tag: agile-atom-1.1.4194, origin/mainnet)
received 
Received: { id: 12345,
  jsonrpc: '2.0',
  result: { is_mine: false, is_valid: false } }

**Comment by Sergei-Beam** [comment]
checked
