### ISSUE TITLE
Cli Wallet current height is 0

### ISSUE THREAD

**Issue by gutongjiang** [BeamMW/beam#395]
**Bug title**
Current height is 0

**Bug description**
when I run `beam-wallet info`, the current height is always 0

**To Reproduce**
Steps to reproduce the behaviour:
1. Run 'beam-wallet info' 

**Current behaviour**
Current height............0
Current state ID..........c0b80030437f0000
...

**Expected behaviour**
Current height != 0

**Platform and build**
* Linux
* ubuntu16.04
* linux-beam-wallet-cli-1.1.4202

**Screenshots (if applicable)**
`./beam-wallet info`
`I 2019-01-23.15:40:17.252 Rules signature: ed91a717313c6eb0`
`I 2019-01-23.15:40:17.252 starting a wallet...`
`Enter password: ****************`
`I 2019-01-23.15:40:23.025 wallet sucessfully opened...`
`____Wallet summary____`

`Current height............0`
`Current state ID..........c0b80030437f0000`

`Available.................0 groth` 
`Maturing..................0 groth` 
`In progress...............0 groth` 
`Unavailable...............0 groth` 
`Available coinbase .......0 groth` 
`Total coinbase............0 groth` 
`Avaliable fee.............0 groth` 
`Total fee.................0 groth` 
`Total unspent.............0 groth`

**Comment by bebest2010** [comment]
you need connect with beam-node  first

**Comment by gutongjiang** [comment]
@bebest2010 I have connect to the mainnet node: eu-node01.mainnet.beam.mw:8100

**Comment by xMinox** [comment]
I'm running a local node on Linux and it happened to me as well. It's easy to reproduce, just run following:
`./beam-wallet refresh` 
`./beam-wallet info`

Eventually you can fired up `beam-wallet listen`, and wait until it'll sync up with the node. Then running `./beam-wallet info` will show correct height, however, balance and transaction history is still empty.

**Comment by gingervik** [comment]
@gutongjiang hi
do you still have this problem?

**Comment by xMinox** [comment]
I do

**Comment by gingervik** [comment]
@xMinox do you run your node with key_owner param?

**Comment by gingervik** [comment]
long time no response
