### ISSUE TITLE
Problem in Receiving Beam

### ISSUE THREAD

**Issue by TalhaMoazSarwar** [BeamMW/beam#400]
Hello, my friend sent me 1 beam. In his transaction history it is showing completed but in my transaction history it stucked on "Syncing with blockchain" in receiving and then after few hours it shows "Failed". Now that 1 beam is not in my friend's wallet nor in my wallet. how can i get that back. we rescaned our wallets but the condition is same.

**Comment by gingervik** [comment]
hi @TalhaMoazSarwar 
Please, send us your and your friend's log
as I understand, you have the last version, don't you?

**Comment by TalhaMoazSarwar** [comment]
My and My Friends Logs & Transaction Screenshots.
![my](https://user-images.githubusercontent.com/5212429/51835981-cdc9f080-2320-11e9-8cd5-7375d9dccda3.jpg)
![friend](https://user-images.githubusercontent.com/5212429/51835983-ce628700-2320-11e9-8d7c-4ba6f10f5ef5.jpg)
[MY_wallet_19_01_23_18_32_23.log](https://github.com/BeamMW/beam/files/2802896/MY_wallet_19_01_23_18_32_23.log)
[FRIENDS_beam_ui_19_01_23_19_00_40.log](https://github.com/BeamMW/beam/files/2802897/FRIENDS_beam_ui_19_01_23_19_00_40.log)

**Comment by TalhaMoazSarwar** [comment]
I'm waiting for your response for very long..

**Comment by gingervik** [comment]
Hi @TalhaMoazSarwar 
your logs are too small.
it's not enought to investigate your problem
I can recommend you and your friend install the last version of our wallet and do a rescan.
if it does not help you can try to restore your wallet (be carefull you will lost your transaction history and addresses)

**Comment by gingervik** [comment]
@TalhaMoazSarwar hi
do you still have this problem or we can close this ticket?

**Comment by gingervik** [comment]
there is no user's response for more than 20 days. can be closed
