### ISSUE TITLE
Wallet api gets easily stuck when sending large amounts of UTXO

### ISSUE THREAD

**Issue by nesbox** [BeamMW/beam#407]
We need to profile our wallet-api or maybe make it asynchronous

User feedback:
> Jinping Gou, [Jan 24, 2019 at 6:26:37 PM]:
> It gets false and doesn't get any response when fetching over 50 utxos
> 
> especially for mining pools, they have hundreds of utxos. hundreds of transactions need to be sent and processed every day. Since around 10% of transactions being sent will be failed, there comes the need to check status of txs and utxos to reassure and filter unsuccessful ones. This is why utxo info are used a lot.

**Comment by Sergei-Beam** [comment]
Checked
