### ISSUE TITLE
Completed Tx not available on UTXO

### ISSUE THREAD

**Issue by snasps** [BeamMW/beam#408]
Last transaction (Pool payment) is completed on wallet side, but not showing up on UTXO

![screenshot 2019-01-25 07 51 52](https://user-images.githubusercontent.com/28044695/51727923-deefd480-2076-11e9-9198-6bd286660588.png)
![screenshot 2019-01-25 07 51 58](https://user-images.githubusercontent.com/28044695/51727927-e44d1f00-2076-11e9-93b2-d8662f70d489.png)

**Comment by gingervik** [comment]
Hi @snasps 
Please, attach all your logs here. We need it for investigation
To find your logs:
- go to Settings tab
- click "Save wallet logs" button on the right side

**Comment by gingervik** [comment]
waiting for user's response for more than 1 month.
close the issue
