### ISSUE TITLE
The OpenCLMiner is doesnt run

### ISSUE THREAD

**Issue by HeroProbability** [BeamMW/beam#409]
**Bug title**
Ive downloaded the Open CL miner for windows but when i try to switch it on its showing the window for a split second but it doesnt run after that

Can anyone help ?

**Comment by gingervik** [comment]
Hello @HeroProbability 
what command do you use for running miner?
you can find all our instructions here
https://beam-docs.readthedocs.io/en/latest/rtd_pages/user_mining_beam.html

**Comment by gingervik** [comment]
hi @HeroProbability 
do you still have any questions?

**Comment by HeroProbability** [comment]
Its just not opening the window, i cant even send commands

На пт, 8.02.2019 г. в 17:35 ч. Vika Khodichenko <notifications@github.com>
написа:

**Comment by gingervik** [comment]
@HeroProbability it's not opening via double-click
did you read iur docs about mining?
[mining docs](https://beam-docs.readthedocs.io/en/latest/rtd_pages/user_mining_beam.html)

**Comment by gingervik** [comment]
there is no user's response for a month. close
