### ISSUE TITLE
Wallet Miner Windows

### ISSUE THREAD

**Issue by HeroProbability** [BeamMW/beam#410]
**Ive selected a CPU Miner Mode But its not mining**
Express the problem in a single concise sentence
Ive selected the CPU mining mode at my max 12 threads and i tried with lower amount of threads, but its staying at 0% usage. Aka its not mining 
**Bug description**

**Comment by gingervik** [comment]
Hi @HeroProbability 
CPU mining is not effective at all and will be removed from the wallet in next update.
I suggest you to use pools for mining with GPU
