### ISSUE TITLE
Beam wallet protocol API Specific operation

### ISSUE THREAD

**Issue by work53** [BeamMW/beam#412]
Beam wallet protocol API operation at each step In exchange
Can anyone help ?

**Comment by nesbox** [comment]
yes, what help do you need?
have you read the docs here https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API?
thank you

**Comment by gingervik** [comment]
hi @work53 do you still have some questions?

**Comment by gingervik** [comment]
waiting for user's response for more than 1 month.
close the issue
