### ISSUE TITLE
beam-wallet core dumped

### ISSUE THREAD

**Issue by JimmyHongjichuan** [BeamMW/beam#413]
I build beam on latest commit (1799765543e1e106267d65b2c2f945058a241890).
When I run beam-wallet.  It failed. Below is the hint:

```
yaanhyy@yaanhyy-System-Product-Name:~/beam$ ./wallet/beam-wallet  init
Segmentation fault (core dumped)
```

**Comment by gingervik** [comment]
@JimmyHongjichuan you should build beam from branch mainnet
all instructions you can find here
https://github.com/BeamMW/beam/wiki/How-to-build

**Comment by gingervik** [comment]
@yaanhyy just use mining_threads=0

**Comment by gingervik** [comment]
@JimmyHongjichuan @yaanhyy do you still have any problems? or we can close this ticket?

**Comment by gingervik** [comment]
waiting for user's response for more than 1 month.
close the issue
