### ISSUE TITLE
  Where to download Beam wallet-API 

### ISSUE THREAD

**Issue by work53** [BeamMW/beam#414]
Where to download Beam wallet-API    windows

**Comment by gingervik** [comment]
@work53 wallet-api has not been released yet
When it will be you can download it on beam.mw/downloads

**Comment by work53** [comment]
How can my wallet dock with the exchange? Please help me. Thank you.





At 2019-01-28 14:53:26, "Vika Khodichenko" <notifications@github.com> wrote:


@work53 wallet-api has not been released yet
When it will be you can download it on beam.mw/downloads

**Comment by gingervik** [comment]
@work53 did you try to use our GUI or cli wallet from beam.mw/downloads?

**Comment by gingervik** [comment]
@work53 are you from exchange and need api?

**Comment by work53** [comment]
yes,I need！





At 2019-01-28 18:14:12, "Vika Khodichenko" <notifications@github.com> wrote:


@work53 are you from exchange and need api?

**Comment by work53** [comment]
I have not tried it, how to operate, I am a newbie




At 2019-01-28 18:13:55, "Vika Khodichenko" <notifications@github.com> wrote:


@work53 did you try to use our GUI or cli wallet from beam.mw/downloads?

**Comment by gingervik** [comment]
@work53 sorry, I do not undestand. are you from excahnge (which one) or you are a newbie?
all instructions you can find [here](https://beam-docs.readthedocs.io/en/latest/index.html)

**Comment by work53** [comment]
Hello, I am a newbie. At the exchange, I want to implement member registration to automatically get the address and transfer. I am looking for help, please help me, the specific method of operation






At 2019-01-30 00:41:30, "Vika Khodichenko" <notifications@github.com> wrote:


@work53 sorry, I do not undestand. are you from excahnge (which one) or you are a newbie?
all instructions you can find here

**Comment by work53** [comment]
你好，我是新手，中国人，希望你能看懂。在交易所，我想实现会员注册自动获取地址和转账。我在寻求帮助，请帮助我，具体的操作方法是什么





At 2019-01-30 00:41:30, "Vika Khodichenko" <notifications@github.com> wrote:


@work53 sorry, I do not undestand. are you from excahnge (which one) or you are a newbie?
all instructions you can find here
