### ISSUE TITLE
Payment proof in UI wallet

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#415]
1. We need add payment proof in Transaction details for outgoing transactions (only in sender wallet)
Command for cli wallet: beam-wallet.exe payment_proof_export --tx_id=

Output for **Payment proof**: 4bd0ca080bd8c3ec4b3061bf5
916aa34266f0649a7c151c6777ffe492f15e0976800000000000000ebb27b5501213c84eb212ea27
6e8ced74f540fbcceb0f4c1c2da2c5108188651a1864ac2f195ce9056c171fd0cd41e8a02dc9c0bb
72861b2e03fbbbb5942e5e63d1a7728a2954a10d3bfb9938f0c17509a6a0e870c6bb22ff2d1297f3
dae7f54592b00e84c6b3c9ea3e3ad9bc43661b6dcf7dbd818ccc92707d1d75b429697e8492653

2.Receiver should have ability to decode (verify) proof from sender
Command for cli wallet: beam-wallet.exe payment_proof_verify --payment_proof=<proof>

Output for verifying: 
Payment tx details:
Sender: 4bd0ca080bd8c3ec4b3061bf5916aa34266f0649a7c151c6777ffe492f15e09768
Receiver: ebb27b5501213c84eb212ea276e8ced74f540fbcceb0f4c1c2da2c5108188651a1
Amount: 6 groth
KernelID: 4ac2f195ce9056c171fd0cd41e8a02dc9c0bb72861b2e03fbbbb5942e5e63d1a

@sasha-abramovich please, provide design for all this stuff

**Comment by sasha-abramovich** [comment]
here we go with the design: https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889?seid=5c64ea62ba87663c1dd45d07

**Comment by gingervik** [comment]
1. only outgoing transactions should have Payment proof
![image](https://user-images.githubusercontent.com/28015224/53297417-af77e780-382f-11e9-8b9e-7d8a9fb930d9.png)

2. Copy button does nothing
![image](https://user-images.githubusercontent.com/28015224/53297788-8f96f280-3834-11e9-85ca-6bb377301aad.png)

3. 

    - click on proof verification icon
    - insert proof code
    - close proof verification window
    - open it again
Result: ![image](https://user-images.githubusercontent.com/28015224/53297813-f5837a00-3834-11e9-9252-8cc89e31d262.png)

4. Copy details button does not work as expected
![image](https://user-images.githubusercontent.com/28015224/53297946-3ed4c900-3837-11e9-9ab3-91d659a8001e.png)

**Comment by Sergei-Beam** [comment]
6. layout moves out
Steps: 
- click on proof verification icon
- insert proof code
- delete the last number
![image](https://user-images.githubusercontent.com/44496108/53342478-0f00f080-391f-11e9-88e9-f8022933df06.png)
- type the deleted number again
Actual: layout moves out
![image](https://user-images.githubusercontent.com/44496108/53342378-e24cd900-391e-11e9-92de-a1122733a83d.png)

**Comment by Sergei-Beam** [comment]
7. change the error message according to design
https://zpl.io/VYKwnoL

**Comment by Sergei-Beam** [comment]
1-7 Checked

8.  Payment proof verification works wrong
8.1 Validator works wrong
![proof_validation](https://user-images.githubusercontent.com/44496108/53501567-748ae380-3abd-11e9-9be9-7cf589bfb495.gif)
8.2 After some length the text is hidden
![field bug](https://user-images.githubusercontent.com/44496108/53501675-a8660900-3abd-11e9-9836-deea89e75f4e.gif)

**Comment by gingervik** [comment]
8 - checked

9. For expired or Not finished transaction we should show message not just "code:"
![image](https://user-images.githubusercontent.com/28015224/53724321-b085c600-3e7a-11e9-8e06-fe2cc505cd3c.png)
@sasha-abramovich please, provide text

**Comment by gingervik** [comment]
9. Payment proof buttons overlap error message
![image](https://user-images.githubusercontent.com/28015224/53883189-60993180-4029-11e9-8348-f4253144a41d.png)

**Comment by Sergei-Beam** [comment]
point 8.2 reproduced again
![image](https://user-images.githubusercontent.com/44496108/54195320-6b434300-44cf-11e9-9521-022b700db4a5.png)

**Comment by Sergei-Beam** [comment]
10. Transaction to myself
For exchange transactions we should not show details and copy buttons
![image](https://user-images.githubusercontent.com/44496108/54351864-8a71da00-4661-11e9-9b9a-1ae38d29a967.png)

**Comment by Sergei-Beam** [comment]
checked
