### ISSUE TITLE
Able to turn on GPU mode without selecting the GPU.

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#421]
**Bug description**
In Settings when turning on the GPU mode, it's possible to apply the changes not having selected the GPU.

**To Reproduce**
Steps to reproduce the behaviour:
Preconditions: 
1. A GPU version of the Desktop Beam application is installed and running.
2. GPU mode is not turned on.
Steps:
1. Navigate to Settings.
2. Turn the "Use GPU" switch ON, but don't check any checkbox with GPU.  

**Current behaviour**
User is able to apply the changes.

**Expected behaviour**
 User is unable to apply the changes without specifying the GPU.

**Platform and build**
* Windows
* 10 x64
* 4323, master

**Screenshot and video (zipped)**
Add screenshots that illustrate a problem you've found.
![image](https://user-images.githubusercontent.com/41323026/51890875-66f31880-23ae-11e9-996e-44ac37cb6efa.png)
[gpu not selected.zip](https://github.com/BeamMW/beam/files/2806450/gpu.not.selected.zip)

**Comment by beam-mw** [comment]
Irrelevant
