### ISSUE TITLE
Add ability to use JSON RPC over HTTP in Wallet API

### ISSUE THREAD

**Issue by nesbox** [BeamMW/beam#423]

**Comment by nesbox** [comment]
added JSON RPC 2.0 over HTTP here 5414213
use `--api_use_http=1` command line parameter to turn on

to test and do POST request with CURL use the following command:
`curl -d '{"jsonrpc":"2.0","id":1,"method":"wallet_status"}' -H "Content-Type: application/json" -X POST http://x.x.x.x:port/api/wallet`

**Comment by Sergei-Beam** [comment]
Checked
