### ISSUE TITLE
Rescan makes blocked UTXO's available

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#425]
<p>**Bug description**&nbsp;</p><p>When there&#39;re some blocked funds and &#39;rescan&#39; is performed - than the balance displays the blocked funds as available.&nbsp;</p><p>**To Reproduce**&nbsp;</p><p>Preconditions: A desktop wallet is installed and running. Some UTXO&#39;s are available in the wallet.&nbsp;</p><p><br></p><p>Steps:&nbsp;</p><p>1. Send some funds to yourself/ perform an exchange.</p><p>&nbsp;2. When the transaction is in &quot;Syncing with blockchain&quot; status - go to Settings and click &#39;rescan&#39;.&nbsp;</p><p>3. After the rescan check the balance.&nbsp;</p><p>**Current behaviour**&nbsp;</p><p>The balance has reverted to the amount prior to when the transaction has been made. i.e. the funds are blocked, but the balance shows the funds as available. See the video attached for more details.&nbsp;</p><p><br></p><p>**Expected behaviour**&nbsp;</p><p>The balance is correct and has not been reverted to the amount prior to when the transaction has been made.&nbsp;</p><p><br></p><p>**Platform and build**&nbsp;</p><p>* Windows * 10 x64 * 4328, master <br>**Video (zipped)** [blocked_funds_as_available.zip](https://github.com/BeamMW/beam/files/2807446/blocked_funds_as_available.zip)</p>

**Comment by gingervik** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D8. Do not remove or edit.` [D8](https://beam.testquality.com/project/5267/result/1067099/defect/3814)

**Comment by gingervik** [comment]
checked on master
