### ISSUE TITLE
Export Addresses: Typo in the Error message 

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#428]
**Bug description**
When providing the **folder only** without the file name - the error message that is shown has a typo in the word "exported".

**To Reproduce**
Steps to reproduce the behaviour:
Preconditions: A cli wallet is running.
Steps:
1. Execute the following command: `beam-wallet export_addresses --export_path="C:\Users\jurij\Documents\Beam"` **(The path must be any but already existing!)**
2. Provide the password.
3. Check the text of the error message shown.

**Current behaviour**
The text is "Failed to save **expoerted** data."

**Expected behaviour**
The text is "Failed to save **exported** data."

**Platform and build**
* Windows,
* 10 x64
* 4328, master

**Screenshot**
![image](https://user-images.githubusercontent.com/41323026/51909968-ef89ad00-23de-11e9-81ef-4d2baa95e6c5.png)

**Comment by jonathancross** [comment]
This was fixed in https://github.com/BeamMW/beam/commit/c95f5bb5c94abd7960015bb2e2a7d2466e29f86b#diff-0306801f2c84a9ac1c90125f5e2f33fe

**Comment by jurijakimuk** [comment]
Tested on 4396, master. Works OK. Closing. Thank you, @jonathancross.
