### ISSUE TITLE
Beam node not releasing file lock on log files

### ISSUE THREAD

**Issue by vrvaderom** [BeamMW/beam#431]
**Bug description**
When log files are rotated, the beam application on linux does not release lock on old log files. 
Hence, when deleting them, the files are not actually deleted until node service is restarted.

**To Reproduce**
1. Start node on linux (./beam-node)
2. Let it run for a few hours
3. Delete old log file
4. Note disk space is not freed, and if running "sudo lsof +L1" you can see the file is still locked by the executable.
5. Restart beam node
6. See that log files are no longer locked.

**Current behaviour**
Log files are locked even after they are no longer written into

**Expected behaviour**
A log file should be released after it's rotated

**Platform and build**
Linux, build 1.1.4202

**Comment by gingervik** [comment]
Acc to @art-gor it has been already fixed in master
@jurijakimuk please, check

**Comment by jurijakimuk** [comment]
Tested on master, 4341, fro cli and UI. Works OK. Closing.
