### ISSUE TITLE
Invalid seed phrases when restore

### ISSUE THREAD

**Issue by yinhm** [BeamMW/beam#433]
Beam wallet was created after mainnet released:
 - on a fresh windows 10 machine;
 - took a picuture from iPhone;

After many failed transtions, and rescan did not help, we thought we should
restore out wallet from seed.

The invalid seed word was `com`, I can not figure out why this happened, what I did
after was, check `mnemonic/dictionary.cpp` en dict, tried `combine, come, comfort,
comic` etc to restore it without luck(clearly).

I tried restore `another wallet` from BeamWalet windows GUI, which is good: all
balance are there.

Then I restore this correct seeded `another wallet` from linux cli:

```
cd beam-1.1.4202
./beam-wallet restore --seed_phrase="xx1;xx2....;xx12;"
./beam-node
./beam-wallet listen -n 127.0.0.1:10000
```

After beam node synced and wallet state synced to Tip, balance are gone(this issue not related to first one).

```
$ ./beam-wallet info -n 127.0.0.1:10000
I 2019-01-30.16:22:50.014 Rules signature: ed91a71731xxxxx
I 2019-01-30.16:22:50.014 starting a wallet...
I 2019-01-30.16:22:50.136 wallet sucessfully opened...
____Wallet summary____

Current height............38463
Current state ID..........178baab2ec5a8ba5

Available.................0 groth 
Maturing..................0 groth 
In progress...............0 groth 
Unavailable...............0 groth 
Available coinbase .......0 groth 
Total coinbase............0 groth 
Avaliable fee.............0 groth 
Total fee.................0 groth 
Total unspent.............0 groth 

                  id |          Beam |         Groth |        height |          maturity |                        status |    type

```

And refresh are not helpful clearly

```
./beam-wallet refresh -n 127.0.0.1:10000
I 2019-01-30.16:23:33.851 Rules signature: ed91a71731xxxxx
I 2019-01-30.16:23:33.851 starting a wallet...
I 2019-01-30.16:23:33.931 wallet sucessfully opened...
I 2019-01-30.16:23:33.932 WalletID ddexxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx subscribes to BBS channel 13
I 2019-01-30.16:23:33.944 Tip has not been changed
I 2019-01-30.16:23:34.855 Sync up to 38465-26c8c36b6eadf005
I 2019-01-30.16:23:34.861 Current state is 38465-26c8c36b6eadf005
I 2019-01-30.16:23:53.931 Sync up to 38466-297ff63c6988cebd
I 2019-01-30.16:23:53.937 Current state is 38466-297ff63c6988cebd
I 2019-01-30.16:24:20.727 Sync up to 38467-a7d821b80ccdee81
I 2019-01-30.16:24:20.732 Current state is 38467-a7d821b80ccdee81
I 2019-01-30.16:24:43.727 Sync up to 38468-d12785feb18fef13
I 2019-01-30.16:24:43.732 Current state is 38468-d12785feb18fef13
```

**Comment by gingervik** [comment]
@yinhm hi
sound like smth impossible.
i can suggest you to download old version of wallet https://github.com/BeamMW/beam/releases/tag/mainnet-release
and try to do restore there with your words from phone picture.

please, doublecheck your photo

**Comment by yinhm** [comment]
I have been successfully restored wallet using Beam-Wallet-1.0.3976.deb.

I don't known why a valid seed in v1.0.3976 became invalid in v1.1.4202.

After restore my wallet have `0 beam` which is very hard to believe since we did a bunch of transactions, there is nearly zero chance we have no any left over beam in the wallet.(We managed to sent 1K+ today to the exchange successfully.)

Anyway, I upgrade BeamWallet to v1.1.4202 after a restore from v3976, still the same after (wallet)migration  and `rescan`, I don't known the logic behind `rescan`. I suspect it did not do any real work: 1.Wallet cpu usage did not change, 2. log after `rescan -> yes` click instantly:
 
```
I 2019-01-30.20:16:30.917 Synchronizing with node: 100% (1/1)
I 2019-01-30.20:16:30.922 Current state is 38698-09c922ddef605634
```

**Comment by gingervik** [comment]
@yinhm one question about your cli wallet and node
did you use parameter key_owner for your node?

**Comment by yinhm** [comment]
I did not use `key_owner` when doing restore and refresh. I have been using `key_owner` when solo, I thought it was for mining.

**Comment by gingervik** [comment]
@yinhm please, run node from scratch with your key_owner parameter and peer (of course)
when it will be synced - try to restore your wallet (or rescan) with using this node
to get your key_owner
please
- create wallet with your seed_phrase
- run _beam-wallet export_owner_key_

**Comment by yinhm** [comment]
After applying export_owner_key, info showing correctly for my `another wallet`.

The problem one with invalid seed word `com` when restore from v1.1.4202, restored successfully with 
v1.0.3976:
```
./beam-wallet restore --seed_phrase="xx1;xx2;...;xx11;com;"
```

Info still showing `0` without luck
```
./beam-wallet info -n 127.0.0.1:10000
I 2019-01-31.22:20:52.340 Rules signature: ed91a7173xxxxxxx
I 2019-01-31.22:20:52.340 starting a wallet...
I 2019-01-31.22:20:52.442 wallet sucessfully opened...
____Wallet summary____

Current height............40239
Current state ID..........030649f6e581d07b

Available.................0 groth 
Maturing..................0 groth
```

**Comment by gingervik** [comment]
@yinhm this means that your seed incorrect
if you use correct seed with YOUR node everything should be restored

**Comment by yinhm** [comment]
@gingervik 

 1. I can not believe photo taken from phone can lie(the timestamp was right after mainnet release)
 1. `com` was a valid seed word in v1.0.3976, but not in  v1.1.4202.

**Comment by yinhm** [comment]
wasn't that's the odd thing? the origin of `com`.

I did triple check `Generate seed phase` from Beam Wallet(both 3976, 4202), and the generated seed is not a editable input.

**Comment by gingervik** [comment]
@yinhm what if your com = c o r n (corn)?

**Comment by yinhm** [comment]
It is. Thank you, save my day.
