### ISSUE TITLE
Enable wallet restore process (with all the related UX)

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#436]
when user wants to restore his wallet:
* warning should be shown that all the current user data (UTXO, transactions history will be erased - YES/NO)
* the wallet app will switch to the integrated node
* after the blockchain scan will be finished the wallet will switch to the node it was previously working with

Related #371

**Comment by gingervik** [comment]
won't fix

**Comment by alexandrashelenkova** [comment]
Wallet restore was implemented
