### ISSUE TITLE
Can't open wallet

### ISSUE THREAD

**Issue by miruashvili** [BeamMW/beam#439]
Hi, I can't open Beam wallet, it says "Failed to start node. Please check your node configuration"

I didn't changed anything.

![untitled](https://user-images.githubusercontent.com/44260773/52182527-827b7a80-2817-11e9-94d9-a6234316f58f.png)

**Comment by gingervik** [comment]
hello @miruashvili 
please, send us your logs
you can find it [here](https://beam-docs.readthedocs.io/en/latest/rtd_pages/user_files_and_locations.html)

**Comment by miruashvili** [comment]
[beam_ui_19_02_08_23_56_34.log](https://github.com/BeamMW/beam/files/2846669/beam_ui_19_02_08_23_56_34.log)

I 2019-02-08.23:56:34.936 Rules signature: ed91a717313c6eb0
I 2019-02-08.23:56:52.073 Found device 0: Radeon RX 570 Series
I 2019-02-08.23:56:52.073 Memory check ok
I 2019-02-08.23:56:52.073 Found device 1: Radeon RX 570 Series
I 2019-02-08.23:56:52.073 Memory check ok
I 2019-02-08.23:56:52.073 Found device 2: Radeon (TM) RX 480 Graphics
I 2019-02-08.23:56:52.073 Memory check ok
I 2019-02-08.23:56:52.084 Found device 3: Intel(R) HD Graphics
I 2019-02-08.23:56:52.084 Memory check failed
I 2019-02-08.23:56:52.084 Device reported 1578MByte memory, 3808 are required 
I 2019-02-08.23:56:54.003 starting a node on 10005 port...
I 2019-02-08.23:57:29.710 Interpreting MB up to 41760...
I 2019-02-08.23:57:30.548 Node stopping...
I 2019-02-08.23:57:30.548 Node stopped
E 2019-02-08.23:57:30.597 underflow
D 2019-02-08.23:58:03.414 beam::io::Reactor::~Reactor
D 2019-02-08.23:58:03.414 closing unclosed handles
D 2019-02-08.23:58:03.414 beam::io::Reactor::~Reactor
D 2019-02-08.23:58:03.414 closing unclosed handles

**Comment by gingervik** [comment]
hello again @miruashvili 
* close your wallet
* go to 
\Users\{your User name}\AppData\Local\Beam Wallet\
* remove your node.db, node.db-journal (if you have it), and all tempmb... files
* run your wallet again

**Comment by miruashvili** [comment]
> hello again @miruashvili
> 
> * close your wallet
> * go to
>   \Users{your User name}\AppData\Local\Beam Wallet\
> * remove your node.db, node.db-journal (if you have it), and all tempmb... files
> * run your wallet again

Thanks, it worked.
