### ISSUE TITLE
CLI and wallet app: Separate al the strings into a textual editable file

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#443]
We want to decouple app & error messages into a separate file, in order to:

- have all the messages in Good English
- have consistent messages across desktop & mobile platforms
- be able to fix a message easily
- be able to support more languages (in the future)

**Comment by anatolse** [comment]
https://github.com
[cli_strings.txt](https://github.com/BeamMW/beam/files/2920364/cli_strings.txt)
/BeamMW/beam/blob/master/ui/translations/english.ts

**Comment by sasha-abramovich** [comment]
UI wallet looks great, CLI doesn't look like an editable file. Suggestions please?

**Comment by anatolse** [comment]
opened separate issues: #545 #544
