### ISSUE TITLE
UI Wallet - wallet crashes when I click cancel while restoring

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#444]
**To Reproduce**
Steps to reproduce the behaviour:
1. Run the wallet
2. click restore
3. enter the recovery phase
4. star restore
5. open the wallet&#39;s data folder
6. wait while wallet gets all temp_blocks
_Note: at this time node.db stands still and does not grow_
7. look at node.db and wait while it begins to grow
8. Click &quot;Cancel&quot; on UI Wallet
Expected: Wallet stops restoring and shows the setup node screen
Actual: Wallet crashes and dumps created

**Comment by GalloNegr** [comment]
I accidentally deleted the Beam desktop wallet.  I have already download new wallet, enter the seeds.  Wallet started by changed my wallet address which I had it to  never expire.  Can someone help in restoring my wallet to its original.  I have my seeds and old wallet address.

**Comment by gingervik** [comment]
@GalloNegr hello 
please, ask for help in https://t.me/BeamSupport or via support@beam.mw

**Comment by gingervik** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D3. Do not remove or edit.` [D3](https://beam.testquality.com/project/5267/result/1067025/defect/3807)

**Comment by gingervik** [comment]
<p>also can be reproduced when user run second wallet on the same PC and use the same port then go back and change it</p>

**Comment by chapati** [comment]
@anatolse, would you please review this and merge.
Thank you.

**Comment by gingervik** [comment]
checked on https://builds.beam-mw.com/files/master/2019.06.20/Release/mac/Beam-Wallet-Masternet-2.1.5510.dmg

bug is still reproduced
[mac2.txt](https://github.com/BeamMW/beam/files/3313824/mac2.txt)

**Comment by gingervik** [comment]
checked
