### ISSUE TITLE
Atomic Swap - cli wallet

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#447]
- [x] libbitcoin integration.
- [x] implement BEAM locked UTXO transaction
- [x] implement BEAM redeem transaction
- [x] implement BEAM refund transaction
- [x] wallet CLI for this issue

**Comment by anatolse** [comment]
- [ ] libbitcoin integration.
- [ ] implement BEAM locked UTXO transaction
- [ ] implement BEAM redeem transaction
- [ ] implement BEAM refund transaction

**Comment by Sergei-Beam** [comment]
all tasks are completed
