### ISSUE TITLE
UI Wallet - Incorrect message shown when port not available

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#449]
Relates to #240 
We need to change the status for user clearly understand the problem
Steps

* create 2 different wallets separately on port 10005
* run 1st wallet on port 10005
* try to run 2nd wallet on port 10005
  Expected:
  Actual: The error that the port already in use is shown
![image](https://user-images.githubusercontent.com/44496108/52418413-12167700-2aff-11e9-8f52-e87931eb1e45.png)

**Comment by chapati** [comment]
This would be fixed in #721

**Comment by gingervik** [comment]
checked
