### ISSUE TITLE
Send screen - red error is shown when user send coin with change

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#450]
Looks like validator is doing wrong double check
![photo_2019-02-08_15-29-03](https://user-images.githubusercontent.com/44496108/52478393-4e58de80-2bb6-11e9-8214-ea621773a67b.jpg)

[send_bug_video.zip](https://github.com/BeamMW/beam/files/2845085/send_bug_video.zip)

**Comment by gingervik** [comment]
can't reproduce
