### ISSUE TITLE
Kernel ID: 0000000000000000000000000000000000000000000000000000000000000000

### ISSUE THREAD

**Issue by paulofoerster** [BeamMW/beam#452]
Hi guys, 

I tried to withdraw my balance from a trader to my wallet and the transaction is marked as complete in the traders side but didn't arrive in my wallet 

Is this code meaning something? Are the coins still coming?

Kernel ID: 0000000000000000000000000000000000000000000000000000000000000000

**Comment by gingervik** [comment]
Hi @paulofoerster 
Do you see transaction in your wallet?
if no - where did you take this kernel id? from sender?

**Comment by paulofoerster** [comment]
yes, there are 2 transactions.

1 doesn't show in my wallet at all, the 2 shows as failed.

should I post the details here? or send in private somewhere?

**Comment by gingervik** [comment]
@paulofoerster you can post it here or send email on support@beam.mw

**Comment by paulofoerster** [comment]
#1

Address: 1309affc929ea7b1acb0fa7fe6a0b7ab7d1a215a1dac94472f41aaee62c26dadc5

Txid: caa3b3a0fda14cb392ae59030840a2c3 

View Kernel ID

Kernel ID: 0000000000000000000000000000000000000000000000000000000000000000


#2

Address:1309affc929ea7b1acb0fa7fe6a0b7ab7d1a215a1dac94472f41aaee62c26dadc5


Txid: 63b7bb6fcf6c45bdbd8238b6fb4ae901 


View Kernel ID

Kernel ID: 0000000000000000000000000000000000000000000000000000000000000000

**Comment by gingervik** [comment]
kernel_id 00000 means that this transaction was not registered in blockchain. so your coins were returned to sender

**Comment by paulofoerster** [comment]
thank you guys, I will contact them instead!
