### ISSUE TITLE
Wallet does not match Pool payouts

### ISSUE THREAD

**Issue by jadestarcat** [BeamMW/beam#453]
Leafpool reports total payouts of 72.0938 Beam
Wallet balance shows as 64.32500718 Beam, 7.76879282 Beam short
Leafpool shows last payout of 7.7688 Beam as " Completed " 3 Days ago 
https://mainnet-explorer.beam.mw/explorer/search/?q=eba25a67a148852d064a35cb543c830c769937f6c241e783d53c3864c45128f7
That amount does not show up in wallet UTXO tab nor on Main page of transactions.
After wallet was updated to 1.1.4202 only 2 entries show up in the transactions list in the main window.
Wallet does not appear to have received the 7.768 Beam hat Leafpool says completed.
I do not recall any error when I queued the payment at Leafpool.
There does not seem to be any documentation at Leafpool for this kind of error.
I have submitted Wallet LOG files to Beam Admin as of 10 Feb.19

**Comment by gingervik** [comment]
Hi @jadestarcat 
we need your logs
do you you only one copy of your wallet? or may be you restore (copy) it to another PC also?

**Comment by Jagor21** [comment]
Hello @gingervik 
I have @jadestarcat logs from his email to Support team.

[beam v1.1.4202 windows report (1).zip](https://github.com/BeamMW/beam/files/2850591/beam.v1.1.4202.windows.report.1.zip)

**Comment by gingervik** [comment]
@jadestarcat it seems like you used 2 wallet with same wallet.db what is forbiden
Please, do next:
*Erase the wallet.db (you can back it up), because it may continue to create duplicated coins. Then restore it via your secret phrase. No need to erase node.db.
*After the sync is complete - send all your "visible" funds to yourself. You can set fee=0. Wait until transaction completes.
*Wait for 2 days. Meanwhile you may use your wallet normally, but some of the funds may still look missing.
*After 2 days: Erase both wallet.db AND node.db. Then - do a full restore.

**Comment by gingervik** [comment]
or wait our upcoming release first)

**Comment by jadestarcat** [comment]
I did not do as you say, I only ever had the one wallet. I know better than to do as such.
Only thing possibly unusual is the HDD in this machine was cloned and replaced with a larger one.
Would that cause the same problem?
The Procedure you have listed below sounds very and unnecessarily complicated and possibly dangerous.
Any other coin it would not be this way.
What exactly is a full restore? I need the procedure for this as your instructions contain aspects that are not clear.
I'd like to get this solved as quickly as possible as its destroying my faith in getting involved with this coin.
Please advise further and I'll start the process.
Thanks for taking time to look into the matter.

Star

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by jadestarcat** [comment]
The original installed of the wallet WAS upgraded to most current version by following the upgrade process which was supposed to be ok. This is all the pertinent intel I hve at the moment. Back on late afternoon, MST. Thanks for all efforts to resolve this matter.
Star

**Comment by jadestarcat** [comment]
Gingervik, if you can just verify the procedure you have described to do full restore after doing the list shown above I will proceed. Thanks for your time on this matter.
Star

**Comment by jadestarcat** [comment]
I think I got the matter solved.
Thanks for all the input.
Star
