### ISSUE TITLE
Can't send 262_800_000 beams in Send screen

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#459]
**Bug description**
In the Send screen the maximum input value in the field Transaction amount is 253 999 999 beams, which is not the biggest possible amount.

**To Reproduce**
Preconditions: A desktop wallet is installed and running.
Steps to reproduce the behaviour:
1. Open the Send screen.
2. Enter 262 800 000 beams.

**Current behaviour**
It's **not** possible to enter the amount of 262 800 000 beams.
The biggest amount possible to enter is 253 999 999.

**Expected behaviour**
It's possible to enter the amount of 262 800 000 beams.

**Platform and build**
* Windows,
* 10 x64
* 4375, master

**Screenshots**
![image](https://user-images.githubusercontent.com/41323026/52632703-52953c80-2ed3-11e9-98e1-45c05acde7e8.png)
![image](https://user-images.githubusercontent.com/41323026/52632745-73f62880-2ed3-11e9-9296-b59d9f2fb140.png)

**Comment by Maxnflaxl** [comment]
moved to beam-ui repo
