### ISSUE TITLE
Testnet - UI: Some screens are not in Testnet colours

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/beam#463]
**Bug title**
Testnet - UI: Some screens are not in Testnet colours

See attached screenshot
![photo_2019-02-13 15 13 20](https://user-images.githubusercontent.com/45590119/52714190-eb928900-2fa1-11e9-835a-cfc5ad7d2139.jpeg)

**Comment by jurijakimuk** [comment]
To be merged.

**Comment by gingervik** [comment]
Testnet
Colors on Settings tab are not good. Please, revert buttons as it was
![image](https://user-images.githubusercontent.com/28015224/55777903-0701a800-5aaa-11e9-8dc0-c346a3cdecf2.png)
