### ISSUE TITLE
EXCEPTION: sqlite error code=14, unable to open database file

### ISSUE THREAD

**Issue by nesbox** [BeamMW/beam#466]
User says:
> Mourad Ilyes Mlik, [14.02.19 10:37]
> Hey guys
> 
> Mourad Ilyes Mlik, [14.02.19 10:37]
> not sure if this is happening only to us
> 
> Mourad Ilyes Mlik, [14.02.19 10:37]
> but the wallet api keep hanging everyday with the same error
> 
> Mourad Ilyes Mlik, [14.02.19 10:38]
> the cronjob is stopped
> 
> Mourad Ilyes Mlik, [14.02.19 10:38]
> but I still get the exception
> 
> Mourad Ilyes Mlik, [14.02.19 10:38]
> EXCEPTION: sqlite error code=14, unable to open database file
> 
> Elina Kaminsky, [14.02.19 10:42]
> @nesbox  may be folder permissions settings?
> 
> Aleš Grm, [14.02.19 10:42]
> It happens after almost 24 hours
> 
> Aleš Grm, [14.02.19 10:42]
> No permissions change in the mean time. And it happens every day
> 
> Elina Kaminsky, [14.02.19 10:43]
> Ah… so it is ok and after 24 hours it happens?
> 
> Aleš Grm, [14.02.19 10:43]
> Yes
> 
> Elina Kaminsky, [14.02.19 10:45]
> And no Backup job running every 24 hours you say
> 
> Aleš Grm, [14.02.19 10:45]
> Exactly, not anymore

**Comment by Sergei-Beam** [comment]
checked
