### ISSUE TITLE
get_utxo API filter

### ISSUE THREAD

**Issue by feeleep75** [BeamMW/beam#467]
BUG: Despite of using get_utxo parameters (count/skip) I always get full list - latest binaries from release, wallet-api compiled from latest 'mainnet' branch

REQUEST: Please add some additional filtering to get_utxo: type of transaction, some sorting (oldest/latest) together with count/skip (if it works)

**Comment by gingervik** [comment]
Hi
this will be fixed in bright boson 2.0
for now get_utxo APi filter works only on master branch (which is incompatible with mainnet)
