### ISSUE TITLE
API gets unresponsive after few hours

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/beam#471]
**Bug title**
API gets unresponsive after few hours

**Bug description**
Since the wallet API upgrade (to 1.2.4419?)  when still using static TCP calls instead of http the API gets unresponsive after few hours, not accepting new connections and also not working through blocks when you check the screen.. it simply stalls. Switching to http seems to fix it for now

//_reported in Beam Developers Support channel_

**Comment by nesbox** [comment]
#466 duplicate
