### ISSUE TITLE
No mining option available in debian menu

### ISSUE THREAD

**Issue by pdarcos** [BeamMW/beam#472]
Just as the title says, I just installed the debian package, chose to run my own node, have a compatible GPU yet there are no mining options available at all under settings....
See photo
![beam](https://user-images.githubusercontent.com/32959420/52916040-e51e4d00-32d2-11e9-9589-ef80d6ccea9a.png)

**Comment by gingervik** [comment]
hello @pdarcos 
mining was removed from our GUI wallet in 1.2.4419 version
please, use our instructions for cli-node mining 
https://beam-docs.readthedocs.io/en/latest/rtd_pages/user_mining_beam.html#mining-guide
