### ISSUE TITLE
how can I create my own node and use it

### ISSUE THREAD

**Issue by lijixy** [BeamMW/beam#479]
I want to create a node, and how to use it? can you give me some development documents..  thank you!

**Comment by gingervik** [comment]
hello @lijixy 
Please, see our [documentation for local setup](https://beam-docs.readthedocs.io/en/latest/rtd_pages/dev_local_setup.html) - if you want to create your own test blockchain
and [beam node user guide](https://beam-docs.readthedocs.io/en/latest/rtd_pages/user_beam_node_guide.html) - if you want to run your node in Mainnet

**Comment by lijixy** [comment]
if I run the wallet-api, the debug is "cannot start server: io::Exception: code=-4091 (EC_EAD
DRINUSE : address already in use)" 
![default](https://user-images.githubusercontent.com/27389800/53308629-dc82d380-38dd-11e9-8fb4-707d2ca469a0.png)

**Comment by lijixy** [comment]
but  the port 10000 is not used !

**Comment by lijixy** [comment]
![default](https://user-images.githubusercontent.com/27389800/53308971-f45b5700-38df-11e9-8ccd-f9b82c5789de.png)

**Comment by lijixy** [comment]
peer disconnected, code=EC_ECONNRESET

**Comment by nesbox** [comment]
Hi, please provide all the commands you use to start the `wallet-api` and command you use to call JSONRPC.
Thank you.

**Comment by lijixy** [comment]
I sent 0.0000001 beam from Wallet A(1226088c4748c67cd22fa92ca2cdc12e3dedfe154237aa56bfe1685c7bb7d699bec) to Wallet B(30bfcc9ed3b5b36e30b98461f6c5a5f380cc2170041cc0b35d1cdc37a6a137fd589) by wallet-api A tx_send,
		{
			"jsonrpc":"2.0", 
	        "id": 1,
	        "method":"wallet_status", 
	        "params":
	        {
			   "txId":"8efa63fe64934b77823dd6a635c5f037",
		       "value" : 1,
		       "fee" : 1,
		       "from" : "1226088c4748c67cd22fa92ca2cdc12e3dedfe154237aa56bfe1685c7bb7d699bec",
		       "address" : "30bfcc9ed3b5b36e30b98461f6c5a5f380cc2170041cc0b35d1cdc37a6a137fd589",
		       "comment" : "thank you!"
	       }
		})

**Comment by lijixy** [comment]
I sent 0.0000001 beam from Wallet A(1226088c4748c67cd22fa92ca2cdc12e3dedfe154237aa56bfe1685c7bb7d699bec) to Wallet B(30bfcc9ed3b5b36e30b98461f6c5a5f380cc2170041cc0b35d1cdc37a6a137fd589) by wallet-api A tx_send,
{
"jsonrpc":"2.0",
"id": 1,
"method":"tx_send",
"params":
{
"value" : 1,
"fee" : 1,
"from" : "1226088c4748c67cd22fa92ca2cdc12e3dedfe154237aa56bfe1685c7bb7d699bec",
"address" : "30bfcc9ed3b5b36e30b98461f6c5a5f380cc2170041cc0b35d1cdc37a6a137fd589",
"comment" : "thank you!"
}
})

**Comment by nesbox** [comment]
Looks good, pls show me command line parameter you used to start `wallet-api`, also show me how do you send this json.

**Comment by lijixy** [comment]
the start commend parameter is : wallet-api.exe --node_addr=172.104.249.212:8101 --pass=123
and eth send this json with nodejs code,
var net = require('net');

var client = new net.Socket();
client.connect(10001, '127.0.0.1', function() {
}

**Comment by nesbox** [comment]
all looks good, but the API thinks your JSON has the wrong syntax and says `expected [ or {`
could you check your json again?
thank you

**Comment by gingervik** [comment]
hi @lijixy do you still have any questions or we can close this ticket?

**Comment by gingervik** [comment]
there is no response from user for 3 weeks
