### ISSUE TITLE
Review send and receive money screens - simple mode (ie no addresses)

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#48]
The designs for the simple mode are here, IF time permits please verify the layout:
- https://zpl.io/a8N9dxJ
![image](https://user-images.githubusercontent.com/44496108/48199526-557d1000-e36d-11e8-95f9-b7685bb238bb.png)
- https://zpl.io/29yOkew
![image](https://user-images.githubusercontent.com/44496108/48199539-5dd54b00-e36d-11e8-9c51-30e8ea850b6e.png)
- https://zpl.io/VD4q6W3
![image](https://user-images.githubusercontent.com/44496108/48199548-6463c280-e36d-11e8-9eee-245828eb131c.png)
- https://zpl.io/29PoAEW
![image](https://user-images.githubusercontent.com/44496108/48199554-6b8ad080-e36d-11e8-99af-34e16bfe88bc.png)

**Comment by Alesio7** [comment]
Hello, is this issue outdated?

**Comment by gingervik** [comment]
irrelevant. design for send screen was changed
