### ISSUE TITLE
validate_address API returns false for all own addresses

### ISSUE THREAD

**Issue by nesbox** [BeamMW/beam#481]

**Comment by Sergei-Beam** [comment]
Make an address to alive from expired and set the expiration_time=never - > address became active.
Then I try to validate this address via API but API returns that address as is_valid=false
![photo_2019-02-21_08-09-36](https://user-images.githubusercontent.com/44496108/53147790-b09fdf00-35b9-11e9-9dac-8ee08d98c7b3.jpg)

**Comment by Sergei-Beam** [comment]
> Make an address active from expired and set the expiration_time=never - > address became active.
> Then I try to validate this address via API but API returns that address as is_valid=false
> ![photo_2019-02-21_08-09-36](https://user-images.githubusercontent.com/44496108/53147790-b09fdf00-35b9-11e9-9dac-8ee08d98c7b3.jpg)

Moved to #483

**Comment by Sergei-Beam** [comment]
Checked
