### ISSUE TITLE
API - Autentification

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#488]
Please, add autentification to API

**Comment by nesbox** [comment]
added _Access Control List_ (ACL) support and it looks like a list with `api_key : access_rights` items
```
alice : write
bob : read
bob2 : write
2f1b078f3b40a13cef1bef97511e7eb17f0b984b94e460d199ff3cf21e6f1974786 : read
```
it can be specified with `--acl_path=wallet_acl.txt` command line parameter and you have to pass `key` value in every JSONRPC request, like this one 
```
curl -d '{"jsonrpc":"2.0","id":1,"method":"wallet_status","key":"bob"}' -H "Content-Type: application/json" -X POST http://127.0.0.1:10000/api/wallet
```

also you can encrypt connection with **TLS** by adding `--use_tls` parameter

**Comment by Sergei-Beam** [comment]
Checked

**Comment by Sergei-Beam** [comment]
Checked
