### ISSUE TITLE
Wallet API - JSON parser works wrong with values starting from 0

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#490]
JSON parser works wrong with values starting from 0.
F.E. for method "tx_send" if
 value, then system sends :
- 020    - 16
- 030    - 24 
- 040    - 32
...
- 060    - 48

Looks like system converts OCT to DEC because 020 OCT = 16 DEC

**Comment by nesbox** [comment]
The problem is not in our JSON parser, we throw an exception for all the octal numbers.

description from `json.hpp`
```
The restrictions about leading zeros is not enforced in C++. Instead,
leading zeros in integer literals lead to an interpretation as octal
number. Internally, the value will be stored as decimal number. For
instance, the C++ integer literal `010` will be serialized to `8`.
During deserialization, leading zeros yield an error.
```
So, as I see OCT to DEC conversion occurs on JavaScript side and we can close the issue.

**Comment by Sergei-Beam** [comment]
checked
