### ISSUE TITLE
Print out user-friendly error message when payment proof is not provided

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#491]
**Bug description**
In CLI wallet when user wants to verify the payment proof, but doesn't provide the payment proof, then no user-friendly error is printed out.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `beam-wallet payment_proof_verify`.

**Current behaviour**
The error message is printed out: `boost::bad_any_cast: failed conversion using boost::any_cast`.

**Expected behaviour**
The error message is printed out (text may vary, it's not specified): `No payment proof provided: --payment-proof parameter is missing`.

**Platform and build**
* Windows
* 10 x64
* 4402, master

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/41323026/53345934-0ca29480-3927-11e9-918f-f1ecb787a744.png)

**Comment by Sergei-Beam** [comment]
@echoby Please change error message text to :
No payment proof provided: --payment_proof parameter is missing"
Because previous has the typo in the command --payment_proof 
![image](https://user-images.githubusercontent.com/44496108/56279401-aeb55080-6110-11e9-9966-f768517a3278.png)

**Comment by Sergei-Beam** [comment]
checked
