### ISSUE TITLE
CLI: CLI help is not updated

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/beam#492]
![photo_2019-02-25 18 17 13](https://user-images.githubusercontent.com/45590119/53351302-b2ef9980-3929-11e9-904d-f13b8005d3d8.jpeg)
Missing:
payment_proof_export
payment_proof_verify
utxo (send specific UTXO)

**Comment by jurijakimuk** [comment]
Tested on 4712, master. Woks OK.
