### ISSUE TITLE
Failed transactions | wallet api

### ISSUE THREAD

**Issue by vsnation** [BeamMW/beam#494]
**Failed transactions**
I faced with the problem when sent 10 transactions using Wallet API post request with a delay 1 second and amount 0.000001 BEAM. All transactions that were sent failed, only one transaction sent successfully

![image](https://user-images.githubusercontent.com/44433026/53400615-4a52fc00-39bf-11e9-98f9-5615ca96e571.png)

**Comment by nesbox** [comment]
logs:
[api_19_02_28_09_47_53.log](https://github.com/BeamMW/beam/files/2913748/api_19_02_28_09_47_53.log)
[node_19_02_28_09_47_48.log](https://github.com/BeamMW/beam/files/2913749/node_19_02_28_09_47_48.log)

**Comment by nesbox** [comment]
any updates?
Did wallet rescan help you?
Thanks

**Comment by vsnation** [comment]
**Thanks! Issue solved.**
