### ISSUE TITLE
Add api func to search block by kernel id to the Node Explorer

### ISSUE THREAD

**Issue by nesbox** [BeamMW/beam#495]

**Comment by nesbox** [comment]
done
use `GET http://x.x.x.x:port/block?kernel={kernel}` request to get block data

**Comment by nesbox** [comment]
also, you can find block by `hash`
use `GET http://x.x.x.x:port/block?hash={hash}` request to get block data

**Comment by jurijakimuk** [comment]
Tested on 2.0.4555 (master). Works OK.
