### ISSUE TITLE
Update wallet-api.cfg template

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#499]
We need to update our cfg template with All new parameters:
HTTP
- use_http

ACL
 - use_acl
 - acl_path

TLS 
  - use_tls
  - tls_cert
  - tls_key

Whitelist
- ip_whitelist

According to #423  #488 #489 #497

**Comment by nesbox** [comment]
updated `wallet-api.cfg`

**Comment by Sergei-Beam** [comment]
checked
