### ISSUE TITLE
Beam Node: parameter miner_type is not working?? (windows)

### ISSUE THREAD

**Issue by see7ter** [BeamMW/beam#504]
**Bug title**
Setup a node in Windows, and want to use gpu's. But miner_type parameter is not recognised. It seems it defaults to cpu (use miner_type=gpu in cfg file)

* Windows 10
* BEAM Build number latest( beam-node-1.2.4419)

![capture2](https://user-images.githubusercontent.com/25307892/53583664-52a76480-3b82-11e9-8452-17518552efe4.PNG)

![capture3](https://user-images.githubusercontent.com/25307892/53585371-0a8a4100-3b86-11e9-9c16-94dba7b58a87.PNG)

**Comment by see7ter** [comment]
also with the correct variable name

![capture2](https://user-images.githubusercontent.com/25307892/53583610-360b2c80-3b82-11e9-8699-1a07ca6714ea.PNG)

**Comment by gingervik** [comment]
hi @see7ter internal miner was removed from node
please, use external miner ([instruction](https://beam-docs.readthedocs.io/en/latest/rtd_pages/user_mining_beam.html#mining-using-external-miner)) or you can run validating node without miner_type parameter
