### ISSUE TITLE
Remove "category" from Addresses screens

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/beam#505]
**Bug title**
Remove "category" from Addresses screens

**Bug description**
"Category" is not implemented, also according to design in Zeplin, doesn't exist anymore 

![image](https://user-images.githubusercontent.com/45590119/53693278-f8d3b400-3da6-11e9-8609-a6a8dfbee3db.png)

**Comment by alexandrashelenkova** [comment]
Design for categories will be provided asap

**Comment by alexandrashelenkova** [comment]
Will be considered during redesign
