### ISSUE TITLE
Add an option to edit contact in address book

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/beam#507]
**Bug title**
Add an option to edit contact in address book

**Bug description**
It is possible only to delete contact
Please add an option to edit (to add comment)

**Comment by sasha-abramovich** [comment]
clone of https://github.com/BeamMW/beam/issues/506 ?

**Comment by jonathancross** [comment]
@sasha-abramovich Seems like a duplicate to me.  Adding / editing / removing comments are same thing in this case (1 field in the "Edit address" pop-over).

**Comment by alexandrashelenkova** [comment]
Contact ux will be improved soon, will provide design when it's ready
