### ISSUE TITLE
Cannot access mining function or create new address in desktop wallet

### ISSUE THREAD

**Issue by taefighter** [BeamMW/beam#509]
**Bug title**
Functions are missing or inaccessible in the desktop wallet

**Bug description**
It appears that there are certain UI buttons that I cannot access or are not appearing in the desktop app on my system. For example, I cannot create a new address. Where there should be a button to create a new address, I do not have one. I tried to edit addresses and delete all addresses. Neither method made a difference, as I cannot create a new address.

Additionally, I cannot turn on any mining options. I have the latest drivers, a GTX 1070, and the 8700k. There is no option to select either CPU or GPU mining. It is not that the options are visible and turned off. Rather, they are not there in a visible space. I have tried viewing the program in windowed and full screen mode, but neither makes a difference. 

**To Reproduce**
I am not sure. I installed and set up the app in Windows 10 Pro 64bit, but I do not know of anything I may have done differently from others. 

**Current behaviour**
This was detailed in the bug description.

**Expected behaviour**
I expected to be able to view UI options to enable mining and create/add addresses. 

**Platform and build**
Windows
10 Pro 64bit
1.2.4419

**Configuration, log, memory dump files (if applicable)**
Add relevant files. The filenames and locations are described here: https://github.com/BeamMW/beam/wiki/Folder-and-file-locations

**Log file(s) (if applicable)**
Add relevant log file(s),  located in the `logs` folder.

**Screenshots (if applicable)**
![addresses screenshot](https://user-images.githubusercontent.com/23706169/53778099-3dec0900-3ec1-11e9-833d-d59160be504a.jpg)

![settings screenshot](https://user-images.githubusercontent.com/23706169/53778201-8b687600-3ec1-11e9-9aae-74b12608b203.jpg)

**Comment by gingervik** [comment]
Hello @taefighter 
1. For new address creation please push on receive button
2. GPU mining was removed from UI wallet. Now Run local node means run validating node on CPU (mining_threads=1) We have instruction for mining using external miner [here](https://beam-docs.readthedocs.io/en/latest/rtd_pages/user_mining_beam.html#mining-using-external-miner)
