### ISSUE TITLE
Check the use case when 1+ wallets are running with the same seed phrase 

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#511]
We have fixed all known issues with this scenario, but, as I know, we didn't perform complete test of this scenario

**Comment by gingervik** [comment]
most of checks were done.
will be recheck and add tests to testquality

**Comment by Sergei-Beam** [comment]
Rechecked with different cases.

**Positive tests.**
Checked case when Wallet and node run on the phrases.
Expected result: Balance updates every time when user spends or receives money
Wallets setups:
- Mobile vs UI Wallet
- Mobile vs CLI Wallet
- UI Wallet vs UI Wallet
- CLI Wallet vs UI Wallet

Nodes setups (same seed phrase):
- Local vs Local
- Remote vs Local
- Remote vs Remote

**Negative tests**
Checked case when Wallet and node run on different phrases.
Expected result: Balance doesn't update

Wallets setups:
- Mobile vs UI Wallet
- Mobile vs CLI Wallet
- UI Wallet vs UI Wallet
- CLI Wallet vs UI Wallet


**Separately were checked:**
- create 2 wallets with the same addresses( not clones) by exporting addresses and sending money to one of them
- sending the same utxo from different wallets(double spent)
- getting the utxo  with the same amount by two wallets
