### ISSUE TITLE
Node Explorer: Implement old logs auto-delete 

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#515]
**Bug description**
Let's delete the old logs like it's currently made for the archive node.
We need to copy exactly the same functionality.

**Acceptance Criteria**
1. The logs for the last 5 days are saved. 
2. The logs older than 5 days are deleted when the executable is run by the user. (Triggered by running the application).
3. The logs older than 5 days are deleted when the node explorer has been running non-stop for more than 5 days. (Due to the System Time).
4. The new parameter and the default value '5' is added to the configuration file.
```
# old logs cleanup period (days)
# log_cleanup_days=5
```
5. The `log_cleanup_days `parameter can be changed by the user.
6. The delete event is logged and printed out , e.g. 
`I 2019-03-11.13:02:09.544 removing old log file "C:\Users\jurij\Documents\Beam\Tests\masternet\beam-wallet\logs\wallet_19_02_22_16_44_52.log"`
![image](https://user-images.githubusercontent.com/41323026/54115675-01a73400-43fe-11e9-9844-13f00f7ba78a.png)

**Notes**
The related task: #254.

**Comment by gingervik** [comment]
should be discussed. not sure that we need it for explorer-node

**Comment by jurijakimuk** [comment]
Tested on master, 4600. 
1-5: OK. 
6: @nesbox Please, add printing out of the deleted files, thank you.

**Comment by nesbox** [comment]
> Tested on master, 4600.
> 1-5: OK.
> 6: @nesbox Please, add printing out of the message what files have been deleted, thank you.

fixed here a265487!

**Comment by jurijakimuk** [comment]
Retested on 4604, master. Works OK.
