### ISSUE TITLE
MacOS binaries still unsigned on Travis :(

### ISSUE THREAD

**Issue by nesbox** [BeamMW/beam#517]

**Comment by gingervik** [comment]
checked on 2.0.4606 and 4611
macOS 10.14.3, 10.14.1, 10.13.6
No warning about unsigned app when user run it first time

**Comment by gingervik** [comment]
please, sign all installer not only BeamWallet.app

**Comment by nesbox** [comment]
DMG was signed here 923fe13

**Comment by gingervik** [comment]
checked
