### ISSUE TITLE
How to complie the testnet wallet-api in ubuntu

### ISSUE THREAD

**Issue by ruanqunfeng** [BeamMW/beam#518]
Describe which documentation is broken or missing here.

**Comment by ruanqunfeng** [comment]
In linux

**Comment by ruanqunfeng** [comment]
![image](https://user-images.githubusercontent.com/15098545/54185359-c97a2100-44e3-11e9-9f84-826bec0b06cf.png)

**Comment by Sergei-Beam** [comment]
@nesbox Can you help there?

**Comment by nesbox** [comment]
sure, pls update your cmake
```
  wget "https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.sh"
  sudo sh cmake-3.12.0-Linux-x86_64.sh --skip-license --prefix=/usr
```

**Comment by ruanqunfeng** [comment]
![image](https://user-images.githubusercontent.com/15098545/54192521-1dd8cd00-44f3-11e9-85f9-583143293772.png)

**Comment by ruanqunfeng** [comment]
also has this problem

**Comment by nesbox** [comment]
ok, what do you see if you call `cmake -version`

**Comment by ruanqunfeng** [comment]
![image](https://user-images.githubusercontent.com/15098545/54192685-8162fa80-44f3-11e9-8c09-f53a77f3e443.png)

**Comment by nesbox** [comment]
hmm, all looks ok, pls try to call `cmake .` again, maybe it requires to restart terminal after install
