### ISSUE TITLE
System doesn't update verification words

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#52]
Steps:
- install new wallet
- click create a new wallet
- create local node
- go to generating recovery phrases screen
- when phrases generated click "Next" 
- the system asks you to enter 6 words to ensure the recovery phrases are written down
- chose to create the local node and go to generating recovery phrases screen
- click "Back" to generating recovery phrases screen
- click "Next" 
Actual: Wallet doesn't update 6 verification words, they still the same as on the first generate
Expected: I think we should generate new words each time when user went back from the screen
<img width="992" alt="default" src="https://user-images.githubusercontent.com/44496108/48249526-70eb2800-e40c-11e8-8da8-efe096b9886a.png">

**Comment by Denis-Asipenko** [comment]
checked
