### ISSUE TITLE
Display "where to buy beam" button (renamed task)

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/beam#520]
We want to make purchasing Beam as easy to find as possible.

1) Have "How To Buy" or "Exchanges List" in our website  //task will be opened on website

2) Use the Beam Icon in our desktop wallet for a web view that will include news and Exchanges list (two different pages)

3) Same thing with our mobile wallets //tasks will be opened on mobile

Important: ALL the external links need to be opened in a browser window outside the Wallet

Put the Exchanges without KYC first on the list

**Design**
zpl.io/aXPxJ7p (Cancel should be selected by default)
zpl.io/bzNgXxM
zpl.io/aR157K0
zpl.io/blPjJe1

@beam-mw please reassign and prioritise according to priorities

**Comment by sasha-abramovich** [comment]
it was decided to have only "where to buy Beam" button and a dialog that will ask permission and an option to switch it on/off in settings.

@alexandrashelenkova we need design please

**Comment by alexandrashelenkova** [comment]
Screens are here
ios
zpl.io/VqWLnGl
zpl.io/25OMeK8
zpl.io/a87NwOX

android
https://zpl.io/V1lmB4X
zpl.io/bJ7ALpx
zpl.io/aRxPxGK

**Comment by alexandrashelenkova** [comment]
Screens for android updated here
zpl.io/bAE0JWx
zpl.io/aRxPxGK

For ios there's no good place for that link yet (cause no sidemenu), so decided to look, how popular this feature gonna be for android users and then add it or not on ios

**Comment by sasha-abramovich** [comment]
@dariatarakanova @alexandrashelenkova we also need the design for desktop, do we have it please?

**Comment by dariatarakanova** [comment]
ios:
https://zpl.io/VYr8mgJ
https://zpl.io/VqveGjZ

**Comment by sasha-abramovich** [comment]
we don't need it for iOS at least yet, as about desktop - let's pass it by @alexandrashelenkova when she's back

**Comment by alexandrashelenkova** [comment]
Desktop version is ok 👍

**Comment by echoby** [comment]
https://www.beam.mw/#exchanges

**Comment by gingervik** [comment]
@echoby switcher should be added to settings
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5b8277d0a4b13457087a631f

**Comment by gingervik** [comment]
Please, change switcher text to 
Allow access to beam.mw (to fetch exchanges)

**Comment by gingervik** [comment]
checked
