### ISSUE TITLE
Documentation Update: new parameter to Wallet API to send specific UTXO

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#521]
Need to update Wallet API documentation according to new ticket #502

**Comment by Sergei-Beam** [comment]
Also, make an update with all new methods and changes from #528 in this ticket

**Comment by nesbox** [comment]
API wiki should be updated with:
- [ ] send specific UTXO api
- [ ] tx_list - added date, get_utxo - added status, get/delete/edit contacts
- [ ] tx_status - added reason of failed TX
- [ ] explorer node, added block search by hash and kernel

**Comment by nesbox** [comment]
node/wallet api has been updated

**Comment by jurijakimuk** [comment]
Documentation updated.
