### ISSUE TITLE
Adjust masternet colors for the Desktop wallet 

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#522]
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889?seid=5c88ecd9a1202f046ea2d0ab

**Comment by alexandrashelenkova** [comment]
Svg version of the icon is here https://drive.google.com/open?id=1d2-r4EZpdTeOYHWKGLxfycR0-pvxlKYO

**Comment by Sergei-Beam** [comment]
Dropdowns still have previous colours
- click receive button -> Expires 
![image](https://user-images.githubusercontent.com/44496108/55217687-2af2fd00-5211-11e9-9c13-0cc4fa42f6f8.png)
- go to addresses -> edit address -> reproduced on both tabs My active addresses and My Expired addresses
![image](https://user-images.githubusercontent.com/44496108/55217750-55dd5100-5211-11e9-83f4-edeeb18c3b30.png)
- settings -> General setting block -> Lock screen
![image](https://user-images.githubusercontent.com/44496108/55217897-ac4a8f80-5211-11e9-80ef-026f5f576d63.png)

**Comment by jurijakimuk** [comment]
Tested on 4712, master. Works OK.
