### ISSUE TITLE
Desktop wallet - New icon for payment proof

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#525]
Please, provide new icon for payment proof (as discussed before)
Also, maybe we should show some text (for example Payment proof) when user hover to the icon
![image](https://user-images.githubusercontent.com/44496108/54353706-c5760c80-4665-11e9-989c-128b61662e40.png)

**Comment by alexandrashelenkova** [comment]
@Sergei-Beam @sasha-abramovich made few variations of the icon, please take a look
![sender-transaction-details](https://user-images.githubusercontent.com/7249484/54580019-152b4e00-4a41-11e9-9036-c3f50399dcb7.jpg)

**Comment by gingervik** [comment]
@sasha-abramovich please, choose one )

**Comment by sasha-abramovich** [comment]
Sorry for delay, I'd vote for the second from the left.

**Comment by gingervik** [comment]
@alexandrashelenkova please, provide icon in zepplin

**Comment by gingervik** [comment]
I am still not sure that icon is understandaple for user. But we add info about it in docs. hope, it'll help

**Comment by alexandrashelenkova** [comment]
@gingervik screens are updated zpl.io/a7Olx4M

**Comment by Sergei-Beam** [comment]
checked
