### ISSUE TITLE
Add Payment Proof to readthedocs.io

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#526]
**Description**
Need to add Payment Proof to the **user_desktop_wallet_guide** document.
The link to the documentaion: https://beam-docs.readthedocs.io/en/latest/rtd_pages/user_desktop_wallet_guide.html

**Comment by Jagor21** [comment]
Completed https://github.com/BeamMW/beam-docs/commit/8231430f61cce8b8ee555d0f95318da2b8686149

**Comment by gingervik** [comment]
@Jagor21 please add all changes acc notes in DM (from me and @Sergei-Beam )

**Comment by Jagor21** [comment]
Changes added here https://github.com/BeamMW/beam-docs/commit/787b465493acf52fc16f9f9e64607d8a7fdfdc0c

**Comment by gingervik** [comment]
checked
