### ISSUE TITLE
Fedora build instructions

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam#527]
Hey Guys!

It is not possible to create pull requests for wiki pages, so I'm posting it like this. 

Please consider adding the following changes to your docs: https://github.com/chapati/beam-wiki/commit/808bb1ffd63d4685c775de8090f126dae6f2d287

Also, it looks like your build instructions are incorrect at the momnt. Your docs state the following in the Linux/Ubuntu & Mac sections: 
 
>  find Beam binary in bin folder, beam-wallet in ui subfolder.

I was unable to find these binaries and it looks like this is just wrong. My commit above includes the real files/paths I was able to find. I've not updated any other sections on that page since I do not have Mac & Ubuntu to check. It looks like you should check it yourself and update the corresponding sections for every environment.

Thanks.

**Comment by gingervik** [comment]
@nesbox please help

**Comment by nesbox** [comment]
Merged your instructions here https://github.com/BeamMW/beam/wiki/How-to-build/712c3e0637056579399f2bfdb9dffc6c86c2cfcd
Thank you!
