### ISSUE TITLE
The button "I understand" moved out on the MacOs interface

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#53]
The button "I understand" moved out on the MacOs interface
MacOS: <img width="1022" alt="default" src="https://user-images.githubusercontent.com/44496108/48250094-2bc7f580-e40e-11e8-923f-25f733d4c5fb.png">
Windows: 
![image](https://user-images.githubusercontent.com/44496108/48250332-07204d80-e40f-11e8-919d-a4b94c7ef779.png)

**Comment by Alesio7** [comment]
Can this issue be closed now? I believe it's been fixed

**Comment by anatolse** [comment]
Ok. Closing
