### ISSUE TITLE
Passphrase when sending funds from wallet

### ISSUE THREAD

**Issue by sikkan666** [BeamMW/beam#532]
**Feature title**
Express the feature in a single concise sentence

Would want a passphrase option/requirement when sending funds from BEAM wallet.

**Describe the current situation we have**
Please bring in the relevant context: what are you suggesting to achieve vs what the current situation is. 

there is currently no such option/requirement, making the wallet vulnerable to unauthorized access where a user might have left the wallet online to be enabled for receiving funds or is awaiting funds to be transferred from an exchange, which may take some time.
**Describe the solution you'd like**

Implement a passphrase option/requirement upon sending funds.
**Describe alternatives you've considered (if relevant)**

**Additional context**

**Comment by gingervik** [comment]
hi @sikkan666 
we are going to implement this https://github.com/BeamMW/beam/issues/146
