### ISSUE TITLE
Missing Consensus Rules options for API

### ISSUE THREAD

**Issue by harzo** [BeamMW/beam#536]
**Missing Consensus Rules options for API**

Putting any Consensus Rules option into `wallet-api.cfg` causes Error:
```E 2019-03-19.11:03:57.220 EXCEPTION: unrecognised option '--Maturity.Coinbase=1'```

but API still verifies Rules signature:
 ```W 2019-03-19.09:27:58.597 127.0.0.1:45520: Incompatible peer cfg!```

**Expected behaviour**
Putting Consensus Rules into api's config file don't cause errors \
Produced Rules signature should match wallet's/node's using the same options.

**Comment by nesbox** [comment]
Added rules options to wallet and explorer api here 0530ea5

**Comment by Sergei-Beam** [comment]
checked
