### ISSUE TITLE
Wallet API - hide kernel lines for failed statuses(method tx_status)

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#537]
Hide kernel lines for method tx_status if the transaction has one of the failed statuses and kernel like on the screen (00000000000...000)
![image](https://user-images.githubusercontent.com/44496108/54606129-fb4b3480-4a5b-11e9-8ae1-2866b6b1063e.png)

**Comment by nesbox** [comment]
fixed here 4431dd5

**Comment by Sergei-Beam** [comment]
Please, also remove the kernel for cancelled transactions
![image](https://user-images.githubusercontent.com/44496108/54807530-97f51880-4c8e-11e9-89fc-a9f0e169385d.png)

**Comment by Sergei-Beam** [comment]
checked
