### ISSUE TITLE
[UI and CLI] User can create a password containing white spaces

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#542]
**Bug description**
User can create a password containing white spaces.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start creating a new wallet.
2. Create and confirm the password: " " (a single white space).

**Current behaviour**
User can create such a password.

**Expected behaviour**
User can not provide white space(s) as a password.

**Comment by alexandrashelenkova** [comment]
User can add spaces to password, so it's not a bug here
