### ISSUE TITLE
Prepare release notes for testnet and mainnet release

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#543]
Releases are comming, please, prepare release notes for testnet (first) and mainnet releases

**Comment by sasha-abramovich** [comment]
The notes will be for both testnet and mainnet :)

**Comment by sasha-abramovich** [comment]
https://docs.google.com/document/d/1vwsMchVJpxRnLwJNUKlzkWkRtrTPg_r2DpkadjHS1AE/edit#
