### ISSUE TITLE
Edit the data of Beam Wallet application in Programs and Features

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#546]
**Bug description**
We need to improve the Beam Wallet application data displayed in Windows' Programs and Features window.  
**To do:**
1) Display the application icon.
2) Display the application size.

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/41323026/54745969-07f69680-4bdc-11e9-832c-796410005205.png)

Related task (done) : #380.

**Comment by beam-mw** [comment]
Probably fixed with new installer. Please retest
