### ISSUE TITLE
Wallet crash while deleting transaction

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/beam#552]
**Bug title**
Wallet crash whole deleting transaction

**To Reproduce**
1. Open wallet and Login
2. Delete one of the transactions

**Current behaviour**
Wallet crashes

* Reproduced on Mac and Windows 
* BEAM Build number 2.0.4707

Always reproduced on MAC
Reproduced also on Windows, but not consistently

**Comment by kaminskyelina** [comment]
[beam_ui_19_03_24_18_44_31.log](https://github.com/BeamMW/beam/files/3000598/beam_ui_19_03_24_18_44_31.log)

**Comment by gingervik** [comment]
[Beam Wallet Testnet damp.zip](https://github.com/BeamMW/beam/files/3001960/Beam.Wallet.Testnet.damp.zip)

**Comment by Sergei-Beam** [comment]
checked
