### ISSUE TITLE
The deleted transaction appears in "receiving" status

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#554]
**Bug description**
When a successful incoming transaction is deleted - then after the wallet restart - this transaction appears in "receiving" status.

**To Reproduce**
**Pre-conditions:** 
Wallet A, Wallet B UI wallets are installed.
Wallet A has some UTXO to send.
**Steps:**
1. From Wallet A send some UTXO to Wallet B.
2. Wallet B receives the transaction and the transaction is in "received" status.
3. Delete the transaction in Wallet B.
4. Close and reopen Wallet B.

**Current behaviour**
The deleted transaction appears in the "receiving" status.
![image](https://user-images.githubusercontent.com/41323026/54914115-486c5200-4f05-11e9-9731-cf70084e1bc7.png)

**Expected behaviour**
The deleted transaction is not displayed.

**Comment by Sergei-Beam** [comment]
checked
