### ISSUE TITLE
Block Explorer - Accessing Block Page by height/kernel

### ISSUE THREAD

**Issue by harzo** [BeamMW/beam#557]
Block Explorer - Accessing block by its height/kernel
--

**Describe the current situation we have**
There is only one way to access Block Page - by
`https://explorer.beam.mw/block/{blockHash}`

**Describe the solution you'd like**
Block Page can be viewed by providing hash or kernel only: 
`https://explorer.beam.mw/block/?kernel={kernelId}`
`https://explorer.beam.mw/block/?height={height}` 

**Additional context**
As a user I would like to check on explorer if transaction kernel is present on blockchain.

**Comment by gingervik** [comment]
hi @harzo 
seems like it was done here (https://github.com/BeamMW/beam/issues/495) 
will be released soon

**Comment by gingervik** [comment]
released. can be closed
