### ISSUE TITLE
Remove cli options  from utilities

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#559]
options.h/cpp brings unexpected dependencies to all projects which use utility. We need to move these cli options close to the places they are used. To beam-node and to beam-wallet and ui.

**Comment by jurijakimuk** [comment]
To be merged

**Comment by jurijakimuk** [comment]
Tested on 4725, master. Looks like the options still work.

**Comment by jurijakimuk** [comment]
Looks like the options functionality has not got broken. Tested on master, 4725
