### ISSUE TITLE
Add ability to paste recovery phrases with spaces/symbols at the beginning or end of the words (Testnet only)

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#56]
1. We should ignore the spaces if user pasted the **correct word** with the spaces at the beginning or end of the word 
<img width="1319" alt="default" src="https://user-images.githubusercontent.com/44496108/48257581-f1695300-e423-11e8-9c67-e53348f7c8c5.png">
2.  We should ignore any symbols if user pasted the **correct word** with symbols at the beginning or end of the word 
<img width="1324" alt="default" src="https://user-images.githubusercontent.com/44496108/48257870-ccc1ab00-e424-11e8-8a93-674c4fce91ae.png">

**Comment by sasha-abramovich** [comment]
This trick can be nice for Testnet, but not for Mainnet. Security will be compromised.

**Comment by gingervik** [comment]
irrelevant
