### ISSUE TITLE
Addresses screen- cannot edit address from "never" to "24 hours"

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#560]
<p>Steps to reproduce the behaviour:
1. Go to Receive screen.
2. Create a new address. select &quot;expires: never&quot;
3. Go to Addresses screen.
4. Click on three dots to open the action menu and select &quot;edit address&quot;
5. Change &quot;Expires&quot; from never to 24h and click Save.
Expected: Changes are saved.
Actual: Changes are not saved.</p>

**Comment by gingervik** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D2. Do not remove or edit.` [D2](https://beam.testquality.com/project/5267/result/1054843/defect/3783)

**Comment by gingervik** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D4. Do not remove or edit.` [D4](https://beam.testquality.com/project/5267/result/1067063/defect/3808)

**Comment by jurijakimuk** [comment]
Tested on 4712, master. Works OK.
