### ISSUE TITLE
Old Synced->New Non-Synced: Transaction appears only after restart

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#564]
**Description**
Transaction that is sent from the Old Synced Wallet (<= 4431) to the New Non-Synced Wallet (> 4431,  height difference with blockchain more than 120 blocks) appears only after restart of the wallet when it's fully synced.

**To Reproduce**
**Pre-conditions:**
Old Synced Wallet (<= 4431)  is installed and running. There is some UTXO to send from this wallet.
New Non-Synced Wallet (> 4431)  is installed and running. It's connected to a wrong/ unexisting remote node, so it's not being synced.
**Steps**:
1. Send some UTXO from Old Synced Wallet  to New Non-Synced Wallet.
2. Start Synchronization of New Non-Synced Wallet.
3. When the sync is over check the transaction status in both wallets.

**Current behaviour**
Sender: The transaction is in "waiting for receiver" status.
Receiver: The transaction has not appeared.

**Expected behaviour**
Sender: The transaction is in "sending" status and then "sent".
Receiver: The transaction is in "receiving" status and then "received".

Notes:

1. The expected behavior is seen when the receiver's wallet is restarted.
2. After sync is over, if NOT to restart the receiver's wallet and sent some UTXO to it to the same address - the new transaction appears and succeeds, but the old transaction does not.

**Platform and build**
* Windows 10 , Linux 18
* Old and new versions in the test: old -> 4412, new -> 4721, testnet.

**Configuration, log, memory dump files (if applicable)**

**Screenshots (if applicable)**
![bug_before_rerun](https://user-images.githubusercontent.com/41323026/55001204-1df1c600-4fe5-11e9-8bea-760c1c540347.png)

Receiver's wallet data zipped:
[Beam Wallet Testnet.zip](https://github.com/BeamMW/beam/files/3008447/Beam.Wallet.Testnet.zip)

**Comment by beam-mw** [comment]
Let's retest this closer to the next release. actual (Bright Boson 2.0) to new (Bright Boson 2.1)

**Comment by gingervik** [comment]
@Sergei-Beam please, check this on new testnet build (with previous one)

**Comment by Sergei-Beam** [comment]
Rechecked
Transaction successfully sent  and received from the Old Synced Wallet (v2.0.4751) to the New Non-Synced Wallet (v2.0.4912)
