### ISSUE TITLE
UI Wallet: Connection is randomly interrupted when connected to remote node.

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#567]
**Bug description**
 The connection is randomly interrupted when connected to remote node. This is seen mostly with **eu nodes**. The connection is restored in a few seconds after it&#39;s lost. 

**To Reproduce** 
1. Install and start setting up UI Wallet.
2. Choose &quot;connect to a random node&quot; and proceed. 
3. Follow the Connection Indicator status while the app is running. 

**Current behaviour**
 The connection is lost from time to time. 

**Expected behaviour** 
The connection is on all the time. 

**Build** testnet, 4721

**Comment by jurijakimuk** [comment]
Seen also with ap nodes on testnet.

**Comment by gingervik** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D5. Do not remove or edit.` [D5](https://beam.testquality.com/project/5267/result/1067069/defect/3809)

**Comment by jurijakimuk** [comment]
[beam_ui_19_04_08_16_03_53.log](https://github.com/BeamMW/beam/files/3054399/beam_ui_19_04_08_16_03_53.log)
@Aleksandr-Starun Pleasem find the log attached.

**Comment by jurijakimuk** [comment]
@Aleksandr-Starun Attaching a zipped video with the issue and the new log file. The issue appears at 3:05 in the video.
[connection error.zip](https://github.com/BeamMW/beam/files/3054444/connection.error.zip)
[beam_ui_19_04_08_16_11_54.log](https://github.com/BeamMW/beam/files/3054447/beam_ui_19_04_08_16_11_54.log)

**Comment by jurijakimuk** [comment]
Node balancer issue. Being fixed by the devops.
