### ISSUE TITLE
Implement filter and other table actions for every table view (UTXO, transactions, address book)

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#57]
Please add filter and other table actions as shown in zeplin: https://zpl.io/bWLWYDM
<img width="1024" alt="default" src="https://user-images.githubusercontent.com/44496108/48258669-b9afda80-e426-11e8-8493-5d1035a49853.png">

**Comment by alexandrashelenkova** [comment]
Add tabs only, filter flow would be in separate task
