### ISSUE TITLE
UI Wallet - different tx sender's and receiver's statuses if wallet is updated during sending

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#571]
<p>Preconditions:</p><p>Wallet_A - version 4419 (old wallet)</p><p>Wallet_B - version 4720 (new wallet)</p><p><br></p><p>Steps:</p><p>- open both wallets and generate an address on Wallet_B</p><p>- go to Wallet_A</p><p>- open Receive tab, paste and send the transaction</p><p>- check the logs and wait while the Walelt_A got the proof from Wallet_B</p><p>- after got it close the Wallet_A</p><p>Note: sender&#39;s transaction should be in &quot;Sending&quot; status when you close the Walelt_A</p><p>- wait while the receiver got transaction&#39;s status &quot; received&quot;</p><p>- replace the Beam-Wallet.exe from version 4419 to 4720 for Wallet_A</p><p>- run Wallet_A and wait while it will be synced</p><p>Expected: AFter sync transaction have the status &quot;sent&quot; after sync</p><p>Actual: After sync, transaction has &quot;Failed&quot; status</p><p>![image](https://user-images.githubusercontent.com/44496108/55060049-9c9c4100-5081-11e9-9864-9489fa14bb90.png)</p><p><br></p><p>Sender&#39;s log:</p><p>[sender_logs.zip](https://github.com/BeamMW/beam/files/3012210/sender_logs.zip)</p><p><br></p><p>Receiver&#39;s log:</p><p>[receiver_log.zip](https://github.com/BeamMW/beam/files/3012217/receiver_log.zip)</p><p><br></p>

**Comment by Sergei-Beam** [comment]
Reproduced with a bit different conditions

Preconditions:
Wallet_A - version 4419 (old wallet)
Wallet_B - version 4669 (new wallet)

Steps:

- open both wallets and generate an address on Wallet_B
- close the Wallet_B
- go to Wallet_A
- open Receive tab, paste and send the transaction
Note: transaction status "waiting for receiver" 
- close the Walelt_A
- replace the Beam-Wallet.exe from version 4419 to 4669 for Wallet_A
- run Wallet_A and wait till Wallet_A is fully synced.
- run Wallet_B
Expected: After running Wallet_B the wallets began to communicate with each other.
Wallet A:
The transaction changes status from "waiting for receiver" to "sending" and then "sent".
Wallet B:
The transaction appears in the list of transactions in "receiving" status and then "received".
Actual: Transaction on the Wallet_A is "Failed", on the Wallet_B stucks in "receiving" status
![photo_2019-03-27_17-34-08](https://user-images.githubusercontent.com/44496108/55087273-e6ede400-50ba-11e9-8dda-b5eba9c9f759.jpg)

**Comment by gingervik** [comment]
will be checked at the end of sprint 2.1

**Comment by gingervik** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D11. Do not remove or edit.` [D11](https://beam.testquality.com/project/5267/result/1067128/defect/3817)

**Comment by gingervik** [comment]
Discussed with @echoby
Won't fix as it can cause a lot of problems in newer version.
