### ISSUE TITLE
Crash in UI Wallet 

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#573]
**Bug title**
UI Wallet crashes on restart

**Bug description**
There is a race condition in node initialization. Sometimes NodeProcessor is initialized before node, in this case NodeProcessor has invalid value for verification threads number and as a result tries to allocate more resources that it has.

**To Reproduce**
1. Started wallet without local node
2. Turned on local node, waited
3. Restarted wallet - >crash

**Current behaviour**
Crash

**Expected behaviour**
Wallet should run

**Comment by gingervik** [comment]
cannot reproduce on new build
