### ISSUE TITLE
WIN builds are not uploaded to S3

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#574]
**Bug description**
WIN builds are not uploaded to С3

**Screenshots**
https://builds.beam.mw/#master/2019.03.27/Debug/
![image](https://user-images.githubusercontent.com/41323026/55088295-8cee1e00-50bc-11e9-99d8-1351d4d3bb80.png)

https://builds.beam.mw/#master/2019.03.27/Release/
![image](https://user-images.githubusercontent.com/41323026/55088532-ed7d5b00-50bc-11e9-8446-f2612960242f.png)

**Comment by gingervik** [comment]
checked on master
