### ISSUE TITLE
Able to set Port value out of accepted range.

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#575]
**Bug description**
In the Setup Node Conectivity screen currently it's possible to enter a port value more than **65535**. We must not allow users to enter value out of this range **1 - 65535**.
**_!!! Edited: The range must be 1 - 65535 !!! (not 0 - 65535)_**

**To Reproduce**
1. Start creating a wallet.
2. Proceed until the Setup Node Conectivity screen is on.
3. In the Run Integrated Node field enter a value more than 65535.

**Current behaviour**
User is able to enter a higher value than the right edge.

**Expected behaviour**
User is NOT able to enter a higher value than the right edge. Maximum possible port number to enter is 65535.

**Notes:**
Currently if the user enters port number higher than allowed, e.g. "88000" - then later there can be a problem switching to the remote node from local node in the app settings.

**Screenshots**
Add screenshots that illustrate a problem you've found.
![image](https://user-images.githubusercontent.com/41323026/55143174-3a117680-514f-11e9-837a-e0d15d65c68b.png)

**Comment by jurijakimuk** [comment]
OK on master, 4725.

**Comment by jurijakimuk** [comment]
Looks like port 0 is not acceptable.
The wallet is offline in this case. Minimal port number allowed must be 1.
Please, 
1) Do not allow entering of 0 as a port number.
2) Fix the message "Port must be a number between 0 and 65535" to "Port must be a number between 1 and 65535".
@echoby Thank you

**Comment by jurijakimuk** [comment]
Please, add the same validation on the Settings screen in these 3 places. Thank you.
![image](https://user-images.githubusercontent.com/41323026/55893008-1410bb00-5bc0-11e9-93fa-f3904d5ca536.png)

**Comment by Sergei-Beam** [comment]
checked
