### ISSUE TITLE
Do NOT print out sqlite errors if they are followed by a user friendly error message

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#576]
**Bug description**
When user enters wrong password to the CLI wallet - user doesn't want to see "sqlite error code=26, file is not a database" error. He/ she reads the next message "Please check your password. If password is lost, restore wallet.db from latest backup or delete it and restore from seed phrase." And that's the most important and enough.
Let's don't print out "sqlite error code=26, file is not a database"  if we're displaying a more human friendly message after that. 

**To Reproduce**
1. Run existing CLI wallet, e.g. `C:\Users\jurij\Documents\Beam\Tests\masternet\beam-wallet>beam-wallet info`.
2. Provide wrong password to the wallet.
3. See the error messages.

**Current behaviour**
```
D 2019-03-28.12:21:53.163 sqlite error code=26, file is not a database
E 2019-03-28.12:21:53.164 Please check your password. If password is lost, restore wallet.db from latest backup or delete it and restore from seed phrase.
```

**Expected behaviour**
`E 2019-03-28.12:21:53.164 Please check your password. If password is lost, restore wallet.db from latest backup or delete it and restore from seed phrase.`

**Platform and build**
* Windows
* 10 x64
* 4674, master

**Screenshots**
Add screenshots that illustrate a problem you've found.
![image](https://user-images.githubusercontent.com/41323026/55146379-82cc2e00-5155-11e9-91fb-462a7cfc3e2b.png)

**Comment by anatolse** [comment]
Why? We log all sqlite errors, it's normal. The second message is from  higher level logic.
