### ISSUE TITLE
CLI Wallet: Change the error message text when invalid seed phrase is provided.

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#577]
**Bug description**
When user restores CLI wallet and provides wrong seed_phrase - the following message appears: 
Invalid **seed phrases** provided: apple;apple;apple;apple;apple;apple;apple;apple;apple;apple;apple;app_le;
We need to change **"seed phrases" to "seed phrase".**
And we could also change "**Please, provide seed phrase for the wallet.**" to  "**Please, provide a valid seed phrase for the wallet**".

**To Reproduce**
1. Restore the CLI wallet with invalid seed phrase: `beam-wallet restore --seed_phrase=apple;apple;apple;apple;apple;apple;apple;apple;apple;apple;apple;app_le;`
2. Provide the password to proceed.
3. See the error message.

**Current behaviour**
```
E 2019-03-28.12:36:20.664 Invalid seed phrases provided: apple;apple;apple;apple;apple;apple;apple;apple;apple;apple;apple;app_le;
E 2019-03-28.12:36:20.666 Please, provide seed phrase for the wallet.
```

**Expected behaviour**
```
E 2019-03-28.12:36:20.664 Invalid seed phrase provided: apple;apple;apple;apple;apple;apple;apple;apple;apple;apple;apple;app_le;
E 2019-03-28.12:36:20.666 Please, provide a valid seed phrase for the wallet.
```
**Platform and build**
* Windows
* 10 x64
* Beam Wallet 2.0.4674 (master)

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/41323026/55147762-0be46480-5158-11e9-9e69-e56ee1f686a1.png)

**Comment by gingervik** [comment]
checked
