### ISSUE TITLE
Wallet is not started if system time is incorrect

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#578]
**Bug description** 
Wallet is not started if system time is incorrect. 

**To Reproduce** 
Pre-conditions: A UI wallet is installed but NOT running. System time is correct. 

**Steps to reproduce the behaviour:**
 1. Change the system time to wrong time. 
2. Run the wallet. 

**Current behaviour** Wallet is not starting. 
**Expected behaviour** The wallet has started. 

The indicator shows the status &quot;System time not synchronized&quot;. ![image](https://user-images.githubusercontent.com/41323026/55228730-f04a8e00-522b-11e9-9cbc-d4f37ec063a8.png) 
**Platform and build**  Windows 10 x64 4731, testnet 
**Log file(s) (if applicable)** [beam_ui_19_03_29_14_01_15.log](https://github.com/BeamMW/beam/files/3022339/beam_ui_19_03_29_14_01_15.log)

**Comment by gingervik** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D7. Do not remove or edit.` [D7](https://beam.testquality.com/project/5267/result/1067075/defect/3812)

**Comment by jurijakimuk** [comment]
Please, change the indicator status to:
"System time not synchronized" , like on the screenshot:
![image](https://user-images.githubusercontent.com/41323026/56887551-97645480-6a7a-11e9-9877-2663574ece63.png)
if we're detecting a time difference while the wallet is running:
![image](https://user-images.githubusercontent.com/41323026/56887637-c5499900-6a7a-11e9-8546-e152c3ab1260.png)

**Comment by Sergei-Beam** [comment]
@echoby After changing the system time Wallet still have the indicator "Online" instead of "System time not synchronized"
![image](https://user-images.githubusercontent.com/44496108/57125660-d8b67600-6d92-11e9-9400-a5ed150c5b8b.png)

Also in logs disappeared the message "Time diff too long....."

**Comment by gingervik** [comment]
Regression
Stucks on downloading screen without any errors
![image](https://user-images.githubusercontent.com/28015224/57228270-0d892e00-701c-11e9-93c5-b9e21c6c766e.png)

**Comment by gingervik** [comment]
Also I do not like many duplicates of error
![image](https://user-images.githubusercontent.com/28015224/57229663-52629400-701f-11e9-99d2-636b593a81d9.png)

**Comment by Sergei-Beam** [comment]
checked
