### ISSUE TITLE
Sender did not receive the transaction when updating from old version.

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#580]
**Bug description**
Sender did not receive the transaction when updating from old version. wallet.db's, logs attached.

**To Reproduce**
1. Install Wallet A, old, 4412.
2. Install Wallet B, new, 4731.
3. Send some UTXO from Wallet B to Wallet A.
4. When the transaction appears in sending and receiving statuses accordingly - close Wallet A.
5. Install the new version (4731) over the old Wallet A.
6. Start Wallet A and wait till new node.db is synced.
7. Check the transaction statuses.

**Current behaviour**
The transaction is sent in Wallet B.
The transaction is **receiving** in Wallet A.
The transaction has **DIFFERENT** kernel IDs.

**Expected behaviour**
The transaction is sent in Wallet B.
The transaction is **received** in Wallet A.
The transaction has the **SAME** kernel ID.

**Platform and build**
* Windows, 10 x64
4412, 4731, testnet.

**Log file(s) (if applicable)**

[sender logs.log](https://github.com/BeamMW/beam/files/3022617/sender.logs.log)
[receiver logs.log](https://github.com/BeamMW/beam/files/3022618/receiver.logs.log)
[wallet.db files.zip](https://github.com/BeamMW/beam/files/3022621/wallet.db.files.zip)

**Screenshots (if applicable)**
![screen](https://user-images.githubusercontent.com/41323026/55232754-82a45f00-5237-11e9-93cf-eedb0d1e10e1.png)

**Comment by gingervik** [comment]
let's check it at the end of bb 2.1

**Comment by jurijakimuk** [comment]
Works as expected on 4735, master.
