### ISSUE TITLE
Ui wallet - Connection is not restored after user was offline (internet was off)

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#582]
Reproduced on testnet
Precon: user has installet UI wallet with connection to remote node

Steps:
- run wallet
- do not enter password
- turn off internet connection
- login
- see your wallet main screen and "Connection error. (testnet)" as status of connection
- turn on your internet

Actual: nothing is changed. Wallet doesn not try to reconnect to remote node
Expected: wallet should be online if internet connection was restored

**Comment by gingervik** [comment]
[beam_ui_19_04_01_10_24_27.log](https://github.com/BeamMW/beam/files/3028205/beam_ui_19_04_01_10_24_27.log)
<img width="1023" alt="Снимок экрана 2019-04-01 в 10 43 34" src="https://user-images.githubusercontent.com/28015224/55311245-10b45b80-546b-11e9-87af-e198f8638808.png">

**Comment by Sergei-Beam** [comment]
One more case

Steps:
- run remote wallet and login
- turn off the internet connection
- go to the setting and switch from remote to local mode
- apply settings
-  return switcher to remote mode
- apply settings
- see your wallet main screen and "Cannot connect to node" as status of connection
- turn on your internet

Actual: nothing is changed. Wallet does not try to reconnect to the remote node
![image](https://user-images.githubusercontent.com/44496108/55880317-20d5e480-5ba9-11e9-9d86-04263ba0b760.png)
![image](https://user-images.githubusercontent.com/44496108/55880339-28958900-5ba9-11e9-8c28-c5392942a166.png)
Expected: wallet should be online if the internet connection was restored

**Comment by Sergei-Beam** [comment]
Reconnection fixed

**Comment by Sergei-Beam** [comment]
The wallet lags when I type the remote address in text format
![2019-04-24_16-53-13](https://user-images.githubusercontent.com/44496108/56664945-c57c1a00-66b1-11e9-9835-e8a0828a25c2.gif)
I think it's related to new address check

**Comment by Sergei-Beam** [comment]
checked
