### ISSUE TITLE
When setting/entering the local password - warn user if CAPS is ON

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#586]
@alexandrashelenkova please prepare the design and reassign to @anatolse

**Comment by dariatarakanova** [comment]
ios https://zpl.io/2j50REr

**Comment by dariatarakanova** [comment]
@alexandrashelenkova please check

**Comment by alexandrashelenkova** [comment]
@dariatarakanova I think we might have that alert only for desktop version. For desktop toast looks good, maybe would just do it's background a bit more opacity?

**Comment by gingervik** [comment]
already done
