### ISSUE TITLE
User-friendly desktop wallet migration

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#587]
* Should have "auto migrate" button by choosing the latest wallet.db and "manual migration" to open the screen to select the node.db file manually
* During manual migration should sort the files in descending "Date modified" and auto-select the most recent one

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova please create the design and reassign to @echoby

**Comment by sasha-abramovich** [comment]
See also: https://github.com/BeamMW/devops/issues/39

**Comment by alexandrashelenkova** [comment]
@sasha-abramovich added migration screens here https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/dashboard?seid=5c373ce13888c4296db07d4f

**Comment by Sergei-Beam** [comment]
@echoby 
1. The wallet cannot read the wallet.db if wallet path include Russian(Cyrillic)
![image](https://user-images.githubusercontent.com/44496108/59666322-48ef4e80-91bd-11e9-81be-7bdb5196cbea.png)
2. Sorting
2.1 We should sort all files descending sort from the last `Date modified`
2.2 For the case when the Wallet installed to specific user's folder at first we should show all files sorted by descending from this specific folder and then all files from default folder (`%AppData%` ) sorted by descending too

**Comment by VladislavKulyba** [comment]
checked

**Comment by Sergei-Beam** [comment]
checked
