### ISSUE TITLE
Mac GUI build fails to create an .app file, only creates executable

### ISSUE THREAD

**Issue by breadsax** [BeamMW/beam#588]
I believe the previous code on mainnet built an .app file in the ui subfolder when compiling on Mac OS. I compiled yesterday after Bright Bosom was officially released and there was no .app file, just the executable. Can this be updated or instructions added to the Mac build steps so that an .app file can be created from the executable binary? Thanks!

**Comment by nesbox** [comment]
You're right, we dropped out `.app` creation phase because we added binaries signing with our certificate. So, at the moment you can only create a `.dmg` installer by calling `cpack` command and extract `.app` from the `.dmg`.
