### ISSUE TITLE
Add ability to create and sign transaction via files exchange

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#593]
By default we use SBBS to communicate between wallets. We need to add an option to store intermediate messages in files to be able to create and sign transaction offline

**Comment by anatolse** [comment]
https://github.com/BeamMW/beam/wiki/Cold-wallet-implementation

**Comment by jurijakimuk** [comment]
To fix:
1) Cold wallet restore
When the restored wallet.db from the cold wallet is moved to the hot wallet - The coins are not restored in the hot wallet when the hot wallet is launched.  
2) Cold wallet receive.
The coins are not received in the hot wallet on [Step 7](https://github.com/BeamMW/beam/wiki/Cold-wallet-implementation#receiving-to-cold-wallet).
The transaction hangs in "waiting for sender" status in the hot wallet.
![image](https://user-images.githubusercontent.com/41323026/56816016-563a2d80-684b-11e9-9541-bbe8fbb98672.png)

**Comment by jurijakimuk** [comment]
OK on master build, 5156
