### ISSUE TITLE
show TX_Id in transaction details

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#596]
Only Kernel ID is not enough. Before reaching blockchain transactions have only TX_ID (and they can fail at this stage). Hence, some exchanges are operating by TX_IDs and not Kernel_IDs

**Comment by alexandrashelenkova** [comment]
Added here zpl.io/2vYm4R7
zpl.io/VDB1y8v
zpl.io/VqwGJR4

**Comment by gingervik** [comment]
@sasha-abramovich @alexandrashelenkova are you sure that we need it "not stored **on** blockchain"?
user can think that smth wrong with transaction

**Comment by sasha-abramovich** [comment]
@gingervik How about adding something like "Kernel ID is enough to be stored on blockchain, TXID is not stored"? I'll rephrase of course :)

**Comment by gingervik** [comment]
@sasha-abramovich why should we have any this comment at all. if user openes details he knows what he want to take from

**Comment by sasha-abramovich** [comment]
@gingervik hmmm! well, we are writing about transaction comment that it is not stored on blockchain. thought that being consistent is better... but I see your point, yet I see my point too. probably it's better to be more informative for the user, isn't that so?

**Comment by gingervik** [comment]
@sasha-abramovich nice example about comment. please, show me where are writing in **Desktop wallet** that it's not stored on blockchain (especially in Transaction's detailes)

**Comment by gingervik** [comment]
by the way in transaction's details a lot of data which is not stored on blockchain

**Comment by gingervik** [comment]
@sasha-abramovich if you are not going to discuss or make any changes in design now plz assign this issue on @echoby

**Comment by gingervik** [comment]
@echoby please, do as design

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova so far we've decided with @gingervik not to mention that tx-id is not stored on blockchain - please update the screenshots (the transaction extended details)

**Comment by Sergei-Beam** [comment]
@echoby Please, move down the Kernel ID as it is shown on the design
![image](https://user-images.githubusercontent.com/44496108/56907430-e2975b00-6aac-11e9-9cb5-fcea3b779491.png)

**Comment by Sergei-Beam** [comment]
checked
