### ISSUE TITLE
Multiple-gpu's support

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#60]

**Comment by gaoyang1120** [comment]
when multiple-gpu's support?

**Comment by gingervik** [comment]
we are working on it right now @gaoyang1120 
should be added soon

**Comment by gaoyang1120** [comment]
before mainnet luanch? Is there a specific time?

**Comment by gingervik** [comment]
we hope so.
no specific date for now
folow us on medium and in Telegram to see all news

**Comment by gingervik** [comment]
already supported
