### ISSUE TITLE
Mac: Application Icon is missing.

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#600]
**Bug description**
Application Icon is missing in the installer for Mac. As a result after drag and drop there's no icon too.
Tested on 4723, masternet.

 **Screenshot**
![image](https://user-images.githubusercontent.com/41323026/55893791-a796bb80-5bc1-11e9-8453-81eb63f04ffa.png)

**Comment by Sergei-Beam** [comment]
checked
