### ISSUE TITLE
Transactions are expiring while the receiver's wallet in sync

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#602]
Preconditions:
Wallet A - synced with blockchain
Wallet B - has the address with expiration_time=never, the wallet out-of-sync a lot of time

Steps:
- run wallet A
- go to send screen
- paste the wallet B address from preconditions
- send the transaction ( tx got status "waiting for the receiver")
- run wallet B
- wait while wallet B have been synced
Actual: After syncing the transaction got status expired
Expected: After syncing transaction should be completed

**Comment by anatolse** [comment]
https://github.com/BeamMW/beam/wiki/Out-of-sync-wallets
I think this is one of listed cases

**Comment by gingervik** [comment]
Yes,, but we should resolve it for somehow @anatolse

**Comment by jurijakimuk** [comment]
Tested when both wallets have the same currently newest version 4817 and have a significant difference in block height, when one of them (**the receiver**) **is out of sync**.
When the transaction got initiated:
- the sender got status "waiting for receiver"
- the receiver got status "receiving"
![image](https://user-images.githubusercontent.com/41323026/57008311-d9ff6b80-6bf7-11e9-9f88-9f240f384cf4.png)
Then in a while both sides got the "expired" status
![image](https://user-images.githubusercontent.com/41323026/57008323-f00d2c00-6bf7-11e9-9b59-0695a1c889e9.png).

**Expected:** The transaction completes successfully with the statuses: "sent", "received" accordingly.

**Height difference example**
![height_diff](https://user-images.githubusercontent.com/41323026/57008250-6f4e3000-6bf7-11e9-8b32-02169dc9d81d.png)

**Zipped logs Test 1 (sender and receiver's)**
[logs_Sergei.zip](https://github.com/BeamMW/beam/files/3133922/Both.logs.txID.8ceddca6ef764d7398f7f1132b76a432.zip)

**Zipped logs Test 2  (sender and receiver's)**
[logs_Juri.zip](https://github.com/BeamMW/beam/files/3133925/logs_Juri.zip)

**Comment by jurijakimuk** [comment]
Case 1 SENDER SYNCED + RECEIVER OUT OF SYNC worked now. The transaction has completed.
Case 2 SENDER OUT OF SYNC + RECEIVER SYNCED still needs a fix.
This time the transaction ended up in:
- transaction status by sender's: side **expired**
- transaction status by receiver's side: **receiving**.
![sender_not_synced](https://user-images.githubusercontent.com/41323026/57123336-182c9480-6d8a-11e9-8c1a-94862a76e58d.png)
**Notes:**
The initiated by sender transaction was shown in "**pending**" status for quite some time during the syncing process until it has changed to "**expired**".
**Logs**
[receiver.log](https://github.com/BeamMW/beam/files/3140878/receiver.log)
[sender.log](https://github.com/BeamMW/beam/files/3140879/sender.log)

**Comment by gingervik** [comment]
@Sergei-Beam please ask @anatolse for non-synced node db for test

**Comment by Sergei-Beam** [comment]
Checked
Case 1 SENDER SYNCED + RECEIVER OUT OF SYNC 
and
Case 2 SENDER OUT OF SYNC + RECEIVER SYNCED 
both are worked now
