### ISSUE TITLE
Mainnet Downloads for Miners dead

### ISSUE THREAD

**Issue by ace354444** [BeamMW/beam#606]
When you click to download, you get the following error for OpenCL:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<script/>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
mainnet/2019.01.17/Release/win/opencl-miner-1.0.65.zip
</Key>
<RequestId>2327617ADD99F397</RequestId>
<HostId>
fsBUEaFlyjyYBR8rZ5MWlht3L2Gcqlu1Zl+lttnpvk/bpWvWu7v7PiYic/P9rj+yW6xW+bCrWWY=
</HostId>
</Error>

**Comment by Sergei-Beam** [comment]
Hello @ace354444 ,

 Thanks for your efforts to make Beam better.
Links really were broken we are fixed them and all starting work.

Regards,
BEAM team
