### ISSUE TITLE
UI Wallet: Need to add a new message to ETA when node Loading UTXO

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#607]
Since we remade sync mode for nodes we need to add a new message to ETA when node Loading UTXO. This loading takes some time ~20-40 sec and looks like Wallet stucks, because the ETA haven't any progress and message.

Please provide the design for that @alexandrashelenkova @sasha-abramovich

**Comment by sasha-abramovich** [comment]
I'm still an advocate to indicate time, not blocks at first. Let's discuss with the devs if this is the right time to do it. Meanwhile, as a quick fix we could just write "loading headers..." or something but that's too technical and not too user-friendly anyways.

**Comment by gingervik** [comment]
@sasha-abramovich we are talking not about headers. it's about UTXO.
Seems like we do not need design for it just fix progressbar

**Comment by alexandrashelenkova** [comment]
When loading starting, progress bar should be already 5% filled to show user that loading is in progress.
