### ISSUE TITLE
Edit Address pop-over should allow user to select / copy the address

### ISSUE THREAD

**Issue by jonathancross** [BeamMW/beam#608]
The **Edit Address** pop-over should allow user to select / copy the address.

**Bug description**
Currently users cannot use this to copy an address to the clipboard.

**To Reproduce**
Steps to reproduce the behaviour:
1. Load _Addresses_ screen
2. Click on 3 dots to the right of an address.
3. Select _edit address_
4. Try to copy the address to the clipboard.

**Current behaviour**
Cannot be selected / copied.

**Expected behaviour**
Should be able to select the address with mouse and copy (right-click or Control-C / Command-C)

**Platform and build**
* Mac (did not confirm on other platforms)
* Mojave
* BEAM Build number: `2.0.4739`

**Comment by gingervik** [comment]
thank you @jonathancross will be done in next sprint

**Comment by gingervik** [comment]
checked on master
