### ISSUE TITLE
CLI wallet. Add a command to get full transaction details

### ISSUE THREAD

**Issue by Jagor21** [BeamMW/beam#613]
**Feature title**
Add a command to get full transaction details (amount, both addresses, kernel id)

**Describe the current situation we have**
Only sender can get this information through payment_proof_export command. Receiver doesn't have such opportunity.

**Describe the solution you'd like**
Command: beam-wallet info --tx_details --tx_id=<id>

**Additional context**
This command will be helpful for organizations that work with a large amount of persons

**Comment by gingervik** [comment]
1. make transaction details more formated (remove time from sender line)
![image](https://user-images.githubusercontent.com/28015224/59089785-a1982f00-8913-11e9-88d4-9a4fa3c3881c.png)
2. Change error when user did not enter tx_id param that param is missing
![image](https://user-images.githubusercontent.com/28015224/59089820-be346700-8913-11e9-9d0b-1539e74f4473.png)
3. user should be able to get info for failed transaction (with error) and receiving/sending

**Comment by gingervik** [comment]
2. fix typo (required)
![image](https://user-images.githubusercontent.com/28015224/59196291-e8e22200-8b96-11e9-8609-b187a14d8050.png)

3. addtransaction status and error (error only for failed transactions)

**Comment by gingervik** [comment]
checked
