### ISSUE TITLE
CLI Wallet - Add the transaction type to transaction history

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#614]
When I use the command --tx_history to see history list it is hard to understand where is the transaction incoming OR outgoing. For me, it looks inconvenient because transactions haven't any flag of type. 

I propose adding the new column with flags incoming|outgoing, between date and amount columns 
![image](https://user-images.githubusercontent.com/44496108/56670578-c4e88100-66bb-11e9-8d59-54901bfbd33a.png)

**Comment by gingervik** [comment]
should be fixed in #447

**Comment by gingervik** [comment]
1. if user send transaction to himself it should have different direction name (not outgoing)
smth like "self transaction" 
![image](https://user-images.githubusercontent.com/28015224/59333955-19929a80-8d02-11e9-9cab-3ac761d68d19.png)

**Comment by gingervik** [comment]
checked
