### ISSUE TITLE
CLI Wallet - Improvements for payment proof

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#615]
https://github.com/BeamMW/beam/issues/415#issuecomment-472804011
According to the next comment, we should actualize the CLI wallet payment proof mechanism too and forbid to export the proof while transaction not yet completed to exclude the possibility of fraud.
@anatolse Please, return proof only if the transaction has the status "sent"
![image](https://user-images.githubusercontent.com/44496108/56671629-a97e7580-66bd-11e9-837d-2eb12a9d695e.png)

**Comment by gingervik** [comment]
checked for next statuses: 

- sent
- received
- expired
- failed
- waiting for receiver
- receiving
