### ISSUE TITLE
UI Wallet - Multilanguage

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#618]
@sasha-abramovich Please provide the design for the settings screen for Localisation module.

Also, we need the official translation to Russian and maybe some other languages.

**Comment by gingervik** [comment]
@echoby please add dropdown in general settings block
![image](https://user-images.githubusercontent.com/28015224/57065758-1ce24180-6cd3-11e9-84b1-86c402330b3e.png)
please, use proper colors for master/testnet/mainnet
thank you

**Comment by alexandrashelenkova** [comment]
Screens are here
zpl.io/2j5qkZ6
zpl.io/blPjJe1

English language should be always on top of the list (even if it's not selected).

**Comment by alexandrashelenkova** [comment]
Let's move dropdown lists to the right side bu now (cause doesn't look good with longer field's headers). Will update the screenshots asap and will keep on thinking about better resolution.

**Comment by Sergei-Beam** [comment]
@echoby 
1. In case when there aren't peers at all the button is moved out and  part of the error message is hidden
![image](https://user-images.githubusercontent.com/44496108/58028605-c1fa7800-7b23-11e9-9b83-0c7796f8e444.png)
2. The "Add" peer button on Russian still called "Add"
![image](https://user-images.githubusercontent.com/44496108/58028661-e7878180-7b23-11e9-8af1-b894d39fcbbc.png)

**Comment by gingervik** [comment]
1, 2 - checked
3.
![image](https://user-images.githubusercontent.com/28015224/58155589-d43bf980-7c7c-11e9-95e0-08c28866395b.png)
4. 
![image](https://user-images.githubusercontent.com/28015224/58155602-dbfb9e00-7c7c-11e9-9dc7-3f7de503182a.png) (can be resolved with redesign https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5b8277d0a4b13457087a631f
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5c0ec2747324832ffbc6aae0 )

**Comment by gingervik** [comment]
5. 
![image](https://user-images.githubusercontent.com/28015224/58179175-5a256800-7cb0-11e9-9ef2-359bc4405390.png)

**Comment by gingervik** [comment]
6. change "Длинна" to "Длина"
![image](https://user-images.githubusercontent.com/28015224/58181966-6eb82f00-7cb5-11e9-808c-85e81034a123.png)

**Comment by gingervik** [comment]
3-6 checked
7.  long path should be 
![image](https://user-images.githubusercontent.com/28015224/58694441-a866f500-839b-11e9-8886-6a6ae1238eb2.png)
8. Please, translate also
![image](https://user-images.githubusercontent.com/28015224/58694849-a94c5680-839c-11e9-8ae2-da5e2bd60047.png)

**Comment by gingervik** [comment]
9. 
![image](https://user-images.githubusercontent.com/28015224/58695300-b584e380-839d-11e9-854d-4bdd0892982a.png)

**Comment by gingervik** [comment]
![image](https://user-images.githubusercontent.com/28015224/59084116-a6081c00-8902-11e9-85b1-eea6688f045d.png)
10. please, rename to "Истекает"

**Comment by gingervik** [comment]
11. too long status
![image](https://user-images.githubusercontent.com/28015224/59088829-47966a00-8911-11e9-8a1b-3706b978f180.png)

**Comment by gingervik** [comment]
12. 
![image](https://user-images.githubusercontent.com/28015224/59196414-41192400-8b97-11e9-91fe-0c00b6ae0518.png)
13. в течени**Е**
![image](https://user-images.githubusercontent.com/28015224/59196510-96edcc00-8b97-11e9-9be3-ed5b5f2933d3.png)
14. errors for failed transactions
![image](https://user-images.githubusercontent.com/28015224/59196583-bd136c00-8b97-11e9-9511-8f803a7fe224.png)
