### ISSUE TITLE
Wallet doesn´t open - blank page - 

### ISSUE THREAD

**Issue by tecnoamigo** [BeamMW/beam#619]
My wallet was running ok and had balance. But today when i ran the wallet its got stuck on this screen:

![image](https://user-images.githubusercontent.com/31414190/56803768-f2d3df80-67f9-11e9-979b-8ab44a101e0c.png)

it´s just a blank screen.

My log looks like this:

I 2019-04-26.07:45:19.540 Beam Wallet UI 2.0.4739 (mainnet)
I 2019-04-26.07:45:19.540 Rules signature: ed91a717313c6eb0
D 2019-04-26.08:01:27.669 beam::io::Reactor::~Reactor
D 2019-04-26.08:01:27.670 beam::io::Reactor::~Reactor
D 2019-04-26.08:01:27.671 closing unclosed handles

I didn´t anything at all.

Does anyone know what to do?

Thanks in advance.

**Comment by anatolse** [comment]
Well, it seems that QT has a problem to draw UI. 
One  possible reason is that you have a problem with your graphics drivers.

**Comment by tecnoamigo** [comment]
You nailed it. I removed the graphics card.
Its working now.
