### ISSUE TITLE
mobile wallet states online, although not fully synch

### ISSUE THREAD

**Issue by rgsnedds** [BeamMW/beam#621]
**Bug title**
Multiple Users seeking support regarding 'synch' but not synch
**Bug description**
Users concerned about failing transactions whilst wallet states online, request to add 'not yet synch' or some message similar while mobile wallet performs synchronisation.

**To Reproduce**
Steps to reproduce the behaviour:
test send to mobile wallet upon opening mobile wallet.
find tx 'expired' after a few seconds.

**Current behaviour**
tx will expire after short time..

**Expected behaviour**
Mobile wallet should state (red light) "synchronising" until fully synch.

**Platform and build**
Beam iOS mobile wallet - multiple users sought support.

**Screenshots (if applicable)**
![Screenshot 2019-04-26 at 20 38 39](https://user-images.githubusercontent.com/36843889/56832239-50e8dd00-6863-11e9-833e-8ce3b4e73fd6.png)
from sending wallet. tx expired.

**Comment by gingervik** [comment]
hi @rgsnedds 
we are working on this issue

**Comment by gingervik** [comment]
fixed and released
