### ISSUE TITLE
[Question] How to sign MacOS Release build on travis ci?

### ISSUE THREAD

**Issue by inix** [BeamMW/beam#622]
**Bug title**
[Question] How to sign MacOS Release build on travis ci?

**Bug description**
I forked the repo and make builds on travis ci,most builds were successed except MacOS Release build.

**To Reproduce**
Steps to reproduce the behaviour:
1. Fork the official repo;
2. Running build on travis ci;
3. MacOS Release build error.

**Current behaviour**
Mac OS Release build error but others were OK.

**Expected behaviour**
MacOS Release build is success.

**Platform and build**
* MacOS
* OS version: travis ci xcode9.3

**Configuration, log, memory dump files (if applicable)**

**Log file(s) (if applicable)**
My error logs:
[log error.txt](https://github.com/BeamMW/beam/files/3125920/log.error.txt)

Official success logs:
[log ok.txt](https://github.com/BeamMW/beam/files/3125924/log.ok.txt)

**Screenshots (if applicable)**

Error:
![mac os release build error](https://user-images.githubusercontent.com/2264291/56875980-b365f700-6a76-11e9-92d7-845f249e8ed7.png)

I notice MacOS travis ci build ok logs contains following environment variables:

```bash
$ export GITHUB_API_KEY=[secure]
$ export BUILD_SERVER=[secure]
$ export ARTIFACTS_KEY=[secure]
$ export ARTIFACTS_SECRET=[secure]
$ export ARTIFACTS_PERMISSIONS=[secure]
$ export ARTIFACTS_REGION=[secure]
$ export ARTIFACTS_BUCKET=[secure]
$ export encrypted_1f9ebee66ea9_key=[secure]
$ export encrypted_1f9ebee66ea9_iv=[secure]
$ export MACOS_DISTRIBUTION_KEY_PASSWORD=[secure]
$ export MACOS_SIGN_IDENTITY=[secure]
```

How to setup these keys on travis ci?

Thanks

**Comment by nesbox** [comment]
Hi, you can't sign your build with our certificates only if you have your own.
I recommend you disable signing section and remove these lines in the Travis script https://github.com/BeamMW/beam/blob/master/.travis.yml#L55
lines `[55-63] [75-80]` and remove `-DBEAM_SIGN_MACOS_BINARY=On` flag on line `[68]`

**Comment by inix** [comment]
@nesbox Hi,the most convenient way is that disable flags from your recommendation.
I have another question: can I have my own certificates and how to setup? Is it free?

Thanks

**Comment by nesbox** [comment]
Yes, you can have your own certificate, it's not free, you can buy it for on the Apple website for developers.
Sorry for the delay with the response.

**Comment by inix** [comment]
@nesbox ok thanks
