### ISSUE TITLE
Address book - Add ability to edit comment for addresses

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#623]
Desktop wallet. 
Please, add ability to edit comment for address

**Comment by echoby** [comment]
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5c45813eb2616abf79edf09e

**Comment by gingervik** [comment]
1. user should not be able to create the same comment for different addresses

**Comment by gingervik** [comment]
- please, show error when user try to save address with existed comment

![image](https://user-images.githubusercontent.com/28015224/59187953-41a5c080-8b7f-11e9-9b0c-63d94bddbef7.png)

2. STR:
- go to receive 
- create address with name "default"
- go to receive 
- create address with name "default"
AR: you have 2 default addresses
ER: user should not be able to create the same comment for different addresses
![image](https://user-images.githubusercontent.com/28015224/59188029-669a3380-8b7f-11e9-80a3-35016a8ab89b.png)

**Comment by gingervik** [comment]
3. STR:
- open in address book edit address for address with blank comment
AR:
![image](https://user-images.githubusercontent.com/28015224/59335614-996e3400-8d05-11e9-99d2-7b78f7debcfd.png)

**Comment by gingervik** [comment]
blocked by #726

**Comment by VladislavKulyba** [comment]
checked
