### ISSUE TITLE
Receive button modification

### ISSUE THREAD

**Issue by omarinoo** [BeamMW/beam#627]
I think the functionality of the receive button should be changed. When pressing on receive, the wallet should display the user the list of existing addresses, and let the user pick an address and show its qr code, alongside with the option to create a new address. I think this would be more intuitive.
Also, currently on desktop there is no way of showing the QR code of an address once it's been created, while it is possible on mobile.

**Comment by sasha-abramovich** [comment]
The task to show QR code was opened for the next sprint: https://github.com/BeamMW/beam/issues/629

As about displaying the list of existing addresses when receiving - what is the major use case if I may to ask? We consider to implement it but would like to understand your perspective and scenarios on that matter.

**Comment by omarinoo** [comment]
> As about displaying the list of existing addresses when receiving - what is the major use case if I may to ask?
Sure. It stems from the fact that the user will most likely press on receive whenever he wants to receive something, but it is often the case that, for whatever reason, he wants to reuse an address. Showing a completely new address every time feels counterintuitive. For a beginner it might even be the case that he thinks that pressing on receive keeps showing the same address, leading to confusion. 
In my view the press button should serve the purpose of showing the list of existing addresses, while showing by a side the relevant QR, and have the option of creating a brand new address.

**Comment by sasha-abramovich** [comment]
Glad to answer (while being sorry for delay) that the required functionality is scheduled to appear in the next released versions of the mobile wallets and afterwards in the desktop wallet as well. Closing this ticket for now (while being thankful for your suggestion) :)
