### ISSUE TITLE
Show QR code in address book

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#629]
https://zpl.io/VqKpDXJ

**Comment by gingervik** [comment]
1. please rename all token to address
![image](https://user-images.githubusercontent.com/28015224/58463129-ee258280-813b-11e9-892c-46b1cbe6863e.png)
2. we should not show QR code for expired addresses
![image](https://user-images.githubusercontent.com/28015224/58463714-09dd5880-813d-11e9-87e3-3f4a036a4113.png)

**Comment by gingervik** [comment]
checked
