### ISSUE TITLE
Online indicator should be displayed on all screens

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#63]

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova can we please add an online status to this screen as well please?

**Comment by alexandrashelenkova** [comment]
@sasha-abramovich on Settings screen? Ya, sure I will add online status there, as soon as I will update the whole screen.

**Comment by sasha-abramovich** [comment]
Sounds like a great idea! Testnet3 was just released, time to see all the updates :)

**Comment by Denis-Asipenko** [comment]
checked
