### ISSUE TITLE
[CLI] Wrong error when restoring the wallet

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#638]
**Bug description**
When restoring the CLI wallet and specifying the custom folder for the wallet.db file without the "wallet.db" file at the end of the path - user gets the "Wallet already initialized" message, which is wrong. The wallet path must be considered correct and the wallet.db file must be created under the specified wallet path nevertheless.

**To Reproduce**
Steps to reproduce the behaviour:
Pre-conditions: The CLI wallet is **not** initialized.
1. Copy the CLI wallet files to the test machine.
2. Run CLI and try to restore the wallet, specifying the custom wallet.db path, e.g.
`./beam-wallet-testnet restore --seed_phrase="apple;apple;apple;apple;apple;apple;apple;apple;apple;apple;apple;apple;" --wallet_path="/home/user/documents/customfolder"`

**Current behaviour**
Restore failed.
The message "Your wallet is already initialized" is printed out.

**Expected behaviour**
The wallet is restored successfully.
The file is created under the specified folder:
/home/user/documents/customfolder/**wallet.db**.
If user doesn't include the file in the wallet_path, we create it ourselves.

**Notes**
Currently the wallet path needs to include the file to work correctly, e.g. **/home/user/documents/customfolder/wallet.db**.
In this case the wallet is restored successfully.

**Platform and build**
* Linux
* OS version: 18
* BEAM Build number: Testnet, 4920.

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/41323026/57676657-ad9f1280-762d-11e9-8919-56c93dd43853.png)

**Comment by levantruong1993** [comment]
I transferred money from bitforex.com floor to beam wallet but didn't see my wallet help me
![60348515_423485578436332_4951593350890258432_n](https://user-images.githubusercontent.com/50684528/57819673-7c0c7f80-77c4-11e9-849b-6a7621bf075b.jpg)

**Comment by jurijakimuk** [comment]
We need to restrict creating wallet DB files with other name than "wallet.db". Because if the file "wallet1.db" is created, we're still looking for the "wallet.db" when using the CLI wallet.
**Explanation:**
I now can run this command:
`beam-wallet-masternet.exe restore --seed_phrase=gorilla;document;chaos;device;sibling;margin;kitchen;another;alone;afford;dinner;diagram;  --wallet_path="C:\Users\jurij\Documents\Beam\Tests\masternet\beam-wallet\wallet1.db"`
This will restore my wallet and create a file "wallet1.db" in the folder specified.
But when I then run:
`beam-wallet-masternet.exe info`
I'll get:
` Please initialize your wallet first...`
That's because we are still looking for the "wallet.db" file, not  "wallet1.db".

**Comment by jurijakimuk** [comment]
OK in master 5647
