### ISSUE TITLE
[CLI] Add ability to expire addresses in CLI

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#639]
**Bug description**
Add ability to expired addresses in CLI.
Currently we can change the expiration time to "24h" and "never".
This task is about adding the third option "now", that will expire the selected address.

**Acceptance Criteria:**
1. When the address is live user can expire this address in CLI, using the command:
beam-wallet change_address_expiration --address=1420ce788c660b15142f598db3d7286d2c8a1373104b91d0155610f959ca413e6e1 **--expiration_time=now**
2. The expired address unsubscribes from the SBBS channel immediately. No incoming transactions are possible on this address.
3. The expiration time of the manually expired address can be changed then to "24h" and "never".

**Comment by VladislavKulyba** [comment]
Checked
