### ISSUE TITLE
If the user selected "Restore Wallet or create new one" There is no way to to back one step and select start migration.

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#641]
![image](https://user-images.githubusercontent.com/44961099/57739515-15ad3180-76de-11e9-9944-9645655281a0.png)

**Comment by levantruong1993** [comment]
![60348515_423485578436332_4951593350890258432_n](https://user-images.githubusercontent.com/50684528/57819525-cb9e7b80-77c3-11e9-91be-f0792d01d34b.jpg)

I transferred money from bitforex.com floor to beam wallet but didn't see my wallet help me

**Comment by gingervik** [comment]
@levantruong1993 hi. please contact our support in telegram https://t.me/BeamSupport
or via email support@beam.mw

**Comment by gingervik** [comment]
restore wallet button changed not acc to design
![image](https://user-images.githubusercontent.com/28015224/58152844-4230f280-7c76-11e9-8b71-80c1fed6f933.png)
![image](https://user-images.githubusercontent.com/28015224/58152856-49f09700-7c76-11e9-8ff2-d7371750f0f5.png)

please just add "back" button as it in migration screen (in one row)
![image](https://user-images.githubusercontent.com/28015224/58152979-94721380-7c76-11e9-8e74-c0cb0920f582.png)

**Comment by gingervik** [comment]
checked
