### ISSUE TITLE
New Release Crashes Wallet on Mac OS High Sierra

### ISSUE THREAD

**Issue by breadsax** [BeamMW/beam#642]
Built from source on High Sierra. Ran cpack to create a .dmg file.

Opened the .app file and chose Start Migration and it crashes.

Was able to restore from seed file but any clicks in the GUI result in a crash.

This was compiling from the latest mainnet branch after the release today. Previous release worked perfectly.

Perhaps related to the open ssl warnings that libssl.dylib and libcrypto.dylib is not a directory ?

EDIT: It actually crashes when selecting the address or transaction tab only. Settings tab worked and default tab works.

**Comment by gingervik** [comment]
hi @breadsax do you have any crash info?

**Comment by breadsax** [comment]
Do you know where the log would be located on Mac? @gingervik 

I can post later today. I simply receive a window that the application crashed unexpectedly as the GUI closes.

**Comment by gingervik** [comment]
logs can be found here /Users/{your User name}/Library/Application Support/Beam Wallet/logs
when this "window that the application crashed unexpectedly" shown there should be some technical info. am I right?

**Comment by breadsax** [comment]
@gingervik It just shows the standard Mac crash message, no technical information shown. I'll post more later today.

I do wonder if it is related to the 2 warnings I receive during compilation that I noted in my OP.

Perhaps an issue with OpenSSL linking? Mac uses it's own version and brew installs openssl in a different path.

https://medium.com/@timmykko/using-openssl-library-with-macos-sierra-7807cfd47892

**Comment by breadsax** [comment]
@gingervik My log file shows no errors, it simply ends. (Is there private information in the log?)

Just the standard Mac message upon crash:

![image](https://user-images.githubusercontent.com/48415390/57811150-20dc7d80-772f-11e9-9989-fe361c8bb569.png)

Perhaps related to issue #647 ?

**Comment by breadsax** [comment]
This has got to be the issue

![image](https://user-images.githubusercontent.com/48415390/57820184-51351380-7751-11e9-8613-3f26fcca406f.png)

**Comment by gingervik** [comment]
@breadsax please, click on report and screen additional details
@nesbox can you help?

@breadsax have you tried to download our wallet from site and install it?

**Comment by breadsax** [comment]
@gingervik It said the crash was on thread 0. I'm afraid of posting private information from that report, but let me see if I can pull some more info.  I appreciate you looking at this.

I only compile all of my wallets from source, so I have not downloaded the wallet compiled by the team.

**Comment by breadsax** [comment]
@gingervik @nesbox Hopefully this crash info will help provide some insight.

Also, please let me know if a team member can build on High Sierra with latest Mac updates installed and latest versions of all dependencies installed. At least that would confirm if it is on my end or not.

Also, thinking it may be an issue with latest Qt version as that has caused other GUI issues on different wallets.

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000004
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

**Comment by nesbox** [comment]
@breadsax could you pls check your QT version by calling `qmake --version`?
thank you

**Comment by breadsax** [comment]
@nesbox @gingervik I have the latest version of all dependencies installed with brew. Qt version is 5.12.4

**Comment by nesbox** [comment]
ok, we will try to reproduce it on QT 5.12, because, we currently use 5.11 version and I think it can cause be the crash.
Thank you.

**Comment by nesbox** [comment]
ok, I've got the crash on QT 5.12

![image](https://user-images.githubusercontent.com/1101448/58315613-852bcb00-7e1a-11e9-8a13-338e48ab9c5f.png)

investigating...

**Comment by nesbox** [comment]
@breadsax 
confirmed, Beam Wallet perfectly works with QT5.11 and crashes with QT5.12
please, uninstall your QT5 using `brew uninstall qt5` command and download/install from the official website https://download.qt.io/official_releases/qt/5.11/5.11.0/qt-opensource-mac-x64-5.11.0.dmg.mirrorlist
also, pls don't forget to add qt folder to PATH env variable (`PATH=/Users/<username>/Qt5.11.0/5.11.0/clang_64/bin:$PATH`)
I'll fix current build instructions...

**Comment by breadsax** [comment]
@nesbox @gingervik Confirmed, this worked for me! Much thanks to you. Issue closed.
