### ISSUE TITLE
Does version 2.0.4739 support cpu mining?

### ISSUE THREAD

**Issue by caokun8008** [BeamMW/beam#643]
Does version 2.0.4739 support CPU mining?
I built this version of binary file on Ubuntu 1604 platform: beam-node, beam-wallet, miner_client, and then I wanted to test mining, rewards, and token transfers, starting with 0 block. I followed the document and found that no mining had begun.
Does not support CPU mining?
I operate on the virtual machine Ubuntu 1604 on macbook.
Https://documentation.beam.mw/en/latest/rtd_pages/user_cli_wallet_guide.html
Https://documentation.beam.mw/en/latest/rtd_pages/user_beam_node_guide.html
https://documentation.beam.mw/en/latest/rtd_pages/user_mining_beam.html

**Comment by gingervik** [comment]
Hi @caokun8008 
cpu minig was removed from our wallet as it's not usefull at all
