### ISSUE TITLE
My wallet (testnet) can receive beams, but unable to send beams

### ISSUE THREAD

**Issue by toebi** [BeamMW/beam#644]
A newbie here is learning how to use the testnet Wallet (installed in my android phone). My wallet can receive beams, but it is unable to send beams. I have tried several times to send beams. All failure!! The recipient was unable to receive my beams and the wallet screen showed "waiting for receiver". It seems my beams are permanently locked up in the wallet. Any suggestions?
![Capture](https://user-images.githubusercontent.com/25330144/57747836-3d33d800-76a5-11e9-89ad-285e1ef4d6b9.PNG)

**Comment by gingervik** [comment]
hi @toebi was your receiver online at the moment you sent him coins?

**Comment by toebi** [comment]
Yes, the receiver was online.

**Comment by gingervik** [comment]
@toebi we can check it together. please, contact me in telegram @gingervik

**Comment by gingervik** [comment]
resolved in telegram. user tried to send testnet coins to mainnet wallet
