### ISSUE TITLE
Desktop wallet - Add ability to export/import wallet data (addresses, transactions history, peers, categories etc)

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#645]
all as in cli
* user should be able export his addresses and select where
* user should be able select file with his addresses and import it
* all this "successfully import/export" info 
* if addresses are from another wallet - show error

@alexandrashelenkova please, provide design

**Comment by gingervik** [comment]
@sasha-abramovich please, provide a design

**Comment by alexandrashelenkova** [comment]
Screens are here https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/dashboard?seid=5cfe104ce5b5c45d507762d0

**Comment by alexandrashelenkova** [comment]
@gingervik please discuss all possible types of errors for import with @sasha-abramovich

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova can we please add a warning saying that if the same addresses are being imported and used by several wallets at the same time it might result in failed transactions?

**Comment by sasha-abramovich** [comment]
Extended the ticket scope - ready to discuss / split the tickets - but don't want to leave the functionality unattended.

**Comment by gingervik** [comment]
duplicate
