### ISSUE TITLE
Login / restore screens updates

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam#649]
Restore moved to one line under login buttons, removed duplications of "Enter password" line, added "back" button where it was missing. ALL the screens are in this section https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/dashboard?seid=5b6ae20bd8ad407defbee7bd

New restore line are for this screens:
https://zpl.io/bAq0P56
https://zpl.io/bAEmmjB

Back button added here:
https://zpl.io/VQ965em
https://zpl.io/2pOYg88

Double "Enter password" fixed here
https://zpl.io/bAEmmjB
https://zpl.io/VOx5n9j
https://zpl.io/2pOYg88
https://zpl.io/VQ965em

Text fixes 
https://zpl.io/bzNvMk8
https://zpl.io/29yO6eA
https://zpl.io/blPjNYv
https://zpl.io/awmNklj

**Comment by gingervik** [comment]
checked
