### ISSUE TITLE
please stop with the crazy version names

### ISSUE THREAD

**Issue by taw00** [BeamMW/beam#650]
## This is the industry standard for versioning.

**Source code (tarballs and the like):**
`name-version`

That's it. Example: `name-version.tar.gz` or `name-version.zip` etc.

And to show dashes and dots: `name-name-vermajor.verminor.verpoint`

If you have some qualifier, sometimes that is added at the end (and each qualifier is dot-notated for each that has a difference context) Example: `name-name-vermajor.verminor.verpoint-hotfix1` ... maybe even `name-name-vermajor.verminor.verpoint-code-name.hotfix1`

Packagers will often break out that hotfix1 and add it to the release number (release numbers are generally associate to binary builds).

**Archive trees**
Archive trees generally follow the name-version format, though sometime deviate and just do name-vermajor, though this is frowned upon.

So, if I explode an archive like `name-name-vermajor.verminor.verpoint.tar.gz` then I expect to have a tree with a root called `name-name-vermajor.verminor.verpoint`

The name of the archive and the name of the exploded root should never deviate from those same elements.

**Binary packages and archives**

Same thing, but with release numbers, and such. Ie. it becomes `name-version-` and then everything else is fair game: `name-name-vermajor.verminor.verpoint-relmajor.relminor-hotfix1.osfamily.buildersinitials.arch.src.rpm` Same root. Always.

## So, what is my point....?

This was supposed to be a simple request and I became verbose. The point: Beam engineering keeps changing their pattern and it doesn't follow industry standards and it is not predictable. There is a certain expectation and automated tooling expects a pattern.

It should be, for example, instead of `beam-bright_boson_2.1.hotfix.tar.gz` you should choose one of these options...
- `beam-2.1.4914.tar.gz` (exploded root: `beam-2.1.4914`)
- `beam-2.1.4914-hotfix.tar.gz` (exploded root: `beam-2.1.4914` or `beam-2.1.4914-hotfix`)
_note, "hotfix" implies 2.1.4914 is being hotfixed, not 2.1.4910, for example, but that is a quibble_
- `beam-2.1.4914-bright-boson.tar.gz` (exploded root: `beam-2.1.4914` or `beam-2.1.4914-bright-boson`)
- `beam-2.1.4914-bright-boson.hotfix.tar.gz` (exploded root: `beam-2.1.4914` or `beam-2.1.4914-bright-boson` or `beam-2.1.4914-bright-boson` or `beam-2.1.4914-hotfix`)

_Note: Your binary builds are better schemed. Thanks for that._

--- 
Anyway. Lengthy diatribe I know, but I wanted to be clear. Please standardize / normalize the naming scheme for archives, root trees, and binary builds. The "standards" can get really nuanced, but that is the core of it.

Thanks!

**Comment by taw00** [comment]
And now... `cold_wallet.tar.gz`
Guys. Please.

**Comment by taw00** [comment]
And now beam-beam-2.1.4919 Why!?!

https://github.com/BeamMW/beam/archive/beam-2.1.4919/beam-beam-2.1.4919.tar.gz

Just call it beam. Done! Gah.

**Comment by gingervik** [comment]
thank you @taw00 
we change name for future releases
