### ISSUE TITLE
SHA256SUM do not match

### ISSUE THREAD

**Issue by hobbit6** [BeamMW/beam#651]
Posted:
d0c1c6e15edd391b4d751ed63860b8d0e1878084a95702bd3a9615d1c77ea59a  Beam-Wallet-2.1.4914.exe

Actual:
df7004774e36262bcf50c8ed5d303dd3061705bf6d905712a569c46e924e49be  Beam-Wallet-2.1.4914.exe

**Comment by gingervik** [comment]
Hello @hobbit6 
Thank you for your issue and attention.
You are right. Incorrect sha256 was published for windows builds. It's fixed.
