### ISSUE TITLE
[Node Explorer API] Rename the node.db file

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#657]
**Bug description**
Node Explorer API
Rename the node db file and the journal file.

**Current file names**
explorer-node_db
explorer-node_db-journal

**Expected file names**
explorer-node.db
explorer-node.db-journal

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/41323026/58008271-b17ed900-7af4-11e9-807e-f2c5cb078494.png)

**Comment by Sergei-Beam** [comment]
Checked on master v. 2.1.5307
