### ISSUE TITLE
[CLI] Command change_address_expiration for ALL address works wrong with argument expiration_time=24h

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#658]
When I try to change the expiration time for ALL address to 24h system sets expiration_time=created_time+24h but it should set expiration_time as current time + 24h

Looks like related to #482

TO Reproduce:
- open the CLI wallet with addresses which have different created times( no matter expired or not)
- run the command :
beam-wallet change_address_expiration --expiration_time=24h
- see the result
Actual: system sets expiration_time=created_time+24h but it should set expiration_time as current time + 24h
![image](https://user-images.githubusercontent.com/44496108/58014628-f3fae280-7b01-11e9-852d-bef6cfdf84b2.png)
![image](https://user-images.githubusercontent.com/44496108/58014654-ff4e0e00-7b01-11e9-90af-21c0d6e220a0.png)

**Comment by gingervik** [comment]
checked on cli
