### ISSUE TITLE
[CLI Wallet] Print Error when a Wallet connects to the Node that's linked to the other Wallet

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#659]
**Bug description**
When a CLI wallet tries to connect to the other's wallet node - then an sql error is printed out.
We need to specify for the user what's exactly going on and figure out a more specific error text.

**To Reproduce**
Pre-conditions:
1. Wallet A is linked with the node A1 by the owner key.
2. Wallet B is linked with the node B1 by the owner key.

Steps:
1. Run Wallet B and Node B1.
2. In Wallet B run the listen command and specify the Node B1's address.
`e.g. beam-wallet listen -n 127.0.0.3333`.
2. Run Wallet A.
3. While Wallet B is listening to Node B1 - in Wallet A run the listen command and specify the Node B1's address.
`e.g. beam-wallet listen -n 127.0.0.3333` (same address as in Step 2)

**Current behaviour**
The user gets the sqlite errors.
![image](https://user-images.githubusercontent.com/41323026/58019568-7b4e5300-7b0e-11e9-9ccd-383052a68d7c.png)

**Expected behaviour**
The user gets the specific error message for the current case.
e.g. "Failed to connect to the node. Make sure the node is not linked to the other wallet by owner key."

**Comment by gingervik** [comment]
@echoby we should not change message better to understand why code=21 error is shown

**Comment by echoby** [comment]
Can't reproduce. Provide beam-node.cfg and wallet.db files, please.

**Comment by jurijakimuk** [comment]
OK in masternet, 5357
