### ISSUE TITLE
[Swap] Don't display "Bitcoin bridge is not initialized" if swap amount exceeds the wallet amount of Beams

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#665]
**Bug description**
If the swap initiator specifies the swap amount, that is bigger than he/ she has in the Beam wallet, e.g. Alice has 49 Beams and specifies --amount 50,
then when the user executes the swap command and after getting the "Unsufficient amount" error user executes the listen command - user sees the "Bitcoin bridge is not initialized" line, which needs to be removed.

**To Reproduce**
Pre-conditions:
The test swap environment is set up.
Alice has 49 Beams.
Steps to reproduce the behaviour:
1. Alice initiates a swap with the amount of 50 Beams expecting some amount of Bitcoins in return, e.g.
`beam-wallet-masternet.exe -n eu-node01.masternet.beam.mw:8100 swap_coins --amount 50 --fee 10 -r 39e9b3c772a6477c39e9ae05ba8cdb4256ccb77fb2d460cd9c599fd533dba199b2d --swap_amount 10 --swap_beam_side --btc_node_addr 127.0.0.1:13300 --btc_user Alice --btc_pass 123`
2 When Alice receives the error "You only have 49 beams" - run the listen command,
e.g.
`beam-wallet-masternet.exe listen -n 127.0.0.1:4444`

**Current behaviour**
The logs contain the message "Bitcoin bridge is not initialized".

**Expected behaviour**
The logs do NOT contain the message "Bitcoin bridge is not initialized".

**Platform and build**
* Windows
* OS version: 10 x64
* BEAM Build number, 5170

**Log file(s) (if applicable)**
[wallet_19_05_22_12_03_30.log](https://github.com/BeamMW/beam/files/3206687/wallet_19_05_22_12_03_30.log)
[wallet_19_05_22_12_03_57.log](https://github.com/BeamMW/beam/files/3206690/wallet_19_05_22_12_03_57.log)

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/41323026/58164116-dfe3ec00-7c8d-11e9-87c4-3f85cf5bede2.png)

**Comment by roman-strilets** [comment]
fixed

**Comment by jurijakimuk** [comment]
OK on 5307, master.
