### ISSUE TITLE
[Swap] Wrong errors when --swap_amount=0

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#668]
**Bug description**
When in the swap details user sets --swap_amount=0, then wrong errors are displayed.

**To Reproduce**
Pre-conditions:
The swap test environment is set up.
Steps to reproduce the behaviour:
1. Run the command, where amount of satoshis will be 0 (zero), e.g.
`beam-wallet-masternet.exe swap_listen -n eu-node01.masternet.beam.mw:8100 --amount 2 --swap_amount 0 --btc_node_addr 127.0.0.1:13400 --btc_pass 123 --btc_user Bob`
2. Confirm the operation with the password.

**Current behaviour**
1) Wrong error regarding the Beam amount is shown. The amount of Beams is unrelated. Also , the amount of Beams in the wallet is bigger than specified in the query anyway.
2) The failure message is literally saying "Failure not implemented yet."

`E 2019-05-22.14:15:37.427 [cc34a2a4841e4c5ea3a022f53f41357d][2] You only have 13 beams 40000000 groth`
`E 2019-05-22.14:15:37.427 [cc34a2a4841e4c5ea3a022f53f41357d] exception msg:`
`E 2019-05-22.14:15:37.428 [cc34a2a4841e4c5ea3a022f53f41357d] Failed. No inputs`
`D 2019-05-22.14:15:37.428 [cc34a2a4841e4c5ea3a022f53f41357d] NotifyFailure not implemented yet.`
`I 2019-05-22.14:15:37.430 [cc34a2a4841e4c5ea3a022f53f41357d] Rollback...`

**Expected behaviour**
There's a relevant error pointing that 0 (zero) amount of satoshi is not acceprtable, e.g.
"Operation Failed. The --swap_amount value must be more than 0." 

**Logs and zipped wallets:** (DM @jurijakimuk for the wallet passwords)
The bug was tested on the Bob's wallet.
[Alice's wallet.zip](https://github.com/BeamMW/beam/files/3207342/Alice.wallet.zip)
[Bob's wallet.zip](https://github.com/BeamMW/beam/files/3207344/Bob.wallet.zip)
[Bob's log.log](https://github.com/BeamMW/beam/files/3207353/wallet_19_05_22_14_15_35.log)
Alice's logs can be found in the zipped archives.

**Comment by roman-strilets** [comment]
fixed

**Comment by Sergei-Beam** [comment]
@roman-strilets Please change the end of error message from:
`should be positive number`
To:
`must be more than 0.`

**Comment by Sergei-Beam** [comment]
checked
