### ISSUE TITLE
[SWAP] System proceeds twice the same SBBS messages

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#669]
As we discussed with @Aleksandr-Starun on our logic, one SBBS message shouldn't be processed 2 times but here it looks like it processed twice
![photo_2019-05-21_15-39-26](https://user-images.githubusercontent.com/44496108/58175824-a91bcf00-7ca9-11e9-8c6a-d192fe802ef6.jpg)

[same double SBBS message.zip](https://github.com/BeamMW/beam/files/3207396/same.double.SBBS.message.zip)

**Comment by Aleksandr-Starun** [comment]
Not a bug. These are features of architecture of wallet.

**Comment by gingervik** [comment]
@Sergei-Beam please, add some more details about why it's not a bug and close

**Comment by Sergei-Beam** [comment]
NOT A BUG.

This related to the established logic. 
We have bbs channels and the time of the last message from them and to separate the old messages we are comparing timestamps through ">" and not through ">=", so the system can get two the same message several times. 
We cannot make a comparison through ">=", because one bbs channel can get a few messages with one timestamp.
