### ISSUE TITLE
[Swap] Transactions are failed after 120 blocks with and without confirmations

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#672]
These two cases look like a bug.

Case 1. Wallet with `--swap_beam_side` becomes offline after got 3/6 confirmations
Steps:
- run 2 cli wallets (Alice and Bob)
- make Bob the initiator of the swap run the cli command `swap_coins` with all needed credentials
- Alice agree the swap and Alice swaps Beam->BTC ( use the flag `--swap_beam_side` with command `swap_listen` for Alice)
- wait while the swap accepted
- generate 3 blocks on BTC chain ( Alice is got 3/6 confirmations from BTC chain)
- stop Alice wallet (CTRL+C)
- wait for 120 blocks
- run Alice wallet
Actual: After running the Alice wallet the transaction is failed
![image](https://user-images.githubusercontent.com/44496108/58255311-61627980-7d75-11e9-9904-afe7338c0208.png)
Both logs:  [120(3 confirmation).zip](https://github.com/BeamMW/beam/files/3212207/120.3.confirmation.zip)

Case 2. Wallets become offline after creating RefundTX and RedeemTX
Steps:
- run 2 cli wallets (Alice and Bob)
- make Alice the initiator of the swap run the cli command `swap_coins` with all needed credentials
- Bob agree the swap and Bob swaps Beam->BTC ( use the flag `--swap_beam_side` with command `swap_listen` for Bob)
- wait while the swap will be accepted and RefundTX, RedeemTX will be create
- stop both wallets Alice & Bob (CTRL+C)
- wait for 120 blocks
- run  both wallets Alice & Bob wallets
Actual: After running both wallets the transaction is failed on Bob wallet, but there is no any information about failing on Alice wallet
Bob:
![image](https://user-images.githubusercontent.com/44496108/58255977-d3878e00-7d76-11e9-9d70-191344ae29ad.png)

Alice:
![image](https://user-images.githubusercontent.com/44496108/58256008-e0a47d00-7d76-11e9-8284-707c95a3c4a5.png)

Both logs: [120(0 conf, both offline).zip](https://github.com/BeamMW/beam/files/3212197/120.0.conf.both.offline.zip)

**Comment by roman-strilets** [comment]
It's not bug. So it was conceived. If the user did not manage to send the transaction to the network in 120 blocks from the beginning of the negotiations, the transaction should be failed

**Comment by gingervik** [comment]
@Sergei-Beam can be closed

**Comment by Sergei-Beam** [comment]
Not a bug

> It's not bug. So it was conceived. If the user did not manage to send the transaction to the network in 120 blocks from the beginning of the negotiations, the transaction should be failed
