### ISSUE TITLE
Transaction failed when expired address' expiration time changed to 'never'

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#674]
**Bug description**
Failed to complete the transaction when the receiver's expired address became alive with expiration time = never.

**To Reproduce**
Pre-conditions: 
A CLI wallet is running (sender)
A UI wallet is running (receiver)
Steps to reproduce the behaviour:
1. Expire an address in UI wallet.
2. Copy its address.
3. From CLI wallet send some UTXO to the copied expired address.
4. In UI wallet change the expiration time for the address to "Never".

**Current behavior:**
The transaction fails on the sender's side.
The transaction hangs in receiving status by the receiver.

**Expected behavior:**
The transaction completes.

**Notes!**
If in Step 4 the expiration time is changed to "24h"  - the issue is not seen.
The issue is also not seen when UI > UI. Only with CLI > UI.

**Platform and build**
* Windows 10 x64
* BEAM Build number, master, 4915

**Log file(s) (if applicable)**
Juri's case:
[Juri.zip](https://github.com/BeamMW/beam/files/3216606/Juri.zip)

Sergei's case: (In his case the transaction hasn't even appeared as receiving by the receiver.)
[Sergei.zip](https://github.com/BeamMW/beam/files/3216607/Sergey.zip)

**Screenshots (if applicable)**
![cli-ui-failed_1](https://user-images.githubusercontent.com/41323026/58324328-42282280-7e2f-11e9-9481-50f1f60ffa90.png)
![cli-ui-failed_2](https://user-images.githubusercontent.com/41323026/58324341-494f3080-7e2f-11e9-9e7c-b101e182a4db.png)
![ui_side](https://user-images.githubusercontent.com/41323026/58324349-4ce2b780-7e2f-11e9-98e2-f93ad071b260.png)

**Comment by Zeke133** [comment]
Was not reproducible on 'master'. Both "24h" and "Never" addresses had received coins successfully.

**Comment by VladislavKulyba** [comment]
Checked. Already fixed
