### ISSUE TITLE
[API Wallet] Add "comment" and "expiration" parameters on address creation

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#676]
**To Do**
Add possibility to add "comment" and "expiration" parameters when creating address.

**Notes**
The "comment" and "expiration" parameters are already implemented to the **edit_address** query.

**Comment by nesbox** [comment]
Also Wiki should be updated after release:

## create_address
Creates new receiver address with given comment and expiration (`expired/never/24h`).

`-->`
```json
{
	"jsonrpc" : "2.0", 
	"id" : 1,
	"method" : "create_address", 
	"params" :
	{
		"expiration" : "24h",
		"comment" : "John Smith"
	}
}
```

`expiration` and `comment` can be ommited.


`<--`
```json
{
	"jsonrpc" : "2.0", 
	"id" : 1,
	"result" : "472e17b0419055ffee3b3813b98ae671579b0ac0dcd6f1a23b11a75ab148cc67"
}
```

**Comment by Sergei-Beam** [comment]
Checked on master v. 2.1.5307
