### ISSUE TITLE
Owner's key

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam#677]
Add ability to see and copy/share owner's key in settings. Ask password before showing it. Add alert that showing that key will show all your transactions on other devices where it will be implemented.

**Comment by dariatarakanova** [comment]
Desktop: https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/dashboard?seid=5cef9a57372bbb1d9e58a131

**Comment by alexandrashelenkova** [comment]
Designs are here
https://zpl.io/beKDRlp
https://zpl.io/VOxgz5L

**Comment by Denis-Asipenko** [comment]
When clicking the "Show owner key" button and after close alert activates the switch.
![2019-12-02_16-04-42](https://user-images.githubusercontent.com/45556620/69961766-99fdbf80-151d-11ea-9ec2-83df66920ed5.gif)

**Comment by Denis-Asipenko** [comment]
checked
