### ISSUE TITLE
Crash mobile wallet on IOS.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#682]
Steps to reproduce the behaviour:
1. Go to addresses screen.
2. Select an address and delete him.
Expected: address delete.
Actual: address doesn't delete.
after several attempts to remove the address the wallet crashes.
Please check this database and tell what happened?
Can we fix this?
Log and database are provided.
Also, the database can be opened and viewed using any sqlite editor.

Network: Testnet
Password: 123
<img width="1019" alt="2" src="https://user-images.githubusercontent.com/45556620/58468685-afe19080-8146-11e9-8522-1f4aecb717de.png">
<img width="1141" alt="1" src="https://user-images.githubusercontent.com/45556620/58468686-afe19080-8146-11e9-8e44-50f7092b4b30.png">
[wallet db.zip](https://github.com/BeamMW/beam/files/3226935/wallet.db.zip)
[beam_19_05_24_23_09_20.zip](https://github.com/BeamMW/beam/files/3226936/beam_19_05_24_23_09_20.zip)

**Comment by chapati** [comment]
Not reproduced an. Looks like previous database changes also fixed this one.
