### ISSUE TITLE
Wallet API - Add ability to export code and decode the Payment proof

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#683]
Since we are added Payment proof for CLI, UI and mobile wallets we should add it to Wallet API.
User should have the ability to export code and decode the Payment Proof.

**Comment by anatolse** [comment]
## export_payment_proof
Exports payment proof for given `txId`.

`-->`
```json
{
	"jsonrpc":"2.0", 
	"id": 4,
	"method":"export_payment_proof", 
	"params":
	{
		"txId" : "a13525181c0d45b0a4c5c1a697c8a7b8"
	}
}
```

`<--`
```json
{
	"jsonrpc":"2.0", 
	"id": 4,
	"result": 
        {
            "payment_proof": "8009f28991ef543253c8b6a2caf15cf99e23fb9c2b4ca30dc463c8ceb354d7979e80ef7d4255dd5e885200648abe5826d8e0ba0157d3e8cf9c42dcc8258b036986e50400371789ee82afc25ee29c9c57bcb1018b725a3a94c0ceb1fa7984ea13de4982553e0d78d925a362982182a971e654857b8e407e7ad2e9cb72b2b8228812f8ec50435351000c94e2c85996e9527d9b0c90a1843205a7ec8f99fa534083e5f1d055d9f53894"
        }
```

`payment_proof` is a hex-encoded byte buffer which contains information about sender, receiver, amount and kernel, signed with receiver's private key. This info could be unpacked and verified using `verify_payment_proof` method by the third party. Receiver creates a payment proof in order give receiver an ability to proof that actual payment was made. Sender does not sign transaction if receiver does not provide him this evidence.

## verify_payment_proof
Verifies the `payment_proof`.

`-->`
```json
{
	"jsonrpc":"2.0", 
	"id": 4,
	"method":"verify_payment_proof", 
	"params":
	{
		"payment_proof" : "8009f28991ef543253c8b6a2caf15cf99e23fb9c2b4ca30dc463c8ceb354d7979e80ef7d4255dd5e885200648abe5826d8e0ba0157d3e8cf9c42dcc8258b036986e50400371789ee82afc25ee29c9c57bcb1018b725a3a94c0ceb1fa7984ea13de4982553e0d78d925a362982182a971e654857b8e407e7ad2e9cb72b2b8228812f8ec50435351000c94e2c85996e9527d9b0c90a1843205a7ec8f99fa534083e5f1d055d9f53894"
	}
}
```

`<--`
```json
{
	"jsonrpc":"2.0", 
	"id": 4,
	"result": 
        {
            "is_valid": true,
            "sender":   "9f28991ef543253c8b6a2caf15cf99e23fb9c2b4ca30dc463c8ceb354d7979e",
            "receiver": "ef7d4255dd5e885200648abe5826d8e0ba0157d3e8cf9c42dcc8258b036986e5",
            "amount":   2300000000,
            "kernel":   "ee82afc25ee29c9c57bcb1018b725a3a94c0ceb1fa7984ea13de4982553e0d78"
        }
```

`is_valid` is `true` if signature is valid,
`sender`   is a sender's SBBS address
`receiver` is a receiver's SBBS address, is it is used to verify the signature 
`amount`   amount sent by this transaction
`kernel`   id of the kernel of this transaction

**Comment by Roberrtt** [comment]
In UI/CLI/Mobile wallets, we don't export a proof for a transaction with the " received" status"
![Screenshot_55](https://user-images.githubusercontent.com/50007056/76641510-cd130e80-6562-11ea-92fc-d92972d3e0c6.png)
![Screenshot_56](https://user-images.githubusercontent.com/50007056/76641513-cdaba500-6562-11ea-81b1-67d98e13f80b.png)

**Comment by Roberrtt** [comment]
checked
