### ISSUE TITLE
Cli - export/import transactions' list

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#687]
Cli only for now

User should be able to export list of his transactions with all details.
Then he should be able import this list of transactions into his wallet on another device

Also do not forget check if imported transactions are belong to the wallet

**Comment by Sergei-Beam** [comment]
@Zeke133 
1. Please add #timestamp# to the default name `export_#timestamp#.dat`

2.  General changes for export, make the export more unique
We should use one unique command and file to export data: addresses and transactions
2.1 Unique commands
Remove the commands: `|export_addresses|export_transactions|import_addresses|import_transactions|`
Create new unique commands: `export_data|import_data`
2.2 Unique file
We should export all data: addresses and transactions to one file `export_#timestamp#.dat`

3. Export to some other wallet (with different seed_phrase)
3.1 We shouldn't be able to export data to some other wallet (with different seed_phrase)
3.2 Take  a look at the screen below, some strange error appears, maybe it's a problem on my side with broken transaction OR it's a bug in the code
![image](https://user-images.githubusercontent.com/44496108/59753845-a652d080-928d-11e9-8813-1f50e934ff54.png)

4. User-friendly message about successfully export|import
We need to have the messages after successfully export|import
![image](https://user-images.githubusercontent.com/44496108/59754683-40674880-928f-11e9-890e-8bd627363ac6.png)

**Comment by Sergei-Beam** [comment]
2,4 - checked

1 - there is no timestamp. Please add it
3.2 - reproduced again
wallet DB: [wallet.zip](https://github.com/BeamMW/beam/files/3314285/wallet.zip)

**Comment by Sergei-Beam** [comment]
1-4 checked
