### ISSUE TITLE
[SWAP] Check that receiver's address is not own address

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#688]
**Bug description**
When swap_coins side sets his/her own address as the receiver's address, we need to consider such request as failure and show the error. 

**To Reproduce**
Pre-conditions: The swap test environment is set up.
1. Initiate a swap by the swap_coins side (Alice, by default) :
`-n eu-node01.masternet.beam.mw:8100 swap_coins --amount 10 --fee 0 -r 1a1d57eb6b0b305f5a1920504748927af5684f2eb50a442dd4fd9c03a0e170d4f77 --swap_amount 30000 --swap_beam_side --btc_node_addr 127.0.0.1:13300 --btc_pass 123 --btc_user Alice --swap_coin=btc --swap_feerate=4500`
and set Alice's own address as a **-r** parameter

**Current behaviour**
There's no validation on Alice's own addresses.

**Expected behaviour**
The swap request must be declined.
The error message is shown to the user:
**"Failed to initiate the atomic swap. Not able to use own address as receiver's."**

**Platform and build**
* Windows 10 x64
* BEAM Build number, masternet, 5294

**Current logs when performing the swap request (no errors)**
[logs.txt](https://github.com/BeamMW/beam/files/3236884/logs.txt)

**Comment by Sergei-Beam** [comment]
@roman-strilets Please change the error message from:
`Can't start swap to yourself.`
To:
`Failed to initiate the atomic swap. Not able to use own address as receiver's.`

**Comment by Sergei-Beam** [comment]
checked
