### ISSUE TITLE
Windows installer says it's missing a required DLL

### ISSUE THREAD

**Issue by MrCoinz** [BeamMW/beam#689]
Windows installer says it's missing a required DLL

I've downloaded the Windows desktop wallet version v. 2.1.4915 and when trying to execute the installer, Windows fails and returns a message that says "There is a problem with this Windows installer package. A DLL required"... "could not be run."

![image](https://user-images.githubusercontent.com/30242262/58758194-3ec42380-8520-11e9-9f30-6e06af8d319b.png)

**Comment by Webonnix** [comment]
Hi MrCoinz
Please try the following:
Go into c:\users\server\AppData\Local\  then right click on "temp" and choose "properies". Choose "security" --> edit --> add, and add the username you are using, and give yourself all rights.

**Comment by MrCoinz** [comment]
I have and my user already has "Allow" on all possible checkboxes, the exception being "special permissions" which is grayed out and can't be checked.

**Comment by Webonnix** [comment]
Hi MrCoinz.
Please collect the OS information and send it by e-mail { albert@beam-mw.com }
Thanks

**Comment by MrCoinz** [comment]
what do you mean by "collect the OS information"?

**Comment by Webonnix** [comment]
win+r -> dxdiag -> "Save All Information..."

**Comment by Webonnix** [comment]
Hi MrCoinz 
I understand that the message above sounded strange. The new type of installer uses Windows installer as the basis, and in your case the solution above should have helped.
But since this did not help in your case, we need to know at least the version of Windows and Windows installer,as we want to solve this issue.
Thanks for understanding

**Comment by MrCoinz** [comment]
Ok, I've saved the txt, but it seems to contain a lot of information that is not relevant to this case. Please tell me what to look for specifically and I will put that here or in the email.

Thanks.

**Comment by MrCoinz** [comment]
Operating System: Windows 10 Home 64-bit (10.0, Build 17763) (17763.rs5_release.180914-1434)
                 Language: English (Regional Setting: English)
      System Manufacturer: Hewlett-Packard
             System Model: HP ENVY TS 17 Notebook PC
                     BIOS: F.65 (type: UEFI)
                Processor: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (8 CPUs), ~2.4GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16316MB RAM

**Comment by MrCoinz** [comment]
Is this information sufficient?

**Comment by Webonnix** [comment]
Hi MrCoinz
Could you provide information about the version of Windows installer ?
Thanks

**Comment by MrCoinz** [comment]
There is no "windows installer" mention in DxDiag

**Comment by Webonnix** [comment]
Please do the following: Win+R -> msiexec -?

**Comment by MrCoinz** [comment]
Windows ® Installer. V 5.0.17763.404

**Comment by vcorem** [comment]
@MrCoinz do you have BitDefender installed on your system?

**Comment by MrCoinz** [comment]
Yes I do.

**Comment by MrCoinz** [comment]
and it keeps blocking my installation saying it's found threats.
![BD threat blocked](https://user-images.githubusercontent.com/36078880/59299637-cedb3900-8c95-11e9-88cd-f8aa01921c99.jpg)

**Comment by MrCoinz** [comment]
I tried adding the installation file to the exclusions list on Bit Defender, but to no effect.

**Comment by Webonnix** [comment]
Hi
Thank you for your answer.
The issue is resolved:
https://builds.beam.mw/mainnet/2019.05.27/Release/win/signed/fix/Beam-Wallet-2.1.4915.exe

**Comment by MrCoinz** [comment]
BEAM wallet has been successfully installed.
Thank you.
