### ISSUE TITLE
Send screen - Fee should be field (not slider)

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#69]
Fee should be field (not slider)
Default = 10 groth. Cannot be > available amount

**Comment by Sergei-Beam** [comment]
Currently, the maximum fee which system allows to transmit equal 999 groth
all that more the system nullifying
 **Sending 1 beams  (fee: 999 groth )**
I 2018-11-13.15:01:24.539 [8cf6933537b14f0090a8f0f3001683d3] Sending 1 beams  (fee: 999 groth )
 **Sending 1 beams  (fee: 1000 groth )**
I 2018-11-13.15:01:24.539 [8cf6933537b14f0090a8f0f3001683d3] Sending 1 beams  **(fee: 0 groth )**

![image](https://user-images.githubusercontent.com/44496108/48412454-c0f02480-e755-11e8-8c4a-bf2ecb519cb1.png)

**Comment by Sergei-Beam** [comment]
Checked
