### ISSUE TITLE
The language name "日本人" in README.md should be "日本語"

### ISSUE THREAD

**Issue by SwimmingTiger** [BeamMW/beam#690]
![README.md screenshot](https://user-images.githubusercontent.com/4986069/58781219-e4a18c00-860d-11e9-9762-2e4f51b55eb4.png)

**日本人** means **People from Japan**.
**日本語** means **The language spoken by people from Japan**.

Although both English expressions are **Japanese**, they are very different.
Refer to the language link on [Wikipedia](https://en.wikipedia.org/wiki/Main_Page):
![Japanese language link on Wikipedia](https://user-images.githubusercontent.com/4986069/58781483-8de88200-860e-11e9-9599-9eacffe611af.png)

**Comment by gingervik** [comment]
thank you @SwimmingTiger 
changed in master
