### ISSUE TITLE
UI Wallet - Wrong exit from fullscreen mode

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#693]
reproduced on master

Steps to reproduce:
1. Go to Wallet
2. Open in fullscreen mode
3. Go to settings
Expected: Wallet stays in fullscreen mode
Actual: Wallet exits from fullscreen mode
![image](https://user-images.githubusercontent.com/28015224/58863648-eb86d800-86bb-11e9-84fc-1067df8262f7.png)

[video.zip](https://github.com/BeamMW/beam/files/3251334/video.zip)

**Comment by VladislavKulyba** [comment]
checked on Mac and Windows
