### ISSUE TITLE
CLI wallet cannot process several incoming transactions on listen command

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#697]
**Notes**
The issue was reproduced, when sender was on:
 - Mobile Wallet,
 - Desktop Wallet 

**Bug description**
When CLI wallet starts to listen to the node and there are several transactions to his address - not all of the transactions are processed and succeed.

**To Reproduce**
Preconditions:
Wallet A (sender, desktop wallet) is installed and running.
Wallet A has 4-5 separate coins to send.
Wallet B (receiver, CLI wallet) is set up.

Steps to reproduce the behaviour:
1. In the CLI wallet create a new address:
`beam-wallet-masternet.exe new_addr`
2. Use this address as the receiver's address and from Wallet A send 4-5 transactions to the address.
3. In the CLI wallet run the `listen` command.

**Current behaviour**
Only some of the transactions are accepted.
The rest hang in the "waiting for receiver" status on the sender's side and don't succeed on both sides.

**Expected behaviour**
All of the transactions are accepted and succeed.

**Platform and build**
* Windows 10 x64
* BEAM Build number: 
Sender (desktop wallet): masternet, 5311,
Receiver (CLI wallet): masternet, 5238.

**Screenshots (if applicable)**
Sender:
![image](https://user-images.githubusercontent.com/41323026/58889496-ad0c1000-86f1-11e9-8e90-5b63ac1df86f.png)

Receiver:
![image](https://user-images.githubusercontent.com/41323026/58889754-18ee7880-86f2-11e9-97bc-11c5f71d646d.png)

Logs:
Sender:
[logs_alice.log](https://github.com/BeamMW/beam/files/3253024/logs_alice.log)

Receiver:
[logs_receiver.zip](https://github.com/BeamMW/beam/files/3253139/logs_receiver.zip)
[wallet_receiver.zip](https://github.com/BeamMW/beam/files/3253087/wallet_receiver.zip)

**Comment by anatolse** [comment]
it is not reproducible

**Comment by gingervik** [comment]
rechecked. cannot reproduce from mobile and GUI wallet
