### ISSUE TITLE
[SWAP] List of cases when we need to notify second side about failures (will be supplemented)

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#702]
1. The transaction is failed on LTC side. Should we notify the other side about it?

`will be supplemented`

**Comment by jurijakimuk** [comment]
Alice hasn't received any notifications from Bob, when Transaction has failed on the Bob's side, he didn't have enough money.
**The wallet.db files and logs:**
[Not_enough_funds_on_Bob_side_No_notification_for_Alice.zip](https://github.com/BeamMW/beam/files/3320301/Not_enough_funds_on_Bob_side_No_notification_for_Alice.zip)

**Comment by roman-strilets** [comment]
It's not bug. When Transaction has failed on the Bob's side and wallet has closed, wallet can not send notification to Alice.
