### ISSUE TITLE
[CLI] Perform Listen when rescanning

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#712]
**Task description**
Currently when rescan is performed, then he wallet balance appears as 0 coins.
It's proposed to **include the listen command to the rescan process** to get the available coins. 

**Current behavior**
Pre-condition: A CLI wallet with some UTXO exists.

1. Perform a rescan in the CLI wallet.
2. When the rescan is done - check the balance.

**Current behaviour**
The balance is 0 coins.

**Expected behaviour**
The balance remains the same.

**Comment by VladislavKulyba** [comment]
Already fixed
