### ISSUE TITLE
Add poll period parameter to cli

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#714]
We have a parameter of polling node period, it is used if we don't want to have permanent connection with a node.

Need to add --node_poll_period to command line options

**Comment by Sergei-Beam** [comment]
1. Wrong message if node_poll_period<0
2. User should be able to set period as 0.
![image](https://user-images.githubusercontent.com/44496108/59490863-61dec380-8e8e-11e9-9294-22c70236d7b3.png)

**Comment by Sergei-Beam** [comment]
1-5 checked

6. @anatolse Please hide the message"Node poll period = 0 ms" in logs if the flag doesn't exist or equal 0.
![image](https://user-images.githubusercontent.com/44496108/59600078-e0469a00-9108-11e9-993c-ba498b400437.png)

7. Please show also a message that node poll period has been automatically rounded up to block rate value if user set the `--node_poll_period` less than the expected rate of blocks 
![image](https://user-images.githubusercontent.com/44496108/59600586-42ec6580-910a-11e9-971c-1a5a817bd2d4.png)

**Comment by Sergei-Beam** [comment]
1-6 checked
7. The message should be shown once, not every block
![image](https://user-images.githubusercontent.com/44496108/59683167-4baf6b00-91e0-11e9-9a93-b787366dc2e2.png)

**Comment by Sergei-Beam** [comment]
checked
