### ISSUE TITLE
[CLI + UI] [Fork] Add validation of fee amount

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#715]
**Bug description**
We need to add the validatation for the fee amount in UI and CLI.

**Acceptance Criteria**
1) The validation must take effect upon a certain blockchain height (fork height)
2) The miminum fee value is 100 groth.
3) The default fee is set to 100 groth in UI.
4) It's not possible to enter the fee <100 groth in UI. The user gets the error with explanations: "The minimum fee is 100 groth."
5) In CLI if outgoing transaction has fee < 100 groth, such transaction is not going to the blockchain. There's a validation that results in the error: "Failed to initiate the send operation. The minimum fee is 100 groth."
6) In CLI if fee is not specified - the hardcoded fee is used, which is 100 groth.

**Comment by jurijakimuk** [comment]
- [ ] UI - in progress

- [ ] CLI - in progress

**Comment by jurijakimuk** [comment]
To be retested in the Fork environment

**Comment by Sergei-Beam** [comment]
@chapati the 'groth' should be written uppercase
Please, change the 'groth' in validator to 'GROTH'  
![image](https://user-images.githubusercontent.com/44496108/60871159-dcef8b80-a23a-11e9-926b-07b18fb6d64d.png)

**Comment by jurijakimuk** [comment]
@chapati Please, see Sergei's comment above. 
The AC items look OK on 5552, masternet.

**Comment by Sergei-Beam** [comment]
checked
