### ISSUE TITLE
[API] [Fork] Add validation of fee amount 

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#716]
If an outgoing transaction has fee < 100 groth, such transaction must not be going to the blockchain. There's a validation that results in the error: "Failed to initiate the send operation. The minimum fee is 100 groth."

**Comment by jurijakimuk** [comment]
Validation OK on master, 5597

**Comment by jurijakimuk** [comment]
If `fee `parameter is commented - we show
'Failed to initiate the send operation. The minimum fee is 100 GROTH.'

**Comment by Sergei-Beam** [comment]
checked
