### ISSUE TITLE
UI Wallet -  Wallet crashes after canceling transaction and closing receiver's window

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam#718]
reproduced on master

Pre-conditions:
1) Two wallets are installed and run: wallet A and wallet B. 

Steps to reproduce:
1. In Wallet A open the Receiver's window and create a new address. Don't close Receiver's window
2. Go to Wallet B. From Wallet B sent some Beams to this address. There is a new transaction in Main Screen with 'waiting for receiver' status. 
3. Cancel this transaction in Wallet B.
4. Close Receiver's window in Wallet A.

Expected: There are no information about this transaction in Wallet A.
Actual: Wallet A is crashed.

[Bug.zip](https://github.com/BeamMW/beam/files/3290279/Bug.zip)

[Beam-Wallet-Masternet-2.1.5414.zip](https://github.com/BeamMW/beam/files/3290283/Beam-Wallet-Masternet-2.1.5414.zip)

**Comment by chapati** [comment]
This one is not reproduced anymore. Looks like previous database fixes also fixed this one.

**Comment by chapati** [comment]
This is not reproduced on the latest master. Looks like the issue was fixed as a part of another bug. Receiver windows is closed normally and transaction status will be changed from 'receiving' to 'cancelled' after 2h. This is by design.

**Comment by VladislavKulyba** [comment]
checked
