### ISSUE TITLE
[UI] Able to open the wallet on the used port. Wrong status.

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#721]
**Bug description**
There's no information that the port is used when launching the wallet on the same port that is used already.
There's a loading icon with the text "connecting", that is spinning endlessly.

**To Reproduce**
Two wallets are installed:
Wallet A,
Wallet B.
All the wallets are closed. 

Steps:
1. Launch Wallet A and restore it using the seed phrase **on port 10005**.
2. While Wallet A is being restored - launch Wallet B **on the same port**.
3. When Wallet B is opened - see the indicator status.

**Current behaviour**
Wallet is opened.
There's a loading icon with the text "connecting", that is spinning endlessly.

**Expected behaviour**
The wallet is NOT open. There's a related connection error that reflects the situation: "`io::Exception: code=-4091 (EC_EADDRINUSE : address already in use)`"

**Platform and build**
* Windows 10 x64,
seen on masternet Wallet A 5414, Wallet B 5414
seen on masternet Wallet A 5414, Wallet B 4412

**Log file(s) (if applicable)**
[beam_ui_19_06_14_14_51_04.log](https://github.com/BeamMW/beam/files/3290560/beam_ui_19_06_14_14_51_04.log)

**Screenshots (if applicable)**
![connecting](https://user-images.githubusercontent.com/41323026/59508832-f27dc980-8eb7-11e9-9e3c-3fc4879bdae9.png)

**Comment by chapati** [comment]
This is related to #240 and #449

**Comment by gingervik** [comment]
checked
