### ISSUE TITLE
[SWAP] The same Swap transaction become as failed twice in logs

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#722]
The same Swap transaction become as failed twice in logs after 720 blocks 
![image](https://user-images.githubusercontent.com/44496108/59517561-85c0fa00-8ecc-11e9-9522-8248d7226c1a.png)

Might be related to #667 and #701

**Comment by roman-strilets** [comment]
please recheck it. now it is not reproduced. maybe it was fixed with another bug

**Comment by Sergei-Beam** [comment]
rechecked
