### ISSUE TITLE
Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates_20180409_all.deb  Hash Sum mismatch

### ISSUE THREAD

**Issue by nb7123** [BeamMW/beam#732]
**Bug title**
ca-certificates hash sum mismatch

**Bug description**
when i build Docker container use the Dockerfile, get this problem

**To Reproduce**
docker build -t "beam:v2.1.4915" .

**Current behaviour**
A clear and concise description of the erroneous behaviour which currently happens.

**Expected behaviour**

**Platform and build**
* Mac
* OS version 10.13.6
* BEAM Build number

**Log file(s) (if applicable)**
Step 1/7 : FROM ubuntu:18.04
18.04: Pulling from library/ubuntu
5b7339215d1d: Pull complete 
14ca88e9f672: Pull complete 
a31c3b1caad4: Pull complete 
b054a26005b7: Pull complete 
Digest: sha256:9b1702dcfe32c873a770a32cfd306dd7fc1c4fd134adfb783db68defc8894b3c
Status: Downloaded newer image for ubuntu:18.04
 ---> 4c108a37151f
Step 2/7 : ARG beam=beam-node-masternet.tar.gz
 ---> Running in 529046f12e3e
Removing intermediate container 529046f12e3e
 ---> a687a49f843b
Step 3/7 : RUN   apt-get -y  update  &&   mkdir -p  /home/beam/node/ &&   apt-get -y install wget  &&   wget -P /home/beam/node/  https://builds.beam.mw/master/latest/Release/linux/$beam  &&   cd /home/beam/node/  && tar -xvf $beam && rm -rf $beam &&   apt-get purge wget -y &&   apt-get autoremove -y &&   rm -rf /var/lib/apt/lists/*
 ---> Running in c6e3490718c0
Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [719 kB]
Get:5 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [4169 B]
Get:6 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [5436 B]
Get:7 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [553 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:12 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [7239 B]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [10.8 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [3918 B]
Get:18 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [2496 B]
Fetched 16.8 MB in 2min 1s (139 kB/s)
Reading package lists...
W: http://archive.ubuntu.com/ubuntu/dists/bionic/universe/binary-amd64/by-hash/SHA256/ca221e8754c933c636b6c0a344617e3444a7c8cb0982ca97725cda9b7bfe1e6a: Automatically disabled Acquire::http::Pipeline-Depth due to incorrect response from server/proxy. (man 5 apt.conf)
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  ca-certificates libpsl5 libssl1.1 openssl publicsuffix
The following NEW packages will be installed:
  ca-certificates libpsl5 libssl1.1 openssl publicsuffix wget
0 upgraded, 6 newly installed, 0 to remove and 5 not upgraded.
Need to get 2515 kB of archives.
After this operation, 6986 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libssl1.1 amd64 1.1.1-1ubuntu2.1~18.04.3 [1295 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 openssl amd64 1.1.1-1ubuntu2.1~18.04.3 [614 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic/main amd64 ca-certificates all 20180409 [151 kB]
Err:3 http://archive.ubuntu.com/ubuntu bionic/main amd64 ca-certificates all 20180409
  Hash Sum mismatch
  Hashes of expected file:
   - SHA256:195ffe05ae7d060146f890b1db225f5e8c3a8c505ffbea1fba30a520a1cd58d8
   - SHA1:8ac5ac1506810b0483f0b80b0652071348459fc4 [weak]
   - MD5Sum:eae40792673dcb994af86284d0a01f36 [weak]
   - Filesize:150932 [weak]
  Hashes of received file:
   - SHA256:9ee729d467162e61a3b25c9e2c41734268837d7d17a72a4ae99bba0cd2f5f16c
   - SHA1:38262ef6d96ecc90edccbb65843287a3d8c95343 [weak]
   - MD5Sum:68a194e048196d05d722f9816dd2cf1c [weak]
   - Filesize:315936 [weak]
  Last modification reported: Tue, 09 Apr 2019 11:38:23 +0000
Err:4 http://archive.ubuntu.com/ubuntu bionic/main amd64 libpsl5 amd64 0.19.1-5build1
  Bad header line Bad header data [IP: 113.215.225.230 80]
Get:5 http://archive.ubuntu.com/ubuntu bionic/main amd64 publicsuffix all 20180223.1310-1 [97.6 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 wget amd64 1.19.4-1ubuntu2.2 [316 kB]
Fetched 2638 kB in 36s (74.0 kB/s)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates_20180409_all.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA256:195ffe05ae7d060146f890b1db225f5e8c3a8c505ffbea1fba30a520a1cd58d8
    - SHA1:8ac5ac1506810b0483f0b80b0652071348459fc4 [weak]
    - MD5Sum:eae40792673dcb994af86284d0a01f36 [weak]
    - Filesize:150932 [weak]
   Hashes of received file:
    - SHA256:9ee729d467162e61a3b25c9e2c41734268837d7d17a72a4ae99bba0cd2f5f16c
    - SHA1:38262ef6d96ecc90edccbb65843287a3d8c95343 [weak]
    - MD5Sum:68a194e048196d05d722f9816dd2cf1c [weak]
    - Filesize:315936 [weak]
   Last modification reported: Tue, 09 Apr 2019 11:38:23 +0000
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libp/libpsl/libpsl5_0.19.1-5build1_amd64.deb  Bad header line Bad header data [IP: 113.215.225.230 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get -y  update  &&   mkdir -p  /home/beam/node/ &&   apt-get -y install wget  &&   wget -P /home/beam/node/  https://builds.beam.mw/master/latest/Release/linux/$beam  &&   cd /home/beam/node/  && tar -xvf $beam && rm -rf $beam &&   apt-get purge wget -y &&   apt-get autoremove -y &&   rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
michaeldeMacBook-Pro:beam michael$ docker build -t "beam:v2.1.4915" .
Sending build context to Docker daemon  3.584kB
Step 1/7 : FROM ubuntu:18.04
 ---> 4c108a37151f
Step 2/7 : ARG beam=beam-node-masternet.tar.gz
 ---> Using cache
 ---> a687a49f843b
Step 3/7 : RUN   apt-get -y  update  &&   mkdir -p  /home/beam/node/ &&   apt-get -y install wget  &&   wget -P /home/beam/node/  https://builds.beam.mw/master/latest/Release/linux/$beam  &&   cd /home/beam/node/  && tar -xvf $beam && rm -rf $beam &&   apt-get purge wget -y &&   apt-get autoremove -y &&   rm -rf /var/lib/apt/lists/*
 ---> Running in a3700168688d
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:3 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [4169 B]
Get:4 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [5436 B]
Get:5 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [719 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Err:7 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
  502  Bad Gateway [IP: 113.215.225.230 80]
Get:8 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:11 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [553 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [10.8 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [7239 B]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1222 kB]
Fetched 16.7 MB in 1min 9s (242 kB/s)
Reading package lists...
W: http://archive.ubuntu.com/ubuntu/dists/bionic/main/binary-amd64/by-hash/SHA256/ff7fd80e902a1acfba06e7b513711da31abe915d95b3ba39ce198e02efd209e5: Automatically disabled Acquire::http::Pipeline-Depth due to incorrect response from server/proxy. (man 5 apt.conf)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  502  Bad Gateway [IP: 113.215.225.230 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  ca-certificates libpsl5 libssl1.1 openssl publicsuffix
The following NEW packages will be installed:
  ca-certificates libpsl5 libssl1.1 openssl publicsuffix wget
0 upgraded, 6 newly installed, 0 to remove and 5 not upgraded.
Need to get 2515 kB of archives.
After this operation, 6986 kB of additional disk space will be used.
Err:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libssl1.1 amd64 1.1.1-1ubuntu2.1~18.04.3
  Bad header line Bad header data [IP: 113.215.225.230 80]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 openssl amd64 1.1.1-1ubuntu2.1~18.04.3 [614 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic/main amd64 ca-certificates all 20180409 [151 kB]
Err:3 http://archive.ubuntu.com/ubuntu bionic/main amd64 ca-certificates all 20180409
  Hash Sum mismatch
  Hashes of expected file:
   - SHA256:195ffe05ae7d060146f890b1db225f5e8c3a8c505ffbea1fba30a520a1cd58d8
   - SHA1:8ac5ac1506810b0483f0b80b0652071348459fc4 [weak]
   - MD5Sum:eae40792673dcb994af86284d0a01f36 [weak]
   - Filesize:150932 [weak]
  Hashes of received file:
   - SHA256:0cccb105591c1089bf625ddf1c19c38791574a92ff5f7f561608899619740df9
   - SHA1:c21cebe6827d225b90007d290b8fc43a04bc1b75 [weak]
   - MD5Sum:1d9bb6051046888c91e5b4ffad57ad9c [weak]
   - Filesize:150932 [weak]
  Last modification reported: Wed, 11 Apr 2018 14:34:45 +0000
Err:4 http://archive.ubuntu.com/ubuntu bionic/main amd64 libpsl5 amd64 0.19.1-5build1
  Bad header line Bad header data [IP: 113.215.225.229 80]
Get:5 http://archive.ubuntu.com/ubuntu bionic/main amd64 publicsuffix all 20180223.1310-1 [97.6 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/main amd64 publicsuffix all 20180223.1310-1 [97.6 kB]
Fetched 1178 kB in 32s (36.6 kB/s)
W: http://archive.ubuntu.com/ubuntu/pool/main/p/publicsuffix/publicsuffix_20180223.1310-1_all.deb: Automatically disabled Acquire::http::Pipeline-Depth due to incorrect response from server/proxy. (man 5 apt.conf)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.3_amd64.deb  Bad header line Bad header data [IP: 113.215.225.230 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates_20180409_all.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA256:195ffe05ae7d060146f890b1db225f5e8c3a8c505ffbea1fba30a520a1cd58d8
    - SHA1:8ac5ac1506810b0483f0b80b0652071348459fc4 [weak]
    - MD5Sum:eae40792673dcb994af86284d0a01f36 [weak]
    - Filesize:150932 [weak]
   Hashes of received file:
    - SHA256:0cccb105591c1089bf625ddf1c19c38791574a92ff5f7f561608899619740df9
    - SHA1:c21cebe6827d225b90007d290b8fc43a04bc1b75 [weak]
    - MD5Sum:1d9bb6051046888c91e5b4ffad57ad9c [weak]
    - Filesize:150932 [weak]
   Last modification reported: Wed, 11 Apr 2018 14:34:45 +0000
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libp/libpsl/libpsl5_0.19.1-5build1_amd64.deb  Bad header line Bad header data [IP: 113.215.225.229 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get -y  update  &&   mkdir -p  /home/beam/node/ &&   apt-get -y install wget  &&   wget -P /home/beam/node/  https://builds.beam.mw/master/latest/Release/linux/$beam  &&   cd /home/beam/node/  && tar -xvf $beam && rm -rf $beam &&   apt-get purge wget -y &&   apt-get autoremove -y &&   rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by nb7123** [comment]
when i change this base container from: ubuntu:18.04 to ubuntu:16.04, it's build success

**Comment by Webonnix** [comment]
He nb7123
We tested this issue on macOS High Sierra 10.13.6 and it did't reproduce.
Probably the problem which was reproduced on your PC is not associated with Ubuntu version
Thank you for your message.

**Comment by gingervik** [comment]
no user's responce for a month
