### ISSUE TITLE
Error Running GPU Miner 2 Issues

### ISSUE THREAD

**Issue by estorbotz** [BeamMW/beam#74]
**Bug description**
GPUMiner closes after displaying few lines.

GPUassert: out of memory C:/Users/grigo/projects/github/beam/pow/impl/equihash_gpu.cu 976
![beam3](https://user-images.githubusercontent.com/45031740/48472003-33cdce00-e830-11e8-9206-1444d9a7ab9f.png)

**Comment by estorbotz** [comment]
![error2](https://user-images.githubusercontent.com/45031740/48495899-dce5ea00-e86b-11e8-9b17-298c6107a0d5.png)

**Comment by estorbotz** [comment]
Dump and Log Files
[Dump and Log Files.zip](https://github.com/BeamMW/beam/files/2581679/Dump.and.Log.Files.zip)

**Comment by gingervik** [comment]
hi @estorbotz 
have you tried our Testnet 3 release build?
does it show the same error?

**Comment by gingervik** [comment]
no responce from user for a lokg time. cannot reproduce
