### ISSUE TITLE
Wallet crashes if you specify an incorrect port and close wallet.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#744]
If you specify the wrong port in the node address(example: eu-node01.masternet.beam.mw:8104) and close the wallet, the wallet crashes.
Precondition: The wallet is installed and runs on a local node.
Steps to reproduce the behaviour:
1. Go to the wallet.
2. Navigate to the Settings screen.
3. Click the switch from local to remote node.
4. Enter node address(example: eu-node01.masternet.beam.mw:8104).
5. Apply the changes  and close the wallet.
Actual: wallet crashes
checked on win
version: 2.1.5534
[Beam Wallet Masternet0.dmp.zip](https://github.com/BeamMW/beam/files/3334109/Beam.Wallet.Masternet0.dmp.zip)

**Comment by chapati** [comment]
Also after you follow steps above wallet will never open and will always crash on close. Will fix crash and looks like a separate bug for always stuck wallet should be opened.

**Comment by chapati** [comment]
Graceful network - shutdown - b1244b8394498fb8b477214ae99b323ef65f4094

**Comment by gingervik** [comment]
checked on master (win)
