### ISSUE TITLE
Restoring Wallet After Crash Loses Addresses Set As "Permanent" (Non-Expiring)

### ISSUE THREAD

**Issue by taoteh1221** [BeamMW/beam#748]
I mined for about 6 weeks on Leafpool, and decided to finally cash out. The way leafpool works for Beam is by a) setting a receive address in the Beam wallet to never expire, b) Using that address as your "login" on leafpool for mining and getting you mining reward after mining for awhile.

My old Beam Wallet froze again and again (debian build from a few months ago, running on Ubuntu 18), and refused to sync, so I deleted the entire beam directory under ~/.local/share/Beam Wallet/ in my user directory, and synced fine with the latest Beam Wallet debian build from beam.mw, and used my same recovery phrase.

The recovery phrase worked fine, I saw my balance as is was before the crash. The problem is my addresses which I marked as "never expire" for mining pools were no longer there. So when I tried a withdrawal from the mining pool to my wallet it did not work (I presume because these addresses were no longer registered in the wallet). 

I still have those addresses saved in a text file. Is there anyway I can add these "never expire" addresses back into my wallet configuration, so I can withdrawal from leafpool, or not?

1. Setup a "never expire" address, save it to a text file backup, and use it to mine on leafpool as your "login" identity
2. Delete ENTIRE beam data directory
3. Resync / restore wallet from seed phrase with latest debian public release
4. See your "never expire" addresses are no longer in the addresses list
5. Try to withdrawal from leafpool with your "never expire" address from step 1 that you mined with there

System:
Ubuntu 18
Original Beam Wallet was a few months old that crashed (no idea what build number), restored after deleting the data directory with latest Beam Wallet .deb file on your beam.mw website as of June 29th.

**Comment by Jagor21** [comment]
Hello @taoteh1221 ,

Addresses and transaction history are stored locally at wallet.db file. You can find it here - **/home/{your User name}/.local/share/Beam Wallet/<version>/wallet.db**
Due to uninstall or restore new wallet.db file is created. In order to keep your addresses and transaction history I recommend creating a backup for your wallet.db file.
Also, I advise to create a new address, make it never expire, and contact Leafpool support with a change address request.

**Comment by taoteh1221** [comment]
Thanks for the info @Jagor21 , I'll see if leafpool can change the payout address.
