### ISSUE TITLE
beam-node-testnet   unable to synchronize data

### ISSUE THREAD

**Issue by EWIT521** [BeamMW/beam#749]
./beam-node-testnet  --port=11000 --pass=123aaa   --miner_key=5TrR6jgkru7sBsuxYzw68ScMYEitWWgDqOZYLIemsbac5AW3ni+SS5l8PyNJV0G+atNcDDwbGdsXMPelkVClaU1OSXksVrI+hmI=  --owner_key=U990KR37/TzPBsuxYzw68ScMYEitWWgDqOZYLIemsbac5AW3ni+SS5nDazUqoneJJeoEHVCvI18kFLFaUWM/ft1GwUFATYYOP1J2oycJuxLtT7D7vtFTj3deTqp6ybPar3VAzoQlpm/ecXDl
I 2019-07-01.11:00:17.134 Beam Node 2.1.4927 (testnet)
I 2019-07-01.11:00:17.134 Rules signature: cfa9cf691cfe775a
I 2019-07-01.11:00:17.438 starting a node on 11000 port...
I 2019-07-01.11:00:17.439 Loading UTXOs...
I 2019-07-01.11:00:17.439 Node ID=d50872d88c509c35
I 2019-07-01.11:00:17.439 Initial Tip: 0-0000000000000000
I 2019-07-01.11:00:17.439 Tx replication is OFF
I 2019-07-01.11:00:17.439 Rescanning owned Txos...
I 2019-07-01.11:00:17.440 Recovered 0/0 unspent/total Txos
I 2019-07-01.11:00:17.440 Requesting block 0-0000000000000000

**Comment by gingervik** [comment]
hi @EWIT521 you forgot to add --peer parameter
list of peers:
ap-nodes.testnet.beam.mw:8100
eu-nodes.testnet.beam.mw:8100
us-nodes.testnet.beam.mw:8100
