### ISSUE TITLE
Mac - Signature for our builds in OS X 10.15 

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#750]
![image](https://user-images.githubusercontent.com/28015224/60445000-04d16480-9c27-11e9-9444-124c27654816.png)
user should not see this message
https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

**Comment by nesbox** [comment]
script example how to notarize app on a CI server (taken from https://github.com/keybase/client/blob/46f5df0aa64ff19198ba7b044bbb7cd907c0be9f/packaging/desktop/package_darwin.sh#L278-L306)
``` sh
# Notarize the dmg
notarize_dmg() {(
  cd "$out_dir"
  if [ "$skip_notarize" = "1" ]; then
    echo "Skipping notarize..."
    return
  fi
  echo "Uploading $dmg_name to notarization service in $out_dir"
  uuid=`xcrun altool --notarize-app --primary-bundle-id "keybase.notarize" --username "apple-dev@keyba.se" --password "@keychain:notarization" --file "$dmg_name" 2>&1 | grep 'RequestUUID' | awk '{ print $3 }'`
  echo "Successfully uploaded to notarization service, polling for result: $uuid"
  sleep 15
  while :
  do
    fullstatus=`xcrun altool --notarization-info "$uuid" --username "apple-dev@keyba.se" --password "@keychain:notarization" 2>&1`
    status=`echo "$fullstatus" | grep 'Status\:' | awk '{ print $2 }'`
    if [ "$status" = "success" ]; then
      echo "Notarization success"
      xcrun stapler staple "$dmg_name"
      return
    elif [ "$status" = "in" ]; then
      echo "Notarization still in progress, sleeping for 15 seconds and trying again"
      sleep 15
    else
      echo "Notarization failed fullstatus below"
      echo "$fullstatus"
      exit 1
    fi
  done
)}
```
so, for us should be smth like `xcrun altool --notarize-app --primary-bundle-id "com.mw.beam.beamwallet" -u "vadim@beam.mw" -p "<pass>" --file ./Beam-Wallet-2.2.5635.dmg
`
some usefull info here https://discuss.pixls.us/t/notarizing-filmulator-for-macos-10-15-catalina-illustrated/12975

**Comment by nesbox** [comment]
Checked on Macos 10.15 Catalina, all works fine.
