### ISSUE TITLE
UI Wallet is stuck on loading and crashed if wrong node/port

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam#751]
Spins from #744 

**Precon:**: 
Wallet is installed and runs on a local node.

**Steps to reproduce behaviour:**

1. Open wallet.
2. Navigate to the Settings screen.
3. Click the switch from a local to remote node.
4. Enter a wrong node address (example: eu-node01.masternet.beam.mw:8104).
6. Apply the changes and close the wallet.
7. Open wallet again

**Actual:** 
Wallet is trying to connect for very long time without visual any visual indication that anything happens. After some time 1.5 min wallet would crash if Debug build. In Release it would open and display 'Cannot connect' which is ok. There is an obvious error that is evident only in debug and should be fixed.

Checked on linux but should be reproducible on any OS. 

![image](https://user-images.githubusercontent.com/12074933/60458274-34946280-9c4f-11e9-9bbc-b4a034f85ec2.png)

**Comment by chapati** [comment]
Fixed in 401669f1cb0e200de815c813f300207f94954e48

**Comment by jurijakimuk** [comment]
There's no way of running the debug version on Linux 19.04 (Disco Dingo). The root cause is missing libraries. @chapati please, take a look.

**Comment by chapati** [comment]
We have issues with debug linux build on our build servers. Please contact me and I'll explain how to test this.

**Comment by Sergei-Beam** [comment]
Checked
