### ISSUE TITLE
Broken Qt 5.11 Link and Build Issue - Build Instructions - Mac OS

### ISSUE THREAD

**Issue by breadsax** [BeamMW/beam#753]
It seems as if Qt 5.11 is still the compatible version of Qt required to build the wallet, but the link in the instructions is now broken as Qt 5.11 is not available to download.

https://download.qt.io/official_releases/qt/5.11/5.11.0/qt-opensource-mac-x64-5.11.0.dmg.mirrorlist

vs.

https://download.qt.io/official_releases/qt/

**Comment by Sergei-Beam** [comment]
@nesbox looks like maybe you can help here. Can you take a look please?

**Comment by breadsax** [comment]
It might be worse than I thought. I had a copy of Qt 5.11 so I tried to compile. When running I get a different error than I received with Qt 5.12. Perhaps related to openssl version?

**Comment by breadsax** [comment]
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [1018]

Application Specific Information:
/usr/local/opt/boost/lib/libboost_locale-mt.dylib

**Comment by breadsax** [comment]
@nesbox Are you able to look at the error I get when launching the wallet after compiling from source?

Do you think it is related to openssl version or boost version?

**Comment by nesbox** [comment]
@breadsax Hi, I haven't seen this crash before, 
as a variant, please, try to build with `-DBEAM_LINK_TYPE=Static` flag

**Comment by breadsax** [comment]
@nesbox I ran the command cmake -DCMAKE_BUILD_TYPE=Release -DBEAM_LINK_TYPE=Static . && make -j4

I then received an error when compiling:

[100%] Building CXX object ui/CMakeFiles/beam-wallet-ui.dir/view_controls_CustomButton_qml.cpp.o
make[2]: *** No rule to make target `/lib/libQt53DAnimation.a', needed by `ui/Beam Wallet'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[100%] Building CXX object ui/CMakeFiles/beam-wallet-ui.dir/view_controls_ConfirmPasswordDialog_qml.cpp.o
[100%] Building CXX object ui/CMakeFiles/beam-wallet-ui.dir/qmlcache_loader.cpp.o
make[1]: *** [ui/CMakeFiles/beam-wallet-ui.dir/all] Error 2
make: *** [all] Error 2

I will try to compile by calling cmake -DBEAM_LINK_TYPE=Static . && make -j4 and see what happens

**Comment by breadsax** [comment]
I received the above error again when attempting to compile.

There were no errors before, just the crash on launch.

Are you able to reproduce from a fresh build @nesbox? Can you please confirm which boost and openssl versions are being used with brew?

**Comment by nesbox** [comment]
The problem is that we support only qt5.10-qt5.11, but the Qt Company removed these builds from their official server for an unknown reason.
I see two ways atm, the easiest is to install https://download.qt.io/official_releases/qt/5.12/ instead of 5.11 and build with our official build instructions, but we haven't tested this version yet. Or second, try to download our prebuilt QT libs, you can clone them here https://github.com/nesbox/qt5-static-mac.git, also use -DBEAM_LINK_TYPE=Static flag with our libs.
Hope this will help you and sorry for the delay with the response.

**Comment by breadsax** [comment]
@nesbox I know my post has become confusing, but the Qt link is a minor issue now. 

I was able to try compiling with Qt 5.11 which worked, but I receive the above crash when starting the wallet.

Are you able to try compiling from source on a fresh Mac Mojave build in a VirtualBox?

Could you please confirm what versions of openssl and boost are installed with brew when you are compiling?

Thanks!

**Comment by nesbox** [comment]
Sorry, so, I have `openssl: stable 1.0.2s` and `boost: stable 1.70.0`

**Comment by breadsax** [comment]
@nesbox Interesting, I have the same versions of those.

Qt 5.12 does not work, I have a previous error reported because it would crash on start after building with that version. That's why we changed the build instructions. Brew would install version 5.12 of Qt.

I did find an archive link on their website https://download.qt.io/archive/qt/5.11/

I may try building with 5.11.3 and see what happens.

Please let me know if you can replicate the crash or if you are able to build on a clean version of Mojave.

**Comment by breadsax** [comment]
It's because of Static versus Dynamic links to Qt isn't it?

https://stackoverflow.com/questions/14224439/link-application-to-static-version-of-qt-on-mac

**Comment by nesbox** [comment]
I use official QT5.11 libs to build Beam and it doesn't crash on the Mojave. Please, check QT from the link you found https://download.qt.io/archive/qt/5.11/ and I'll fix our Build Instructions then.
Thanks.

**Comment by breadsax** [comment]
Thank you @nesbox . I wonder if these instructions are also an option?

https://github.com/BeamMW/beam/commit/2120eff2e9e42e6eb7fd0de821d4587e6d81e228

**Comment by nesbox** [comment]
Yes, these instructions were added to install qt5.11 with the Brew, because you can't point version and Brew installs 5.12 version by default.

**Comment by breadsax** [comment]
@nesbox I don't know why, but I still get the crash when starting the wallet after compiling both of those ways. Thank you for your efforts.

**Comment by nesbox** [comment]
@breadsax Hi, could you please try to fully uninstall QT from the Brew using `brew uninstall qt5` and then
``` bash
curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/56c500b569c724b049be7ab9e12d9693f85522f9/Formula/qt.rb
brew install ./qt.rb
brew link qt5 --force
export PATH=/usr/local/opt/qt/bin:$PATH
```
and rebuild, because I think you still use incorrect QT version

**Comment by breadsax** [comment]
@nesbox I tried that way and it crashed again when starting the wallet. Same error:

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [6847]

Application Specific Information:
/usr/local/opt/boost/lib/libboost_locale-mt.dylib

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libicuuc.64.dylib             	0x0000000109556d0e uprv_strnicmp_64 + 121
1   libicuuc.64.dylib             	0x00000001095380e0 ulocimp_getLanguage_64 + 73

**Comment by breadsax** [comment]
@nesbox Do you think it is related to boost based on the error? Perhaps dynamic linking versus static?

**Comment by nesbox** [comment]
I don't think so.
could you pls show all the files you have in `beam/ui` directory after a build is done?

**Comment by breadsax** [comment]
@nesbox Here is what I have in that directory. Thank you. 

![Screen Shot 2019-07-19 at 5 05 52 PM](https://user-images.githubusercontent.com/48415390/61568202-ea312500-aa47-11e9-9f61-4e558eb55f18.png)
![Screen Shot 2019-07-19 at 5 06 11 PM](https://user-images.githubusercontent.com/48415390/61568208-f0270600-aa47-11e9-8f94-e695ae370073.png)
![Screen Shot 2019-07-19 at 5 07 22 PM](https://user-images.githubusercontent.com/48415390/61568211-f3ba8d00-aa47-11e9-9c52-87cd41d129e2.png)

**Comment by breadsax** [comment]
@nesbox @Sergei-Beam @gingervik 

I wanted to confirm this was still an issue with the Build Instructions. I went back and reinstalled cleanly, followed the Build Instructions and compiled version 2.1 and it works perfectly. 

Versions 2.2 and 3.0 will crash after starting the executable when building on OS X (testing on Mojave) with current build instructions.

Can you please also verify CMake version being used? Is it the most current that brew installs?

Thank you!

**Comment by nesbox** [comment]
I have cmake version 3.14.0

**Comment by breadsax** [comment]
@nesbox Ok, thanks, interesting. I think it is a conflict with previous version of Beam being installed on my machine.

I compiled version 3.0 in a VirtualBox and everything works.

It is a strange conflict as node.db and wallet.db don't appear to be accessed when starting version 3.0 on my machine with the crash.

I am going to try installing from the .dmg I created on the VirtualBox and see how that goes.

**Comment by breadsax** [comment]
@nesbox I tried to install the working .dmg I had built in a VirtualBox on my Mac and when I launch the wallet I still get the crash. I tried removing the ~/(user)/Library/Application Support/Beam Wallet directory to see if it was a conflict with a previous node.db and/or wallet.db file and the wallet still crashes on start. 

Where could this conflict be? Why am I able to build and run version 2.1, but not 2.2 or 3.0?

**Comment by nesbox** [comment]
ok, what happens when you install 2.1 2.2 or 3.0 from our official downloads section https://www.beam.mw/downloads?

**Comment by breadsax** [comment]
@nesbox I don't normally like to download, but I did so that I could test the issue. I was able to get 3.0 to successfully start from the downloaded .dmg. Not sure why it builds correctly, but will not start. Some conflict with previous Qt installation from the build instructions maybe? I had uninstalled that version of Qt though, so I don't know.

**Comment by breadsax** [comment]
@nesbox I was finally able to compile and run this without the crash! I pulled from mainnet branch today with current changes, updated to the new cmake, and then ran the instructions from the .travis.yml file for OS X release. I modified by not running the things necessary to sign for Mac. 

I pulled the static Qt from those instructions in your repo. I exported that to PATH. 

My final command was cmake -DCMAKE_BUILD_TYPE=Release -DBEAM_LINK_TYPE=Static -DBRANCH_NAME=Mainnet . && make -j 4

Can you please update the build instructions regarding Qt? 

I can then close the issue.

Thank you for your help!

**Comment by Ryan-i** [comment]
> @nesbox I was finally able to compile and run this without the crash! I pulled from mainnet branch today with current changes, updated to the new cmake, and then ran the instructions from the .travis.yml file for OS X release. I modified by not running the things necessary to sign for Mac.
> 
> I pulled the static Qt from those instructions in your repo. I exported that to PATH.
> 
> My final command was cmake -DCMAKE_BUILD_TYPE=Release -DBEAM_LINK_TYPE=Static -DBRANCH_NAME=Mainnet . && make -j 4
> 
> Can you please update the build instructions regarding Qt?
> 
> I can then close the issue.
> 
> Thank you for your help!

I have the same error,please help me
