### ISSUE TITLE
Clicking on Kernel ID should open Blockchain explorer

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#754]

**Comment by dariatarakanova** [comment]
https://zpl.io/a7Olx4M

**Comment by sasha-abramovich** [comment]
@dariatarakanova we need a dialog just like on mobile that explains about the privacy risk related

**Comment by echoby** [comment]
Need icon in svg format https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5c64ea5c19485e4646f1121e?did=5d5be78b641a109bd3427d1f

**Comment by dariatarakanova** [comment]
> Need icon in svg format https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5c64ea5c19485e4646f1121e?did=5d5be78b641a109bd3427d1f

Alexandra sent icon in zeplin (comment)

**Comment by gingervik** [comment]
we need it for received. sent, completed only

**Comment by gingervik** [comment]
checked on master
