### ISSUE TITLE
Issue with upgrading to 2.2.5635 from version 1.1.4202 on Windows 10

### ISSUE THREAD

**Issue by overcookedpanda** [BeamMW/beam#755]
Wallet password not accepted when opening migrated wallet.

When installing version 2.2.5635 onto a system with a wallet.db file from version 1.1.4202 it detects the old wallet and states it will be migrated, but after migration, the wallet cannot be opened and simply says "Invalid Password" even when using the correct wallet password.

**Platform and build**
Windows 10
Beam 2.2.5635

**Comment by overcookedpanda** [comment]
It should be noted that I was able to update to version 2.1.4914 successfully and the password is recognized, I then tried to install 2.2.5635 again with the same results, so really no idea what is going on here.

**Comment by gingervik** [comment]
@Jagor21 please, handle

**Comment by gingervik** [comment]
@overcookedpanda we are working on reproducing and fixing this issue

**Comment by gingervik** [comment]
will be fixed [here](https://github.com/BeamMW/beam/issues/788)
thank you for finding bug
