### ISSUE TITLE
When will beamvm support confidential asset?

### ISSUE THREAD

**Issue by vjoke** [BeamMW/beam#756]
**Feature title**
Confidential Asset

**Describe the current situation we have**
I want to know when beam will support confidential asset

**Comment by vjoke** [comment]
does anybody can answer my question?

**Comment by gingervik** [comment]
hi @vjoke 
acc to our roadmap confidential assest will not be implemented in several future releases

**Comment by gingervik** [comment]
for all discussion please join our community in telegram or discord
https://t.me/BeamPrivacy
https://discord.gg/BHZvAhg
