### ISSUE TITLE
Improve UX on wallet load

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#757]
Reported by Guy Corem: 
In Desktop Wallet, "Loading wallet..." phase can be very long on old computers, in the log, I see: Loading UTXOs... and later Rescanning owned TXOs... Takes long minutes, we need to give some feedback / hints to the user; it's very long and concering without the CLI log. Took long minutes to pass it, without any feedback to the user.

**Comment by alexandrashelenkova** [comment]
Already implemented
