### ISSUE TITLE
Move UI for Send/Receive screens to separate components

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#758]
Send and Receive views are parts of the wallet view. We have to move them to separate views to be able to extend and maintain them

**Comment by chapati** [comment]
Send/receive should be tested carefully, there were many changes

**Comment by gingervik** [comment]
will be checked during regression testing

**Comment by chapati** [comment]
> will be checked during regression testing
Yup, changes are not visible to testers, just need to test that nothing is broken (send/receive works), this is a part of swap ui changes and can be tested only after swap ui is merged

**Comment by gingervik** [comment]
checked during regression
