### ISSUE TITLE
User cannot access wallet.db after upgrade due to invalid database version

### ISSUE THREAD

**Issue by Jagor21** [BeamMW/beam#762]
After upgrading from 1.1.4202 to 2.2.5635 user is getting "Invalid DB version: 9. Expected: 15" message and database refuses to accept right password.

[Logs](https://drive.google.com/drive/folders/1bCLTW6Xz5jSl06EjhZ2_XEg0gOWBWGpI?usp=sharing)

OS: macOS High Sierra v. 10.13.2

**Comment by gingervik** [comment]
i think was fixed in 3.1
