### ISSUE TITLE
User cannot access wallet.db after upgrade due to generic SQLite error

### ISSUE THREAD

**Issue by Jagor21** [BeamMW/beam#763]
User cannot access wallet.db after upgrade due to generic SQLite error: "sqlite error code=1, there is already another table or index with this name: storage_del"

[Logs](https://drive.google.com/drive/folders/1NJug7IwXnONQxVSkP_vyIYlxYFSlpIsX?usp=sharing)

OS: Windows 7

**Comment by gingervik** [comment]
i think was fixed in 3.1
