### ISSUE TITLE
Wallet crashes & address not saved

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam#765]
**Steps**
1. Open 'Receive Beam' view
2. New address is generated
3. Add comment to be able to identify new address
4. Close wallet while 'Receive' view is opened

**Actual**
Wallet crashes and address is not saved (open wallet again to check).

![Selection_183](https://user-images.githubusercontent.com/12074933/61156433-6be2f900-a504-11e9-977f-e03ceb470153.png)

**Comment by chapati** [comment]
This is caused in https://github.com/BeamMW/beam/commit/668936a3240b5cd91f84f8cf6ac259d17b616b0c by moving AppModel construction after QT Engine

**Comment by gingervik** [comment]
checked on 3.0.5638
