### ISSUE TITLE
Fix color of connection error status indicator

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam#768]
Correct red color should be #ff746b
https://zpl.io/bWjwvne

**Comment by alexandrashelenkova** [comment]
<img width="392" alt="Screenshot 2019-07-10 at 17 30 46" src="https://user-images.githubusercontent.com/7249484/61206974-7da3e680-a726-11e9-8d23-2cf7cd48c9a2.png">

**Comment by gingervik** [comment]
checked
