### ISSUE TITLE
[API] Tx_split method must take into account the amount of outputs when calculating the minimum fee

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/beam#769]
**Bug description**
An API **tx_split** request may have several outputs, so this will require spending more than 100 groth of fee (minimum fee). In order for that transaction to succeed - we need to calculate the minimum fee taking into account an amount of outputs, provided in the request.

**Formula to implement when calculating the fee:**
Minimum Fee = (amounts of outputs) * 10 + (amount of kernels) * 10

**Acceptance Criteria**
1) When a split is requested and no fee is specified - the automatically calculated fee is used. No error is shown.
2) When a split is requested and the fee specifed is less than the automatically calculated fee - there's an error: "The minimum fee must be: {automatically calculated fee} ."
3)  When a split is requested and the fee specifed equals the automatically calculated fee - the operation succeeds.
4)  When a split is requested and the fee specifed is more than the automatically calculated fee - the operation succeeds.

**Comment by Sergei-Beam** [comment]
1-4 Checked
