### ISSUE TITLE
Changing the SIGHUP processing on MacOs / Linux

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#77]
**TASK:** We should change the processing SIGHUP process and make the shutdown cli beam-node after closing the Terminal

BUG as a result of incorrect work
**Bug description**
cli beam-node process didn't close when user closed the Terminal on MacOs/Linux systems and continue working
We should process SIGHUP and make the shutdown beam-node process after closing the Terminal
**To Reproduce**
1. Run 'the cli beam-node' via Terminal
2. Wait while system downloaded macroblock
3. close the Terminal
4. open System Monitor and check the process

**Current behavior**
cli beam-node process didn't close when user closed the Terminal on MacOs/Linux systems and continue working

**Comment by gingervik** [comment]
checked on mac and linux

**Comment by chapati** [comment]
Now on linux several cli commands cannot be chained in one script without trap "" INT. Also wrapper is required for our automation. Should check if possible to fix.
