### ISSUE TITLE
Create panel for swap offers

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#772]
there is no design yet.

In general, there should be a list of transaction parameters (swaps), this list should be sortable and filterable, each item could initiate a transaction(there should be a button for this)

**Comment by alexandrashelenkova** [comment]
@anatolse created new task here https://github.com/BeamMW/beam/issues/849, it includes not only swap offers but also swap transactions list. Should I close that one or the new one?

**Comment by alexandrashelenkova** [comment]
Updated screens are here https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/dashboard?seid=5d638945e0f07c9bf9710ca7
Please pay attention to notes on screens (ONLY violet comments).
<img width="123" alt="64518227-5fbcc180-d324-11e9-8690-b8f7733655b6" src="https://user-images.githubusercontent.com/7249484/64525215-ea0c2200-d332-11e9-91e3-55574af3080c.png">

**Comment by Sergei-Beam** [comment]
1. Rate shows in the wrong format
![image](https://user-images.githubusercontent.com/44496108/65679614-1a0b3300-e05e-11e9-80c9-2d0fa52c5061.png)

**Comment by Zeke133** [comment]
rate format fixed

**Comment by Sergei-Beam** [comment]
checked
