### ISSUE TITLE
Desktop Wallet doesn't load addresses

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam#773]
**Steps**
1. Run Wallet
2. Open the Receive view. New address is generated automatically
3. Add some comment that would be easily identifiable in the future, let's say 'beam'
![Selection_186](https://user-images.githubusercontent.com/12074933/61314712-46a90000-a80e-11e9-81d7-0eb5f94a4b15.png)
4. Navigate to the Addresses view. Address is saved at this moment
![Selection_187](https://user-images.githubusercontent.com/12074933/61314815-8374f700-a80e-11e9-9b4d-a84e6141d3ff.png)
5. Close Wallet
6. Open Wallet again and navigate to the Receive view
7. Enter the same comment as in the step 3.

**Actual**
Wallet doesn't warn about the duplicate comment
![Selection_188](https://user-images.githubusercontent.com/12074933/61315101-1877f000-a80f-11e9-9518-920d414e7e11.png)

Also if you navigate to another view while duplicate comment is entered without warning wallet would save address with the duplicate comment.
![Selection_190](https://user-images.githubusercontent.com/12074933/61315459-db602d80-a80f-11e9-8c1b-1df0eb83e96c.png)

**Expected**
Wallet should warn about duplicate comments. No addresses saved with duplicate comments.

**Note**
If you navigate to Addresses view and come back to the Receive view without closing wallet warning would be displayed correctly.

![Selection_189](https://user-images.githubusercontent.com/12074933/61315199-4eb56f80-a80f-11e9-975f-ecbdf891543f.png)

Reproduced on the latest master as well as on master dated June 1st.

**Comment by gingervik** [comment]
reproduced on build from 16.07
checked on Beam-Wallet-Masternet-3.0.5638.exe
