### ISSUE TITLE
Unable to build mainnet on Ubuntu 18.04

### ISSUE THREAD

**Issue by graemes** [BeamMW/beam#776]
**Bug title**
Unable to build mainnet on Ubuntu 18.04

**Bug description**
Unable to build mainnet on Ubuntu 18.04.  Fails on libbitcoin_chain.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run 'cmake -DCMAKE_BUILD_TYPE=Release           -DBEAM_NO_QT_UI_WALLET=On           -DBEAM_USE_AVX=On           -DBEAM_USE_GPU=Off           . &&           make -j$(nproc)'

**Current behaviour**
Receive following error message:

BEAM_VERSION: 3.0.5659
-- Boost version: 1.65.1
-- Using OpenSSL 1.1.1
start libuv
GNU
-fvisibility=hidden;--std=gnu89;-Wall;-Wextra;-Wstrict-prototypes;-Wno-unused-parameter
CMake Error at 3rdparty/libbitcoin/src/chain/CMakeLists.txt:36 (target_link_libraries):
  Object library target "libbitcoin_chain" may not link to anything.

**Expected behaviour**
To build the node software.

**Platform and build**
* Ubuntu
* OS version: 18.04
* BEAM_VERSION: 3.0.5659

**Configuration, log, memory dump files (if applicable)**
Add relevant files. The filenames and locations are described here: https://github.com/BeamMW/beam/wiki/Folder-and-file-locations

**Log file(s) (if applicable)**
Add relevant log file(s),  located in the `logs` folder.

[CMakeOutput.log](https://github.com/BeamMW/beam/files/3400867/CMakeOutput.log)

**Screenshots (if applicable)**
Add screenshots that illustrate a problem you've found.

**Comment by nesbox** [comment]
Hi, could you please give us CMake output you see on the screen?
with info about Cmake version and etc.
Thank you.

**Comment by graemes** [comment]
Hi,

cmake version:
> apt list --installed | grep cmake
> 
> cmake/bionic,now 3.10.2-1ubuntu2 amd64 [installed]
> cmake-data/bionic,now 3.10.2-1ubuntu2 all [installed,automatic]

Output:
> cmake -DCMAKE_BUILD_TYPE=Release           -DBEAM_NO_QT_UI_WALLET=On           -DBEAM_USE_AVX=${USE_AVX}           -DBEAM_USE_GPU=${USE_GPU}           . &&           make -j$(nproc)
> 
> BRANCH_NAME: 
> -- The C compiler identification is GNU 7.4.0
> -- The CXX compiler identification is GNU 7.4.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> BEAM_VERSION: 3.0.0
> -- Boost version: 1.65.1
> -- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1")
> -- Using OpenSSL 1.1.1
> start libuv
> GNU
> -fvisibility=hidden;--std=gnu89;-Wall;-Wextra;-Wstrict-prototypes;-Wno-unused-parameter
> CMake Error at 3rdparty/libbitcoin/src/chain/CMakeLists.txt:36 (target_link_libraries):
>   Object library target "libbitcoin_chain" may not link to anything.
>

**Comment by graemes** [comment]
Noticed that the build instructions (although for 14.04) specify downloading/installing cmake 3.12.0.
Had assumed (wrongly) that the cmake in 18.04 would be modern enough - not the case - installed 3.12.0 and build successful.

**Comment by graemes** [comment]
If anyone else comes across this, there is an officially supported PPA at: https://blog.kitware.com/ubuntu-cmake-repository-now-available/ but I didn't have any success with the version (3.14.1) provided.

**Comment by graemes** [comment]
Final update - successfully built with kitware cmake ppa (https://apt.kitware.com/) - cmake 3.15.0.

**Comment by gingervik** [comment]
can be closed
