### ISSUE TITLE
Problem with SBBS messages broadcast

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#780]
Problem with SBBS messages broadcast

If you send a lot of SBBS messages to the node from wallet, not all of them reach other nodes, as a result some sbbs messages don't get to the recipients.

To reproduce:
1. Make 500 sends using wallet API
2. Some of them (about 1-9) will not become completed.

Log analysis has shown that ALL transactions were accepted by the Receiver, but some confirmation messages doesn't reach the Sender. These SBBS messages are presented in the Receiver's node.db, but don't exist  in Sender's node.db.

**Comment by anatolse** [comment]
Please, check that transactions are correctly restored after wallet relaunch, no BBS messages should be lost

**Comment by gingervik** [comment]
1. checked on 200, 500, 700, 1000 transactions - fixed

**Comment by gingervik** [comment]
2. https://github.com/BeamMW/beam/issues/780#issuecomment-546993878 checked
