### ISSUE TITLE
Add in CFG file --treasury_path-flag for run a local testnet.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#786]
Please add in CFG file --treasury_path-flag for more convenient setup a local testnet .
https://github.com/BeamMW/beam/issues/785

**Comment by gingervik** [comment]
only in master and testnet

**Comment by iamien1993** [comment]
checked a node's cfg file on masternet, Beam Node 3.0.5663 (clear_cathode_3.1RC)
