### ISSUE TITLE
Invalid password when user update wallet from v 1.1.4202 to v. 3.0.5660

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#788]
Description:
User has his old version wallet 1.1.4202
He knows his password. It works perfectly
Then he decided to update it to the last version
When he tries to log in - password is invalid

But! if he update from 1.1.4202 to 2.1.4915 - password is ok
from 2.1.4915to v. 3.0.5660 - password is ok

**Comment by bitcodernull** [comment]
when will the fix release?

**Comment by gingervik** [comment]
checked on master. fixed
