### ISSUE TITLE
Desktop wallet - Add wallet version on the loading screen

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#789]
Please, add wallet version on the loading screen
@alexandrashelenkova will provide design

**Comment by alexandrashelenkova** [comment]
Screen is here https://zpl.io/bAq0P56

**Comment by chapati** [comment]
Fixed for all start screens - load, restore, seed phrase &c.

**Comment by iamien1993** [comment]
build: Masternet 3.0.5663

checked:
first screen
create new wallet
create new wallet (seed phrase)
create new wallet (inputting phrase)
create new wallet (creating password)
create new wallet (setup node)
create new wallet (creating wallet process)
restore wallet (seed phrase)
restore wallet (creating password)
restore wallet (setup node)
