### ISSUE TITLE
In progress panel - support for swap currencies

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam#792]
Add support for swap incoming/outgoing/maturing to the 'In Progress' panel
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5c64ea5c19485e4646f1121e

**Comment by chapati** [comment]
This is done at the pure UI side. Some logic updates are pending. Check when swap UI is fully merged into master.

**Comment by sasha-abramovich** [comment]
It looks like in the new design we don't need this functionality. @chapati please talk to me if required.
