### ISSUE TITLE
'Peer's signature is not valid' on rescan on vesrion > 2.1.xxxx

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#793]
All outgoing transactions will report error 'Peer's signature is not valid' while rescan and become Failed.
Balance is valid. Only transaction statuses become invalid.

Steps to reproduce the behaviour:
1. Update wallet with transactions from 2.1 to >=2.2
2. Rescan UTXO
3. All outgoing transaction become Failed

**Comment by Sergei-Beam** [comment]
checked
