### ISSUE TITLE
Explorer-node. Add API to report node peers

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#799]
extend explorer's API with new method 'peers'.
It should return the list of known peers

**Comment by shrikus** [comment]
And please consider adding peers_count to the /status endpoint as it’s often much more useful to know the count rather than the list.

**Comment by nesbox** [comment]
also, Wiki should be updated after release

### status

`GET http://x.x.x.x:port/status`

_Description_: Gets current blockchain status.

_Response_:  
```json
{
  "chainwork": "0x38594101d0a0",
  "hash": "7353b5e4ad29a2ffa5f7952749d1eb04acedd82215b1f4f01d75107165f4622b",
  "height": 20531,
  "low_horizon": 19090,
  "timestamp": 1550158283,
  "peers_count": 10
}
```
***
### peers

`GET http://x.x.x.x:port/peers`

_Description_: Gets current peers list.

_Response_:  
```json
["18.197.8.221:8100","18.202.159.243:8100","18.220.39.232:10000","18.222.59.46:10000","18.223.28.27:10000","34.242.133.248:8100","50.18.137.128:8100","63.34.107.70:8100","63.34.124.161:8100"]
```
***

**Comment by Sergei-Beam** [comment]
checked
