### ISSUE TITLE
When user switches from local node to remote mined UTXOs are not displayed

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#8]
Steps:

- connect wallet to remote node - all mined UTXO are displayed- 
- switch from remote node to local node- 
- wait while sync is ended- 
- switch from local node to remote

Result: all mined UTXO are not displayed before reset local data

**Comment by anatolse** [comment]
Already fixed after implementing FlyClient

**Comment by gingervik** [comment]
checked
