### ISSUE TITLE
[UI wallet] Send beam: all elements of the screen are locked if we make an exchange with expired address

### ISSUE THREAD

**Issue by iamien1993** [BeamMW/beam#802]
**To Reproduce**
Steps to reproduce the behaviour:
1. Run the app.
2. create an expired address/ change an active address to expired
3. Wallet > Send
4. Fill the fields in, Send to - own expired address
5. Click Send > Send > ok

**Current behaviour**
Confirmation popup has been closed, buttons "back"/"send" and fields are not available for clicking/editing
![image](https://user-images.githubusercontent.com/44057235/62924126-18402580-bdb8-11e9-9ec5-7255fbd2cc8e.png)

**Expected behaviour**
Confirmation popup has been closed, buttons "back"/"send" and fields are available for clicking/editing

**Platform and build**
* Mac
* 10.14.6 (18G87)
* Masternet (3.1.5674), Mainnet (3.1.5765)

**Comment by VladislavKulyba** [comment]
checked
