### ISSUE TITLE
[UI wallet] Settings: Show in folder doesn't work on MacOS in case the wallet has been installed into custom folder

### ISSUE THREAD

**Issue by iamien1993** [BeamMW/beam#804]
**Preconditions**
Install the wallet to custom folder (don't forget about .cfg file)

**To Reproduce**
1. Run the wallet
2. Open the Settings screen
3. click to "Show in folder"

**Current behaviour**
Folder which contains the app does not open.

**Expected behaviour**
Folder which contains the app is opened

**Platform and build**
* MacOS 10.14.6 (18G87)
* Masternet (3.1.5674), Mainnet (3.1.5765)

**Hint:** it works on Linux/Windows

**Comment by gingervik** [comment]
@iamien1993 what in you cfg file? only "appdata=" or full path?

**Comment by gingervik** [comment]
cannot reproduce. if there is right path in cfg file everything is ok
