### ISSUE TITLE
Beam loves Linux

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam#810]
There are several reports on issues with Linux builds already:

- Problems on Ubuntu 16 when following our build instructions
- On the latest Fedora lrelease & lupdate are now lrelease-qt5 & lupdate-qt5
- Request for CentOS 7 builds
- Need to move build servers to Ubuntu 18 LTS (preliminary dockerfile attached)

Feel free to post your Linux requests and issues here.

**Comment by chapati** [comment]
[Ubunto 18 Dockerfile.zip](https://github.com/BeamMW/beam/files/3509378/Ubunto.18.Dockerfile.zip)

**Comment by chapati** [comment]
[Ubuntu 18 Dockerfile.zip](https://github.com/BeamMW/beam/files/3509380/Ubuntu.18.Dockerfile.zip)

**Comment by mikeyb** [comment]
Feel free to ping me if there is any testing needed in ubuntu

**Comment by chapati** [comment]
Updated build instruction for Ubuntu, Fedora, Centos. Fixed comilation errors.
https://github.com/BeamMW/beam/wiki/How-to-build#fedora-29

**Comment by chapati** [comment]
Decided not to support Ubuntu 16 and do not touch builds for the moment.
Full Docker is not necessary as well - we're using light config.
