### ISSUE TITLE
Loading process and progress bar improvements

### ISSUE THREAD

**Issue by echoby** [BeamMW/beam#814]

**Comment by Sergei-Beam** [comment]
checked

**Comment by Sergei-Beam** [comment]
@echoby Please, remove ETA for the case when we're rebuilding the UTXO-image.
UTXO-image is rebuilding in case when user changes the seed phrase in the folder where was the UTXO-image file created on other seed. 

![image](https://user-images.githubusercontent.com/44496108/65039255-800b0280-d95a-11e9-9243-a2932d0093c2.png)

**Comment by sasha-abramovich** [comment]
@echoby please rename the stages (for both regular loading/sync and restore):

- Scanning existing blocks
- Downloading new blocks
- Scanning new blocks

On restore there is no scanning, so please rename wherever applicable.

**Comment by gingervik** [comment]
Scanning existing blocks -> Rebuilding data
Scanning new blocks -> Locating your funds

**Comment by gingervik** [comment]
checked
