### ISSUE TITLE
Zombie processes

### ISSUE THREAD

**Issue by Crypto2** [BeamMW/beam#815]
Whether shut down cleanly or if it crashes wallet-api leaves zombie processes that never go away.

![image](https://user-images.githubusercontent.com/7625236/63381231-44cee100-c366-11e9-8b79-e2e875a7f914.png)

**Comment by chapati** [comment]
Generally zombie state is not a problem of the process itself. On linux when parent has not closed the child process properly this child becomes zombie. It looks like there is a problem in how YOU control/launch/spawn the wallet-api and not in the wallet-api itself. You need to provide more details on this. How you run wallet-api, how you make it exit &c.

**Comment by Crypto2** [comment]
They are launched via a cron job shell script (bash), bash of course closes any handles of it's children properly so wouldn't have anything to do with that.

The only way it is ever closed is if it crashes or via SIGINT (killall -s SIGINT or kill -s SIGINT)

**Comment by chapati** [comment]
@Crypto2 Would you please attach your crontab file & your shell script. Ty.

**Comment by Crypto2** [comment]
`* * * * * /<username>/BEAM/run_coin`

```
#!/bin/bash

PROC=wallet-api
#PIDOF=/bin/pidof
#RET=`${PIDOF} ${PROC}`
RET=`ps aux | grep wallet-api | grep -v defunct | grep -v grep`
if [ "$RET" == "" ]; then
   cd /<username>/BEAM
   ./${PROC} &
fi
```

Normally I use the commented out pidof code but it sees the zombies. I use this same script for countless other coins and programs of all types with no issues.

**Comment by gingervik** [comment]
not relevant
