### ISSUE TITLE
Open Windows wallet does not sync after Internet outage

### ISSUE THREAD

**Issue by beggsdl** [BeamMW/beam#817]
**Bug title**
Open Windows wallet does not sync after Internet outage

**Bug description**
My Windows wallet is always left open. My Internet connection went out for several hours one night. The next day, I unlocked wallet, created new receiving key, then initiated transfer from mining pool. After several minutes, the transaction was not showing up in wallet. I checked blockchain height of wallet and found it was way behind and not updating. Restarting wallet allowed it to sync properly, but the transaction never came into the wallet. It had to be cancelled at the pool. Restarting the transaction using the same receiving key that was created when wallet was not sync'd did work ok.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Windows wallet and let it sync
2. Disconnect Internet and leave disconnected for a short while (my Internet was out for probably 6 hours, but I'm guessing leaving it disconnected for 5 minutes would possibly cause the issue).
3. Reconnect Internet
4. Check Blockchain Height and see that it is behind and will not sync.
5. Restart wallet and then it will sync as expected.

**Current behaviour**
Windows wallet does not automatically start sync'ing after Internet connection is lost for a period of time.

**Expected behaviour**
Windows wallet should pick back up and start to sync again once Internet connection is restored.

**Platform and build**
* Windows Beam wallet v3.1.5765
* Windows 10 v1809 x64
* 3.1.5765

**Configuration, log, memory dump files (if applicable)**
Log file 19_08_19_17_44 shows when the Internet connection was lost
Log file 19_08_20_14_44 shows when I closed the wallet because it was not sync'ing. Log files previous to this one were 0 KB.
Log file 19_08_20_17_19 shows me restarting the wallet.

[beam_ui_19_08_20_17_17_09.log](https://github.com/BeamMW/beam/files/3527521/beam_ui_19_08_20_17_17_09.log)
[beam_ui_19_08_19_17_44_18.log](https://github.com/BeamMW/beam/files/3527522/beam_ui_19_08_19_17_44_18.log)
[beam_ui_19_08_20_14_44_18.log](https://github.com/BeamMW/beam/files/3527523/beam_ui_19_08_20_14_44_18.log)

**Comment by gingervik** [comment]
@Sergei-Beam please, check

**Comment by Sergei-Beam** [comment]
@beggsdl Hi. I cannot reproduce it according to your steps.
I think except the lost internet you also close your PC(laptop) or no, on the description you wrote that "I unlocked wallet". The wallet is locked if you use: hibernate the PC or the sleep mode or lock functionality. Each can be related to issue
Can you remember:
1. What you did when left pc to the night?
2. When the internet was lost before close|hibernate(sleep)|lock wallet or after?

**Comment by beggsdl** [comment]
The computer my wallet is installed on is powered on all the time and does not hibernate.  It is not a laptop.  I have my wallet set to auto-lock after 5 minutes and it is always up and running.  So here is how this happened:
1. My wallet was running, but locked
2. There was a wide-spread Internet outage with my provider at 2019-08-19 19:25:04
3. After my internet was restored (probably restored around 2019-08-20 02:00:00), I unlocked the wallet (I think at 2019-08-20 17:14:33, based on the log file)
4. The wallet did not restart sync'ing blocks after the Internet connection was restored.  I could tell because the current block in my wallet was far behind the latest block.
5. Once I closed the wallet (at 2019-08-20 17:17:03) and opened it again, it started to sync

In the log 19_08_19_17_44_18, you can see at 19:25:04 the first "connection timed out" message.  This is when my Internet went out. One more log files after this one continued to show "connection time out" messages, but then the logs became empty, meaning no wallet activity or attempt to communicate.
Log file 19_08_20_14_44_18 shows me closing the wallet.  All log files before this file were 0k, which means there wasn't any activity with the wallet (no sync'ing).
Log file 19_08_20_17_17_09 shows me opening the wallet and it starting to communicate and sync.

Once my Internet was lost, there was "connection timed out" message activity in one more log file until 2019-08-19 22:38:49, so about 3 hours 14 minutes.  Maybe you need to keep it disconnected at least this long.

**Comment by beam-mw** [comment]
In Double Dopple 4.0 wallet restart will be less painful and pretty quick. We recommend just restarting the wallet in these situations
