### ISSUE TITLE
 How can I access the node's api via rpc or http?

### ISSUE THREAD

**Issue by wshhz** [BeamMW/beam#819]
## I just want to build a complete local test node, not connected to the external network, how can I set it up?

**Comment by gingervik** [comment]
hello @wshhz 
please, read our documentation
https://documentation.beam.mw/en/latest/
https://github.com/BeamMW/beam/wiki#apis

**Comment by wshhz** [comment]
I found the api but didn't see the docker related information.

**Comment by gingervik** [comment]
@Webonnix please, reply

**Comment by Webonnix** [comment]
Hi @wshhz
You can run the testnet node via docker:
1) docker run -d --name beam_node_testnet -p 8100:8100 mimblewimblebeam/testnet:latest o
2) If you want to build, You can use this dockerfile as an example:  https://github.com/BeamMW/beam/files/3509380/Ubuntu.18.Dockerfile.zip
3) About "...not connected to the external network, how can I set it up?" - please, read the following information:  3.1) https://dev.to/andre/docker-restricting-in--and-outbound-network-traffic-67p
3.2) https://stackoverflow.com/questions/41107012/block-outgoing-connections-to-private-ips-from-docker-containers
Please, let me know if you have any questions
Thanks

**Comment by wshhz** [comment]
Thanks,but because the docker related information is too small, I still choose to compile the source code to run the node.
