### ISSUE TITLE
UI Wallet - Peers didn't change in settings.ini after updating 

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam#823]
After updating old peers are saved in settings.ini

Steps to reproduce:
1. Go to the settings.ini file. Make sure that peers from old version
2. Update wallet from v1
3. Go to the settings.ini file

Expected: Peers are changed to the latest
Actual: Peers are the same

Reproduces on old version which are not used a balancer

**Comment by iamien1993** [comment]
works with mainnet & testnet only

**Comment by Roberrtt** [comment]
Reproduced in Linux

**Comment by VladislavKulyba** [comment]
Checked
