### ISSUE TITLE
I want to build a local node, then test the transfer transaction, how should I get the token?

### ISSUE THREAD

**Issue by wshhz** [BeamMW/beam#824]
First of all, I need to build a completely local node, not connected to the test network and the node of the main network. Secondly, I can set the initial token for my account to facilitate the test transfer. Finally, I also need to be able to get information about the node via http request, such as total node height, single block information, etc., or send a request via http request. What should I do?

**Comment by gingervik** [comment]
read our documentation
1. [How to build](https://github.com/BeamMW/beam/wiki/How-to-build)
2. test tokens you can get from here https://faucet.beamprivacy.community/
3. use our explorer node for [here](https://github.com/BeamMW/beam/wiki/Beam-Node-Explorer-API)

**Comment by wshhz** [comment]
thanks,I think your documentation needs to be improved, especially the API documentation. Documents like iost are very clear and you can choose the language.
https://developers.iost.io/docs/en/6-reference/API.html

**Comment by gingervik** [comment]
@wshhz thank you for your recommendations!
