### ISSUE TITLE
Receive screen - user should be able to copy address not only token

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#829]
should be discussed with @sasha-abramovich 

in new design user cannot copy his address on receive screen .only token

![image](https://user-images.githubusercontent.com/28015224/63918459-69514a00-ca45-11e9-914e-4202bb20a59f.png)

**Comment by sasha-abramovich** [comment]
I simply agree :)

**Comment by gingervik** [comment]
@sasha-abramovich good answer but can you please be more detailed? should we add button "copy address"? or shoul user just copy it manually from address field?

**Comment by sasha-abramovich** [comment]
how token is currently copied? Please attach a screenshot (or few) that always helps. As an alternative it would be nice to pick the Mobile practice - simply ask in the channel and update the task after. just my 5 cents.

**Comment by gingervik** [comment]
@sasha-abramovich description is updated. it would be nice if you first start using your advices

**Comment by sasha-abramovich** [comment]
Please initiate the discussion about the issue you've started in the Telegram channel, it would make much better sense.

**Comment by chapati** [comment]
This has been resolved in Task #832

**Comment by gingervik** [comment]
Please, on Create swap jffer tab there should be button copy token, not address
we do not need button copy address for swap
![image](https://user-images.githubusercontent.com/28015224/64155517-99309100-ce3b-11e9-904d-4a7a009573e9.png)

**Comment by gingervik** [comment]
checked on master
