### ISSUE TITLE
It is possible to send money to illegal address

### ISSUE THREAD

**Issue by azaidelson** [BeamMW/beam#83]
**Bug description**
In the wallet, it is possible to hit "Send' and then type something like "111222333" into the address and send money

**To Reproduce**
1. Start wallet
2. Click "Send"
3. Enter illegal address (111222333) and amount, hit send.

**Current behavior**
Transaction starts, UTXO status is moved to "Draft"

**Expected behavior**
The system should recognize "111222333" as an illegal address and should not let people send money to it. One way is to check that the address conforms to some standard representation (use checksum, length, etc.)

**Platform**
Tested on Windows, probably same on all platforms

**Build**
1.0.3005

**Configuration file (if applicable)**
Add configuration file. The file with `cfg` extension is located in the same folder the main executable resides in.

**Log file(s) (if applicable)**
Attached

**Memory dump (in case of node crash on Windows)**
N/A

**Screenshots (if applicable)**
Add screenshots that illustrate a problem you've found.
![image](https://user-images.githubusercontent.com/21197401/48692314-3c325a00-ebde-11e8-8f63-09b0636f2e93.png)

**Your contact details (if possible)**
zaidelson@beam-mw.com

**Comment by sasha-abramovich** [comment]
@anatolse as a process of switching to full-fledged transaction token can we consider some "checksum" baked into the token to minimize the chance of random sequences recognized as addresses?

**Comment by Alesio7** [comment]
Is it safe to close this issue yet?
