### ISSUE TITLE
Create swap offer - user should be able to enter rate manually

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#830]
As it works on exchanges user should be able to enter not only receive and sent amoun but also a rate.
If user enter rate manually one of empty fields (receive or sent) should be filled automatically

@sasha-abramovich @alexandrashelenkova please change design in zeplin and give us link

**Comment by sasha-abramovich** [comment]
Please attach a screenshot in this and similar issues, we can think from there. Even with some notes please. I want to be sure that we understand each other. Not necessarily new design will be required, it might be as well explained in the same ticket when a screenshot is shown.

**Comment by gingervik** [comment]
please, see design https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5bd18f9c7eebd309e6c75633

**Comment by sasha-abramovich** [comment]
We can make Rate editable as well. @alexandrashelenkova what do you think?

**Comment by alexandrashelenkova** [comment]
Made rate field editable.
Also let's replace Receive amount and Sent amount fields, so when user will change rate, Receive amount should changes as well.
Updates design is here https://zpl.io/VqlKPrm
![receive-swap](https://user-images.githubusercontent.com/7249484/64027801-0d391380-cb74-11e9-9c0b-b72ed4579d8e.jpg)

**Comment by gingervik** [comment]
1. When user delete rate receive amount still have number counted as sent amount*last deleted number in rate field
Please, see attached video
[rate.zip](https://github.com/BeamMW/beam/files/3629791/rate.zip)

**Comment by gingervik** [comment]
2. Receive amount changes when user enter rate and then move pointer to "receive amount" field
please, see attached video


[receiv.zip](https://github.com/BeamMW/beam/files/3641681/receiv.zip)

**Comment by chapati** [comment]
> 1. Receive amount changes when user enter rate and then move pointer to "receive amount" field
>    please, see attached video
> 
> [receiv.zip](https://github.com/BeamMW/beam/files/3641681/receiv.zip)

Unfortunately this cannot be fixed. User is able to enter arbitrary value fir rate, but receive amount should be always rounded to groth. So we allow user to enter any rate but when he leaves the rate field it displays the closest correct rate possible.

In your example you enter 54 BTC and rate of 89 which gives us 0.606741573 beams. This amount is not possible (last 3 should be rounded up to get groth) and the closest rate to get 0.60674157 is 89.000000445

**Comment by gingervik** [comment]
ok, can be closed
