### ISSUE TITLE
Atomic Swap screen - show the composite status of the nodes for all the coins in a user-friendly and informative way

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#831]
Example, in this case i have problem with bitcoin node. My balance = 0. Please, make it also red
![image](https://user-images.githubusercontent.com/28015224/63918410-5179c600-ca45-11e9-8a19-fbabab5af5fe.png)

**Comment by chapati** [comment]
This is on the swap branch.

**Comment by gingervik** [comment]
as I remember this task should be redesign by @alexandrashelenkova  and @sasha-abramovich

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova this is a task of showing a composite online status properly. Please also suggest what should be shown in balance for that currency (if at all).

**Comment by alexandrashelenkova** [comment]
Updated screen is here https://zpl.io/bPglvgl
If all coins are online, main indicator (on top of the screen) should be green.
If all coins are offline, main indicator should be red.
If some of the coin's status isn't online but others are, main status indicator should become yellow with description in breaks about how many coins are connected and how many aren't.

This task should be implemented with this one https://github.com/BeamMW/beam/issues/833 (main screen redesign), cause coins with problem statuses should be marked with red circle.

**Comment by alexandrashelenkova** [comment]
Update: work still in progress

**Comment by alexandrashelenkova** [comment]
Update: screen are approved, task should be implemented with this one https://github.com/BeamMW/beam/issues/849

**Comment by gingervik** [comment]
can be closed
