### ISSUE TITLE
Swap transactions list on Atomic swap panel

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#845]
Add list of the swap transactions to Atomic swap panel

Draft design is here https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5d6f766c6765b59ba248a34d

**Comment by alexandrashelenkova** [comment]
Created separate task for whole Atomic Swap section here https://github.com/BeamMW/beam/issues/849
Closing that one.
