### ISSUE TITLE
Laser: names for flags, command and table headers

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#846]
Need to decide how better to call flags, command and table headers @sasha-abramovich 
Below I gave the current state.

General command: `laser `

Lightning options:
  `--open`                               open lightning channel
 ` --transfer`                           send to lightning channel
  `--wait_incoming`                      wait for open incomming lightning channel
 ` --list `                              view all opened lightning channel
  `--serve [=arg(=all)]`                 listen lightning channels  --serve [chID1, ..., chIDN]
  `--close arg`                          close opened lightning channel --close <chID1, ..., chIDN> [all,a]
  `--delete arg`                         delete laser channel --delete <chID1,..., chIDN>
  `--a_my arg`                           amount to lock in channel on my side (in Beams, 1 Beam = 100,000,000 groth)
`  --a_trg arg    `                      amount to lock in channel on target side (in Beams, 1 Beam = 100,000,000 groth)
 ` --laser_target arg `                  address of laser receiver
  `--lfee arg (=100) `                   fee (in Groth, 100,000,000 groth = 1 Beam)
  `--laser_lock_time arg`                lock time in blocks beam transaction
  `--channel arg `                       laser channel ID
  `-a [ --all ]   `                      all channels
  `--graceful_close`                     graceful close flag

laser Channels table:
![image](https://user-images.githubusercontent.com/44496108/64333445-31b34680-cfdf-11e9-9796-2af7ecede6c7.png)

**Comment by beam-mw** [comment]
@echoby please discuss with @sasha-abramovich

**Comment by sasha-abramovich** [comment]
Lightning options (renamed after talking with @BigRomanov and @echoby):
`--open --> --laser_open` open channel
`--a_my arg --> --laser_my_locked_amount` amount to lock in channel on my side (in Beams, 1 Beam = 100,000,000 groth)
`--a_trg arg --> --laser_remote_locked_amount` amount to lock in channel on target side (in Beams, 1 Beam = 100,000,000 groth)
`--close arg --> --laser_close` close opened lightning channel --close <chID1, ..., chIDN> [all,a]
`--delete arg --> --laser_delete` delete laser channel --delete <chID1,..., chIDN>
`--list --> --laser_channels` view all opened lightning channel
`-a [ --all ] all` channels **(same as list ???)**
`--serve [=arg(=all)] --> --laser_listen` listen lightning channels --serve [chID1, ..., chIDN]
`--transfer --> --laser_send` send to lightning channel
`--wait_incoming --> --laser_receive` wait for open incomming lightning channel
`--laser_target --> --laser_address` arg address of laser receiver
`--lfee arg (=100) --> --laser_fee` fee (in Groth, 100,000,000 groth = 1 Beam)
`--laser_lock_time arg --> --laser_lock_time` lock time in blocks beam transaction
`--channel arg --> --laser_channel` laser channel ID

--graceful_close graceful close flag

**Comment by echoby** [comment]
Laser commands:
  --laser_channels_list                view all opened lightning channel
  --laser_receive                      wait for open incomming lightning
                                       channel
                                       --laser_my_locked_amount <amount in
                                       beam>
                                       --laser_remote_locked_amount <amount in
                                       beam>
                                       --laser_fee <amount in groth>
                                       --laser_lock_time <blocks count before
                                       can close>
  --laser_open                         open lightning channel
                                       --laser_my_locked_amount <amount in
                                       beam>
                                       --laser_remote_locked_amount <amount in
                                       beam>
                                       --laser_fee <amount in groth>
                                       --laser_lock_time <blocks count before
                                       can close>
  --laser_listen arg                   listen lightning channels
                                       arg: [channel ID1, ..., channel IDN]
                                       arg can be unspecified
  --laser_send arg                     send to lightning channel
                                       arg: <amount in beam>
                                       --laser_channel <channel ID>
  --laser_close arg                    close opened lightning channel. Use
                                       after lock time is up or if other side
                                       is offline
                                       arg: <channel ID1, ..., channel IDN>
                                       arg must be specified
  --laser_drop arg                     drop opened lightning channel. Use after
                                       lock time is up or if other side is
                                       offline
                                       arg: <channel ID1, ..., channel IDN>
                                       arg must be specified
  --laser_delete arg                   delete closed laser channel from data
                                       base
                                       arg: <channel ID1, ..., channel IDN>
                                       arg must be specified

Laser options:
  --laser_my_locked_amount arg         amount to lock in channel on my side (in
                                       Beams, 1 Beam = 100,000,000 groth)
  --laser_remote_locked_amount arg     amount to lock in channel on target side
                                       (in Beams, 1 Beam = 100,000,000 groth)
  --laser_address arg                  address of laser receiver
  --laser_fee arg                      fee (in Groth, 100,000,000 groth = 1
                                       Beam)
  --laser_lock_time arg                lock time in blocks beam transaction
  --laser_channel arg                  laser channel ID

**Comment by echoby** [comment]
[laser_commands.txt](https://github.com/BeamMW/beam/files/4091477/laser_commands.txt)

**Comment by echoby** [comment]
https://github.com/BeamMW/beam/wiki/Laser-BEAM-commands
was updated

**Comment by Sergei-Beam** [comment]
checked
