### ISSUE TITLE
Updated Wallet, Transferred coins from pool. Everything was fine, until i rebooted my computer.  And now POOF they're gone 

### ISSUE THREAD

**Issue by dannybreal** [BeamMW/beam#847]
I

**Comment by dannybreal** [comment]
Helloooo!!!! Does anyone even care? Looks like an abandoned project to me. They fuckwd up the hard fork and have 0 support. Coins missing and wallets not transacting. A proper shitshow. And they claim to be the bitcoin killer

**Comment by gingervik** [comment]
First of all, please. Check what version of wallet you are trying to run.

go to C:\Program Files\
Do you see Beam, Beam Wallet or both of this folders?
Please, run the wallet from Beam Wallet folder

**Comment by dannybreal** [comment]
Speedy assistance on the weekend, thanks
