### ISSUE TITLE
Laser: immediately OUTput funds for the side which doesn't know about the closing channel

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#851]
Need to decide can we do that or no and how?
@valdok, please do that when you will have time according to the priorities.

**_Case:_**
Imagine that we have 2 sides on payment channels: Alice & Bob
The balances are **Alice** - 5 , **Bob** - 7
In case, if **Bob** decides to close the channel before ending the lock_time, currently both sides will wait while the lock_time is ended and only after that the funds will be returned to both sides. But it looks inconvenient for the Alice as she didn't want to close it, but after the close, she wants to return the funds faster.

There is an idea to immediately OUTput funds for the side which doesn't know about the closing channel before the lock_time is ended in my example it is an Alice.

**Comment by valdok** [comment]
Not really important
