### ISSUE TITLE
Change background colour (mainnet) + add gradient (all)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam#852]
1. Change colours **(mainnet only)** 
(https://zpl.io/V0pyql9)
- background to #042548
- sidemenu background #000000 (opacity 10%)
- also please notice updated colours on Atomic Swap and Wallet screens for transaction lists and available, in progress, balances cards
2. Change background colour on starting screen colours **(mainnet only)** 
https://zpl.io/bAq0P56

3. Add gradient on top of the screen **(all wallets)**:
- for all screens except Send and Receive screens #035B8F (https://zpl.io/V0pyql9)
- for Receive screen #0BCCF7, 50% opacity (https://zpl.io/aBZB4xO)
- for Send screen #DA68F5, 50% opacity (https://zpl.io/boPDpQE)

**Comment by Sergei-Beam** [comment]
1. According to design gradient for BEAM should be the same on both screens main and swap 
Design:
![image](https://user-images.githubusercontent.com/44496108/65677111-b41cac80-e059-11e9-9269-daf79e0ef08e.png)

Master mains_creen:
![image](https://user-images.githubusercontent.com/44496108/65677198-dadae300-e059-11e9-96eb-7c3917b77d67.png)
Master swap_screen:
![image](https://user-images.githubusercontent.com/44496108/65677223-e4fce180-e059-11e9-9d58-aa5c45170611.png)

**Comment by gingervik** [comment]
can be closed
