### ISSUE TITLE
[UI Wallet] implement Electrum settings

### ISSUE THREAD

**Issue by roman-strilets** [BeamMW/beam#860]
discuss with @sasha-abramovich  and @roman-strilets

**Comment by Sergei-Beam** [comment]
1. We shouldn't show actions Copy/Paste if user didn't click on the field :
- to see seed 
![image](https://user-images.githubusercontent.com/44496108/66400952-1034e880-e9eb-11e9-9446-3ce9ac9536a5.png)
- if phrase not generated yet OR to enter/paste seed from the buffer
![image](https://user-images.githubusercontent.com/44496108/66401060-32c70180-e9eb-11e9-9fbb-b135b4d07b22.png)

2. When user clicks on the field "Double click to generate new seed phrase" and then right-click in field to paste the seed from buffer we shouldn't hide the cursor and show the mask: "Double click to generate new seed phrase".
![2019-10-08_16-47-19](https://user-images.githubusercontent.com/44496108/66401504-e92ae680-e9eb-11e9-857f-40dee9001737.gif)

**Comment by Sergei-Beam** [comment]
checked
