### ISSUE TITLE
[UI Wallet] Wallet crashes during rescan

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#861]
The problem appears only on the **Windows** system:
- When user click on Cancel during the restore the Wallet doesn't remove the `wallet.db` file and after click again to proceed the wallet get crash because cannot overwrite the DB. 

It should work otherwise as it has done on MAC & Linux.
- When user click on Cancel during the restore the Wallet should remove the `wallet.db` file and after click again to proceed the wallet should create new DB. 
The functionality above related only to DB which created during new restore, the mechanic about saving the old `wallet.db` via adding `timestamp` also should work

It might be related to #259

Case 1
STR:
- Open the wallet
- Select restore wallet
- Input words, node setup, click proceed wallet
 - When progress bar starts moving click on Cancel
- Click again to proceed wallet 
Actual: wallet crashes

Case 2
STR:
- Open the wallet
- Select restore wallet
- Input words, node setup, click proceed wallet
 - When progress bar starts moving click on Cancel
- wait for a while (~5-10 sec)
Actual: wallet crashes

**Comment by chapati** [comment]
I was unable to reproduce this on Fedora Linux.
Would you please 

1) Provide info about the initial test conditions - on which OS it crashed
2) Test if it crashes on Linux 

Thank you.

**Comment by Sergei-Beam** [comment]
Investigated the problem, description updated

**Comment by Sergei-Beam** [comment]
checked
