### ISSUE TITLE
Let the wallet know that the node protocol version is incompatible

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#869]
The idea is to be able to inform the user that the node works with the newer protocol version and that his wallet must be updated.

**Comment by gingervik** [comment]
need to be rechecked by QA

**Comment by gingervik** [comment]
when you connected via remote node - error: you are trying to connect to incompatible peer
start via local node - error "failed to start node. please, check your node configuration". in logs: Data configuration is incompatible: 2a8f0a9e03485540
