### ISSUE TITLE
Crash in logger. Race condition

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#876]
Leave wallet working for a while. Sometimes it crashes in logger code

>	Beam Wallet Masternet.exe!beam::LoggerImpl::write_impl(int level, const char * header, unsigned __int64 headerSize, const char * msg, unsigned __int64 size) Line 116	C++
 	Beam Wallet Masternet.exe!beam::CombinedLogger::write_message(const beam::LogMessageHeader & header, const char * buf, unsigned __int64 size) Line 243	C++
 	Beam Wallet Masternet.exe!beam::LogMessage::~LogMessage() Line 369	C++

_sink is nullptr

Crash is caused by log rotation event, which happens each 3h.

**Comment by Sergei-Beam** [comment]
cannot reproduce
