### ISSUE TITLE
Optional Dark Theme Color

### ISSUE THREAD

**Issue by Alesio7** [BeamMW/beam#877]
When the team's not busy..

-Let's introduce an option to have a stealth/dark wallet theme color to hide Beam's attractiveness from onlookers. Consider a black to white hue as shown in the pictures.

-It would be accessible as an optional toggle bar in the settings or hidden.

![gradient-map-1001](https://user-images.githubusercontent.com/41215180/65392277-ec15ae00-dd40-11e9-88ff-577d70038ac4.jpg)

**Comment by sasha-abramovich** [comment]
Adding this only as a tentative candidate for one of our future milestones. Let's examine if we can expose our color scheme as a file that can be processed when the app loads. We could allow people to create and exchange nice custom color schemes for their wallets :)

**Comment by Alesio7** [comment]
Would be interesting to see a picture of the implementation
