### ISSUE TITLE
Wallet should know and display whether the node is trusted

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#879]

**Comment by anatolse** [comment]
The wallet knows if he is connected to his "own" node (integrated node is always "his" node). Could you provide me details what I should show in UI.

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova please provide the design and reassign to @anatolse

**Comment by alexandrashelenkova** [comment]
Reassigned to @dariatarakanova 
Please let's have green lock icon for trusted node (instead of green circle).

**Comment by dariatarakanova** [comment]
Design: https://zpl.io/bWnNnGx

**Comment by alexandrashelenkova** [comment]
@dariatarakanova can try to make it same size as a circle? 10x10 px?

**Comment by dariatarakanova** [comment]
> @dariatarakanova can try to make it same size as a circle? 10x10 px?

done =) please check

**Comment by gingervik** [comment]
checked for 
- integrated node
- remote node with owner key 
- remote node with owner and miner key
- remote node with miner key also 
Everything is ok
