### ISSUE TITLE
Accept offer button on Atomic Swap

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#888]
A shortcut to "Send" dialog. When closed, In progress transactions tab on Atomic Swap screen should be opened.

**Comment by alexandrashelenkova** [comment]
Added button next to "create offer" button

**Comment by alexandrashelenkova** [comment]
Can we change icons in "Accept offer" and "Create offer" buttons please? Made icons more in "atomic swap" style, but it might be improved more later. 
New icons are here https://zpl.io/V1Dl1l4

**Comment by Sergei-Beam** [comment]
checked, separate ticket created
