### ISSUE TITLE
Add statuses to Atomic swap transactions

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#889]
get inspired here: https://zpl.io/2ERlRGn

**Comment by alexandrashelenkova** [comment]
Added Failed status for swap transactions and updated Cancelled one for swaps.

**Comment by Sergei-Beam** [comment]
@anatolse Please, change the color for status: failed according to new design https://zpl.io/b6xJ58q

**Comment by Sergei-Beam** [comment]
Checked, new functionality will be added here #1037
