### ISSUE TITLE
Offline state not updated to Online when node started

### ISSUE THREAD

**Issue by azaidelson** [BeamMW/beam#89]
**Bug description**
Wallet does not change from Offline to Online when node starts

[beam v1.0.3056 windows report.zip](https://github.com/BeamMW/beam/files/2612209/beam.v1.0.3056.windows.report.zip)

change status from Offline to Online when node started

**To Reproduce**
1. Start local node
2. Start wallet configured to use local node
3. Wallet shows status: Online
4. Stop the node. Wallet immediately changes the status to "Offline" (expected)
5. Now start the node. Wallet does not change the status to "Online" until I switch to another screen and then back to UTXO screen

**Platform**
Windows

**Build**
1.0.3056

**Configuration file (if applicable)**
Add configuration file. The file with `cfg` extension is located in the same folder the main executable resides in.

**Log file(s) (if applicable)**
Add relevant log file(s),  located in the `logs` folder.

**Memory dump (in case of node crash on Windows)**
Add file with extension `dmp`, located in the node directory. A dedicated memory dump file is created per each crash case.

**Screenshots (if applicable)**
Add screenshots that illustrate a problem you've found.

**Your contact details (if possible)**
IF possible, please leave your Mail or Telegram, so we'll be able to ask for more information in especially challenging cases :)

**Comment by gingervik** [comment]
cannot reproduce it on master. will be rechecked on testnet3 branch
