### ISSUE TITLE
[UI Wallet] Wallet screen: comment in the general transaction info contains unknown symbol

### ISSUE THREAD

**Issue by iamien1993** [BeamMW/beam#890]
**To Reproduce**
1. run wallet which contains some UTXO
2. click "send", then fill in "Send To" using your own address/address of another Wallet.
3. fill in "Transaction amount", then click "send" and confirm sending
4. click on the transaction to view General transaction info

**Current behaviour**
General transaction info is displaying. Comment field contains unknown symbol.
![image](https://user-images.githubusercontent.com/44057235/65430855-438b4b00-de21-11e9-9361-5febbdf35e7a.png)

**Expected behaviour**
General transaction info is displaying. Comment field does not contain symbols.

**Platform and build**
* MacOS
* BEAM Build number: 3.1.6095

**Comment by gingervik** [comment]
checked on master 3.1.6168
