### ISSUE TITLE
[Regression ]Addresses Add Contact - Fail [D15] [D16] [D17] [D18] [D19] [D20] [D21] [D22]

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#893]
<br>

**Step 1 Pass**

Navigate to the Transaction screen.

**Step 2 Pass**

Click 'send' button.

![null](<https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_2485.png>)

**Step 3 Pass**

Fill in the receiver's address in the 'Send To' field.

Leave the comment "**To Barbara**" in the 'Comment' field.

Fill the amount and the transaction fee and proceed with the sending.

![null](<https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_6697.png>)

**Step 4 Fail**

Navigate to Addresses > Contacts Tab.

![null](<https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_2489.png>)

**Comment by Sergei-Beam** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D15. Do not remove or edit.` [D15](https://beam.testquality.com/project/5267/result/1470953/defect/5182)

**Comment by Sergei-Beam** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D16. Do not remove or edit.` [D16](https://beam.testquality.com/project/5267/result/1470959/defect/5183)

**Comment by Sergei-Beam** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D17. Do not remove or edit.` [D17](https://beam.testquality.com/project/5267/result/1470951/defect/5184)

**Comment by gingervik** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D18. Do not remove or edit.` [D18](https://beam.testquality.com/project/5267/result/1470834/defect/5189)

**Comment by gingervik** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D19. Do not remove or edit.` [D19](https://beam.testquality.com/project/5267/result/1470836/defect/5190)

**Comment by Sergei-Beam** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D20. Do not remove or edit.` [D20](https://beam.testquality.com/project/5267/result/1470980/defect/5191)

**Comment by Sergei-Beam** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D21. Do not remove or edit.` [D21](https://beam.testquality.com/project/5267/result/1470981/defect/5192)

**Comment by gingervik** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D22. Do not remove or edit.` [D22](https://beam.testquality.com/project/5267/result/1470842/defect/5193)

**Comment by gingervik** [comment]
checked
