### ISSUE TITLE
Wallet crashes on Swap Offer page (debug mode)

### ISSUE THREAD

**Issue by roman-strilets** [BeamMW/beam#895]
Steps to reproduce the behaviour:
1. Run Wallet
2. Navigate to Swap Offer page
3. Exit from wallet

![image](https://user-images.githubusercontent.com/40387866/65498763-23ad6300-dec5-11e9-9ad6-1848f8ec4cf3.png)

**Comment by Aleksandr-Starun** [comment]
Problem with removal of the reactor moved to separate bug - https://github.com/BeamMW/beam/issues/1020
