### ISSUE TITLE
[Regression] Edit address. The added comment does the address as expired

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#898]
Steps:
- open the wallet
- click the receive button
- Make sure the default address expiration time is set to 24hr and comment field is empty
- Navigate to My Active Addresses tab.
- Find the created address and open to edit it
- Add any comment
Expected: Comment added and address still be active
Actual: Comment added, but address makes expired

**Comment by iamien1993** [comment]
tested
v 3.1.6187
