### ISSUE TITLE
Make migration automatic and improve error messaging when new wallet version is not compatible with the previous DB version

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#90]
Currently the message supplied is "invalid password or wallet data unreadable". Much more user-friendly message will help: "Wallet DB indicates a deprecated version: "testnet 2.1", wallet app expects "testnet 2.2" version - please delete the DB file an re-create it from scratch from the app".

Also, it worth to show the button to restore the wallet from the blockchain (ie. to switch to restore flow).

**Comment by sasha-abramovich** [comment]
Note also: https://github.com/BeamMW/beam/issues/372

**Comment by alexandrashelenkova** [comment]
Duplicated of this task https://github.com/BeamMW/beam/issues/587
