### ISSUE TITLE
[Regression] [UI Wallet] Bypass a dictionary validation for seed phrase doesn't work

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#900]
The feature is broken. It was added in #796

Steps:
- open the wallet
- click restore
- enter seed phrase but in 1 word make a mistake ( system should mark it red)
- hold down the "Shift" button
Expected: system should ignore the dictionary validation and allow the user to proceed
Actual: nothing happened

**Comment by Roberrtt** [comment]
checked on version: 3.1.6196

**Comment by Roberrtt** [comment]
checked on master version :3.1.6196
