### ISSUE TITLE
Empty swap offer book view

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#903]
If we have no offers, offers view should look like this https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5d722a856c443486850135e8

**Comment by chapati** [comment]
Would you please check why onChanged is not always fired for offersTable.model.count.
After this one is done task can be closed. Ty.

**Comment by iamien1993** [comment]
checked:
- Receive/Send BEAM with different currencies
