### ISSUE TITLE
[CLI Wallet] Make flag --file_location as required for import_data command

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#904]
We need to make required flag `--file_location` for `import_data` command

Also, need to add error message if user runs the command `beam-wallet import_data` without the flag  `--file_location`
![image](https://user-images.githubusercontent.com/44496108/65594047-90def800-df9a-11e9-82ea-8edd4e6f5ed9.png)

**Comment by maektwain** [comment]
I have started work on this one will push a pr soon.

**Comment by Denis-Asipenko** [comment]
checked
