### ISSUE TITLE
[Regression] New sending transaction  doesn't appear in transactions tabel

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#905]
1. Send BEAM to any address

Result: This transaction doesn't appear in tx list. If you navigate to another page and then return to the wallet page, this tx will be in the list

Expected: New transaction appears in le transactions list

**Comment by gingervik** [comment]
now transaction is appeared, but user should scroll up to see it
Please, see attached video
[scroll up.zip](https://github.com/BeamMW/beam/files/3656917/scroll.up.zip)

**Comment by gingervik** [comment]
checked on master 4.0.6240
