### ISSUE TITLE
[UI Wallet] Wallet crashes during creation if the path includes Cyrillic

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#906]
Precondition:
The wallet created and path includes Cyrillic.

Steps:
- open exists wallet ( wallet should have wallet.db)
- Click on "Restore or create a new one" button and create a new wallet
- generate the new seed phrase
- validate the phase 
- set the password
- setup the node to Local node and click proceed
Expected:  the wallet is created and the old DB is backed up with adding timestamps
Actual: wallet crashes
![image](https://user-images.githubusercontent.com/44496108/65605447-c93e0080-dfb1-11e9-8292-7625bf90fadb.png)

**Comment by Roberrtt** [comment]
checked on version :3.1.6196
