### ISSUE TITLE
[UI Wallet] There is no vertical scroll on settings screen

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#907]
Precondition:
Screen resolution 1366 x 768

Steps
- open exists wallet
- open settings
- make scroll up and down.
Expected: There is a scroll to view the bottom information.
Actual: There is no scroll and it is impossible to see the bottom information.
![Screenshot_20](https://user-images.githubusercontent.com/50007056/65609077-dbbb3880-dfb7-11e9-9813-85b25ae2dce9.png)

**Comment by chapati** [comment]
Settings view should be scrollable with mouse wheel now.

**Comment by Roberrtt** [comment]
checked on master 4.0.6240
