### ISSUE TITLE
Disable swap settings if there are active swap transactions

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#910]
If we have active BTC swap transaction -> BTC settings should be disabled
If we have active LTC swap transaction -> LTC settings should be disabled
If we have active QTUM swap transaction -> QTUMsettings should be disabled

**Comment by chapati** [comment]
UI side is done. Implement 

bool getCanEditBTC() const;
bool getCanEditLTC() const;
bool getCanEditQTUM() const;

in SettingsViewModel

**Comment by gingervik** [comment]
checked for bitcoin

**Comment by Sergei-Beam** [comment]
сhecked for LTC&QTUM
