### ISSUE TITLE
Atomic Swap screen - Beam balance takes several second to load

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#918]
Steps:
- Open beam wallet
- Go to Atomic Swap screen
Actual: beam balance "jump" from 0 to actual in several miliseconds
Expected; user should not see this "jump"

Please, see atached video
[swap_0.zip](https://github.com/BeamMW/beam/files/3657113/swap_0.zip)

**Comment by chapati** [comment]
This cannot be fixed at UI side. Balance is displayed as soon as it is provided by logic. Please check logic and fix if that's possible. Ty.

**Comment by gingervik** [comment]
checked
