### ISSUE TITLE
"Failed to start node" error message when node is running

### ISSUE THREAD

**Issue by azaidelson** [BeamMW/beam#92]
**Bug description**
Wallet shows "Failed to start node" error message when switching from remote node to local node
**To Reproduce**
1. Run local node (beam_node.exe)
2. Open wallet
3. In Settings, switch "Run Local Node" off, click "Apply". Wallet connects to remote node
4. Now switch "Run Local Node" to on, click "Apply"
5. The wallet shows "Failed to start local node" message. The Node clearly shows that the Wallet is actually connected:
I 2018-11-24.18:25:56.658 +Peer 127.0.0.1:63188
I 2018-11-24.18:25:56.659 Peer 127.0.0.1:63188 Connected
I 2018-11-24.18:25:56.659 Peer 127.0.0.1:63188 Auth. Type=O, ID=824a6e7df1b9675e

**Expected behavior**
The "Failed to start local node" message should not show.
[beam v1.0.3056 windows report.zip](https://github.com/BeamMW/beam/files/2612413/beam.v1.0.3056.windows.report.zip)

**Comment by gingervik** [comment]
Hi, @azaidelson 
It seems like you run cli node and try to run local node from UI wallet, don't you?
I bet that you use port: 10000 for both of them.

**Comment by gingervik** [comment]
default port for UI local node was changed to prevent such issues
