### ISSUE TITLE
[UI SWAP] The newly created offer is not displayed on the offers board for user who created it

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#924]
The newly created offer is not displayed on the offers board for user who created it and sometimes only after updating the board it starts to appear on your offers board.

Steps:
- open wallet
- open the Atomic SWAP screen
- click create offer
- filling in the data and click publish
Actual: created offer is not displayed on the offers board

**Comment by Zeke133** [comment]
Without correct update info about newly created offers board can't work properly.
In case when transaction immediately canceled before the offer appeared on the board offer update message with new status wouldn't be sent. Such a way offer will not be cancelled for the network.

**Comment by iamien1993** [comment]
checked

build 4.0.6346 (Mac)

**Comment by Roberrtt** [comment]
Checked

build 4.0.6413(Win 10)
