### ISSUE TITLE
[UI SWAP]The received amount isn't displayed correctly.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#927]
On the "Atomic Swap" screen in the transactions tab, the amount received is not displayed correctly. 
Actual:
![image](https://user-images.githubusercontent.com/45556620/65691499-9b23f380-e079-11e9-85d1-4daab870462a.png)
Design:
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5d6f766c6765b59ba248a34d
![image](https://user-images.githubusercontent.com/45556620/65691536-ad059680-e079-11e9-9988-27ce9338d607.png)

**Comment by Sergei-Beam** [comment]
checked
