### ISSUE TITLE
[UI SWAP] Screens do not close after clicking button "publish transaсtion token" \ "send".

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#928]
Screens "Swap currencies " \ "Create swap offer" do not close after clicking button  "send"(**In the alert "Confirmation transaction details"**) \ "publish translation token".
![image](https://user-images.githubusercontent.com/45556620/65693874-a842e180-e07d-11e9-865e-88ecddad1c48.png)

**Comment by Sergei-Beam** [comment]
1.  The bug with Close Create Swap Offer page is fixed in #931

2. Bug with "Swap currencies " still be actual
Steps:
- click accept offer
- paste the token into Send to field 
- click swap
Actual: page doesn't close

**Comment by gingervik** [comment]
checked on master 4.0.6249
