### ISSUE TITLE
Indicator "System time is not syncronized" does not change even when time is ok

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#929]
Steps: 
- run wallet
- change your local time +2 hours
- check your wallet status - System time is not syncronized error is shown
- change your time back to current
AR: Indicator "System time is not syncronized" does not change

[beam_ui_19_09_26_15_04_41.log](https://github.com/BeamMW/beam/files/3658194/beam_ui_19_09_26_15_04_41.log)
![image](https://user-images.githubusercontent.com/28015224/65696349-bdba0a80-e081-11e9-9193-800bf780dc15.png)

**Comment by anatolse** [comment]
I'm not sure that this is a regression. We check time when secure connection has established. If the difference is too big we close this connection, but all existing connections are still alive, wallet is also connected to the node and there is no event to detect when time will become correct. So, we have changed UI, but have no ability to notify  it, that everithing is correct. The question is: Should we really show this error in UI? If we need then we have to rethink this feature implementation.

**Comment by beam-mw** [comment]
Can not reproduce
