### ISSUE TITLE
Address expiration date and address management

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#93]
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5be2c36d42ac6a3fe694572e
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5be2c36ef9d5b53eec1a914d
![address book_contacts](https://user-images.githubusercontent.com/28015224/49003094-49b58a00-f172-11e8-9b72-7d4c64df0047.png)
![address book_my addresses](https://user-images.githubusercontent.com/28015224/49003095-49b58a00-f172-11e8-8080-27cf09f9d561.png)

**Comment by Sergei-Beam** [comment]
Need to fix small bugs and add some changes:
1. remove transaction list action until there isn't groups filter
2. when I create an address the added comment is stored as a name for the new active address, but when I send transaction to someone, we also create a new address in the active addresses tab, but the comment is not saved as a name
3. The same as in point 2 for new contact, need to keep comment as a name for the new contact

**Comment by Sergei-Beam** [comment]
Checked
Separate tickets for expiration date and contact list were created
#127 
#128
