### ISSUE TITLE
QTUM symbol in fonts

### ISSUE THREAD

**Issue by Zeke133** [BeamMW/beam#934]
![image](https://user-images.githubusercontent.com/32778545/65755019-f0fca800-e11a-11e9-9454-8b5b5223726c.png)
Create a symbol for QTUM in font and replace

**Comment by Sergei-Beam** [comment]
checked. Symbol was added
![image](https://user-images.githubusercontent.com/44496108/65944967-8e1d5080-e43b-11e9-80cf-016ad09739be.png)
