### ISSUE TITLE
Add 'txID' parameter to 'tx_send' method

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#935]
in current API we do not allow to pass 'txID' and we generate it internally.
We need to allow the client to pass its own 'txID', this should allow user to process(store) 'txID' before wallet negotiations and tx procession begins

**Comment by nesbox** [comment]
Wiki update:

## tx_send
Sends transactions with a specific value to a given address.

`-->`
```json
{
	"jsonrpc":"2.0", 
	"id": 2,
	"method":"tx_send", 
	"params":
	{
		"value" : 12342342,
		"fee" : 2,
		"from" : "472e17b0419055ffee3b3813b98ae671579b0ac0dcd6f1a23b11a75ab148cc67",
		"address" : "472e17b0419055ffee3b3813b98ae671579b0ac0dcd6f1a23b11a75ab148cc67",
		"comment" : "thank you!"
	}
}
```
`value` and `fee` are in Groth

`from` address can be omitted, new own address will be generated and registered in this case.

`fee` and `comment` can be omitted.

`txId` you can provide your own transaction ID.

You can also preselect specific UTXOs for a transaction by adding `coins` array parameter, like `"coins" : ["00057e8eca5673476e6f726d000000000000015d3ef79800", "00057e8eca1233476e6f726d000000000000015d3ef79800"]`

`<--`
```json
{
	"jsonrpc":"2.0", 
	"id": 2,
	"result":
	{
		"txId" : "10c4b760c842433cb58339a0fafef3db"
	}
}
```
Returns transaction id or error code.

**Comment by Sergei-Beam** [comment]
@nesbox please, add a check for txId if that txId already exists in DB

**Comment by Sergei-Beam** [comment]
2. Also, let's add the same parameter `"txId"` for `method: 'tx_split'`

**Comment by Sergei-Beam** [comment]
2. check for split is missed, @nesbox please add it also for `split`
![image](https://user-images.githubusercontent.com/44496108/66124044-0cb8f000-e5ec-11e9-9b63-974f1e138995.png)

**Comment by Sergei-Beam** [comment]
checked
