### ISSUE TITLE
Extend API with  'generate_tx_id' method

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#936]
this method should simply generate 16-byte UUID which can be passed as 'txID' parameter to 'tx_send' method

**Comment by nesbox** [comment]
Also, don't forget to update the docs on Wiki:

## generate_tx_id
Generates ID for a transaction.

`-->`
```json
{
	"jsonrpc":"2.0", 
	"id": 2,
	"method":"generate_tx_id"
}
```
`<--`
```json
{
	"jsonrpc":"2.0", 
	"id": 2,
	"result":"10c4b760c842433cb58339a0fafef3db"
}
```

**Comment by Sergei-Beam** [comment]
checked.
@andreibaranouski Please, add test for that method in future)
