### ISSUE TITLE
[UI SWAP] Restrict the amount of BEAMs using on SWAP to maximum emissions

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#937]
User shouldn't be able to set the amount of BEAMs in offer more than maximum emissions.
![image](https://user-images.githubusercontent.com/44496108/65869722-a03bb800-e383-11e9-94a7-975ee1447a0a.png)

**Comment by chapati** [comment]
Currently we have upper limit of 255,000,000 and lower limit 0.00000001 on all inputs. We cannot restrict user of entering any rate but if entered rated violates limits the following will happen:

- value in input will be set to the lower or upper bound
- rate will be highlighted in red and 'Invalid rate' amount would appear
- when use will leave the rate input rate would be adjusted to have correct value

**Comment by VladislavKulyba** [comment]
checked
