### ISSUE TITLE
 [UI SWAP]All numbers should be displayed on locale format(balances,rate etc.) 

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#938]
Please, show all numbers on Atomic Swap screen according to locale format
Rate:
![image](https://user-images.githubusercontent.com/44496108/65873103-d9c3f180-e38a-11e9-9784-55f73b1888d7.png)
Balances:
![image](https://user-images.githubusercontent.com/44496108/65873846-dd587800-e38c-11e9-828b-9054d2a3e7e0.png)

**Comment by VladislavKulyba** [comment]
checked
