### ISSUE TITLE
[UI SWAP] Make the separator for the rate as dot for all locales as it was done for send screen

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#939]
If my locale separator is comma I can't enter anything except comma. But the system only understands the dot separator.
So, please, make the separator for the rate as dot for all locales as it was done for send screen.
![image](https://user-images.githubusercontent.com/44496108/65873409-b2215900-e38b-11e9-8245-c0df32051fdc.png)

**Comment by VladislavKulyba** [comment]
checked
