### ISSUE TITLE
[UI SWAP] The rate turns red or resets to zero due to incorrect rounding

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#940]
For reproduce just use the same amounts as on screens below.
Red rate: ![image](https://user-images.githubusercontent.com/44496108/65886731-8612d180-e3a5-11e9-816c-ea2121f9db7f.png)

Zero rate: ![image](https://user-images.githubusercontent.com/44496108/65886853-bce8e780-e3a5-11e9-8dec-7999fa7f3cba.png)

**Comment by iamien1993** [comment]
"Rate" value is not displayed in case Send = 99.99999999 and Receive = 0.00000001
![image](https://user-images.githubusercontent.com/44057235/66189431-6673f580-e692-11e9-810f-3791711606df.png)

**Comment by iamien1993** [comment]
main bug - fixed

**Comment by iamien1993** [comment]
additional bug - fixed

build 4.0.6380
