### ISSUE TITLE
[SWAP] Transaction list. Allow to get Tx token for Pending transactions

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#941]
We need an ability to restore tx token from Pending swap transaction. For example if we have corrupted our clipboard.

1. Click 'Create offer'
2. Fill offer
3. press 'Copy to clipboard' & 'Close'
4. New pending tx appears in list
if you lost your clipboard buffer at this moment there are no way to restore token

I propose to add a new action "Copy token" to the context menu to solve this situation

**Comment by iamien1993** [comment]
checked

4.0.6321

**Comment by Sergei-Beam** [comment]
Devs decided to allow copy token via "Copy token" action for all statuses because there's nothing wrong with that if user will be able to copy token. But need to check how it will works if user will try to copy and paste already completed offer and trying to proceed( case relates to #947)
