### ISSUE TITLE
Search button on the main screen is not implemented

### ISSUE THREAD

**Issue by iamien1993** [BeamMW/beam#944]
**Bug description**
New design contains search button  that was not implemented
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5d88b2a8df0f9f61082b8cdd
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5d933215977e0917d3bf4dc2
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5d93321774d8b315f334dfff

**To Reproduce**
Steps to reproduce the behaviour:
1. Run wallet

**Current behaviour**
main screen is open. 
search and delete buttons don't implemented
![image](https://user-images.githubusercontent.com/44057235/65951499-d858fe80-e448-11e9-8a0e-f3ecb95d9473.png)

**Expected behaviour**
main screen is open
search and delete buttons are implemented

**Platform and build**
* BEAM Build number: v.4.0.6246

**Comment by chapati** [comment]
Contact me before testing the last change. I'll explain what has been done.

**Comment by gingervik** [comment]
1. when you click on search button pointer should be automatically focused inside search field (tooltip text should disappear when user starts enter text)
2. 
STR:
- open wallet
- click on search button
- enter 11 (all results are not expanded)
![image](https://user-images.githubusercontent.com/28015224/67836713-608cfb00-fafe-11e9-889b-494d68787d7d.png)
- expand first search result
- change search text
Actual: first search result is expended
Expected: is user change text all search results should be shown in compact view

**Comment by gingervik** [comment]
checked on master 4.0.6571
