### ISSUE TITLE
[UI SWAP] Make logs for BTC/LTC/QTUM confirmations more user-friendly

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#946]
Since we were adding confirmations not only for the transaction according to #897 we should appear them in a more user-friendly view for users

Now they look almost the same, the only difference is the numbers in brackets.
![image](https://user-images.githubusercontent.com/44496108/65955070-ff66fe80-e44f-11e9-8c04-d4fd323e3960.png)
As an example, we can just add to current confirmation messages the affiliation:
- Beam RedeemTX constructed.
`[5] 5/6 confirmations for RedeemTX are received.`
- Beam LockTX completed.
`[7] 5/6 confirmations for Beam LockTX are received.`

**Comment by Sergei-Beam** [comment]
@roman-strilets please, change a typo in the message
![image](https://user-images.githubusercontent.com/44496108/66207688-16118d80-e6bc-11e9-9530-5a089b8720bb.png)

**Comment by roman-strilets** [comment]
fixed in https://github.com/BeamMW/beam/commit/78a1d83ef88c6970d0ca822fea4d3299fbf1ab90

**Comment by Sergei-Beam** [comment]
checked
