### ISSUE TITLE
[UI SWAP]  Add warning and forbid to accept the same offer twice

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#947]
We need to show for the user some warning when they try to accept the same offer twice.
Steps:
- create an offer on Wallet A and copy token
- open Wallet B
- Click send or accept offer and paste the token
- accept the offer on Wallet A
- Click send or accept offer and paste the same token again
- accept the offer on Wallet A
Expected: User shouldn't be able to accept the same offer twice

**Comment by Sergei-Beam** [comment]
@alexandrashelenkova please, make the design for that

**Comment by alexandrashelenkova** [comment]
The screen is here https://zpl.io/beW8Pvl
@sasha-abramovich please approve the english

**Comment by sasha-abramovich** [comment]
Why not "You've already accepted this offer"?

**Comment by alexandrashelenkova** [comment]
Text fixed.

**Comment by sasha-abramovich** [comment]
_You have already accepted the offer with this transaction token._ How about it @alexandrashelenkova?

**Comment by sasha-abramovich** [comment]
Alternatively, _The offer with this transaction token is already accepted_

**Comment by alexandrashelenkova** [comment]
Text fixed :)

**Comment by Roberrtt** [comment]
Checked :
Build: 4.0.6333
