### ISSUE TITLE
[UI SWAP] Add warning and forbid to accept own offer

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#948]
We need to show for the user some warning when they try to accept OWN offer.
Steps:
- create an offer on Wallet A and copy token
- Click send or accept offer and paste the token
- try to accept own offer.
Expected: User shouldn't be able to accept own offer
Actual: Currently we have forbidden it, but there is no warning for the user on UI
![image](https://user-images.githubusercontent.com/44496108/65958440-0f82dc00-e458-11e9-8dbe-0c9fccf97376.png)

**Comment by Sergei-Beam** [comment]
@alexandrashelenkova please, make the design for that

**Comment by alexandrashelenkova** [comment]
The screen is here https://zpl.io/aBZkvNp
@sasha-abramovich please approve the english

**Comment by sasha-abramovich** [comment]
It's unclear how in general we can get to the situation of accepting our own offer in UI. Let's talk why it can happen. As about English, I would just say "You can't accept your own offer". But again, it shouldn't happen in the UX flow.

**Comment by alexandrashelenkova** [comment]
User can copy his offer's token and input it in field on Send screen.

**Comment by sasha-abramovich** [comment]
_The transaction token was generated by you, therefore it is not allowed to accept your own offer._

**Comment by alexandrashelenkova** [comment]
Text fixed :)

**Comment by Sergei-Beam** [comment]
1. We should close the window and move user from which he is trying to accept the own offer:
- move to general screen if user use the button `Send`
- move to Atomic Swap -> tab where the user used button `Accept offer` 

![image](https://user-images.githubusercontent.com/44496108/66470223-d8cd4700-ea91-11e9-80b4-a9072599c8b8.png)

**Comment by Sergei-Beam** [comment]
checked

**Comment by Sergei-Beam** [comment]
The alert is broken. The wrong alert is shown when I try to paste own token

**Comment by gingervik** [comment]
https://github.com/BeamMW/beam/issues/948#issuecomment-539926088 is reproduced again

**Comment by gingervik** [comment]
checked on master 4.0.6463
