### ISSUE TITLE
Rename statuses for "sending" and "receiving" transactions to "in progress"

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam#949]
Statuses are here https://zpl.io/2ERlRGn

**Comment by iamien1993** [comment]
checked (with icons):
* "sending" and "receiving"  are changed to "in progress"
* sent/received
* sending/sent to own address
* cancelled (sender)
* expired

**Comment by iamien1993** [comment]
also need to change statuses for CLI

**Comment by iamien1993** [comment]
checked
