### ISSUE TITLE
Wallet backup and restore documentation

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#95]
Describe scenarios for restore and backup

**Comment by sasha-abramovich** [comment]
Executable file and Wallet DB are de-coupled. It should be possible to determine DB version.

Scenario:
- Computer is broken
- New computer is bought and the DB is restored from HD backup
- Before we have backward compatibility we should be able to know the DB version by looking at the file.

**Comment by sasha-abramovich** [comment]
@gingervik @BigRomanov how about baking a version number automatically into the filename?

**Comment by sasha-abramovich** [comment]
following our talk, let's indicate the version number into the major folder name (and into the main DB file name - only if it can be used without the rest of the files).
