### ISSUE TITLE
[UI SWAP] Forbid to paste the usual address on Accept offer screen

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#951]
Please, forbid to paste the usual address on Accept offer screen and add a warning if user tries to paste it.

**Comment by VladislavKulyba** [comment]
Manual input is blocked if the first symbol is a numeral
![image](https://user-images.githubusercontent.com/51320829/66646862-110a8c00-ec30-11e9-87e6-51b30027c05e.png)

**Comment by Zeke133** [comment]
let's discuss this task with design cause without additional "accept" button it's hard to solve

**Comment by sasha-abramovich** [comment]
> Only swap token is supported
> 
> You have supplied a regular wallet address instead. Please paste a swap token to continue.

**Comment by echoby** [comment]
Popup removed + validation only for swap token + usual sbbs address is invalid for this case
Approved by @sasha-abramovich

**Comment by Sergei-Beam** [comment]
1. We need to change the error messages for validators since we have different logics on different screens.
So when user pastes wrong address or token on Send screen we should show 
- **Invalid wallet address or swap token**
When user pastes token OR trying to paste the usual address on Accept Offer screen we should show
- **Invalid swap token**

2. Manual input is broken.
When I start to input the address after 1st symbol the system opens the form and moves down the cursor

**Comment by Roberrtt** [comment]
Checked

**Comment by Sergei-Beam** [comment]
@echoby Please fix the following things:

points 1-2 from comment https://github.com/BeamMW/beam/issues/951#issuecomment-543092454  are Missed 

3. Wallet -> Send button
When I typing manually the token wallet doesn't change the button send to swap.
 
4. Add realtime validation while user typing the address or token.
When user typing the address or token we should check IS address OR token valid now or no, if both are invalid we should show the error message from point 1.

**Comment by Sergei-Beam** [comment]
1-4 checked
