### ISSUE TITLE
[UI SWAP] Close Create Swap Offer page if user doesn't have connected currency and he clicks close alert

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#952]
We need to close the Create Swap Offer page if user clicks `close` on this alert
![image](https://user-images.githubusercontent.com/44496108/65963011-8ae98b00-e462-11e9-83ab-996090382d4f.png)

**Comment by iamien1993** [comment]
checked:
- "**cancel**" button transfers user to _Atomic Swap_ screen
- "**change settings**" button transfers user to _Swap Settings_ screen
- the click in area around the popup doesn't work
v 4.0.6330

**Comment by iamien1993** [comment]
task will be retested after this fix
https://github.com/BeamMW/beam/issues/988

**Comment by iamien1993** [comment]
checked:
- "**cancel**" button transfers user to _Atomic Swap_ screen (which was opened before)
- "**change settings**" button transfers user to _Swap Settings_ screen
- the click in area around the popup doesn't work
- messages and working with several currencies

build 4.0.6380
