### ISSUE TITLE
[UI SWAP] Wallet shouldn't remember the sub-tab on the Transactions tab 

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#954]
The wallet shouldn't remember the sub-tab which user is opened on the Transactions tab.
By default, if user leave the Transactions tab and came back we should open the sub-tab `Transactions->All` 

Steps:
- open wallet
- open Atomic Swap screen
- chose `Transactions` tab
- chose sub-tab `Transactions->In progress`
- switch to `Active offers` tab
- go back to `Transactions` tab
Expected: after came back the wallet opens sub-tab `Transactions->All`
Actual: wallet remembers and opens sub-tab`Transactions->In progress`
![2019-09-30_12-19-42](https://user-images.githubusercontent.com/44496108/65964081-cd13cc00-e464-11e9-8ccc-ddd4259cb824.gif)

**Comment by gingervik** [comment]
checked on master 4.0.6264
