### ISSUE TITLE
Forbid simultaneous swap transactions

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#956]
For now, we have a known limitation for the swap transaction: simultaneous transactions may failed for given currency(BTC, LTC, QTUM). The reasons are limitations of electrum and disability to control coin selection on non-BEAM side. I propose to detect simultaneous transaction on specific type of coin and forbid it. Note that simultaneous swaps on BTC , LTC , QTUM (one for each type) are allowed.

**Comment by roman-strilets** [comment]
This limitation is not actually now. Wallet is supported simultaneous swap transactions

**Comment by Sergei-Beam** [comment]
checked
