### ISSUE TITLE
[UI Wallet] Atomic Swap screen: table sorting works incorrectly for several columns

### ISSUE THREAD

**Issue by iamien1993** [BeamMW/beam#959]
**Bug description**
Tab "ACTIVE OFFERS"
First click on the head of column Date|Time / Expiration should use **DESC** sorting
First click on the head of column Send/Receive/Rate should use **ASC** sorting
Sorting by default - Date|Time (**DESC**)

Tab "TRANSACTIONS"
First click on the head of column Created on should use **DESC** sorting
First click on the head of column From/To/Sent/Received/Status should use **ASC** sorting
Sorting by default - Created on (**DESC**)

**To Reproduce**
Steps to reproduce the behaviour:
1. Run a wallet
2. Open "Atomic Swap" screen
3. click "Receive"

**Current behaviour**
Receive is sorted incorrectly
![image](https://user-images.githubusercontent.com/44057235/66041071-a49dd780-e521-11e9-8269-750a6a78da34.png)

**Expected behaviour**
Receive is sorted **ASC**

**Platform and build**
* BEAM Build number: v 4.0.6264

**Comment by iamien1993** [comment]
"Receive" sorting works incorrectly

**steps:**
1) run wallet
2) open _Atomic Swap_ screen
3) sort table by Receive
**Actual result:**
ASC sorting works incorrectly 
![image](https://user-images.githubusercontent.com/44057235/66124216-7e913980-e5ec-11e9-9359-fb8fadb267b0.png)

**Comment by iamien1993** [comment]
Active offers - checked
Transactions - checked (except To/Status)

v 4.0.6285

**Comment by iamien1993** [comment]
Status icon and colour do not change after sorting.
**STR:**
1) create several offers
2) open _Transactions_ tab
3) cancel the offers (except the last one)
4) use sorting by Status 2 times

**Actual result:**
cancelled status gets the icon & colour of pending status
![image](https://user-images.githubusercontent.com/44057235/66202674-05a6e600-e6af-11e9-9b71-4ccb0646d764.png)
**Expected result:** sorting works correctly

**Comment by iamien1993** [comment]
probably, this bag depends on task with status changing

**Comment by iamien1993** [comment]
checked

build 4.0.6302

**Comment by Roberrtt** [comment]
Reproduce.
Color do not change after sorting.

Steps:

create several offers
open Transactions tab
cancel the offers (except the last one)
use sorting by Status 2 times

Actual:
Canceled status gets the color of the pending status
![Screenshot_130](https://user-images.githubusercontent.com/50007056/67275884-328b3380-f4cc-11e9-9858-abc40be85f08.png)

**Comment by Roberrtt** [comment]
Checked:
