### ISSUE TITLE
Settings reorganisation + atomic swap settings

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam#960]
New settings screen are here https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/dashboard?seid=5d8c86245e8f8e1617b68adb

Please notice violet comments on some screens 
<img width="188" alt="Screenshot 2019-10-02 at 21 20 59" src="https://user-images.githubusercontent.com/7249484/66047778-f878e280-e55a-11e9-8d5d-537f32f8cd59.png">

**Comment by gingervik** [comment]
will be done in next release

**Comment by chapati** [comment]
Already have v3.
This is not relevant anymore. Moved to #1488
