### ISSUE TITLE
Update Beam logo

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam#961]
Please update Beam logo to the improved one on all screens where it is:
- initialization screens
- restore screens
- side menu screens
- share transaction details screen https://zpl.io/2ERpNjM

Please take logo from https://zpl.io/bAq0P56

**Comment by chapati** [comment]
New logo when scaled to small size looks ugly. I've used new svg for big logos (start/init screen) and left an old one for sidebar. Would you please provide new logo that looks fins when scaled down. Ty.
![Selection_039](https://user-images.githubusercontent.com/12074933/66104077-31976e00-e5c0-11e9-967a-17ffa1c92bff.png)

**Comment by dariatarakanova** [comment]
@chapati please try this one https://drive.google.com/file/d/1IqMyNYBZEkS9kkzLJWseYvDS8pDTNulU/view?usp=sharing

**Comment by iamien1993** [comment]
checked:
1) authorization screen
2) restore/new wallet screens
3) side menu screens

share transaction details screen - screen is not implemented yet

build v4.0.6302
