### ISSUE TITLE
Changes in settings for swap transactions

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#962]
Please combine the panels to configure the node and the electrum, as shown in the screenshots
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5d90701b3a69a1029392b645

**Comment by Sergei-Beam** [comment]
Settings screen was updated, need to rework it

**Comment by Aleksandr-Starun** [comment]
Indicator has been added at 9a01e034cfa95d197ddb43468e6633e42c3a2296

**Comment by VladislavKulyba** [comment]
1. Default fee should be 0.005 QTUM/kB
2. Change units for BTC, LTC, QTUM default rate units to relevant. 
sat/kB to BTC/kB
ph/kB to LTC/kB
qsat/kB to QTUM/kB
 
![image](https://user-images.githubusercontent.com/51320829/67861840-0a39af80-fb32-11e9-8e37-7dd7277027e6.png)

**Comment by VladislavKulyba** [comment]
checked
