### ISSUE TITLE
Dialog  for the seed phrase for electrum

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#963]
Entering new seed
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5d90701b3104ce15cfb924e4

Genetrate new seed
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5d90701c33a7e662022d3717

View
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5d90716b6dff5665633dfb46

**Comment by Roberrtt** [comment]
Remove this "\n " from the text
![Screenshot_238](https://user-images.githubusercontent.com/50007056/68058598-9f8f9c00-fd0a-11e9-9b75-4bef924f98db.png)

**Comment by VladislavKulyba** [comment]
checked
