### ISSUE TITLE
Atomic Swap - Lose connection when change currency to LTC

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam#966]
Changing currency in Atomic Swap Tab from BTC or QTUM to LTC leads to losing connection with node. 

Steps to reproduce:
1. Run wallet. Connection indicator has status 'online'
2. Go to Atomic Swap Tab. 
3. Change currency from BTC to LTC

Actual Result: Connection indicator shows 'Node protocol error'
Expected Result: Connection indicator has status 'online'

![image](https://user-images.githubusercontent.com/51320829/66118388-f0fb1d00-e5de-11e9-9240-1ab86bfe0eaa.png)

**Comment by Zeke133** [comment]
This was caused by swap offers protocol update. Will not reproduce anymore.

**Comment by VladislavKulyba** [comment]
Doesn't reproduce
