### ISSUE TITLE
[UI Wallet] Wallet: balance card works incorrect after sending to another wallet

### ISSUE THREAD

**Issue by iamien1993** [BeamMW/beam#967]
**Use two wallets: 1 - sender, 2 - receiver.**

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the wallets
2. send some coins from 1 to 2.
**Actual intermediate result:**
sender:
![image](https://user-images.githubusercontent.com/44057235/66118630-91514180-e5df-11e9-9eca-ec73891e2c46.png)
receiver:
![image](https://user-images.githubusercontent.com/44057235/66118655-9d3d0380-e5df-11e9-8ce8-d06f6a7f9d9d.png)
**Expected intermediate result:**
sender: 
![image](https://user-images.githubusercontent.com/44057235/66118572-64049380-e5df-11e9-9b5f-430300f98eba.png)
receiver:
![image](https://user-images.githubusercontent.com/44057235/66118599-78489080-e5df-11e9-832e-551b1643fbfd.png)

i.e. sender lost the value on the balance card and receiver lost the "Sending/Receiving" balance card
3. wait until transaction is done

**Current behaviour**
Transaction is completed, but balance card displays incorrect information.

sender: 
![image](https://user-images.githubusercontent.com/44057235/66118840-06247b80-e5e0-11e9-804b-abc4a140e794.png)
receiver:
![image](https://user-images.githubusercontent.com/44057235/66118860-1177a700-e5e0-11e9-902e-64f58168fabf.png)

**Expected behaviour**
Transaction is completed, balance card displays the "available" value

sender: 
![image](https://user-images.githubusercontent.com/44057235/66118881-20f6f000-e5e0-11e9-9ee6-4c9e02da7540.png)
receiver:
![image](https://user-images.githubusercontent.com/44057235/66118892-2b18ee80-e5e0-11e9-9b6b-1f3c5e73f40c.png)

**Platform and build**
* MacOS
* BEAM Build number: v 4.0.6277.
* Beam Build number with expected results: v 4.0.6264

Please, write to me in case you have questions

**Comment by Aleksandr-Starun** [comment]
Fixed at https://github.com/BeamMW/beam/commit/50c5421b259c03f087fba9dfce113633edaf3f0c

**Comment by iamien1993** [comment]
checked
v 4.0.6294
