### ISSUE TITLE
[UI SWAP] Сhange the display of other people's offers on the board

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#971]
We should invert the next information for other people's offers on the board:
- coins' symbols
- Sender
- Receiver
- also, the Rate should be a recount according to changed sender/receiver
![image](https://user-images.githubusercontent.com/44496108/66197291-c1154d80-e6a2-11e9-9e44-b97f07b0d579.png)

**Comment by VladislavKulyba** [comment]
One user creates offer:
Send BTC -> Receive BEAM (offer must be on Receive BEAM Tab)
The other one user accepts offer:
Send BEAM -> Receive BTC (offer must be on Send BEAM Tab)

![image](https://user-images.githubusercontent.com/51320829/66834460-50a1e280-ef66-11e9-9cd4-e6f9c80ec923.png)

**Comment by Sergei-Beam** [comment]
checked
