### ISSUE TITLE
[UI SWAP] Change the status for swap transaction according to Tx progress

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#977]
We should change the status for swap transaction if Tx changes progress.

As an example, if wallets start to send messages to each other the statuses should be changed to `in progress`
![image](https://user-images.githubusercontent.com/44496108/66303404-9d9d0d80-e903-11e9-9a2c-4e39720b5a2a.png)

**Comment by VladislavKulyba** [comment]
when offer is expired transaction should have status "expired", not "failed"
![image](https://user-images.githubusercontent.com/51320829/67275793-066fb280-f4cc-11e9-881f-8c2b47938987.png)

**Comment by echoby** [comment]
fixed at: https://github.com/BeamMW/beam/commit/cf734083e9f6755e75851e719ce4628cb8c471a8

**Comment by Sergei-Beam** [comment]
Checked, new functionality will be added here #1037
