### ISSUE TITLE
[SWAP] Transaction has expired when node is not up to date

### ISSUE THREAD

**Issue by roman-strilets** [BeamMW/beam#979]
steps to reproduce:
1. init wallet
2. set bitcoin settings
3. create swap transaction:
beam-wallet-masternet.exe swap_init -n "eu-node01.masternet.beam.mw:8100" -a 1 --swap_amount 200000 --swap_coin=btc

Result:
 Failed. Transaction has expired
![image](https://user-images.githubusercontent.com/40387866/66321178-dac7c680-e928-11e9-8491-4a534e9d8315.png)

**Comment by Roberrtt** [comment]
Checked
