### ISSUE TITLE
[SWAP] Add "Connecting" state to balance pane at the start of the wallet

### ISSUE THREAD

**Issue by roman-strilets** [BeamMW/beam#980]
![image](https://user-images.githubusercontent.com/40387866/66321589-7c4f1800-e929-11e9-9e50-b9d3129dc507.png)

**Comment by VladislavKulyba** [comment]
Reproduced. 
Steps to reproduce:
1. Go to Swap Settings
2. Set data for BTC node (node address incorrect)
3. Close the Wallet
4. Open the Wallet 

Expected: "Connecting" state at balance panel
Actual: Error message: "Cannot connect to peer. Please check in the address in settings and retry"

**Comment by Roberrtt** [comment]
Checked: 
Build 4.0.6420
