### ISSUE TITLE
The wallet crashes if swap nodes are not configured and user tries to accept offer

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#984]
We should show the pop-up(see the screen below) if swap nodes are not configured and user tries to accept the offer via:
- Send button on the general screen
- Accept offer button on the Atomic Swap screen
- Accept offer on the Atomic Swap Board

Precondition:
The wallet created and swap nodes are not configured

Steps
1: Open exists wallet
2: Open Atomic swap tab
3: Open the swap on the receiver
4: Accept any offer
5: Click swap
Expected: Pop-up is opened
![Screenshot_90](https://user-images.githubusercontent.com/50007056/66394460-e0331880-e9dd-11e9-95ad-9483e393932e.png)

Actual: Wallet crashes

**Comment by sasha-abramovich** [comment]
let's remove the dialog box and write in the validator? @alexandrashelenkova what do you think?

**Comment by alexandrashelenkova** [comment]
Alert is fine for me here actually.

**Comment by sasha-abramovich** [comment]
Alert is good if so. @roman-strilets - if possible it's better to write something like "Bitcoin is not connected, please review your settings and try again"

**Comment by Roberrtt** [comment]
Checked
