### ISSUE TITLE
[UI SWAP] Wrong gradient for Send and Accept offer screens

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam#986]
We should have the same gradient (pink) as at first screen when clicking Send or Accept offer button
Send screen
![image](https://user-images.githubusercontent.com/44496108/66484770-530cc400-eab0-11e9-84f6-8928dd25a32a.png)
After pasting the usual address
As an example here design for send screen with usual address https://zpl.io/boPDpQE
![image](https://user-images.githubusercontent.com/44496108/66484839-6d46a200-eab0-11e9-9ed5-bc45374453e7.png)

After pasting the token
![image](https://user-images.githubusercontent.com/44496108/66484832-6881ee00-eab0-11e9-89b4-866ec3f0ab99.png)

Accept offer screen
![image](https://user-images.githubusercontent.com/44496108/66485011-bac30f00-eab0-11e9-8058-5abc89a645df.png)

After pasting the token
![image](https://user-images.githubusercontent.com/44496108/66485047-c9112b00-eab0-11e9-84b2-973d4cb5499c.png)

**Comment by iamien1993** [comment]
checked

build: 4.0.6330
