### ISSUE TITLE
Invalid state of UTXO after blockchain rollback

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam#989]
1. Mainnet. Mobile wallet connected to node without owner_key
2. Send beam
3. Transaction completed
4. Rollback happens rignt to the block before transaction become completed
5. Close app
6. Restart app (6 hours)

Result: Utxo which were spent become avaliable, available become unconfirmed

I 2019-10-08.05:12:20.783 [c8dbd1e0bcce48e5b59ac1f3c90e9e76] Transaction completed
D 2019-10-08.05:12:20.784 Async update finished!
I 2019-10-08.05:12:20.784 Synchronizing with node: 100% (1/1)
I 2019-10-08.05:12:20.785 Current state is 398006-e83c745fcf533cab
D 2019-10-08.05:12:20.785 Async update started!
D 2019-10-08.05:12:20.785 Async update finished!
I 2019-10-08.05:13:19.273 Rolled back to 398005-6769fc08ba6de8ef  <--- Rollback, states of UTXO are changed and transactions should change their state
I 2019-10-08.05:13:19.297 Sync up to 398007-fa9b03472e51cfd7
I 2019-10-08.05:13:19.298 Current state is 398007-fa9b03472e51cfd7 
D 2019-10-08.05:13:19.298 Async update started!  <-- Here changed transactions should request proofs, but this doesn't happen
D 2019-10-08.05:13:19.298 Async update finished!
/// Shutdown app
/// Restart app

I 2019-10-08.11:47:24.649 Application has started
I 2019-10-08.11:47:24.651 OS VERSION: iOS 13.1.2
I 2019-10-08.11:47:24.651 DEVICE TYPE: iPhone
I 2019-10-08.11:47:24.651 DEVICE MODEL ID: iPhone11,8
I 2019-10-08.11:47:24.651 APP VERSION: 3.0.1 BUILD 1
I 2019-10-08.11:47:24.651 LANGUAGE CODE: en
I 2019-10-08.11:47:24.661 Rules signature
I 2019-10-08.11:47:27.408 WalletID 183983f657d6d16b5836260918b58c2ac2aacef34fcb0005eaa9327742a59edb918 subscribes to BBS channel 387
I 2019-10-08.11:47:27.408 WalletID 130f8d7bccdad4e9d30c1d8abd49710d8c79ed3a8f664449ba3af612e06b1923f51 subscribes to BBS channel 304
I 2019-10-08.11:47:32.394 Sync up to 398389-b90ae0271c47aa53
I 2019-10-08.11:47:32.394 Current state is 398389-b90ae0271c47aa53
D 2019-10-08.11:47:32.394 Async update started!  <-- no update here
D 2019-10-08.11:47:32.394 Async update finished!

Expected:
Transactions changed on rollback should update their state and confirm their kernels

Scenario #2

1. Close sender wallet on the Registering(In progress) stage, by log this should happen after 'sending tx for registration' but before 'register status '. And wait for a while (several minutes)
2. Open sender wallet after that: transaction should again try to send tx to node( 'sending tx for registration') and it should get 'register status 17 ' and tx should become failed and locked UTXO should become available. This means that while sender's wallet was closed transaction was added to blockchain
3. After these steps all transactions with inputs of the previously failed transaction will fail, and you have to do rescan or restore

**Comment by Sergei-Beam** [comment]
cannot reproduce
