### ISSUE TITLE
[cli] irrelevant error when send trx with negative fee

### ISSUE THREAD

**Issue by andreibaranouski** [BeamMW/beam#995]
**To Reproduce**
if set negative fee we get error that 'The argument for option '--fee' must be equal to or more than 0.'
```
./beam-wallet-masternet send --pass password --wallet_path wallet.db -a 0.001 -f -1 -n eu-node01.masternet.beam.mw:8100 -r 3b6bd1c22ebc0662fb6f5cb9d630db5af9028904766789db6e13e407f8bf52865ea
The argument for option '--fee' must be equal to or more than 0.
```

but actually should be 'The minimum fee is 100 GROTH.'

**Comment by kazaryan-t** [comment]
Need to add min fee when user sets negative fee.
Actually, the min fee for regular txs = 100 000 groth, for offline and max privacy txs = 1100000 groth.

![Командная строка 2021-06-29 15 01 50](https://user-images.githubusercontent.com/68247034/123794171-3a2eec80-d8eb-11eb-846c-389e2cc2a2a7.png)

**Comment by anatolse** [comment]
I'm not sure if this a bug. There are two validations here: 
- command line (it can perform simple checks only )
- and transaction specific

I can remove the first one. Should I? @gingervik

**Comment by gingervik** [comment]
leave it as it works now. it's ok. thank you!
