### ISSUE TITLE
[UI SWAP] canceling of the various currency transactions don't delete the offer of the latest transaction

### ISSUE THREAD

**Issue by iamien1993** [BeamMW/beam#999]
**Bug description**
If we cancel several transactions which contain the various currencies, orders with the last currency don't delete

**To Reproduce**
Steps to reproduce the behaviour:
1. Run wallet which has connection with bitcoin and litecoin
2. create offers:
* BTC-BEAM
* LTC-BEAM
3. open _Transactions_ tab
4. cancel the transactions which have been created
5.  open _Active offers_ tab
6. check offers

**Current behaviour**
_Active offers_ grid contains one of the orders that have been canceled on the step 4.
[Screen Recording 2019-10-14 at 09.28.17.zip](https://github.com/BeamMW/beam/files/3724304/Screen.Recording.2019-10-14.at.09.28.17.zip)

Notice about second bug: **Cancel offer** button will delete the record of transaction in _Transactions_ grid!

**Expected behaviour**
_Active offers_ grid don't contain one of the orders that have been canceled on the step 4.

**Platform and build**
* MacOS
* BEAM Build number: v 4.0.6351

**Log file(s) (if applicable)**
[beam_ui_19_10_14_09_14_04.log](https://github.com/BeamMW/beam/files/3724318/beam_ui_19_10_14_09_14_04.log)

**Comment by iamien1993** [comment]
reproduced - the second order is not canceled.
[Screen Recording 2019-10-18 at 12.25.52.zip](https://github.com/BeamMW/beam/files/3743298/Screen.Recording.2019-10-18.at.12.25.52.zip)

history deleting - fixed

build: 4.0.6398

**Comment by Roberrtt** [comment]
Checked 

build : 4.0.6420
